// ---------------------------------------------------------------------------
// localization_en.cpp – English translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetEnglishTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Disconnected"},
            {"status_connecting", "Connecting..."},
            {"status_connected", "Connected"},
            {"status_auth_failed", "Auth Failed – check token"},
            {"status_reconnecting", "Reconnecting..."},
            {"status_error", "Error"},
            {"status_unknown", "Unknown"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Profit"},
            {"profit_per_hour", "Profit/Hour"},
            {"tp_sell", "TP Sell"},
            {"tp_instant", "TP Instant"},
            {"total_items", "Total Items"},
            {"session", "Session"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "GW2 API"},
            {"session_time_label", "Session Time"},
            {"reset_button", "Reset"},
            {"reset_tooltip", "Reset all farming counters (manual reset)"},

            // Tabs
            {"tab_summary", "Overview"},
            {"tab_items", "Items"},
            {"tab_currencies", "Currencies"},
            {"tab_profit", "Profit"},
            {"tab_favorites", "Favorites"},
            {"tab_ignored", "Ignored"},
            {"tab_filter", "Filter"},
            {"tab_custom_profit", "Custom Profit"},
            {"tab_debug", "Debug"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF not connected"},
            {"warning_drf_not_connected_desc", "This plugin requires DRF for data transmission."},
            {"warning_drf_install", "Install DRF via Nexus Addon Manager or https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ DRF Token invalid"},
            {"warning_drf_token_invalid_desc", "Please check your DRF Token in Settings."},
            {"warning_gw2_api_key_not_set", "⚠️ GW2 API Key not set"},
            {"warning_gw2_api_key_not_set_desc", "Please set your GW2 API Key in Settings for item details."},
            {"overview", "Overview"},
            {"overview_tooltip", "Current farming session overview"},
            {"total_profit", "Total Profit"},
            {"total_profit_tooltip", "Total custom profit from all items"},
            {"total_items_count", "Total Items"},
            {"total_items_tooltip", "Total number of unique items tracked"},
            {"total_currencies", "Total Currencies"},
            {"total_currencies_tooltip", "Total number of unique currencies tracked"},
            {"profit_per_hour_label", "Profit Per Hour"},
            {"profit_per_hour_tooltip", "Profit per hour based on session duration"},
            {"session_duration", "Session Duration"},
            {"session_duration_tooltip", "Current farming session duration"},
            {"top_items_profit", "Top Items (Profit)"},
            {"top_items_profit_tooltip", "Top 5 items by profit value"},
            {"loading", "Loading..."},
            {"coin", "Coin"},
            {"top_items_count", "Top Items (Count)"},
            {"top_items_count_tooltip", "Top 5 items by count"},
            {"top_currencies", "Top Currencies"},
            {"top_currencies_tooltip", "Top 5 currencies by count"},
            {"quick_statistics", "Quick Statistics"},
            {"quick_statistics_tooltip", "Overview of farming statistics"},
            {"average_item_value", "Average Item Value"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Total Unique Items"},
            {"warning_no_data", "⚠️ No data loaded"},
            {"warning_no_data_desc", "Waiting for DRF data..."},
            {"export", "Export"},
            {"export_tooltip", "Export farming data to file"},
            {"export_json", "Export as JSON"},
            {"export_csv", "Export as CSV"},

            // Items Tab
            {"search_hint", "Search items..."},
            {"clear", "Clear"},
            {"sort_count_high", "Sort: |Count| high"},
            {"sort_count_low", "Sort: |Count| low"},
            {"sort_id_up", "Sort: Item ID up"},
            {"sort_id_down", "Sort: Item ID down"},
            {"sort_name_az", "Sort: Name A–Z"},
            {"sort_tooltip", "Sort items by count, ID, or name"},
            {"rarity_all", "Rarity: all"},
            {"rarity_basic", "Rarity: Basic+"},
            {"rarity_fine", "Rarity: Fine+"},
            {"rarity_masterwork", "Rarity: Masterwork+"},
            {"rarity_rare", "Rarity: Rare+"},
            {"rarity_exotic", "Rarity: Exotic+"},
            {"rarity_ascended", "Rarity: Ascended+"},
            {"rarity_legendary", "Rarity: Legendary only"},
            {"rarity_tooltip", "Filter items by minimum rarity"},
            {"rarity", "Rarity"},
            {"type", "Type"},
            {"vendor_value", "Vendor Value"},
            {"tp_buy_net", "TP Buy (Net)"},
            {"account_bound", "Account-bound"},
            {"yes", "Yes"},
            {"no", "No"},
            {"nosell", "NoSell"},
            {"favorite", "Favorite"},
            {"ignore", "Ignore"},

            // Currencies Tab
            {"search_currencies_hint", "Search currencies..."},
            {"api_id", "API ID"},
            {"currency_name", "Currency Name"},
            {"count", "Count"},

            // Profit Tab
            {"profits", "Profits"},
            {"profits_tooltip", "Total profits from farming"},
            {"approx_profits", "Approx. Profits"},
            {"approx_gold_per_hour", "Approx. Gold Per Hour"},
            {"trading_profits", "Trading Profits"},
            {"trading_profits_tooltip", "Profits from Trading Post"},
            {"approx_trading_profits_listings", "Approx. Trading Profits (Listings)"},
            {"approx_trading_profits_instant", "Approx. Trading Profits (Instant Sell)"},
            {"trading_details", "Trading Details (Opportunity Cost)"},
            {"trading_details_tooltip", "Opportunity cost of using items instead of selling"},
            {"lost_profit_vs_tp_sell", "Lost Profit (vs TP Sell)"},
            {"lost_profit_per_hour_vs_tp_sell", "Lost Profit Per Hour (vs TP Sell)"},
            {"session_duration_label", "Session duration"},
            {"session_duration_tooltip", "Current farming session duration"},

            // Filter Tab
            {"sell_method_filters", "Sell Method Filters"},
            {"sellable_to_vendor", "Sellable to vendor"},
            {"sellable_to_vendor_tooltip", "Show items sellable to vendor"},
            {"sellable_on_tp", "Sellable on TP"},
            {"sellable_on_tp_tooltip", "Show items sellable on Trading Post"},
            {"has_custom_profit", "Has custom profit"},
            {"has_custom_profit_tooltip", "Show items with custom profit values"},
            {"api_knowledge_filters", "API Knowledge Filters"},
            {"known_by_api", "Known by API"},
            {"known_by_api_tooltip", "Show items known by GW2 API"},
            {"unknown_by_api", "Unknown by API"},
            {"unknown_by_api_tooltip", "Show items not known by GW2 API"},
            {"item_type_filters", "Item Type Filters"},
            {"type_armor", "Armor"},
            {"type_armor_tooltip", "Show armor items"},
            {"type_weapon", "Weapon"},
            {"type_weapon_tooltip", "Show weapon items"},
            {"type_trinket", "Trinket"},
            {"type_trinket_tooltip", "Show trinket items"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Show gizmo items"},
            {"type_crafting_material", "Crafting Material"},
            {"type_crafting_material_tooltip", "Show crafting materials"},
            {"type_consumable", "Consumable"},
            {"type_consumable_tooltip", "Show consumable items"},
            {"type_gathering_tool", "Gathering Tool"},
            {"type_gathering_tool_tooltip", "Show gathering tools"},
            {"type_bag", "Bag"},
            {"type_bag_tooltip", "Show bags"},
            {"type_container", "Container"},
            {"type_container_tooltip", "Show containers"},
            {"type_mini_pet", "Mini Pet"},
            {"type_mini_pet_tooltip", "Show mini pets"},
            {"currency_filters_label", "Currency Filters"},
            {"currency_main", "Main Currencies"},
            {"currency_fractal", "Fractal/Raid/Dungeon Currencies"},
            {"currency_wvw_pvp", "WvW/PvP Currencies"},
            {"currency_map", "Map-specific Currencies"},
            {"filter_karma", "Karma"},
            {"currency_karma_tooltip", "Show karma currency"},
            {"currency_laurel", "Laurel"},
            {"currency_laurel_tooltip", "Show laurel currency"},
            {"currency_gem", "Gem"},
            {"currency_gem_tooltip", "Show gem currency"},
            {"currency_fractal_relic", "Fractal Relic"},
            {"currency_fractal_relic_tooltip", "Show fractal relic currency"},
            {"currency_badge_of_honor", "Badge of Honor"},
            {"currency_badge_of_honor_tooltip", "Show badge of honor currency"},
            {"currency_guild_commendation", "Guild Commendation"},
            {"currency_guild_commendation_tooltip", "Show guild commendation currency"},
            {"currency_transmutation_charge", "Transmutation Charge"},
            {"currency_transmutation_charge_tooltip", "Show transmutation charge currency"},
            {"currency_spirit_shards", "Spirit Shards"},
            {"currency_spirit_shards_tooltip", "Show spirit shards currency"},
            {"currency_unbound_magic", "Unbound Magic"},
            {"currency_unbound_magic_tooltip", "Show unbound magic currency"},
            {"currency_volatile_magic", "Volatile Magic"},
            {"currency_volatile_magic_tooltip", "Show volatile magic currency"},
            {"currency_airship_parts", "Airship Parts"},
            {"currency_airship_parts_tooltip", "Show airship parts currency"},
            {"currency_geode", "Geode"},
            {"currency_geode_tooltip", "Show geode currency"},
            {"currency_ley_line_crystals", "Ley-Line Crystals"},
            {"currency_ley_line_crystals_tooltip", "Show ley-line crystals currency"},
            {"currency_trade_contracts", "Trade Contracts"},
            {"currency_trade_contracts_tooltip", "Show trade contracts currency"},
            {"currency_elegy_mosaic", "Elegy Mosaic"},
            {"currency_elegy_mosaic_tooltip", "Show elegy mosaic currency"},
            {"currency_uncommon_coins", "Uncommon Coins"},
            {"currency_uncommon_coins_tooltip", "Show uncommon coins currency"},
            {"currency_astral_acclaim", "Astral Acclaim"},
            {"currency_astral_acclaim_tooltip", "Show astral acclaim currency"},
            {"currency_pristine_fractal_relics", "Pristine Fractal Relics"},
            {"currency_pristine_fractal_relics_tooltip", "Show pristine fractal relics currency"},
            {"currency_unstable_fractal_essence", "Unstable Fractal Essence"},
            {"currency_unstable_fractal_essence_tooltip", "Show unstable fractal essence currency"},
            {"currency_magnetite_shards", "Magnetite Shards"},
            {"currency_magnetite_shards_tooltip", "Show magnetite shards currency"},
            {"currency_gaeting_crystals", "Gaeting Crystals"},
            {"currency_gaeting_crystals_tooltip", "Show gaeting crystals currency"},
            {"currency_prophet_shards", "Prophet Shards"},
            {"currency_prophet_shards_tooltip", "Show prophet shards currency"},
            {"currency_green_prophet_shards", "Green Prophet Shards"},
            {"currency_green_prophet_shards_tooltip", "Show green prophet shards currency"},
            {"currency_wvw_skirmish_tickets", "WvW Skirmish Tickets"},
            {"currency_wvw_skirmish_tickets_tooltip", "Show WvW skirmish tickets currency"},
            {"currency_proofs_of_heroics", "Proofs of Heroics"},
            {"currency_proofs_of_heroics_tooltip", "Show proofs of heroics currency"},
            {"currency_pvp_league_tickets", "PvP League Tickets"},
            {"currency_pvp_league_tickets_tooltip", "Show PvP league tickets currency"},
            {"currency_ascended_shards_of_glory", "Ascended Shards of Glory"},
            {"currency_ascended_shards_of_glory_tooltip", "Show ascended shards of glory currency"},
            {"currency_research_notes", "Research Notes"},
            {"currency_research_notes_tooltip", "Show research notes currency"},
            {"currency_tyrian_defense_seal", "Tyrian Defense Seal"},
            {"currency_tyrian_defense_seal_tooltip", "Show tyrian defense seal currency"},
            {"currency_testimony_of_desert_heroics", "Testimony of Desert Heroics"},
            {"currency_testimony_of_desert_heroics_tooltip", "Show testimony of desert heroics currency"},
            {"currency_testimony_of_jade_heroics", "Testimony of Jade Heroics"},
            {"currency_testimony_of_jade_heroics_tooltip", "Show testimony of jade heroics currency"},
            {"currency_testimony_of_castoran_heroics", "Testimony of Castoran Heroics"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Show testimony of castoran heroics currency"},
            {"currency_legendary_insight", "Legendary Insight"},
            {"currency_legendary_insight_tooltip", "Show legendary insight currency"},
            {"currency_tales_of_dungeon_delving", "Tales of Dungeon Delving"},
            {"currency_tales_of_dungeon_delving_tooltip", "Show tales of dungeon delving currency"},
            {"currency_imperial_favor", "Imperial Favor"},
            {"currency_imperial_favor_tooltip", "Show imperial favor currency"},
            {"currency_canach_coins", "Canach Coins"},
            {"currency_canach_coins_tooltip", "Show canach coins currency"},
            {"currency_ancient_coin", "Ancient Coin"},
            {"currency_ancient_coin_tooltip", "Show ancient coin currency"},
            {"currency_unusual_coin", "Unusual Coin"},
            {"currency_unusual_coin_tooltip", "Show unusual coin currency"},
            {"currency_jade_sliver", "Jade Sliver"},
            {"currency_jade_sliver_tooltip", "Show jade sliver currency"},
            {"currency_static_charge", "Static Charge"},
            {"currency_static_charge_tooltip", "Show static charge currency"},
            {"currency_pinch_of_stardust", "Pinch of Stardust"},
            {"currency_pinch_of_stardust_tooltip", "Show pinch of stardust currency"},
            {"currency_calcified_gasp", "Calcified Gasp"},
            {"currency_calcified_gasp_tooltip", "Show calcified gasp currency"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Show ursus oblige currency"},
            {"currency_gaeting_crystal_janthir", "Gaeting Crystal (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Show gaeting crystal (janthir) currency"},
            {"currency_antiquated_ducat", "Antiquated Ducat"},
            {"currency_antiquated_ducat_tooltip", "Show antiquated ducat currency"},
            {"currency_aether_rich_sap", "Aether-Rich Sap"},
            {"currency_aether_rich_sap_tooltip", "Show aether-rich sap currency"},

            // Additional Filters
            {"additional_filters", "Additional Filters"},
            {"account_bound", "Account-bound"},
            {"account_bound_tooltip", "Show account-bound items"},
            {"not_account_bound", "Not Account-bound"},
            {"not_account_bound_tooltip", "Show non-account-bound items"},
            {"nosell_items", "NoSell"},
            {"nosell_items_tooltip", "Show NoSell items"},
            {"not_nosell", "Not NoSell"},
            {"not_nosell_tooltip", "Show sellable items"},
            {"favorite_items", "Favorite"},
            {"favorite_items_tooltip", "Show favorite items"},
            {"not_favorite", "Not Favorite"},
            {"not_favorite_tooltip", "Show non-favorite items"},
            {"ignored_items", "Ignored"},
            {"ignored_items_tooltip", "Show ignored items"},
            {"not_ignored", "Not Ignored"},
            {"not_ignored_tooltip", "Show non-ignored items"},

            // Range Filters
            {"range_filters", "Range Filters"},
            {"show_range_filters", "Show Range Filters"},
            {"filter_min_price", "Filter Min Price"},
            {"filter_max_price", "Filter Max Price"},
            {"filter_min_quantity", "Filter Min Quantity"},
            {"filter_max_quantity", "Filter Max Quantity"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Window"},
            {"show_profit", "Show Profit"},
            {"show_profit_tooltip", "Display total profit in mini window"},
            {"show_profit_per_hour", "Show Profit/Hour"},
            {"show_profit_per_hour_tooltip", "Display profit per hour in mini window"},
            {"show_tp_sell", "Show TP Sell (Listings)"},
            {"show_tp_sell_tooltip", "Display TP sell profit (listings) in mini window"},
            {"show_tp_instant", "Show TP Instant (Instant Sell)"},
            {"show_tp_instant_tooltip", "Display TP instant sell profit in mini window"},
            {"show_total_items", "Show Total Items"},
            {"show_total_items_tooltip", "Display total item count in mini window"},
            {"show_session_duration", "Show Session Duration"},
            {"show_session_duration_tooltip", "Display session duration in mini window"},
            {"window_click_through", "Window click through"},
            {"window_click_through_tooltip", "Allows clicking through the mini window to the game"},

            // Main Window Settings
            {"main_window", "Main Window"},
            {"click_through", "Click through"},
            {"click_through_tooltip", "Allows clicking through the main window to the game"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Advanced UI Settings"},
            {"no_advanced_ui_settings", "(No advanced UI settings available)"},

            // Display Settings
            {"display_settings", "Display Settings"},
            {"show_item_icons", "Show Item Icons"},
            {"show_item_icons_tooltip", "Display item icons in the list"},
            {"show_rarity_border", "Show Rarity Border"},
            {"show_rarity_border_tooltip", "Display colored border based on item rarity"},
            {"enable_grid_view", "Enable Grid View"},
            {"enable_grid_view_tooltip", "Display items in a grid layout instead of list"},
            {"grid_icon_size", "Grid Icon Size"},
            {"grid_icon_size_tooltip", "Size of icons in grid view"},

            // Count Display Settings
            {"count_display_settings", "Count Display Settings"},
            {"count_text_color", "Count Text Color"},
            {"count_text_color_tooltip", "Color of count text"},
            {"count_background_color", "Count Background Color"},
            {"count_background_color_tooltip", "Color of count background"},
            {"count_font_size", "Count Font Size"},
            {"count_font_size_tooltip", "Size of count font"},
            {"count_horizontal_alignment", "Count Horizontal Alignment"},
            {"count_horizontal_alignment_tooltip", "Horizontal alignment of count text"},

            // Gradient Background Settings
            {"gradient_background_settings", "Gradient Background Settings"},
            {"enable_gradient_backgrounds", "Enable Gradient Backgrounds"},
            {"enable_gradient_backgrounds_tooltip", "Enable gradient background for windows"},
            {"gradient_top_color", "Gradient Top Color"},
            {"gradient_top_color_tooltip", "Top color of gradient background"},
            {"gradient_bottom_color", "Gradient Bottom Color"},
            {"gradient_bottom_color_tooltip", "Bottom color of gradient background"},

            // Custom Profit System
            {"custom_profit_system", "Custom Profit System"},
            {"enable_custom_profit", "Enable Custom Profit"},
            {"enable_custom_profit_tooltip", "Enable custom profit values for items"},

            // Search
            {"search_settings", "Search"},
            {"enable_search", "Enable Search"},
            {"enable_search_tooltip", "Enable search functionality"},

            // Ignored Items
            {"ignored_items_settings", "Ignored Items"},
            {"enable_ignored_items", "Enable Ignored Items"},
            {"enable_ignored_items_tooltip", "Enable ignored items functionality"},

            // Auto Reset
            {"auto_reset_settings", "Auto Reset"},
            {"enable_auto_reset", "Enable Auto Reset"},
            {"enable_auto_reset_tooltip", "Automatically reset farming session after a duration"},
            {"auto_reset_duration", "Auto Reset Duration (minutes)"},
            {"auto_reset_duration_tooltip", "Duration in minutes before auto reset"},

            // DRF Settings
            {"drf_settings", "DRF Settings"},
            {"drf_token", "DRF Token"},
            {"drf_token_tooltip", "Your DRF authentication token"},
            {"edit_token", "Edit Token"},
            {"save_token", "Save Token"},

            // GW2 API Settings
            {"gw2_api_settings", "GW2 API Settings"},
            {"gw2_api_key", "GW2 API Key"},
            {"gw2_api_key_tooltip", "Your GW2 API key for item details"},
            {"edit_key", "Edit Key"},
            {"save_key", "Save Key"},

            // Language Settings
            {"language_settings", "Language"},
            {"language_tooltip", "Select interface language"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "No accounts configured"},
            {"no_profiles_created", "No profiles created yet"},
            {"count_label", "Count:"},
            {"profit_label", "Profit:"},
            {"no_profit", "No profit"},
            {"vendor_value_label", "Vendor Value:"},
            {"tp_sell_gross_label", "TP Sell (Gross):"},
            {"tp_sell_net_label", "TP Sell (Net):"},
            {"tp_buy_gross_label", "TP Buy (Gross):"},
            {"tp_buy_net_label", "TP Buy (Net):"},
            {"ignored_items_label", "Ignored Items:"},
            {"ignored_currencies_label", "Ignored Currencies:"},
            {"total_items_label", "Total Items:"},
            {"total_currencies_label", "Total Currencies:"},
            {"total_profit_label", "Total Profit:"},
            {"tp_sell_profit_label", "TP Sell Profit:"},
            {"vendor_profit_label", "Vendor Profit:"},
            {"profit_per_hour_label", "Profit Per Hour:"},
            {"opportunity_cost_profit_label", "Opportunity Cost Profit:"},
            {"opportunity_cost_profit_per_hour_label", "Opportunity Cost Profit/Hour:"},
            {"custom_profit_feature_placeholder", "Feature implemented - UI follows"},
            {"custom_profit_items_header", "Items with Custom Profit"},
            {"custom_profit_currencies_header", "Currencies with Custom Profit"},
            {"add_custom_profit_item", "Add Custom Profit for Item"},
            {"add_custom_profit_currency", "Add Custom Profit for Currency"},
            {"custom_profit_set_profit", "Set Profit"},
            {"custom_profit_remove", "Remove"},
            {"custom_profit_value", "Profit Value (Copper)"},
            {"custom_profit_set_tooltip", "Set custom profit value for this item"},
            {"custom_profit_remove_tooltip", "Remove custom profit value for this item"},
            {"no_custom_profit_items", "(No items with custom profit)"},
            {"no_custom_profit_currencies", "(No currencies with custom profit)"},
            {"clear_all_custom_profits", "Clear All Custom Profits"},
            {"clear_all_custom_profits_tooltip", "Clear all custom profit values"},
            {"tabs_settings", "Other Tabs"},
            {"tabs_description", "Show or hide other tabs"},
            {"enable_ignored_tab", "Enable Ignored Tab"},
            {"enable_ignored_tab_tooltip", "Show Ignored tab in main view"},
            {"custom_profit_settings", "Custom Profit"},
            {"overview_label", "Overview:"},
            {"total_profit_label_simple", "Total Profit"},
            {"total_items_label_simple", "Total Items"},
            {"total_currencies_label_simple", "Total Currencies"},
            {"profit_per_hour_label_simple", "Profit Per Hour"},
            {"session_duration_label_simple", "Session Duration"},
            {"export_label", "Export:"},
            {"quick_actions", "Quick Actions:"},
            {"reset_confirm", "Are you sure you want to reset all settings to defaults?"},
            {"reset_warning", "This action cannot be undone."},
            {"export_settings", "Export Settings to File:"},
            {"import_settings", "Import Settings from File:"},
            {"edit_account", "Edit Account: %s"},
            {"account_name", "Account Name:"},
            {"drf_token_label", "DRF Token:"},
            {"gw2_api_key_label", "GW2 API Key:"},
            {"reload_config", "Reload Configuration:"},
            {"auto_reset_label", "Automatic reset:"},
            {"next_reset_utc", "Next scheduled reset (UTC): %s"},
            {"favorites_ui", "Favorites UI:"},
            {"favorites_colors", "Favorites Colors:"},
            {"visual_enhancements", "Visual Enhancements:"},
            {"mini_window_widget", "Mini Window (Overlay Widget):"},
            {"main_window_label", "Main Window:"},
            {"profiles_description", "Profiles allow you to save different configurations and switch between them quickly."},
            {"create_new_profile", "Create New Profile:"},
            {"current_profile", "Current Profile: %s"},
            {"auto_backup", "Automatically backup your settings before major changes"},
            {"notifications", "Configure in-game notifications for important events"},
            {"profit_goal", "Profit Goal:"},
            {"reset_warning_label", "Reset Warning:"},
            {"session_complete", "Session Complete:"},
            {"manage_ignored_items", "Manage ignored items"},
            {"manage_ignored_currencies", "Manage ignored currencies"},
            {"rarity_label", "Rarity: %s"},
            {"type_label", "Type: %d"},
            {"account_bound_label", "Account Bound: %s"},
            {"nosell_label", "NoSell: %s"},
            {"item_id_label", "Item ID: %d"},
            {"currency_id_label", "Currency ID: %d"},
            {"sell_method_filters_label", "Sell Method Filters:"},
            {"api_knowledge_filters_label", "API Knowledge Filters:"},
            {"additional_filters_label", "Additional Filters:"},
            {"item_type_filters_label", "Item Type Filters:"},
            {"currency_filters_label", "Currency Filters:"},
            {"price_range", "Price Range (Copper):"},
            {"quantity_range", "Quantity Range:"},
            {"debug_info", "Debug Information"},
            {"drf_status", "DRF Status: %s"},
            {"drf_reconnect_count", "DRF Reconnect Count: %d"},
            {"gw2_api_status", "GW2 API Status: %s"},
            {"gw2_api_reconnect_count", "GW2 API Reconnect Count: %d"},
            {"session_duration_debug", "Session Duration: %s"},
            {"gw2_memory", "GW2 Process Memory: %zu MB"},
            {"gw2_api_request_count", "GW2 API Request Count: %d"},
            {"ignored_items_count", "Ignored Items: %d"},
            {"ignored_currencies_count", "Ignored Currencies: %d"},
            {"drf_logs", "DRF Logs:"},
            {"last_100_entries", "(Last 100 entries)"},
            {"gw2_api_logs", "GW2 API Logs:"},
            {"item_currency_details", "Item/Currency Details (First 5):"},
            {"item_label", "Item %d: %s (Count: "},
            {"loaded_label", ", Loaded: %s)"},
            {"currency_label", "Currency %d: %s (Count: "},
            {"custom_profit_items", "Custom Profit Items (First 5):"},
            {"custom_profit_item", "Item %d: %s (Custom Profit: "},
            {"no_custom_profit_items", "(No custom profit items)"},
            {"ignored_items_debug", "Ignored Items (First 5):"},
            {"yes_label", "Yes"},
            {"no_label", "No"},
            {"profits_label", "Profits:"},
            {"profits_tooltip", "Total profits from farming"},
            {"approx_profits_label", "Approx. Profits:"},
            {"approx_profits_tooltip", "Total profit from custom profit values"},
            {"approx_gold_per_hour_label", "Approx. Gold Per Hour:"},
            {"approx_gold_per_hour_tooltip", "Profit per hour based on session duration"},
            {"trading_profits_label", "Trading Profits:"},
            {"trading_profits_tooltip", "Profits from selling items on Trading Post"},
            {"approx_trading_profits_listings_label", "Approx. Trading Profits (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Total profit if sold via TP listings"},
            {"approx_trading_profits_instant_label", "Approx. Trading Profits (Instant Sell):"},
            {"approx_trading_profits_instant_tooltip", "Total profit if sold via TP instant buy orders"},
            {"trading_details_label", "Trading Details (Opportunity Cost):"},
            {"trading_details_tooltip", "Profit lost by not selling via TP listings"},
            {"lost_profit_vs_tp_sell_label", "Lost Profit (vs TP Sell):"},
            {"lost_profit_vs_tp_sell_tooltip", "Gold = profit lost, Red = profit gained vs TP sell"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Lost Profit Per Hour (vs TP Sell):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Opportunity cost per hour"},
            {"session_duration_debug_label", "Session duration: %s"},
            {"session_duration_debug_tooltip", "Current farming session duration"},
            {"tab_items", "Items"},
            {"manage_ignored_items", "Manage ignored items"},
            {"clear_all_ignored_items", "Clear All Ignored Items"},
            {"unignore_item", "Unignore item"},
            {"tab_currencies", "Currencies"},
            {"manage_ignored_currencies", "Manage ignored currencies"},
            {"clear_all_ignored_currencies", "Clear All Ignored Currencies"},
            {"unignore_currency", "Unignore currency"},
            {"sell_method_filters_label", "Sell Method Filters:"},
            {"api_knowledge_filters_label", "API Knowledge Filters:"},
            {"additional_filters_label", "Additional Filters:"},
            {"item_type_filters_label", "Item Type Filters:"},
            {"currency_filters_label", "Currency Filters:"},
            {"price_range", "Price Range (Copper):"},
            {"quantity_range", "Quantity Range:"},
            {"debug_information", "Debug Information"},
            {"drf_status_label", "DRF Status: %s"},
            {"drf_status_tooltip", "Current DRF connection status"},
            {"drf_reconnect_count_label", "DRF Reconnect Count: %d"},
            {"drf_reconnect_count_tooltip", "Number of DRF reconnection attempts"},
            {"gw2_api_status_label", "GW2 API Status: %s"},
            {"gw2_api_status_tooltip", "Current GW2 API connection status"},
            {"gw2_api_reconnect_count_label", "GW2 API Reconnect Count: %d"},
            {"gw2_api_reconnect_count_tooltip", "Number of GW2 API reconnection attempts"},
            {"session_duration_debug", "Session Duration: %s"},
            {"session_duration_debug_tooltip", "Current farming session duration"},
            {"gw2_process_memory_label", "GW2 Process Memory: %zu MB"},
            {"gw2_process_memory_tooltip", "Current GW2 process memory usage"},
            {"gw2_api_request_count_label", "GW2 API Request Count: %d"},
            {"gw2_api_request_count_tooltip", "Total number of GW2 API requests made"},
            {"ignored_items_debug_label", "Ignored Items: %d"},
            {"ignored_items_debug_tooltip", "Number of ignored items"},
            {"ignored_currencies_debug_label", "Ignored Currencies: %d"},
            {"ignored_currencies_debug_tooltip", "Number of ignored currencies"},
            {"drf_logs_label", "DRF Logs:"},
            {"clear_drf_logs", "Clear DRF Logs"},
            {"clear_drf_logs_tooltip", "Clear all DRF log entries"},
            {"last_100_entries", "(Last 100 entries)"},
            {"gw2_api_logs_label", "GW2 API Logs:"},
            {"clear_gw2_logs", "Clear GW2 Logs"},
            {"clear_gw2_logs_tooltip", "Clear all GW2 API log entries"},
            {"settings_label", "Settings:"},
            {"api_key_label", "API Key: %s"},
            {"api_key_tooltip", "GW2 API key status"},
            {"not_set", "Not set"},
            {"set", "Set"},
            {"drf_token_label", "DRF Token: %s"},
            {"drf_token_tooltip", "DRF token status"},
            {"toggle_hotkey_label", "Toggle Hotkey: %s"},
            {"toggle_hotkey_tooltip", "Main window toggle hotkey"},
            {"auto_reset_mode_label", "Auto-Reset Mode: %d"},
            {"auto_reset_mode_tooltip", "Current automatic reset mode"},
            {"next_reset_label", "Next Reset: %s"},
            {"next_reset_tooltip", "Next scheduled reset time (UTC)"},
            {"fake_drf_server_label", "Fake DRF Server:"},
            {"use_fake_drf_server", "Use fake DRF server"},
            {"use_fake_drf_server_tooltip", "For testing purposes only"},
            {"reset_all_data", "Reset All Data"},
            {"reset_all_data_tooltip", "Reset all farming data"},
            {"coin", "Coin"},
            {"rarity_label", "Rarity: %s"},
            {"type_label", "Type: %d"},
            {"account_bound_label", "Account-bound: %s"},
            {"nosell_label", "NoSell: %s"},
            {"yes_label", "Yes"},
            {"no_label", "No"},
            {"sort_price_down", "Sort: Item Price down"},
            {"sort_price_up", "Sort: Item Price up"},
            {"sort_count_high", "Sort: |Count| high"},
            {"sort_count_low", "Sort: |Count| low"},
            {"sort_name_az", "Sort: Name A–Z"},
            {"sort_tooltip", "Sort items by count, ID, or name"},
            {"rarity_all", "Rarity: all"},
            {"rarity_basic", "Rarity: Basic+"},
            {"rarity_fine", "Rarity: Fine+"},
            {"rarity_masterwork", "Rarity: Masterwork+"},
            {"rarity_rare", "Rarity: Rare+"},
            {"rarity_exotic", "Rarity: Exotic+"},
            {"rarity_ascended", "Rarity: Ascended+"},
            {"rarity_legendary", "Rarity: Legendary only"},
            {"rarity_tooltip", "Filter items by minimum rarity"},
            {"search_items_hint", "Search items..."},
            {"column_icon", "Icon"},
            {"column_name", "Name"},
            {"column_count", "Count"},
            {"column_profit", "Profit"},
            {"column_favorite", "Favorite"},
            {"column_ignore", "Ignore"},
            {"toggle_favorite", "Toggle favorite"},
            {"toggle_ignore", "Toggle ignore"},
            {"vendor_value_format", "Vendor Value: %s"},
            {"tp_sell_gross_format", "TP Sell (Gross): %s"},
            {"tp_sell_net_format", "TP Sell (Net): %s"},
            {"tp_buy_gross_format", "TP Buy (Gross): %s"},
            {"tp_buy_net_format", "TP Buy (Net): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Favorites Settings"},
            {"favorites_first", "Favorites first"},
            {"favorites_first_tooltip", "Shows favorites first in item/currency lists"},
            {"enable_favorite_text_color", "Enable favorite text color"},
            {"enable_favorite_text_color_tooltip", "Highlights favorite items/currencies with custom text color"},
            {"text_color", "Text Color"},
            {"enable_favorite_row_color", "Enable favorite row color"},
            {"enable_favorite_row_color_tooltip", "Highlights favorite items/currencies with custom row background color"},
            {"row_color", "Row Color"},
            
            // Filter - Additional
            {"filter_favorite", "Favorite"},
            {"filter_favorite_tooltip", "Show favorite items (outside Favorites tab)"},
            {"filter_not_favorite", "Not Favorite"},
            {"filter_research_notes", "Research Notes"},
            {"filter_research_notes_tooltip", "Show research notes currency"},
            {"range_filters", "Range Filters"},
            {"range_filters_tooltip", "Show price and quantity range filters"},
            {"filter_min_price_tooltip", "Minimum price filter (0 = disabled)"},
            {"filter_max_price_tooltip", "Maximum price filter (0 = disabled)"},
            {"filter_min_quantity_tooltip", "Minimum quantity filter (0 = disabled)"},
            {"filter_max_quantity_tooltip", "Maximum quantity filter (0 = disabled)"},
            {"filter_min_price", "Min Price"},
            {"filter_max_price", "Max Price"},
            {"filter_min_quantity", "Min Quantity"},
            {"filter_max_quantity", "Max Quantity"},
            
            // Currencies Tab
            {"search_currencies_hint", "Search currencies..."},
            {"clear_search", "Clear"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Search favorite items..."},
            {"search_favorite_currencies_hint", "Search favorite currencies..."},
            {"clear_search_favorites", "Clear"},
            
            // Summary Tab - Table Columns
            {"column_label", "Label"},
            {"column_value", "Value"},
            {"column_item", "Item"},
            {"column_count", "Count"},
            {"column_currency", "Currency"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Items by Profit"},
            {"top_items_count_header", "Top Items (Count)"},
            {"top_currencies_count_header", "Top Currencies (Count)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 items by profit value"},
            {"top_items_count_tooltip", "Top 10 items by count"},
            {"top_currencies_count_tooltip", "Top 10 currencies by count"},
            
            // Settings Tab - General
            {"show_main_window", "Show main window"},
            {"reset_all", "Reset All"},
            {"reset_all_tooltip", "Reset all settings to default values"},
            {"export", "Export"},
            {"export_tooltip", "Export settings to a JSON file"},
            {"import", "Import"},
            {"import_tooltip", "Import settings from a JSON file"},
            {"save", "Save"},
            {"save_tooltip", "Save current settings"},
            {"general_settings", "General Settings"},
            {"account_management", "Account Management"},
            {"add_account", "+ Add Account"},
            {"remove_account", "- Remove Account"},
            {"save_account", "Save Account"},
            {"reload_drf_token", "Reload DRF Token"},
            {"reload_gw2_api_key", "Reload GW2 API Key"},
            {"reset_settings", "Auto Reset"},
            {"visual_settings", "Visual Settings"},
            {"gradient_backgrounds", "Gradient backgrounds"},
            {"gradient_backgrounds_tooltip", "Enables smooth gradient backgrounds for a more modern look"},
            {"top_gradient_color", "Top gradient color"},
            {"top_gradient_color_tooltip", "Top gradient color"},
            {"bottom_gradient_color", "Bottom gradient color"},
            {"bottom_gradient_color_tooltip", "Bottom gradient color"},
            {"show_item_icons", "Show item icons (GW2 render)"},
            {"show_item_icons_tooltip", "Loads icons from render.guildwars2.com via Nexus."},
            {"icon_size", "Icon Size"},
            {"icon_size_tooltip", "Size of item icons in pixels (16-96)"},
            {"show_rarity_borders", "Show rarity borders"},
            {"show_rarity_borders_tooltip", "Shows colored borders around icons based on item rarity"},
            {"rarity_border_thickness", "Rarity Border Thickness"},
            {"rarity_border_thickness_tooltip", "Adjust the thickness of rarity borders (1.0 - 10.0)"},
            {"enable_grid_view_items", "Enable Grid View (Items)"},
            {"enable_grid_view_items_tooltip", "Toggle between list and grid view in Items tab"},
            {"grid_icon_size_items", "Grid Icon Size (Items)"},
            {"grid_icon_size_items_tooltip", "Size of icons in grid view for Items (16-128)"},
            {"enable_grid_view_currencies", "Enable Grid View (Currencies)"},
            {"enable_grid_view_currencies_tooltip", "Toggle between list and grid view in Currencies tab"},
            {"grid_icon_size_currencies", "Grid Icon Size (Currencies)"},
            {"grid_icon_size_currencies_tooltip", "Size of icons in grid view for Currencies (16-128)"},
            {"show_mini_window", "Show mini window"},
            {"show_mini_window_tooltip", "Shows a small overlay widget with key statistics"},
            {"mini_window_show_profit", "Show Profit"},
            {"mini_window_show_profit_tooltip", "Display total profit in mini window"},
            {"mini_window_show_profit_per_hour", "Show Profit/Hour"},
            {"mini_window_show_profit_per_hour_tooltip", "Display profit per hour in mini window"},
            {"mini_window_show_tp_sell", "Show TP Sell (Listings)"},
            {"mini_window_show_tp_sell_tooltip", "Display TP sell profit (listings) in mini window"},
            {"mini_window_show_tp_instant", "Show TP Instant (Instant Sell)"},
            {"mini_window_show_tp_instant_tooltip", "Display TP instant sell profit in mini window"},
            {"mini_window_show_total_items", "Show Total Items"},
            {"mini_window_show_total_items_tooltip", "Display total item count in mini window"},
            {"mini_window_show_session_duration", "Show Session Duration"},
            {"mini_window_show_session_duration_tooltip", "Display session duration in mini window"},
            {"mini_window_click_through", "Window click through"},
            {"mini_window_click_through_tooltip", "Allows clicking through the mini window to the game"},
            {"main_window_click_through", "Click through"},
            {"main_window_click_through_tooltip", "Allows clicking through the main window to the game"},
            {"settings_profiles", "Settings Profiles"},
            {"select_profile", "Select a profile to apply its settings"},
            {"create_new_profile", "Create New Profile"},
            {"create_new_profile_tooltip", "Create a new profile with current settings"},
            {"create", "Create"},
            {"update_profile", "Update Profile"},
            {"update_profile_tooltip", "Update current profile with current settings"},
            {"delete_profile", "Delete Profile"},
            {"delete_profile_tooltip", "Delete current profile"},
            {"automatic_backups", "Automatic Backups"},
            {"enable_automatic_backups", "Enable automatic backups"},
            {"enable_automatic_backups_tooltip", "Automatically create backups before changes"},
            {"backup_frequency", "Backup Frequency"},
            {"backup_frequency_tooltip", "How often to create automatic backups"},
            {"max_backups", "Maximum Backups"},
            {"max_backups_tooltip", "Maximum number of backups to keep (1-20)"},
            {"notification_settings", "Notification Settings"},
            {"enable_notifications", "Enable notifications"},
            {"enable_notifications_tooltip", "Enable in-game notifications"},
            {"notify_profit_goal", "Notify when profit goal reached"},
            {"notify_profit_goal_tooltip", "Notify when you reach your profit goal"},
            {"profit_goal_gold", "Profit Goal (Gold)"},
            {"profit_goal_gold_tooltip", "Profit goal in gold coins (1-1000)"},
            {"notify_reset_warning", "Notify before reset"},
            {"notify_reset_warning_tooltip", "Notify before automatic reset occurs"},
            {"reset_warning_minutes", "Reset Warning (Minutes)"},
            {"reset_warning_minutes_tooltip", "Minutes before reset to show warning (1-60)"},
            {"notify_session_complete", "Notify after session duration"},
            {"notify_session_complete_tooltip", "Notify after farming for a certain duration"},
            {"session_complete_hours", "Session Complete (Hours)"},
            {"session_complete_hours_tooltip", "Hours of farming before notification (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Sellable to vendor"},
            {"filter_sellable_to_vendor_tooltip", "Show items sellable to vendor"},
            {"filter_sellable_on_tp", "Sellable on TP"},
            {"filter_sellable_on_tp_tooltip", "Show items sellable on Trading Post"},
            {"filter_custom_profit", "Has custom profit"},
            {"filter_custom_profit_tooltip", "Show items with custom profit set"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Known by API"},
            {"filter_known_by_api_tooltip", "Show items known by GW2 API"},
            {"filter_unknown_by_api", "Unknown by API"},
            {"filter_unknown_by_api_tooltip", "Show items not known by GW2 API"},
            
            // Filter - Additional
            {"show_ignored_items", "Show ignored items"},
            {"show_ignored_items_tooltip", "Show ignored items/currencies in Items and Currencies tabs (disable to hide). Difference from 'Ignored' filter: This filter controls display in Items/Currencies tabs, the 'Ignored' filter controls display in Filter tab."},
            
            // Filter - Item Types
            {"filter_type_armor", "Armor"},
            {"filter_type_armor_tooltip", "Show armor items"},
            {"filter_type_backpack", "Backpack"},
            {"filter_type_backpack_tooltip", "Show backpack items"},
            {"filter_type_bag", "Bag"},
            {"filter_type_bag_tooltip", "Show bags"},
            {"filter_type_container", "Container"},
            {"filter_type_container_tooltip", "Show containers"},
            {"filter_type_consumable", "Consumable"},
            {"filter_type_consumable_tooltip", "Show consumable items"},
            {"filter_type_crafting_material", "Crafting Material"},
            {"filter_type_crafting_material_tooltip", "Show crafting materials"},
            {"filter_type_gathering_tool", "Gathering Tool"},
            {"filter_type_gathering_tool_tooltip", "Show gathering tools"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Show gizmo items"},
            {"filter_type_gizmo_container", "Gizmo Container"},
            {"filter_type_gizmo_container_tooltip", "Show gizmo container items"},
            {"filter_type_mini_pet", "Mini Pet"},
            {"filter_type_mini_pet_tooltip", "Show mini pets"},
            {"filter_type_tool", "Tool"},
            {"filter_type_tool_tooltip", "Show tool items"},
            {"filter_type_trinket", "Trinket"},
            {"filter_type_trinket_tooltip", "Show trinket items"},
            {"filter_type_trophy", "Trophy"},
            {"filter_type_trophy_tooltip", "Show trophy items"},
            {"filter_type_unlock", "Unlock"},
            {"filter_type_unlock_tooltip", "Show unlock items"},
            {"filter_type_upgrade_component", "Upgrade Component"},
            {"filter_type_upgrade_component_tooltip", "Show upgrade components"},
            {"filter_type_weapon", "Weapon"},
            {"filter_type_weapon_tooltip", "Show weapon items"},
            
            // Filter - Currencies (all tooltips need to be added)
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Show karma currency"},
            {"filter_laurel", "Laurel"},
            {"filter_laurel_tooltip", "Show laurel currency"},
            {"filter_gem", "Gem"},
            {"filter_gem_tooltip", "Show gem currency"},
            {"filter_fractal_relic", "Fractal Relic"},
            {"filter_fractal_relic_tooltip", "Show fractal relic currency"},
            {"filter_badge_of_honor", "Badge of Honor"},
            {"filter_badge_of_honor_tooltip", "Show badge of honor currency"},
            {"filter_guild_commendation", "Guild Commendation"},
            {"filter_guild_commendation_tooltip", "Show guild commendation currency"},
            {"filter_transmutation_charge", "Transmutation Charge"},
            {"filter_transmutation_charge_tooltip", "Show transmutation charge currency"},
            {"filter_spirit_shards", "Spirit Shards"},
            {"filter_spirit_shards_tooltip", "Show spirit shards currency"},
            {"filter_unbound_magic", "Unbound Magic"},
            {"filter_unbound_magic_tooltip", "Show unbound magic currency"},
            {"filter_volatile_magic", "Volatile Magic"},
            {"filter_volatile_magic_tooltip", "Show volatile magic currency"},
            {"filter_airship_parts", "Airship Parts"},
            {"filter_airship_parts_tooltip", "Show airship parts currency"},
            {"filter_geode", "Geode"},
            {"filter_geode_tooltip", "Show geode currency"},
            {"filter_ley_line_crystals", "Ley-Line Crystals"},
            {"filter_ley_line_crystals_tooltip", "Show ley-line crystals currency"},
            {"filter_trade_contracts", "Trade Contracts"},
            {"filter_trade_contracts_tooltip", "Show trade contracts currency"},
            {"filter_elegy_mosaic", "Elegy Mosaic"},
            {"filter_elegy_mosaic_tooltip", "Show elegy mosaic currency"},
            {"filter_uncommon_coins", "Uncommon Coins"},
            {"filter_uncommon_coins_tooltip", "Show uncommon coins currency"},
            {"filter_astral_acclaim", "Astral Acclaim"},
            {"filter_astral_acclaim_tooltip", "Show astral acclaim currency"},
            
            // Debug Tab
            {"total_tracked_items", "Total number of tracked items"},
            {"total_tracked_items_tooltip", "Total number of tracked items"},
            {"total_tracked_currencies", "Total number of tracked currencies"},
            {"total_tracked_currencies_tooltip", "Total number of tracked currencies"},
            {"total_custom_profit", "Total custom profit"},
            {"total_custom_profit_tooltip", "Total custom profit"},
            {"total_tp_sell_profit", "Total TP sell profit"},
            {"total_tp_sell_profit_tooltip", "Total TP sell profit"},
            {"total_vendor_sell_profit", "Total vendor sell profit"},
            {"total_vendor_sell_profit_tooltip", "Total vendor sell profit"},
            {"profit_per_hour_calculation", "Profit per hour calculation"},
            {"profit_per_hour_calculation_tooltip", "Profit per hour calculation"},
            {"opportunity_cost_vs_tp_sell", "Opportunity cost vs TP sell"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Opportunity cost vs TP sell"},
            {"opportunity_cost_per_hour", "Opportunity cost per hour"},
            {"opportunity_cost_per_hour_tooltip", "Opportunity cost per hour"},
            {"first_5_tracked_items", "First 5 tracked items and currencies with details"},
            {"first_5_tracked_items_tooltip", "First 5 tracked items and currencies with details"},
            {"first_5_custom_profit", "First 5 items with custom profit set"},
            {"first_5_custom_profit_tooltip", "First 5 items with custom profit set"},
            {"first_5_ignored_items", "First 5 ignored items"},
            {"first_5_ignored_items_tooltip", "First 5 ignored items"},
            
            // Debug Settings
            {"debug_settings", "Debug Settings"},
            {"enable_debug_tab", "Enable Debug Tab"},
            {"enable_debug_tab_tooltip", "Shows the debug tab with additional information"},
            
            // Currencies Tab
            {"gold_format", "Gold: %lld"},
            {"count_format", "Count: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Toggle favorite"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Toggle ignore"},
            
            // Additional Filters
            {"filter_account_bound", "Account-bound"},
            {"filter_account_bound_tooltip", "Show account-bound items"},
            {"filter_not_account_bound", "Not Account-bound"},
            {"filter_not_account_bound_tooltip", "Show non-account-bound items"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "Show NoSell items"},
            {"filter_not_nosell", "Not NoSell"},
            {"filter_not_nosell_tooltip", "Show sellable items"},
            {"filter_ignored", "Ignored"},
            {"filter_ignored_tooltip", "Show ignored items"},
            {"filter_not_ignored", "Not Ignored"},
            {"filter_not_ignored_tooltip", "Show non-ignored items"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Pristine Fractal Relics"},
            {"filter_pristine_fractal_relics_tooltip", "Show pristine fractal relics currency"},
            {"filter_unstable_fractal_essence", "Unstable Fractal Essence"},
            {"filter_unstable_fractal_essence_tooltip", "Show unstable fractal essence currency"},
            {"filter_magnetite_shards", "Magnetite Shards"},
            {"filter_magnetite_shards_tooltip", "Show magnetite shards currency"},
            {"filter_gaeting_crystals", "Gaeting Crystals"},
            {"filter_gaeting_crystals_tooltip", "Show gaeting crystals currency"},
            {"filter_prophet_shards", "Prophet Shards"},
            {"filter_prophet_shards_tooltip", "Show prophet shards currency"},
            {"filter_green_prophet_shards", "Green Prophet Shards"},
            {"filter_green_prophet_shards_tooltip", "Show green prophet shards currency"},
            {"filter_wvw_skirmish_tickets", "WvW Skirmish Tickets"},
            {"filter_wvw_skirmish_tickets_tooltip", "Show WvW skirmish tickets currency"},
            {"filter_proofs_of_heroics", "Proofs of Heroics"},
            {"filter_proofs_of_heroics_tooltip", "Show proofs of heroics currency"},
            {"filter_pvp_league_tickets", "PvP League Tickets"},
            {"filter_pvp_league_tickets_tooltip", "Show PvP league tickets currency"},
            {"filter_ascended_shards_of_glory", "Ascended Shards of Glory"},
            {"filter_ascended_shards_of_glory_tooltip", "Show ascended shards of glory currency"},
            {"filter_tyrian_defense_seal", "Tyrian Defense Seal"},
            {"filter_tyrian_defense_seal_tooltip", "Show tyrian defense seal currency"},
            {"filter_testimony_of_desert_heroics", "Testimony of Desert Heroics"},
            {"filter_testimony_of_desert_heroics_tooltip", "Show testimony of desert heroics currency"},
            {"filter_testimony_of_jade_heroics", "Testimony of Jade Heroics"},
            {"filter_testimony_of_jade_heroics_tooltip", "Show testimony of jade heroics currency"},
            {"filter_testimony_of_castoran_heroics", "Testimony of Castoran Heroics"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Show testimony of castoran heroics currency"},
            {"filter_legendary_insight", "Legendary Insight"},
            {"filter_legendary_insight_tooltip", "Show legendary insight currency"},
            {"filter_tales_of_dungeon_delving", "Tales of Dungeon Delving"},
            {"filter_tales_of_dungeon_delving_tooltip", "Show tales of dungeon delving currency"},
            {"filter_imperial_favor", "Imperial Favor"},
            {"filter_imperial_favor_tooltip", "Show imperial favor currency"},
            {"filter_canach_coins", "Canach Coins"},
            {"filter_canach_coins_tooltip", "Show canach coins currency"},
            {"filter_ancient_coin", "Ancient Coin"},
            {"filter_ancient_coin_tooltip", "Show ancient coin currency"},
            {"filter_unusual_coin", "Unusual Coin"},
            {"filter_unusual_coin_tooltip", "Show unusual coin currency"},
            {"filter_jade_sliver", "Jade Sliver"},
            {"filter_jade_sliver_tooltip", "Show jade sliver currency"},
            {"filter_static_charge", "Static Charge"},
            {"filter_static_charge_tooltip", "Show static charge currency"},
            {"filter_pinch_of_stardust", "Pinch of Stardust"},
            {"filter_pinch_of_stardust_tooltip", "Show pinch of stardust currency"},
            {"filter_calcified_gasp", "Calcified Gasp"},
            {"filter_calcified_gasp_tooltip", "Show calcified gasp currency"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Show ursus oblige currency"},
            {"filter_gaeting_crystal_janthir", "Gaeting Crystal (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Show gaeting crystal (janthir) currency"},
            {"filter_antiquated_ducat", "Antiquated Ducat"},
            {"filter_antiquated_ducat_tooltip", "Show antiquated ducat currency"},
            {"filter_aether_rich_sap", "Aether-Rich Sap"},
            {"filter_aether_rich_sap_tooltip", "Show aether-rich sap currency"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Reset All"},
            {"reset_all_tooltip", "Reset all settings to default values"},
            {"reset_confirm", "Are you sure you want to reset all settings?"},
            {"reset_warning", "This action cannot be undone."},
            {"yes_reset", "Yes, Reset"},
            {"cancel", "Cancel"},
            {"export", "Export"},
            {"export_tooltip", "Export settings to a JSON file"},
            {"export_settings", "Export Settings"},
            {"import", "Import"},
            {"import_settings", "Import Settings"},
            {"save", "Save"},
            {"save_tooltip", "Save current settings"},
            
            // Settings Tab - General
            {"general_settings", "General Settings"},
            {"account_management", "Account Management"},
            {"account_prefix", "Account"},
            {"remove_account", "- Remove Account"},
            {"save_account", "Save Account"},
            {"reconnect_drf_token", "Reconnect to DRF with the current token"},
            {"reload_gw2_api_key_tooltip", "Reload GW2 API key for item data fetching"},
            {"reset_settings", "Auto Reset"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Never (manual Reset only)"},
            {"auto_reset_on_load", "On addon load"},
            {"auto_reset_daily", "Daily reset (00:00 UTC)"},
            {"auto_reset_weekly", "Weekly (Mon 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Weekly NA WvW (Sat 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Weekly EU WvW (Fri 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Weekly map bonus (Thu 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minutes after last unload"},
            {"auto_reset_custom_days", "Custom (days)"},
            {"auto_reset_tooltip", "When to automatically reset farming counters"},
            {"minutes_after_unload_tooltip", "Minutes after addon unload before automatic reset"},
            {"reset_interval_days", "Reset interval (days)"},
            {"reset_interval_days_tooltip", "Custom reset interval in days (1-30 days)"},
            
            // Visual Settings
            {"top_gradient_color", "Top"},
            {"top_gradient_color_tooltip", "Top gradient color"},
            {"bottom_gradient_color", "Bottom"},
            {"bottom_gradient_color_tooltip", "Bottom gradient color"},
            {"icon_size", "Icon size"},
            {"icon_size_tooltip", "Size of item icons in pixels (16-96)"},
            {"border_size", "Border Size"},
            {"border_size_tooltip", "Adjust the thickness of rarity borders (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Toggle between list and grid view in Items tab"},
            {"grid_icon_size_items", "Grid Icon size (Items)"},
            {"grid_icon_size_items_tooltip", "Size of icons in grid view for Items (16-128)"},
            {"grid_icon_size_currencies", "Grid Icon size (Currencies)"},
            {"grid_icon_size_currencies_tooltip", "Size of icons in grid view for Currencies (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Show mini window"},
            {"show_mini_window_tooltip", "Shows a small overlay widget with key statistics"},
            {"mini_window_show_profit", "Show Profit"},
            {"mini_window_show_profit_tooltip", "Display total profit in mini window"},
            {"mini_window_show_profit_per_hour", "Show Profit/Hour"},
            {"mini_window_show_profit_per_hour_tooltip", "Display profit per hour in mini window"},
            {"mini_window_show_tp_sell", "Show TP Sell (Listings)"},
            {"mini_window_show_tp_sell_tooltip", "Display TP sell profit (listings) in mini window"},
            {"mini_window_show_tp_instant", "Show TP Instant (Instant Sell)"},
            {"mini_window_show_tp_instant_tooltip", "Display TP instant sell profit in mini window"},
            {"mini_window_show_total_items", "Show Total Items"},
            {"mini_window_show_total_items_tooltip", "Display total item count in mini window"},
            {"mini_window_show_session_duration", "Show Session Duration"},
            {"mini_window_show_session_duration_tooltip", "Display session duration in mini window"},
            {"mini_window_click_through", "Window click through"},
            {"mini_window_click_through_tooltip", "Allows clicking through the mini window to the game"},
            
            // Main Window
            {"main_window_label", "Main Window"},
            {"main_window_click_through", "Click through"},
            {"main_window_click_through_tooltip", "Allows clicking through the main window to the game"},
            
            // Settings Profiles
            {"settings_profiles", "Settings Profiles"},
            {"default_no_profile", "Default (No Profile)"},
            {"select_profile_tooltip", "Select a profile to apply its settings"},
            {"create", "Create"},
            {"create_tooltip", "Create a new profile with current settings"},
            {"update_profile", "Update Profile"},
            {"update_profile_tooltip", "Update current profile with current settings"},
            {"delete_profile", "Delete Profile"},
            {"delete_profile_tooltip", "Delete current profile"},
            
            // Automatic Backups
            {"automatic_backups", "Automatic Backups"},
            {"enable_automatic_backups", "Enable automatic backups"},
            {"enable_automatic_backups_tooltip", "Automatically create backups before changes"},
            {"backup_frequency", "Backup frequency"},
            {"backup_frequency_tooltip", "How often to create automatic backups"},
            {"backup_manual_only", "Manual only"},
            {"backup_daily", "Daily"},
            {"backup_weekly", "Weekly"},
            {"max_backup_count", "Max backup count"},
            {"max_backup_count_tooltip", "Maximum number of backups to keep (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Notification Settings"},
            {"enable_notifications", "Enable notifications"},
            {"enable_notifications_tooltip", "Enable in-game notifications"},
            {"profit_goal", "Profit Goal"},
            {"notify_profit_goal", "Notify when profit goal reached"},
            {"notify_profit_goal_tooltip", "Notify when you reach your profit goal"},
            {"profit_goal_gold", "Profit goal (gold)"},
            {"profit_goal_gold_tooltip", "Profit goal in gold coins (1-1000)"},
            {"reset_warning_label", "Reset Warning"},
            {"notify_reset_warning", "Notify before reset"},
            {"notify_reset_warning_tooltip", "Notify before automatic reset occurs"},
            {"warning_minutes", "Warning minutes"},
            {"warning_minutes_tooltip", "Minutes before reset to show warning (1-60)"},
            {"session_complete", "Session Complete"},
            {"notify_session_complete", "Notify after session duration"},
            {"notify_session_complete_tooltip", "Notify after farming for a certain duration"},
            {"session_hours", "Session hours"},
            {"session_hours_tooltip", "Hours of farming before notification (1-24)"},
        };
        return translations;
    }
}
