// ---------------------------------------------------------------------------
// localization_pt.cpp – Portuguese translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetPortugueseTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Desconectado"},
            {"status_connecting", "Conectando..."},
            {"status_connected", "Conectado"},
            {"status_auth_failed", "Falha de autenticação – verifique o token"},
            {"status_reconnecting", "Reconectando..."},
            {"status_error", "Erro"},
            {"status_unknown", "Desconhecido"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Lucro"},
            {"profit_per_hour", "Lucro/Hora"},
            {"tp_sell", "Venda TP"},
            {"tp_instant", "Venda Instantânea TP"},
            {"total_items", "Total de Itens"},
            {"session", "Sessão"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "API GW2"},
            {"session_time_label", "Tempo da Sessão"},
            {"reset_button", "Redefinir"},
            {"reset_tooltip", "Redefinir todos os contadores de farming (redefinição manual)"},

            // Tabs
            {"tab_summary", "Visão Geral"},
            {"tab_items", "Itens"},
            {"tab_currencies", "Moedas"},
            {"tab_profit", "Lucro"},
            {"tab_favorites", "Favoritos"},
            {"tab_ignored", "Ignorados"},
            {"tab_filter", "Filtro"},
            {"tab_custom_profit", "Lucro Personalizado"},
            {"tab_debug", "Depuração"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF não conectado"},
            {"warning_drf_not_connected_desc", "Este plugin requer DRF para transmissão de dados."},
            {"warning_drf_install", "Instale o DRF via Nexus Addon Manager ou https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ Token DRF inválido"},
            {"warning_drf_token_invalid_desc", "Por favor verifique seu Token DRF nas Configurações."},
            {"warning_gw2_api_key_not_set", "⚠️ Chave API GW2 não definida"},
            {"warning_gw2_api_key_not_set_desc", "Por favor defina sua Chave API GW2 nas Configurações para detalhes dos itens."},
            {"overview", "Visão Geral"},
            {"overview_tooltip", "Visão geral da sessão de farming atual"},
            {"total_profit", "Lucro Total"},
            {"total_profit_tooltip", "Lucro personalizado total de todos os itens"},
            {"total_items_count", "Total de Itens"},
            {"total_items_tooltip", "Número total de itens únicos rastreados"},
            {"total_currencies", "Total de Moedas"},
            {"total_currencies_tooltip", "Número total de moedas únicas rastreadas"},
            {"profit_per_hour_label", "Lucro Por Hora"},
            {"profit_per_hour_tooltip", "Lucro por hora baseado na duração da sessão"},
            {"session_duration", "Duração da Sessão"},
            {"session_duration_tooltip", "Duração da sessão de farming atual"},
            {"top_items_profit", "Top Itens (Lucro)"},
            {"top_items_profit_tooltip", "Top 5 itens por valor de lucro"},
            {"loading", "Carregando..."},
            {"coin", "Moeda"},
            {"top_items_count", "Top Itens (Quantidade)"},
            {"top_items_count_tooltip", "Top 5 itens por quantidade"},
            {"top_currencies", "Top Moedas"},
            {"top_currencies_tooltip", "Top 5 moedas por quantidade"},
            {"quick_statistics", "Estatísticas Rápidas"},
            {"quick_statistics_tooltip", "Visão geral das estatísticas de farming"},
            {"average_item_value", "Valor Médio do Item"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Total de Itens Únicos"},
            {"warning_no_data", "⚠️ Nenhum dado carregado"},
            {"warning_no_data_desc", "Aguardando dados do DRF..."},
            {"export", "Exportar"},
            {"export_tooltip", "Exportar dados de farming para arquivo"},
            {"export_json", "Exportar como JSON"},
            {"export_csv", "Exportar como CSV"},

            // Items Tab
            {"search_hint", "Buscar itens..."},
            {"clear", "Limpar"},
            {"sort_count_high", "Ordenar: |Qtd| alto"},
            {"sort_count_low", "Ordenar: |Qtd| baixo"},
            {"sort_id_up", "Ordenar: ID Item alto"},
            {"sort_id_down", "Ordenar: ID Item baixo"},
            {"sort_name_az", "Ordenar: Nome A–Z"},
            {"sort_tooltip", "Ordenar itens por quantidade, ID ou nome"},
            {"rarity_all", "Raridade: todas"},
            {"rarity_basic", "Raridade: Básico+"},
            {"rarity_fine", "Raridade: Fino+"},
            {"rarity_masterwork", "Raridade: Obra-prima+"},
            {"rarity_rare", "Raridade: Raro+"},
            {"rarity_exotic", "Raridade: Exótico+"},
            {"rarity_ascended", "Raridade: Ascendido+"},
            {"rarity_legendary", "Raridade: Apenas Lendário"},
            {"rarity_tooltip", "Filtrar itens por raridade mínima"},
            {"rarity", "Raridade"},
            {"type", "Tipo"},
            {"vendor_value", "Valor do Vendedor"},
            {"tp_buy_net", "Compra TP (Líquido)"},
            {"account_bound", "Vinculado à Conta"},
            {"yes", "Sim"},
            {"no", "Não"},
            {"nosell", "Não vendável"},
            {"favorite", "Favorito"},
            {"ignore", "Ignorar"},

            // Currencies Tab
            {"search_currencies_hint", "Buscar moedas..."},
            {"api_id", "ID API"},
            {"currency_name", "Nome da Moeda"},
            {"count", "Quantidade"},

            // Profit Tab
            {"profits", "Lucros"},
            {"profits_tooltip", "Lucros totais do farming"},
            {"approx_profits", "Lucros Aprox."},
            {"approx_gold_per_hour", "Ouro Aprox. Por Hora"},
            {"trading_profits", "Lucros de Comércio"},
            {"trading_profits_tooltip", "Lucros do Posto de Comércio"},
            {"approx_trading_profits_listings", "Lucros de Comércio Aprox. (Listagens)"},
            {"approx_trading_profits_instant", "Lucros de Comércio Aprox. (Venda Instantânea)"},
            {"trading_details", "Detalhes de Comércio (Custo de Oportunidade)"},
            {"trading_details_tooltip", "Custo de oportunidade de usar itens em vez de vendê-los"},
            {"lost_profit_vs_tp_sell", "Lucro Perdido (vs Venda TP)"},
            {"lost_profit_per_hour_vs_tp_sell", "Lucro Perdido Por Hora (vs Venda TP)"},
            {"session_duration_label", "Duração da sessão"},
            {"session_duration_tooltip", "Duração da sessão de farming atual"},

            // Filter Tab
            {"sell_method_filters", "Filtros de Método de Venda"},
            {"sellable_to_vendor", "Vendível ao vendedor"},
            {"sellable_to_vendor_tooltip", "Mostrar itens vendíveis ao vendedor"},
            {"sellable_on_tp", "Vendível no TP"},
            {"sellable_on_tp_tooltip", "Mostrar itens vendíveis no Posto de Comércio"},
            {"has_custom_profit", "Tem lucro personalizado"},
            {"has_custom_profit_tooltip", "Mostrar itens com valores de lucro personalizados"},
            {"api_knowledge_filters", "Filtros de Conhecimento API"},
            {"known_by_api", "Conhecido pela API"},
            {"known_by_api_tooltip", "Mostrar itens conhecidos pela API GW2"},
            {"unknown_by_api", "Desconhecido pela API"},
            {"unknown_by_api_tooltip", "Mostrar itens desconhecidos pela API GW2"},
            {"item_type_filters", "Filtros de Tipo de Item"},
            {"type_armor", "Armadura"},
            {"type_armor_tooltip", "Mostrar itens de armadura"},
            {"type_weapon", "Arma"},
            {"type_weapon_tooltip", "Mostrar itens de arma"},
            {"type_trinket", "Adereço"},
            {"type_trinket_tooltip", "Mostrar itens de adereço"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Mostrar itens gizmo"},
            {"type_crafting_material", "Material de Criação"},
            {"type_crafting_material_tooltip", "Mostrar materiais de criação"},
            {"type_consumable", "Consumível"},
            {"type_consumable_tooltip", "Mostrar consumíveis"},
            {"type_gathering_tool", "Ferramenta de Coleta"},
            {"type_gathering_tool_tooltip", "Mostrar ferramentas de coleta"},
            {"type_bag", "Bolsa"},
            {"type_bag_tooltip", "Mostrar bolsas"},
            {"type_container", "Contêiner"},
            {"type_container_tooltip", "Mostrar contêineres"},
            {"type_mini_pet", "Mini Pet"},
            {"type_mini_pet_tooltip", "Mostrar mini pets"},
            {"currency_filters", "Filtros de Moedas"},
            {"currency_karma", "Karma"},
            {"currency_karma_tooltip", "Mostrar moeda Karma"},
            {"currency_laurel", "Louro"},
            {"currency_laurel_tooltip", "Mostrar moeda Louro"},
            {"currency_gem", "Gema"},
            {"currency_gem_tooltip", "Mostrar moeda Gema"},
            {"currency_fractal_relic", "Relíquia Fractal"},
            {"currency_fractal_relic_tooltip", "Mostrar moeda Relíquia Fractal"},
            {"currency_badge_of_honor", "Insígnia de Honra"},
            {"currency_badge_of_honor_tooltip", "Mostrar moeda Insígnia de Honra"},
            {"currency_guild_commendation", "Comenda de Guilda"},
            {"currency_guild_commendation_tooltip", "Mostrar moeda Comenda de Guilda"},
            {"currency_transmutation_charge", "Carga de Transmutação"},
            {"currency_transmutation_charge_tooltip", "Mostrar moeda Carga de Transmutação"},
            {"currency_spirit_shards", "Fragmentos de Espírito"},
            {"currency_spirit_shards_tooltip", "Mostrar moeda Fragmentos de Espírito"},
            {"currency_unbound_magic", "Magia Não Vinculada"},
            {"currency_unbound_magic_tooltip", "Mostrar moeda Magia Não Vinculada"},
            {"currency_volatile_magic", "Magia Volátil"},
            {"currency_volatile_magic_tooltip", "Mostrar moeda Magia Volátil"},
            {"currency_airship_parts", "Peças de Dirigível"},
            {"currency_airship_parts_tooltip", "Mostrar moeda Peças de Dirigível"},
            {"currency_geode", "Geodo"},
            {"currency_geode_tooltip", "Mostrar moeda Geodo"},
            {"currency_ley_line_crystals", "Cristais de Linha Ley"},
            {"currency_ley_line_crystals_tooltip", "Mostrar moeda Cristais de Linha Ley"},
            {"currency_trade_contracts", "Contratos Comerciais"},
            {"currency_trade_contracts_tooltip", "Mostrar moeda Contratos Comerciais"},
            {"currency_elegy_mosaic", "Mosaico de Elegia"},
            {"currency_elegy_mosaic_tooltip", "Mostrar moeda Mosaico de Elegia"},
            {"currency_uncommon_coins", "Moedas Incomuns"},
            {"currency_uncommon_coins_tooltip", "Mostrar moeda Moedas Incomuns"},
            {"currency_astral_acclaim", "Aplauso Astral"},
            {"currency_astral_acclaim_tooltip", "Mostrar moeda Aplauso Astral"},
            {"currency_pristine_fractal_relics", "Relíquias Fractais Prístinas"},
            {"currency_pristine_fractal_relics_tooltip", "Mostrar moeda Relíquias Fractais Prístinas"},
            {"currency_unstable_fractal_essence", "Essência Fractal Instável"},
            {"currency_unstable_fractal_essence_tooltip", "Mostrar moeda Essência Fractal Instável"},
            {"currency_magnetite_shards", "Fragmentos de Magnetita"},
            {"currency_magnetite_shards_tooltip", "Mostrar moeda Fragmentos de Magnetita"},
            {"currency_gaeting_crystals", "Cristais Gaeting"},
            {"currency_gaeting_crystals_tooltip", "Mostrar moeda Cristais Gaeting"},
            {"currency_prophet_shards", "Fragmentos de Profeta"},
            {"currency_prophet_shards_tooltip", "Mostrar moeda Fragmentos de Profeta"},
            {"currency_green_prophet_shards", "Fragmentos de Profeta Verdes"},
            {"currency_green_prophet_shards_tooltip", "Mostrar moeda Fragmentos de Profeta Verdes"},
            {"currency_wvw_skirmish_tickets", "Bilhetes de Skirmish WvW"},
            {"currency_wvw_skirmish_tickets_tooltip", "Mostrar moeda Bilhetes de Skirmish WvW"},
            {"currency_proofs_of_heroics", "Provas de Heroísmo"},
            {"currency_proofs_of_heroics_tooltip", "Mostrar moeda Provas de Heroísmo"},
            {"currency_pvp_league_tickets", "Bilhetes de Liga PvP"},
            {"currency_pvp_league_tickets_tooltip", "Mostrar moeda Bilhetes de Liga PvP"},
            {"currency_ascended_shards_of_glory", "Fragmentos de Glória Ascendidos"},
            {"currency_ascended_shards_of_glory_tooltip", "Mostrar moeda Fragmentos de Glória Ascendidos"},
            {"currency_research_notes", "Notas de Pesquisa"},
            {"currency_research_notes_tooltip", "Mostrar moeda Notas de Pesquisa"},
            {"currency_tyrian_defense_seal", "Selo de Defesa Tirenio"},
            {"currency_tyrian_defense_seal_tooltip", "Mostrar moeda Selo de Defesa Tirenio"},
            {"currency_testimony_of_desert_heroics", "Testemunho de Heroísmo do Deserto"},
            {"currency_testimony_of_desert_heroics_tooltip", "Mostrar moeda Testemunho de Heroísmo do Deserto"},
            {"currency_testimony_of_jade_heroics", "Testemunho de Heroísmo de Jade"},
            {"currency_testimony_of_jade_heroics_tooltip", "Mostrar moeda Testemunho de Heroísmo de Jade"},
            {"currency_testimony_of_castoran_heroics", "Testemunho de Heroísmo Castorano"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Mostrar moeda Testemunho de Heroísmo Castorano"},
            {"currency_legendary_insight", "Visão Lendária"},
            {"currency_legendary_insight_tooltip", "Mostrar moeda Visão Lendária"},
            {"currency_tales_of_dungeon_delving", "Contos de Exploração de Masmorra"},
            {"currency_tales_of_dungeon_delving_tooltip", "Mostrar moeda Contos de Exploração de Masmorra"},
            {"currency_imperial_favor", "Favor Imperial"},
            {"currency_imperial_favor_tooltip", "Mostrar moeda Favor Imperial"},
            {"currency_canach_coins", "Moedas Canach"},
            {"currency_canach_coins_tooltip", "Mostrar moeda Moedas Canach"},
            {"currency_ancient_coin", "Moeda Antiga"},
            {"currency_ancient_coin_tooltip", "Mostrar moeda Moeda Antiga"},
            {"currency_unusual_coin", "Moeda Incomum"},
            {"currency_unusual_coin_tooltip", "Mostrar moeda Moeda Incomum"},
            {"currency_jade_sliver", "Lasca de Jade"},
            {"currency_jade_sliver_tooltip", "Mostrar moeda Lasca de Jade"},
            {"currency_static_charge", "Carga Estática"},
            {"currency_static_charge_tooltip", "Mostrar moeda Carga Estática"},
            {"currency_pinch_of_stardust", "Pitada de Pó Estelar"},
            {"currency_pinch_of_stardust_tooltip", "Mostrar moeda Pitada de Pó Estelar"},
            {"currency_calcified_gasp", "Suspiro Calcificado"},
            {"currency_calcified_gasp_tooltip", "Mostrar moeda Suspiro Calcificado"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Mostrar moeda Ursus Oblige"},
            {"currency_gaeting_crystal_janthir", "Cristal Gaeting (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Mostrar moeda Cristal Gaeting (Janthir)"},
            {"currency_antiquated_ducat", "Ducado Antigo"},
            {"currency_antiquated_ducat_tooltip", "Mostrar moeda Ducado Antigo"},
            {"currency_aether_rich_sap", "Seiva Rica em Éter"},
            {"currency_aether_rich_sap_tooltip", "Mostrar moeda Seiva Rica em Éter"},

            // Additional Filters
            {"additional_filters", "Filtros Adicionais"},
            {"account_bound", "Vinculado à Conta"},
            {"account_bound_tooltip", "Mostrar itens vinculados à conta"},
            {"not_account_bound", "Não Vinculado à Conta"},
            {"not_account_bound_tooltip", "Mostrar itens não vinculados à conta"},
            {"nosell_items", "Não vendável"},
            {"nosell_items_tooltip", "Mostrar itens não vendáveis"},
            {"not_nosell", "Vendível"},
            {"not_nosell_tooltip", "Mostrar itens vendíveis"},
            {"favorite_items", "Favorito"},
            {"favorite_items_tooltip", "Mostrar itens favoritos"},
            {"not_favorite", "Não Favorito"},
            {"not_favorite_tooltip", "Mostrar itens não favoritos"},
            {"ignored_items", "Ignorado"},
            {"ignored_items_tooltip", "Mostrar itens ignorados"},
            {"not_ignored", "Não Ignorado"},
            {"not_ignored_tooltip", "Mostrar itens não ignorados"},

            // Range Filters
            {"range_filters", "Filtros de Intervalo"},
            {"show_range_filters", "Mostrar Filtros de Intervalo"},
            {"filter_min_price", "Filtro Preço Mín"},
            {"filter_max_price", "Filtro Preço Máx"},
            {"filter_min_quantity", "Filtro Quantidade Mín"},
            {"filter_max_quantity", "Filtro Quantidade Máx"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Janela"},
            {"show_profit", "Mostrar Lucro"},
            {"show_profit_tooltip", "Exibir lucro total na mini janela"},
            {"show_profit_per_hour", "Mostrar Lucro/Hora"},
            {"show_profit_per_hour_tooltip", "Exibir lucro por hora na mini janela"},
            {"show_tp_sell", "Mostrar Venda TP (Listagens)"},
            {"show_tp_sell_tooltip", "Exibir lucro de venda TP (listagens) na mini janela"},
            {"show_tp_instant", "Mostrar Venda Instantânea TP"},
            {"show_tp_instant_tooltip", "Exibir lucro de venda instantânea TP na mini janela"},
            {"show_total_items", "Mostrar Total de Itens"},
            {"show_total_items_tooltip", "Exibir quantidade total de itens na mini janela"},
            {"show_session_duration", "Mostrar Duração da Sessão"},
            {"show_session_duration_tooltip", "Exibir duração da sessão na mini janela"},
            {"window_click_through", "Clique através da janela"},
            {"window_click_through_tooltip", "Permite clicar através da mini janela para o jogo"},

            // Main Window Settings
            {"main_window", "Janela Principal"},
            {"click_through", "Clique através"},
            {"click_through_tooltip", "Permite clicar através da janela principal para o jogo"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Configurações Avançadas de UI"},
            {"no_advanced_ui_settings", "(Nenhuma configuração avançada de UI disponível)"},

            // Display Settings
            {"display_settings", "Configurações de Exibição"},
            {"show_item_icons", "Mostrar Ícones de Itens"},
            {"show_item_icons_tooltip", "Exibir ícones de itens na lista"},
            {"show_rarity_border", "Mostrar Borda de Raridade"},
            {"show_rarity_border_tooltip", "Exibir borda colorida baseada na raridade do item"},
            {"enable_grid_view", "Ativar Visualização em Grade"},
            {"enable_grid_view_tooltip", "Exibir itens em layout de grade em vez de lista"},
            {"grid_icon_size", "Tamanho do Ícone da Grade"},
            {"grid_icon_size_tooltip", "Tamanho dos ícones na visualização em grade"},

            // Count Display Settings
            {"count_display_settings", "Configurações de Exibição de Quantidade"},
            {"count_text_color", "Cor do Texto de Quantidade"},
            {"count_text_color_tooltip", "Cor do texto de quantidade"},
            {"count_background_color", "Cor de Fundo de Quantidade"},
            {"count_background_color_tooltip", "Cor do fundo de quantidade"},
            {"count_font_size", "Tamanho da Fonte de Quantidade"},
            {"count_font_size_tooltip", "Tamanho da fonte de quantidade"},
            {"count_horizontal_alignment", "Alinhamento Horizontal de Quantidade"},
            {"count_horizontal_alignment_tooltip", "Alinhamento horizontal do texto de quantidade"},

            // Gradient Background Settings
            {"gradient_background_settings", "Configurações de Fundo Gradiente"},
            {"enable_gradient_backgrounds", "Ativar Fundos Gradiente"},
            {"enable_gradient_backgrounds_tooltip", "Ativar fundo gradiente para janelas"},
            {"gradient_top_color", "Cor Superior do Gradiente"},
            {"gradient_top_color_tooltip", "Cor superior do fundo gradiente"},
            {"gradient_bottom_color", "Cor Inferior do Gradiente"},
            {"gradient_bottom_color_tooltip", "Cor inferior do fundo gradiente"},

            // Custom Profit System
            {"custom_profit_system", "Sistema de Lucro Personalizado"},
            {"enable_custom_profit", "Ativar Lucro Personalizado"},
            {"enable_custom_profit_tooltip", "Ativar valores de lucro personalizados para itens"},

            // Search
            {"search_settings", "Busca"},
            {"enable_search", "Ativar Busca"},
            {"enable_search_tooltip", "Ativar funcionalidade de busca"},

            // Ignored Items
            {"ignored_items_settings", "Itens Ignorados"},
            {"enable_ignored_items", "Ativar Itens Ignorados"},
            {"enable_ignored_items_tooltip", "Ativar funcionalidade de itens ignorados"},

            // Auto Reset
            {"auto_reset_settings", "Auto Reset"},
            {"enable_auto_reset", "Ativar Auto Reset"},
            {"enable_auto_reset_tooltip", "Redefinir automaticamente a sessão de farming após uma duração"},
            {"auto_reset_duration", "Duração do Auto Reset (minutos)"},
            {"auto_reset_duration_tooltip", "Duração em minutos antes do auto reset"},

            // DRF Settings
            {"drf_settings", "Configurações DRF"},
            {"drf_token", "Token DRF"},
            {"drf_token_tooltip", "Seu token de autenticação DRF"},
            {"edit_token", "Editar Token"},
            {"save_token", "Salvar Token"},

            // GW2 API Settings
            {"gw2_api_settings", "Configurações API GW2"},
            {"gw2_api_key", "Chave API GW2"},
            {"gw2_api_key_tooltip", "Sua chave API GW2 para detalhes dos itens"},
            {"edit_key", "Editar Chave"},
            {"save_key", "Salvar Chave"},

            // Language Settings
            {"language_settings", "Idioma"},
            {"language_tooltip", "Selecionar idioma da interface"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "Nenhuma conta configurada"},
            {"no_profiles_created", "Nenhum perfil criado ainda"},
            {"count_label", "Quantidade:"},
            {"profit_label", "Lucro:"},
            {"no_profit", "Sem lucro"},
            {"vendor_value_label", "Valor do Vendedor:"},
            {"tp_sell_gross_label", "Venda TP (Bruto):"},
            {"tp_sell_net_label", "Venda TP (Líquido):"},
            {"tp_buy_gross_label", "Compra TP (Bruto):"},
            {"tp_buy_net_label", "Compra TP (Líquido):"},
            {"ignored_items_label", "Itens Ignorados:"},
            {"ignored_currencies_label", "Moedas Ignoradas:"},
            {"total_items_label", "Total de Itens:"},
            {"total_currencies_label", "Total de Moedas:"},
            {"total_profit_label", "Lucro Total:"},
            {"tp_sell_profit_label", "Lucro de Venda TP:"},
            {"vendor_profit_label", "Lucro de Venda do Vendedor:"},
            {"profit_per_hour_label", "Lucro Por Hora:"},
            {"opportunity_cost_profit_label", "Lucro de Custo de Oportunidade:"},
            {"opportunity_cost_profit_per_hour_label", "Lucro de Custo de Oportunidade/Hora:"},
            {"custom_profit_feature_placeholder", "Funcionalidade implementada - UI a ser adicionada"},
            {"overview_label", "Visão Geral:"},
            {"total_profit_label_simple", "Lucro Total"},
            {"total_items_label_simple", "Total de Itens"},
            {"total_currencies_label_simple", "Total de Moedas"},
            {"profit_per_hour_label_simple", "Lucro Por Hora"},
            {"session_duration_label_simple", "Duração da Sessão"},
            {"export_label", "Exportar:"},
            {"quick_actions", "Ações Rápidas:"},
            {"reset_confirm", "Tem certeza de que deseja redefinir todas as configurações para os padrões?"},
            {"reset_warning", "Esta ação não pode ser desfeita."},
            {"export_settings", "Exportar Configurações para Arquivo:"},
            {"import_settings", "Importar Configurações de Arquivo:"},
            {"edit_account", "Editar Conta: %s"},
            {"account_name", "Nome da Conta:"},
            {"drf_token_label", "Token DRF:"},
            {"gw2_api_key_label", "Chave API GW2:"},
            {"reload_config", "Recarregar Configuração:"},
            {"auto_reset_label", "Auto Reset:"},
            {"next_reset_utc", "Próximo reset agendado (UTC): %s"},
            {"favorites_ui", "UI de Favoritos:"},
            {"favorites_colors", "Cores de Favoritos:"},
            {"visual_enhancements", "Melhorias Visuais:"},
            {"mini_window_widget", "Mini Janela (Widget Overlay):"},
            {"main_window_label", "Janela Principal:"},
            {"profiles_description", "Perfis permitem salvar diferentes configurações e alternar rapidamente entre elas."},
            {"create_new_profile", "Criar Novo Perfil:"},
            {"current_profile", "Perfil Atual: %s"},
            {"auto_backup", "Fazer backup automático das configurações antes de mudanças importantes"},
            {"notifications", "Configurar notificações no jogo para eventos importantes"},
            {"profit_goal", "Meta de Lucro:"},
            {"reset_warning_label", "Aviso de Reset:"},
            {"session_complete", "Sessão Concluída:"},
            {"manage_ignored_items", "Gerenciar itens ignorados"},
            {"manage_ignored_currencies", "Gerenciar moedas ignoradas"},
            {"rarity_label", "Raridade: %s"},
            {"type_label", "Tipo: %d"},
            {"account_bound_label", "Vinculado à Conta: %s"},
            {"nosell_label", "Não vendível: %s"},
            {"sell_method_filters_label", "Filtros de Método de Venda:"},
            {"api_knowledge_filters_label", "Filtros de Conhecimento API:"},
            {"additional_filters_label", "Filtros Adicionais:"},
            {"item_type_filters_label", "Filtros de Tipo de Item:"},
            {"currency_filters_label", "Filtros de Moedas:"},
            {"price_range", "Intervalo de Preço (Cobre):"},
            {"quantity_range", "Intervalo de Quantidade:"},
            {"debug_info", "Informações de Debug"},
            {"drf_status", "Status DRF: %s"},
            {"drf_reconnect_count", "Contagem de Reconexões DRF: %d"},
            {"gw2_api_status", "Status API GW2: %s"},
            {"gw2_api_reconnect_count", "Contagem de Reconexões API GW2: %d"},
            {"session_duration_debug", "Duração da Sessão: %s"},
            {"gw2_memory", "Memória do Processo GW2: %zu MB"},
            {"gw2_api_request_count", "Contagem de Solicitações API GW2: %d"},
            {"ignored_items_count", "Itens Ignorados: %d"},
            {"ignored_currencies_count", "Moedas Ignoradas: %d"},
            {"drf_logs", "Logs DRF:"},
            {"last_100_entries", "(Últimas 100 entradas)"},
            {"gw2_api_logs", "Logs API GW2:"},
            {"item_currency_details", "Detalhes de Item/Moeda (Primeiros 5):"},
            {"item_label", "Item %d: %s (Quantidade: "},
            {"loaded_label", ", Carregado: %s)"},
            {"currency_label", "Moeda %d: %s (Quantidade: "},
            {"custom_profit_items", "Itens de Lucro Personalizado (Primeiros 5):"},
            {"custom_profit_item", "Item %d: %s (Lucro Personalizado: "},
            {"no_custom_profit_items", "(Sem itens de lucro personalizado)"},
            {"ignored_items_debug", "Itens Ignorados (Primeiros 5):"},
            {"yes_label", "Sim"},
            {"no_label", "Não"},
            {"profits_label", "Lucros:"},
            {"profits_tooltip", "Lucros totais do farming"},
            {"approx_profits_label", "Lucros Aproximados:"},
            {"approx_profits_tooltip", "Lucro total de valores de lucro personalizado"},
            {"approx_gold_per_hour_label", "Ouro Por Hora Aproximado:"},
            {"approx_gold_per_hour_tooltip", "Lucro por hora baseado na duração da sessão"},
            {"trading_profits_label", "Lucros de Trading:"},
            {"trading_profits_tooltip", "Lucros da venda de itens no Trading Post"},
            {"approx_trading_profits_listings_label", "Lucros de Trading Aproximados (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Lucro total se vendido via TP listings"},
            {"approx_trading_profits_instant_label", "Lucros de Trading Aproximados (Venda Instantânea):"},
            {"approx_trading_profits_instant_tooltip", "Lucro total se vendido via TP buy orders instantâneos"},
            {"trading_details_label", "Detalhes de Trading (Custo de Oportunidade):"},
            {"trading_details_tooltip", "Lucro perdido por não vender via TP listings"},
            {"lost_profit_vs_tp_sell_label", "Lucro Perdido (vs Venda TP):"},
            {"lost_profit_vs_tp_sell_tooltip", "Ouro = lucro perdido, Vermelho = lucro ganho vs venda TP"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Lucro Perdido Por Hora (vs Venda TP):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Custo de oportunidade por hora"},
            {"session_duration_debug_label", "Duração da sessão: %s"},
            {"session_duration_debug_tooltip", "Duração da sessão de farming atual"},
            {"tab_items", "Itens"},
            {"manage_ignored_items", "Gerenciar itens ignorados"},
            {"clear_all_ignored_items", "Limpar todos os itens ignorados"},
            {"unignore_item", "Parar de ignorar item"},
            {"tab_currencies", "Moedas"},
            {"manage_ignored_currencies", "Gerenciar moedas ignoradas"},
            {"clear_all_ignored_currencies", "Limpar todas as moedas ignoradas"},
            {"unignore_currency", "Parar de ignorar moeda"},
            {"sell_method_filters_label", "Filtros de Método de Venda:"},
            {"api_knowledge_filters_label", "Filtros de Conhecimento API:"},
            {"additional_filters_label", "Filtros Adicionais:"},
            {"item_type_filters_label", "Filtros de Tipo de Item:"},
            {"currency_filters_label", "Filtros de Moedas:"},
            {"price_range", "Intervalo de Preço (Cobre):"},
            {"quantity_range", "Intervalo de Quantidade:"},
            {"debug_information", "Informações de Depuração"},
            {"drf_status_label", "Status DRF: %s"},
            {"drf_status_tooltip", "Status de conexão DRF atual"},
            {"drf_reconnect_count_label", "Contagem de Reconexão DRF: %d"},
            {"drf_reconnect_count_tooltip", "Número de tentativas de reconexão DRF"},
            {"gw2_api_status_label", "Status API GW2: %s"},
            {"gw2_api_status_tooltip", "Status de conexão API GW2 atual"},
            {"gw2_api_reconnect_count_label", "Contagem de Reconexão API GW2: %d"},
            {"gw2_api_reconnect_count_tooltip", "Número de tentativas de reconexão API GW2"},
            {"session_duration_debug", "Duração da Sessão: %s"},
            {"session_duration_debug_tooltip", "Duração da sessão de farming atual"},
            {"gw2_process_memory_label", "Memória do Processo GW2: %zu MB"},
            {"gw2_process_memory_tooltip", "Uso de memória do processo GW2 atual"},
            {"gw2_api_request_count_label", "Contagem de Solicitações API GW2: %d"},
            {"gw2_api_request_count_tooltip", "Número total de solicitações API GW2 feitas"},
            {"ignored_items_debug_label", "Itens Ignorados: %d"},
            {"ignored_items_debug_tooltip", "Número de itens ignorados"},
            {"ignored_currencies_debug_label", "Moedas Ignoradas: %d"},
            {"ignored_currencies_debug_tooltip", "Número de moedas ignoradas"},
            {"drf_logs_label", "Logs DRF:"},
            {"clear_drf_logs", "Limpar Logs DRF"},
            {"clear_drf_logs_tooltip", "Limpar todas as entradas de logs DRF"},
            {"last_100_entries", "(Últimas 100 entradas)"},
            {"gw2_api_logs_label", "Logs API GW2:"},
            {"clear_gw2_logs", "Limpar Logs GW2"},
            {"clear_gw2_logs_tooltip", "Limpar todas as entradas de logs API GW2"},
            {"settings_label", "Configurações:"},
            {"api_key_label", "Chave API: %s"},
            {"api_key_tooltip", "Status da chave API GW2"},
            {"not_set", "Não definida"},
            {"set", "Definida"},
            {"drf_token_label", "Token DRF: %s"},
            {"drf_token_tooltip", "Status do token DRF"},
            {"toggle_hotkey_label", "Tecla de Alternar: %s"},
            {"toggle_hotkey_tooltip", "Tecla de alternar janela principal"},
            {"auto_reset_mode_label", "Modo Auto-Reset: %d"},
            {"auto_reset_mode_tooltip", "Modo de reinicialização automática atual"},
            {"next_reset_label", "Próximo Reset: %s"},
            {"next_reset_tooltip", "Hora do próximo reinício programado (UTC)"},
            {"fake_drf_server_label", "Servidor DRF Falso:"},
            {"use_fake_drf_server", "Usar servidor DRF falso"},
            {"use_fake_drf_server_tooltip", "Apenas para fins de teste"},
            {"reset_all_data", "Redefinir Todos os Dados"},
            {"reset_all_data_tooltip", "Redefinir todos os dados de farming"},
            {"coin", "Moeda"},
            {"rarity_label", "Raridade: %s"},
            {"type_label", "Tipo: %d"},
            {"account_bound_label", "Vinculado à conta: %s"},
            {"nosell_label", "Não vendável: %s"},
            {"yes_label", "Sim"},
            {"no_label", "Não"},
            {"sort_price_down", "Ordenar: Preço do item decrescente"},
            {"sort_price_up", "Ordenar: Preço do item crescente"},
            {"sort_count_high", "Ordenar: |Contagem| alta"},
            {"sort_count_low", "Ordenar: |Contagem| baixa"},
            {"sort_name_az", "Ordenar: Nome A–Z"},
            {"sort_tooltip", "Ordenar itens por contagem, ID ou nome"},
            {"rarity_all", "Raridade: todos"},
            {"rarity_basic", "Raridade: Básico+"},
            {"rarity_fine", "Raridade: Fino+"},
            {"rarity_masterwork", "Raridade: Obra-prima+"},
            {"rarity_rare", "Raridade: Raro+"},
            {"rarity_exotic", "Raridade: Exótico+"},
            {"rarity_ascended", "Raridade: Ascendido+"},
            {"rarity_legendary", "Raridade: Apenas lendário"},
            {"rarity_tooltip", "Filtrar itens por raridade mínima"},
            {"search_items_hint", "Pesquisar itens..."},
            {"column_icon", "Ícone"},
            {"column_name", "Nome"},
            {"column_count", "Contagem"},
            {"column_profit", "Lucro"},
            {"column_favorite", "Favorito"},
            {"column_ignore", "Ignorar"},
            {"toggle_favorite", "Alternar favorito"},
            {"toggle_ignore", "Alternar ignorar"},
            {"vendor_value_format", "Valor do vendedor: %s"},
            {"tp_sell_gross_format", "Venda TP (Bruto): %s"},
            {"tp_sell_net_format", "Venda TP (Líquido): %s"},
            {"tp_buy_gross_format", "Compra TP (Bruto): %s"},
            {"tp_buy_net_format", "Compra TP (Líquido): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Configurações de Favoritos"},
            {"favorites_first", "Favoritos primeiro"},
            {"favorites_first_tooltip", "Mostra favoritos primeiro nas listas de itens/moedas"},
            {"enable_favorite_text_color", "Ativar cor de texto favorito"},
            {"enable_favorite_text_color_tooltip", "Destaca itens/moedas favoritos com cor de texto personalizada"},
            {"text_color", "Cor do Texto"},
            {"enable_favorite_row_color", "Ativar cor de linha favorito"},
            {"enable_favorite_row_color_tooltip", "Destaca itens/moedas favoritos com cor de fundo de linha personalizada"},
            {"row_color", "Cor da Linha"},
            
            // Filter - Additional
            {"filter_favorite", "Favorito"},
            {"filter_favorite_tooltip", "Mostrar itens favoritos"},
            {"filter_not_favorite", "Não Favorito"},
            {"filter_not_favorite_tooltip", "Mostrar itens não favoritos"},
            {"filter_research_notes", "Notas de Pesquisa"},
            {"filter_research_notes_tooltip", "Mostrar moeda notas de pesquisa"},
            {"range_filters", "Filtros de Intervalo"},
            {"range_filters_tooltip", "Mostrar filtros de intervalo de preço e quantidade"},
            {"filter_min_price_tooltip", "Filtro de preço mínimo (0 = desativado)"},
            {"filter_max_price_tooltip", "Filtro de preço máximo (0 = desativado)"},
            {"filter_min_quantity_tooltip", "Filtro de quantidade mínima (0 = desativado)"},
            {"filter_max_quantity_tooltip", "Filtro de quantidade máxima (0 = desativado)"},
            {"filter_min_price", "Preço Mín"},
            {"filter_max_price", "Preço Máx"},
            {"filter_min_quantity", "Quantidade Mín"},
            {"filter_max_quantity", "Quantidade Máx"},
            
            // Summary Tab - Table Columns
            {"column_label", "Rótulo"},
            {"column_value", "Valor"},
            {"column_item", "Item"},
            {"column_count", "Quantidade"},
            {"column_currency", "Moeda"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Itens por Lucro"},
            {"top_items_count_header", "Top Itens (Quantidade)"},
            {"top_currencies_count_header", "Top Moedas (Quantidade)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 itens por valor de lucro"},
            {"top_items_count_tooltip", "Top 10 itens por quantidade"},
            {"top_currencies_count_tooltip", "Top 10 moedas por quantidade"},
            
            // Settings Tab - General
            {"show_main_window", "Mostrar janela principal"},
            {"reset_all", "Redefinir tudo"},
            {"reset_all_tooltip", "Redefinir todas as configurações para valores padrão"},
            {"export", "Exportar"},
            {"export_tooltip", "Exportar configurações para um arquivo JSON"},
            {"import", "Importar"},
            {"import_tooltip", "Importar configurações de um arquivo JSON"},
            {"save", "Salvar"},
            {"save_tooltip", "Salvar configurações atuais"},
            {"general_settings", "Configurações gerais"},
            {"account_management", "Gerenciamento de contas"},
            {"add_account", "+ Adicionar conta"},
            {"remove_account", "- Remover conta"},
            {"save_account", "Salvar conta"},
            {"reload_drf_token", "Recarregar token DRF"},
            {"reload_gw2_api_key", "Recarregar chave API GW2"},
            {"reset_settings", "Auto Reset"},
            {"visual_settings", "Configurações visuais"},
            {"gradient_backgrounds", "Fundos gradiente"},
            {"gradient_backgrounds_tooltip", "Ativa fundos gradiente suaves para uma aparência mais moderna"},
            {"top_gradient_color", "Cor gradiente superior"},
            {"top_gradient_color_tooltip", "Cor gradiente superior"},
            {"bottom_gradient_color", "Cor gradiente inferior"},
            {"bottom_gradient_color_tooltip", "Cor gradiente inferior"},
            {"show_item_icons", "Mostrar ícones de itens (renderização GW2)"},
            {"show_item_icons_tooltip", "Carrega ícones de render.guildwars2.com via Nexus."},
            {"icon_size", "Tamanho do ícone"},
            {"icon_size_tooltip", "Tamanho dos ícones de itens em pixels (16-96)"},
            {"show_rarity_borders", "Mostrar bordas de raridade"},
            {"show_rarity_borders_tooltip", "Mostra bordas coloridas ao redor dos ícones baseadas na raridade"},
            {"rarity_border_thickness", "Espessura da borda de raridade"},
            {"rarity_border_thickness_tooltip", "Ajustar a espessura das bordas de raridade (1.0 - 10.0)"},
            {"enable_grid_view_items", "Ativar visualização em grade (Itens)"},
            {"enable_grid_view_items_tooltip", "Alternar entre visualização em lista e grade na aba Itens"},
            {"grid_icon_size_items", "Tamanho do ícone da grade (Itens)"},
            {"grid_icon_size_items_tooltip", "Tamanho dos ícones na visualização em grade para Itens (16-128)"},
            {"enable_grid_view_currencies", "Ativar visualização em grade (Moedas)"},
            {"enable_grid_view_currencies_tooltip", "Alternar entre visualização em lista e grade na aba Moedas"},
            {"grid_icon_size_currencies", "Tamanho do ícone da grade (Moedas)"},
            {"grid_icon_size_currencies_tooltip", "Tamanho dos ícones na visualização em grade para Moedas (16-128)"},
            {"show_mini_window", "Mostrar mini janela"},
            {"show_mini_window_tooltip", "Mostra um pequeno widget de sobreposição com estatísticas principais"},
            {"mini_window_show_profit", "Mostrar lucro"},
            {"mini_window_show_profit_tooltip", "Mostrar lucro total na mini janela"},
            {"mini_window_show_profit_per_hour", "Mostrar lucro/hora"},
            {"mini_window_show_profit_per_hour_tooltip", "Mostrar lucro por hora na mini janela"},
            {"mini_window_show_tp_sell", "Mostrar venda TP (Listas)"},
            {"mini_window_show_tp_sell_tooltip", "Mostrar lucro de venda TP (listas) na mini janela"},
            {"mini_window_show_tp_instant", "Mostrar venda instantânea TP"},
            {"mini_window_show_tp_instant_tooltip", "Mostrar lucro de venda instantânea TP na mini janela"},
            {"mini_window_show_total_items", "Mostrar total de itens"},
            {"mini_window_show_total_items_tooltip", "Mostrar número total de itens na mini janela"},
            {"mini_window_show_session_duration", "Mostrar duração da sessão"},
            {"mini_window_show_session_duration_tooltip", "Mostrar duração da sessão na mini janela"},
            {"mini_window_click_through", "Janela clicável"},
            {"mini_window_click_through_tooltip", "Permite clicar através da mini janela para o jogo"},
            {"main_window_click_through", "Clicável"},
            {"main_window_click_through_tooltip", "Permite clicar através da janela principal para o jogo"},
            {"settings_profiles", "Perfis de configurações"},
            {"select_profile", "Selecione um perfil para aplicar suas configurações"},
            {"create_new_profile", "Criar novo perfil"},
            {"create_new_profile_tooltip", "Criar um novo perfil com configurações atuais"},
            {"create", "Criar"},
            {"update_profile", "Atualizar perfil"},
            {"update_profile_tooltip", "Atualizar perfil atual com configurações atuais"},
            {"delete_profile", "Excluir perfil"},
            {"delete_profile_tooltip", "Excluir perfil atual"},
            {"automatic_backups", "Backups automáticos"},
            {"enable_automatic_backups", "Ativar backups automáticos"},
            {"enable_automatic_backups_tooltip", "Criar automaticamente backups antes de alterações"},
            {"backup_frequency", "Frequência de backup"},
            {"backup_frequency_tooltip", "Com que frequência criar backups automáticos"},
            {"max_backups", "Backups máximos"},
            {"max_backups_tooltip", "Número máximo de backups para manter (1-20)"},
            {"notification_settings", "Configurações de notificação"},
            {"enable_notifications", "Ativar notificações"},
            {"enable_notifications_tooltip", "Ativar notificações no jogo"},
            {"notify_profit_goal", "Notificar quando a meta de lucro for atingida"},
            {"notify_profit_goal_tooltip", "Notificar quando você atingir sua meta de lucro"},
            {"profit_goal_gold", "Meta de lucro (Ouro)"},
            {"profit_goal_gold_tooltip", "Meta de lucro em moedas de ouro (1-1000)"},
            {"notify_reset_warning", "Notificar antes de redefinir"},
            {"notify_reset_warning_tooltip", "Notificar antes que uma redefinição automática ocorra"},
            {"reset_warning_minutes", "Aviso de redefinição (Minutos)"},
            {"reset_warning_minutes_tooltip", "Minutos antes da redefinição para mostrar aviso (1-60)"},
            {"notify_session_complete", "Notificar após duração da sessão"},
            {"notify_session_complete_tooltip", "Notificar após farmar por uma certa duração"},
            {"session_complete_hours", "Sessão concluída (Horas)"},
            {"session_complete_hours_tooltip", "Horas de farm antes da notificação (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Vendível ao comerciante"},
            {"filter_sellable_to_vendor_tooltip", "Mostrar itens vendíveis ao comerciante"},
            {"filter_sellable_on_tp", "Vendível no TP"},
            {"filter_sellable_on_tp_tooltip", "Mostrar itens vendíveis no Posto de Comércio"},
            {"filter_custom_profit", "Lucro personalizado"},
            {"filter_custom_profit_tooltip", "Mostrar itens com lucro personalizado"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Conhecido pela API"},
            {"filter_known_by_api_tooltip", "Mostrar itens conhecidos pela API GW2"},
            {"filter_unknown_by_api", "Desconhecido pela API"},
            {"filter_unknown_by_api_tooltip", "Mostrar itens desconhecidos pela API GW2"},
            
            // Filter - Additional
            {"show_ignored_items", "Mostrar itens ignorados"},
            {"show_ignored_items_tooltip", "Mostrar itens/moedas ignorados nas abas Itens e Moedas (desmarque para ocultar)"},
            
            // Filter - Item Types
            {"filter_type_armor", "Armadura"},
            {"filter_type_armor_tooltip", "Mostrar itens de armadura"},
            {"filter_type_weapon", "Arma"},
            {"filter_type_weapon_tooltip", "Mostrar itens de arma"},
            {"filter_type_trinket", "Adereço"},
            {"filter_type_trinket_tooltip", "Mostrar itens de adereço"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Mostrar itens gizmo"},
            {"filter_type_crafting_material", "Material de crafting"},
            {"filter_type_crafting_material_tooltip", "Mostrar materiais de crafting"},
            {"filter_type_consumable", "Consumível"},
            {"filter_type_consumable_tooltip", "Mostrar consumíveis"},
            {"filter_type_gathering_tool", "Ferramenta de coleta"},
            {"filter_type_gathering_tool_tooltip", "Mostrar ferramentas de coleta"},
            {"filter_type_bag", "Bolsa"},
            {"filter_type_bag_tooltip", "Mostrar bolsas"},
            {"filter_type_container", "Contêiner"},
            {"filter_type_container_tooltip", "Mostrar contêineres"},
            {"filter_type_mini_pet", "Mini mascote"},
            {"filter_type_mini_pet_tooltip", "Mostrar mini mascotes"},
            
            // Filter - Currencies
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Mostrar moeda Karma"},
            {"filter_laurel", "Louro"},
            {"filter_laurel_tooltip", "Mostrar moeda Louro"},
            {"filter_gem", "Gema"},
            {"filter_gem_tooltip", "Mostrar moeda Gema"},
            {"filter_fractal_relic", "Relíquia de fractal"},
            {"filter_fractal_relic_tooltip", "Mostrar moeda Relíquia de fractal"},
            {"filter_badge_of_honor", "Insígnia de honra"},
            {"filter_badge_of_honor_tooltip", "Mostrar moeda Insígnia de honra"},
            {"filter_guild_commendation", "Recomendação de guilda"},
            {"filter_guild_commendation_tooltip", "Mostrar moeda Recomendação de guilda"},
            {"filter_transmutation_charge", "Carga de transmutação"},
            {"filter_transmutation_charge_tooltip", "Mostrar moeda Carga de transmutação"},
            {"filter_spirit_shards", "Fragmentos de espírito"},
            {"filter_spirit_shards_tooltip", "Mostrar moeda Fragmentos de espírito"},
            {"filter_unbound_magic", "Magia não vinculada"},
            {"filter_unbound_magic_tooltip", "Mostrar moeda Magia não vinculada"},
            {"filter_volatile_magic", "Magia volátil"},
            {"filter_volatile_magic_tooltip", "Mostrar moeda Magia volátil"},
            {"filter_airship_parts", "Peças de dirigível"},
            {"filter_airship_parts_tooltip", "Mostrar moeda Peças de dirigível"},
            {"filter_geode", "Geodo"},
            {"filter_geode_tooltip", "Mostrar moeda Geodo"},
            {"filter_ley_line_crystals", "Cristais de linhas ley"},
            {"filter_ley_line_crystals_tooltip", "Mostrar moeda Cristais de linhas ley"},
            {"filter_trade_contracts", "Contratos comerciais"},
            {"filter_trade_contracts_tooltip", "Mostrar moeda Contratos comerciais"},
            {"filter_elegy_mosaic", "Mosaico de elegia"},
            {"filter_elegy_mosaic_tooltip", "Mostrar moeda Mosaico de elegia"},
            {"filter_uncommon_coins", "Moedas incomuns"},
            {"filter_uncommon_coins_tooltip", "Mostrar moeda Moedas incomuns"},
            {"filter_astral_acclaim", "Aclamação astral"},
            {"filter_astral_acclaim_tooltip", "Mostrar moeda Aclamação astral"},
            
            // Debug Tab
            {"total_tracked_items", "Número total de itens rastreados"},
            {"total_tracked_items_tooltip", "Número total de itens rastreados"},
            {"total_tracked_currencies", "Número total de moedas rastreadas"},
            {"total_tracked_currencies_tooltip", "Número total de moedas rastreadas"},
            {"total_custom_profit", "Lucro personalizado total"},
            {"total_custom_profit_tooltip", "Lucro personalizado total"},
            {"total_tp_sell_profit", "Lucro de venda TP total"},
            {"total_tp_sell_profit_tooltip", "Lucro de venda TP total"},
            {"total_vendor_sell_profit", "Lucro de venda comerciante total"},
            {"total_vendor_sell_profit_tooltip", "Lucro de venda comerciante total"},
            {"profit_per_hour_calculation", "Cálculo de lucro por hora"},
            {"profit_per_hour_calculation_tooltip", "Cálculo de lucro por hora"},
            {"opportunity_cost_vs_tp_sell", "Custo de oportunidade vs venda TP"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Custo de oportunidade vs venda TP"},
            {"opportunity_cost_per_hour", "Custo de oportunidade por hora"},
            {"opportunity_cost_per_hour_tooltip", "Custo de oportunidade por hora"},
            {"first_5_tracked_items", "Primeiros 5 itens e moedas rastreados com detalhes"},
            {"first_5_tracked_items_tooltip", "Primeiros 5 itens e moedas rastreados com detalhes"},
            {"first_5_custom_profit", "Primeiros 5 itens com lucro personalizado"},
            {"first_5_custom_profit_tooltip", "Primeiros 5 itens com lucro personalizado"},
            {"first_5_ignored_items", "Primeiros 5 itens ignorados"},
            {"first_5_ignored_items_tooltip", "Primeiros 5 itens ignorados"},
            
            // Debug Settings
            {"debug_settings", "Configurações de Depuração"},
            {"enable_debug_tab", "Ativar Aba de Depuração"},
            {"enable_debug_tab_tooltip", "Mostra a aba de depuração com informações adicionais"},
            
            // Currencies Tab
            {"gold_format", "Ouro: %lld"},
            {"count_format", "Quantidade: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Alternar favorito"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Alternar ignorar"},
            
            // Additional Filters
            {"filter_account_bound", "Vinculado à conta"},
            {"filter_account_bound_tooltip", "Mostrar itens vinculados à conta"},
            {"filter_not_account_bound", "Não vinculado à conta"},
            {"filter_not_account_bound_tooltip", "Mostrar itens não vinculados à conta"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "Mostrar itens NoSell"},
            {"filter_not_nosell", "Não NoSell"},
            {"filter_not_nosell_tooltip", "Mostrar itens vendáveis"},
            {"filter_ignored", "Ignorado"},
            {"filter_ignored_tooltip", "Mostrar itens ignorados"},
            {"filter_not_ignored", "Não Ignorado"},
            {"filter_not_ignored_tooltip", "Mostrar itens não ignorados"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Relíquias fractais imaculadas"},
            {"filter_pristine_fractal_relics_tooltip", "Mostrar moeda Relíquias fractais imaculadas"},
            {"filter_unstable_fractal_essence", "Essência fractal instável"},
            {"filter_unstable_fractal_essence_tooltip", "Mostrar moeda Essência fractal instável"},
            {"filter_magnetite_shards", "Fragmentos de magnetita"},
            {"filter_magnetite_shards_tooltip", "Mostrar moeda Fragmentos de magnetita"},
            {"filter_gaeting_crystals", "Cristais Gaeting"},
            {"filter_gaeting_crystals_tooltip", "Mostrar moeda Cristais Gaeting"},
            {"filter_prophet_shards", "Fragmentos de profeta"},
            {"filter_prophet_shards_tooltip", "Mostrar moeda Fragmentos de profeta"},
            {"filter_green_prophet_shards", "Fragmentos de profeta verdes"},
            {"filter_green_prophet_shards_tooltip", "Mostrar moeda Fragmentos de profeta verdes"},
            {"filter_wvw_skirmish_tickets", "Bilhetes de escaramuça WvW"},
            {"filter_wvw_skirmish_tickets_tooltip", "Mostrar moeda Bilhetes de escaramuça WvW"},
            {"filter_proofs_of_heroics", "Provas de heroísmo"},
            {"filter_proofs_of_heroics_tooltip", "Mostrar moeda Provas de heroísmo"},
            {"filter_pvp_league_tickets", "Bilhetes de liga PvP"},
            {"filter_pvp_league_tickets_tooltip", "Mostrar moeda Bilhetes de liga PvP"},
            {"filter_ascended_shards_of_glory", "Fragmentos de glória ascendentes"},
            {"filter_ascended_shards_of_glory_tooltip", "Mostrar moeda Fragmentos de glória ascendentes"},
            {"filter_tyrian_defense_seal", "Selo de defesa tiriano"},
            {"filter_tyrian_defense_seal_tooltip", "Mostrar moeda Selo de defesa tiriano"},
            {"filter_testimony_of_desert_heroics", "Testemunho de heroísmo do deserto"},
            {"filter_testimony_of_desert_heroics_tooltip", "Mostrar moeda Testemunho de heroísmo do deserto"},
            {"filter_testimony_of_jade_heroics", "Testemunho de heroísmo de jade"},
            {"filter_testimony_of_jade_heroics_tooltip", "Mostrar moeda Testemunho de heroísmo de jade"},
            {"filter_testimony_of_castoran_heroics", "Testemunho de heroísmo castorano"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Mostrar moeda Testemunho de heroísmo castorano"},
            {"filter_legendary_insight", "Perspectiva lendária"},
            {"filter_legendary_insight_tooltip", "Mostrar moeda Perspectiva lendária"},
            {"filter_tales_of_dungeon_delving", "Contos de exploração de masmorras"},
            {"filter_tales_of_dungeon_delving_tooltip", "Mostrar moeda Contos de exploração de masmorras"},
            {"filter_imperial_favor", "Favor imperial"},
            {"filter_imperial_favor_tooltip", "Mostrar moeda Favor imperial"},
            {"filter_canach_coins", "Moedas Canach"},
            {"filter_canach_coins_tooltip", "Mostrar moeda Moedas Canach"},
            {"filter_ancient_coin", "Moeda antiga"},
            {"filter_ancient_coin_tooltip", "Mostrar moeda Moeda antiga"},
            {"filter_unusual_coin", "Moeda incomum"},
            {"filter_unusual_coin_tooltip", "Mostrar moeda Moeda incomum"},
            {"filter_jade_sliver", "Fragmento de jade"},
            {"filter_jade_sliver_tooltip", "Mostrar moeda Fragmento de jade"},
            {"filter_static_charge", "Carga estática"},
            {"filter_static_charge_tooltip", "Mostrar moeda Carga estática"},
            {"filter_pinch_of_stardust", "Pitada de poeira estelar"},
            {"filter_pinch_of_stardust_tooltip", "Mostrar moeda Pitada de poeira estelar"},
            {"filter_calcified_gasp", "Suspiro calcificado"},
            {"filter_calcified_gasp_tooltip", "Mostrar moeda Suspiro calcificado"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Mostrar moeda Ursus Oblige"},
            {"filter_gaeting_crystal_janthir", "Cristal Gaeting (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Mostrar moeda Cristal Gaeting (Janthir)"},
            {"filter_antiquated_ducat", "Ducado antiquado"},
            {"filter_antiquated_ducat_tooltip", "Mostrar moeda Ducado antiquado"},
            {"filter_aether_rich_sap", "Seiva rica em éter"},
            {"filter_aether_rich_sap_tooltip", "Mostrar moeda Seiva rica em éter"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Redefinir tudo"},
            {"reset_all_tooltip", "Redefinir todas as configurações para valores padrão"},
            {"reset_confirm", "Tem certeza de que deseja redefinir todas as configurações?"},
            {"reset_warning", "Esta ação não pode ser desfeita."},
            {"yes_reset", "Sim, redefinir"},
            {"cancel", "Cancelar"},
            {"export", "Exportar"},
            {"export_tooltip", "Exportar configurações para um arquivo JSON"},
            {"export_settings", "Exportar configurações"},
            {"import", "Importar"},
            {"import_settings", "Importar configurações"},
            {"save", "Salvar"},
            {"save_tooltip", "Salvar configurações atuais"},
            
            // Settings Tab - General
            {"general_settings", "Configurações gerais"},
            {"account_management", "Gerenciamento de contas"},
            {"account_prefix", "Conta"},
            {"remove_account", "- Remover conta"},
            {"save_account", "Salvar conta"},
            {"reconnect_drf_token", "Reconectar ao DRF com o token atual"},
            {"reload_gw2_api_key_tooltip", "Recarregar chave API GW2 para buscar dados de itens"},
            {"reset_settings", "Auto Reset"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Nunca (apenas redefinição manual)"},
            {"auto_reset_on_load", "Ao carregar o addon"},
            {"auto_reset_daily", "Redefinição diária (00:00 UTC)"},
            {"auto_reset_weekly", "Semanal (Seg 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Semanal NA WvW (Sáb 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Semanal EU WvW (Sex 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Semanal bônus de mapa (Qui 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minutos após o último descarregamento"},
            {"auto_reset_custom_days", "Personalizado (dias)"},
            {"auto_reset_tooltip", "Quando redefinir automaticamente os contadores de farming"},
            {"minutes_after_unload_tooltip", "Minutos após o descarregamento do addon antes da redefinição automática"},
            {"reset_interval_days", "Intervalo de redefinição (dias)"},
            {"reset_interval_days_tooltip", "Intervalo de redefinição personalizado em dias (1-30 dias)"},
            
            // Visual Settings
            {"top_gradient_color", "Superior"},
            {"top_gradient_color_tooltip", "Cor de gradiente superior"},
            {"bottom_gradient_color", "Inferior"},
            {"bottom_gradient_color_tooltip", "Cor de gradiente inferior"},
            {"icon_size", "Tamanho do ícone"},
            {"icon_size_tooltip", "Tamanho dos ícones de itens em pixels (16-96)"},
            {"border_size", "Tamanho da borda"},
            {"border_size_tooltip", "Ajustar a espessura das bordas de raridade (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Alternar entre visualização de lista e grade na aba Itens"},
            {"grid_icon_size_items", "Tamanho do ícone de grade (Itens)"},
            {"grid_icon_size_items_tooltip", "Tamanho dos ícones na visualização de grade para Itens (16-128)"},
            {"grid_icon_size_currencies", "Tamanho do ícone de grade (Moedas)"},
            {"grid_icon_size_currencies_tooltip", "Tamanho dos ícones na visualização de grade para Moedas (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Mostrar mini janela"},
            {"show_mini_window_tooltip", "Mostra um pequeno widget de sobreposição com estatísticas principais"},
            {"mini_window_show_profit", "Mostrar lucro"},
            {"mini_window_show_profit_tooltip", "Mostrar lucro total na mini janela"},
            {"mini_window_show_profit_per_hour", "Mostrar lucro/hora"},
            {"mini_window_show_profit_per_hour_tooltip", "Mostrar lucro por hora na mini janela"},
            {"mini_window_show_tp_sell", "Mostrar venda TP (Listas)"},
            {"mini_window_show_tp_sell_tooltip", "Mostrar lucro de venda TP (listas) na mini janela"},
            {"mini_window_show_tp_instant", "Mostrar venda instantânea TP"},
            {"mini_window_show_tp_instant_tooltip", "Mostrar lucro de venda instantânea TP na mini janela"},
            {"mini_window_show_total_items", "Mostrar total de itens"},
            {"mini_window_show_total_items_tooltip", "Mostrar quantidade total de itens na mini janela"},
            {"mini_window_show_session_duration", "Mostrar duração da sessão"},
            {"mini_window_show_session_duration_tooltip", "Mostrar duração da sessão na mini janela"},
            {"mini_window_click_through", "Janela clicável"},
            {"mini_window_click_through_tooltip", "Permite clicar através da mini janela para o jogo"},
            
            // Main Window
            {"main_window_label", "Janela principal"},
            {"main_window_click_through", "Clicável"},
            {"main_window_click_through_tooltip", "Permite clicar através da janela principal para o jogo"},
            
            // Settings Profiles
            {"settings_profiles", "Perfis de configurações"},
            {"default_no_profile", "Padrão (Sem perfil)"},
            {"select_profile_tooltip", "Selecionar um perfil para aplicar suas configurações"},
            {"create", "Criar"},
            {"create_tooltip", "Criar um novo perfil com configurações atuais"},
            {"update_profile", "Atualizar perfil"},
            {"update_profile_tooltip", "Atualizar perfil atual com configurações atuais"},
            {"delete_profile", "Excluir perfil"},
            {"delete_profile_tooltip", "Excluir perfil atual"},
            
            // Automatic Backups
            {"automatic_backups", "Backups automáticos"},
            {"enable_automatic_backups", "Ativar backups automáticos"},
            {"enable_automatic_backups_tooltip", "Criar automaticamente backups antes de alterações"},
            {"backup_frequency", "Frequência de backup"},
            {"backup_frequency_tooltip", "Com que frequência criar backups automáticos"},
            {"backup_manual_only", "Apenas manual"},
            {"backup_daily", "Diário"},
            {"backup_weekly", "Semanal"},
            {"max_backup_count", "Máximo de backups"},
            {"max_backup_count_tooltip", "Número máximo de backups a manter (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Configurações de notificação"},
            {"enable_notifications", "Ativar notificações"},
            {"enable_notifications_tooltip", "Ativar notificações no jogo"},
            {"profit_goal", "Meta de lucro"},
            {"notify_profit_goal", "Notificar quando a meta de lucro for atingida"},
            {"notify_profit_goal_tooltip", "Notificar quando você atingir sua meta de lucro"},
            {"profit_goal_gold", "Meta de lucro (ouro)"},
            {"profit_goal_gold_tooltip", "Meta de lucro em moedas de ouro (1-1000)"},
            {"reset_warning_label", "Aviso de redefinição"},
            {"notify_reset_warning", "Notificar antes da redefinição"},
            {"notify_reset_warning_tooltip", "Notificar antes que a redefinição automática ocorra"},
            {"warning_minutes", "Minutos de aviso"},
            {"warning_minutes_tooltip", "Minutos antes da redefinição para mostrar aviso (1-60)"},
            {"session_complete", "Sessão concluída"},
            {"notify_session_complete", "Notificar após duração da sessão"},
            {"notify_session_complete_tooltip", "Notificar após farming por uma certa duração"},
            {"session_hours", "Horas de sessão"},
            {"session_hours_tooltip", "Horas de farming antes da notificação (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Pesquisar moedas..."},
            {"clear_search", "Limpar"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Pesquisar itens favoritos..."},
            {"search_favorite_currencies_hint", "Pesquisar moedas favoritas..."},
            {"clear_search_favorites", "Limpar"},
        };
        return translations;
    }
}
