// ---------------------------------------------------------------------------
// localization_zh.cpp – Chinese translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetChineseTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "已断开连接"},
            {"status_connecting", "连接中..."},
            {"status_connected", "已连接"},
            {"status_auth_failed", "认证失败 – 检查令牌"},
            {"status_reconnecting", "重新连接中..."},
            {"status_error", "错误"},
            {"status_unknown", "未知"},

            // Mini Window
            {"mini_window_title", "Farming Tracker 迷你窗口"},
            {"profit", "利润"},
            {"profit_per_hour", "利润/小时"},
            {"tp_sell", "TP出售"},
            {"tp_instant", "TP即时出售"},
            {"total_items", "总物品数"},
            {"session", "会话"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "GW2 API"},
            {"session_time_label", "会话时间"},
            {"reset_button", "重置"},
            {"reset_tooltip", "重置所有 farming 计数器（手动重置）"},

            // Tabs
            {"tab_summary", "概览"},
            {"tab_items", "物品"},
            {"tab_currencies", "货币"},
            {"tab_profit", "利润"},
            {"tab_favorites", "收藏"},
            {"tab_ignored", "已忽略"},
            {"tab_filter", "过滤器"},
            {"tab_custom_profit", "自定义利润"},
            {"tab_debug", "调试"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF 未连接"},
            {"warning_drf_not_connected_desc", "此插件需要 DRF 进行数据传输。"},
            {"warning_drf_install", "通过 Nexus 插件管理器或 https://drf.rs/ 安装 DRF"},
            {"warning_drf_token_invalid", "⚠️ DRF 令牌无效"},
            {"warning_drf_token_invalid_desc", "请在设置中检查您的 DRF 令牌。"},
            {"warning_gw2_api_key_not_set", "⚠️ GW2 API 密钥未设置"},
            {"warning_gw2_api_key_not_set_desc", "请在设置中设置您的 GW2 API 密钥以获取物品详情。"},
            {"overview", "概览"},
            {"overview_tooltip", "当前 farming 会话概览"},
            {"total_profit", "总利润"},
            {"total_profit_tooltip", "所有物品的自定义利润总和"},
            {"total_items_count", "总物品数"},
            {"total_items_tooltip", "追踪的唯一物品总数"},
            {"total_currencies", "总货币数"},
            {"total_currencies_tooltip", "追踪的唯一货币总数"},
            {"profit_per_hour_label", "每小时利润"},
            {"profit_per_hour_tooltip", "基于会话时间的每小时利润"},
            {"session_duration", "会话持续时间"},
            {"session_duration_tooltip", "当前 farming 会话持续时间"},
            {"top_items_profit", "热门物品（利润）"},
            {"top_items_profit_tooltip", "按利润值排名的前5个物品"},
            {"loading", "加载中..."},
            {"coin", "硬币"},
            {"top_items_count", "热门物品（数量）"},
            {"top_items_count_tooltip", "按数量排名的前5个物品"},
            {"top_currencies", "热门货币"},
            {"top_currencies_tooltip", "按数量排名的前5个货币"},
            {"quick_statistics", "快速统计"},
            {"quick_statistics_tooltip", "farming 统计概览"},
            {"average_item_value", "平均物品价值"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "总唯一物品数"},
            {"warning_no_data", "⚠️ 未加载数据"},
            {"warning_no_data_desc", "等待 DRF 数据..."},
            {"export", "导出"},
            {"export_tooltip", "将 farming 数据导出到文件"},
            {"export_json", "导出为 JSON"},
            {"export_csv", "导出为 CSV"},

            // Items Tab
            {"search_hint", "搜索物品..."},
            {"clear", "清除"},
            {"sort_count_high", "排序：|数量| 高"},
            {"sort_count_low", "排序：|数量| 低"},
            {"sort_id_up", "排序：物品ID 高"},
            {"sort_id_down", "排序：物品ID 低"},
            {"sort_name_az", "排序：名称 A–Z"},
            {"sort_tooltip", "按数量、ID或名称排序物品"},
            {"rarity_all", "稀有度：全部"},
            {"rarity_basic", "稀有度：基础+"},
            {"rarity_fine", "稀有度：精良+"},
            {"rarity_masterwork", "稀有度：大师+"},
            {"rarity_rare", "稀有度：稀有+"},
            {"rarity_exotic", "稀有度：异色+"},
            {"rarity_ascended", "稀有度：升华+"},
            {"rarity_legendary", "稀有度：仅传说"},
            {"rarity_tooltip", "按最低稀有度过滤物品"},
            {"rarity", "稀有度"},
            {"type", "类型"},
            {"vendor_value", "商人价值"},
            {"tp_buy_net", "TP购买（净）"},
            {"account_bound", "账号绑定"},
            {"yes", "是"},
            {"no", "否"},
            {"nosell", "不可出售"},
            {"favorite", "收藏"},
            {"ignore", "忽略"},

            // Currencies Tab
            {"search_currencies_hint", "搜索货币..."},
            {"api_id", "API ID"},
            {"currency_name", "货币名称"},
            {"count", "数量"},

            // Profit Tab
            {"profits", "利润"},
            {"profits_tooltip", "farming 总利润"},
            {"approx_profits", "约计利润"},
            {"approx_gold_per_hour", "约计每小时金币"},
            {"trading_profits", "交易利润"},
            {"trading_profits_tooltip", "来自交易站的利润"},
            {"approx_trading_profits_listings", "约计交易利润（挂单）"},
            {"approx_trading_profits_instant", "约计交易利润（即时出售）"},
            {"trading_details", "交易详情（机会成本）"},
            {"trading_details_tooltip", "使用物品而非出售的机会成本"},
            {"lost_profit_vs_tp_sell", "损失利润（vs TP出售）"},
            {"lost_profit_per_hour_vs_tp_sell", "每小时损失利润（vs TP出售）"},
            {"session_duration_label", "会话持续时间"},
            {"session_duration_tooltip", "当前 farming 会话持续时间"},

            // Filter Tab
            {"sell_method_filters", "出售方式过滤器"},
            {"sellable_to_vendor", "可出售给商人"},
            {"sellable_to_vendor_tooltip", "显示可出售给商人的物品"},
            {"sellable_on_tp", "可在TP出售"},
            {"sellable_on_tp_tooltip", "显示可在交易站出售的物品"},
            {"has_custom_profit", "有自定义利润"},
            {"has_custom_profit_tooltip", "显示有自定义利润值的物品"},
            {"api_knowledge_filters", "API知识过滤器"},
            {"known_by_api", "API已知"},
            {"known_by_api_tooltip", "显示GW2 API已知的物品"},
            {"unknown_by_api", "API未知"},
            {"unknown_by_api_tooltip", "显示GW2 API未知的物品"},
            {"item_type_filters", "物品类型过滤器"},
            {"type_armor", "护甲"},
            {"type_armor_tooltip", "显示护甲物品"},
            {"type_weapon", "武器"},
            {"type_weapon_tooltip", "显示武器物品"},
            {"type_trinket", "饰品"},
            {"type_trinket_tooltip", "显示饰品物品"},
            {"type_gizmo", "装置"},
            {"type_gizmo_tooltip", "显示装置物品"},
            {"type_crafting_material", "制作材料"},
            {"type_crafting_material_tooltip", "显示制作材料"},
            {"type_consumable", "消耗品"},
            {"type_consumable_tooltip", "显示消耗品"},
            {"type_gathering_tool", "采集工具"},
            {"type_gathering_tool_tooltip", "显示采集工具"},
            {"type_bag", "背包"},
            {"type_bag_tooltip", "显示背包"},
            {"type_container", "容器"},
            {"type_container_tooltip", "显示容器"},
            {"type_mini_pet", "迷你宠物"},
            {"type_mini_pet_tooltip", "显示迷你宠物"},
            {"currency_filters_label", "货币过滤器"},
            {"currency_main", "主要货币"},
            {"currency_fractal", "碎层/副本/地牢货币"},
            {"currency_wvw_pvp", "WvW/PvP货币"},
            {"currency_map", "地图特定货币"},
            {"filter_karma", "业力"},
            {"currency_karma_tooltip", "显示业力货币"},
            {"currency_laurel", "月桂"},
            {"currency_laurel_tooltip", "显示月桂货币"},
            {"currency_gem", "宝石"},
            {"currency_gem_tooltip", "显示宝石货币"},
            {"currency_fractal_relic", "碎层遗物"},
            {"currency_fractal_relic_tooltip", "显示碎层遗物货币"},
            {"currency_badge_of_honor", "荣誉徽章"},
            {"currency_badge_of_honor_tooltip", "显示荣誉徽章货币"},
            {"currency_guild_commendation", "公会嘉奖"},
            {"currency_guild_commendation_tooltip", "显示公会嘉奖货币"},
            {"currency_transmutation_charge", "转化充能"},
            {"currency_transmutation_charge_tooltip", "显示转化充能货币"},
            {"currency_spirit_shards", "灵魄碎片"},
            {"currency_spirit_shards_tooltip", "显示灵魄碎片货币"},
            {"currency_unbound_magic", "未绑定魔法"},
            {"currency_unbound_magic_tooltip", "显示未绑定魔法货币"},
            {"currency_volatile_magic", "不稳定魔法"},
            {"currency_volatile_magic_tooltip", "显示不稳定魔法货币"},
            {"currency_airship_parts", "飞艇零件"},
            {"currency_airship_parts_tooltip", "显示飞艇零件货币"},
            {"currency_geode", "晶洞"},
            {"currency_geode_tooltip", "显示晶洞货币"},
            {"currency_ley_line_crystals", "魔力线水晶"},
            {"currency_ley_line_crystals_tooltip", "显示魔力线水晶货币"},
            {"currency_trade_contracts", "贸易契约"},
            {"currency_trade_contracts_tooltip", "显示贸易契约货币"},
            {"currency_elegy_mosaic", "挽歌马赛克"},
            {"currency_elegy_mosaic_tooltip", "显示挽歌马赛克货币"},
            {"currency_uncommon_coins", "稀有硬币"},
            {"currency_uncommon_coins_tooltip", "显示稀有硬币货币"},
            {"currency_astral_acclaim", "星际赞誉"},
            {"currency_astral_acclaim_tooltip", "显示星际赞誉货币"},
            {"currency_pristine_fractal_relics", "纯净碎层遗物"},
            {"currency_pristine_fractal_relics_tooltip", "显示纯净碎层遗物货币"},
            {"currency_unstable_fractal_essence", "不稳定碎层精华"},
            {"currency_unstable_fractal_essence_tooltip", "显示不稳定碎层精华货币"},
            {"currency_magnetite_shards", "磁石碎片"},
            {"currency_magnetite_shards_tooltip", "显示磁石碎片货币"},
            {"currency_gaeting_crystals", "盖廷水晶"},
            {"currency_gaeting_crystals_tooltip", "显示盖廷水晶货币"},
            {"currency_prophet_shards", "先知碎片"},
            {"currency_prophet_shards_tooltip", "显示先知碎片货币"},
            {"currency_green_prophet_shards", "绿色先知碎片"},
            {"currency_green_prophet_shards_tooltip", "显示绿色先知碎片货币"},
            {"currency_wvw_skirmish_tickets", "WvW skirmish 票"},
            {"currency_wvw_skirmish_tickets_tooltip", "显示 WvW skirmish 票货币"},
            {"currency_proofs_of_heroics", "英雄证明"},
            {"currency_proofs_of_heroics_tooltip", "显示英雄证明货币"},
            {"currency_pvp_league_tickets", "PvP 联赛票"},
            {"currency_pvp_league_tickets_tooltip", "显示 PvP 联赛票货币"},
            {"currency_ascended_shards_of_glory", "升华荣耀碎片"},
            {"currency_ascended_shards_of_glory_tooltip", "显示升华荣耀碎片货币"},
            {"currency_research_notes", "研究笔记"},
            {"currency_research_notes_tooltip", "显示研究笔记货币"},
            {"currency_tyrian_defense_seal", "泰瑞亚防御印"},
            {"currency_tyrian_defense_seal_tooltip", "显示泰瑞亚防御印货币"},
            {"currency_testimony_of_desert_heroics", "沙漠英雄证词"},
            {"currency_testimony_of_desert_heroics_tooltip", "显示沙漠英雄证词货币"},
            {"currency_testimony_of_jade_heroics", "玉石英雄证词"},
            {"currency_testimony_of_jade_heroics_tooltip", "显示玉石英雄证词货币"},
            {"currency_testimony_of_castoran_heroics", "卡斯特兰英雄证词"},
            {"currency_testimony_of_castoran_heroics_tooltip", "显示卡斯特兰英雄证词货币"},
            {"currency_legendary_insight", "传奇洞察"},
            {"currency_legendary_insight_tooltip", "显示传奇洞察货币"},
            {"currency_tales_of_dungeon_delving", "地牢探索故事"},
            {"currency_tales_of_dungeon_delving_tooltip", "显示地牢探索故事货币"},
            {"currency_imperial_favor", "帝国恩宠"},
            {"currency_imperial_favor_tooltip", "显示帝国恩宠货币"},
            {"currency_canach_coins", "卡纳克硬币"},
            {"currency_canach_coins_tooltip", "显示卡纳克硬币货币"},
            {"currency_ancient_coin", "古代硬币"},
            {"currency_ancient_coin_tooltip", "显示古代硬币货币"},
            {"currency_unusual_coin", "异常硬币"},
            {"currency_unusual_coin_tooltip", "显示异常硬币货币"},
            {"currency_jade_sliver", "玉石碎片"},
            {"currency_jade_sliver_tooltip", "显示玉石碎片货币"},
            {"currency_static_charge", "静电充能"},
            {"currency_static_charge_tooltip", "显示静电充能货币"},
            {"currency_pinch_of_stardust", "一撮星尘"},
            {"currency_pinch_of_stardust_tooltip", "显示一撮星尘货币"},
            {"currency_calcified_gasp", "钙化叹息"},
            {"currency_calcified_gasp_tooltip", "显示钙化叹息货币"},
            {"currency_ursus_oblige", "乌尔苏斯义务"},
            {"currency_ursus_oblige_tooltip", "显示乌尔苏斯义务货币"},
            {"currency_gaeting_crystal_janthir", "盖廷水晶（詹瑟）"},
            {"currency_gaeting_crystal_janthir_tooltip", "显示盖廷水晶（詹瑟）货币"},
            {"currency_antiquated_ducat", "古老杜卡特"},
            {"currency_antiquated_ducat_tooltip", "显示古老杜卡特货币"},
            {"currency_aether_rich_sap", "以太丰富树液"},
            {"currency_aether_rich_sap_tooltip", "显示以太丰富树液货币"},

            // Additional Filters
            {"additional_filters", "附加过滤器"},
            {"account_bound", "账号绑定"},
            {"account_bound_tooltip", "显示账号绑定物品"},
            {"not_account_bound", "非账号绑定"},
            {"not_account_bound_tooltip", "显示非账号绑定物品"},
            {"nosell_items", "不可出售"},
            {"nosell_items_tooltip", "显示不可出售物品"},
            {"not_nosell", "可出售"},
            {"not_nosell_tooltip", "显示可出售物品"},
            {"favorite_items", "收藏"},
            {"favorite_items_tooltip", "显示收藏物品"},
            {"not_favorite", "未收藏"},
            {"not_favorite_tooltip", "显示未收藏物品"},
            {"ignored_items", "已忽略"},
            {"ignored_items_tooltip", "显示已忽略物品"},
            {"not_ignored", "未忽略"},
            {"not_ignored_tooltip", "显示未忽略物品"},

            // Range Filters
            {"range_filters", "范围过滤器"},
            {"show_range_filters", "显示范围过滤器"},
            {"filter_min_price", "过滤最低价格"},
            {"filter_max_price", "过滤最高价格"},
            {"filter_min_quantity", "过滤最低数量"},
            {"filter_max_quantity", "过滤最高数量"},

            // Mini Window Settings
            {"mini_window_settings", "迷你窗口"},
            {"show_profit", "显示利润"},
            {"show_profit_tooltip", "在迷你窗口中显示总利润"},
            {"show_profit_per_hour", "显示利润/小时"},
            {"show_profit_per_hour_tooltip", "在迷你窗口中显示每小时利润"},
            {"show_tp_sell", "显示TP出售（挂单）"},
            {"show_tp_sell_tooltip", "在迷你窗口中显示TP出售利润（挂单）"},
            {"show_tp_instant", "显示TP即时出售"},
            {"show_tp_instant_tooltip", "在迷你窗口中显示TP即时出售利润"},
            {"show_total_items", "显示总物品数"},
            {"show_total_items_tooltip", "在迷你窗口中显示总物品数量"},
            {"show_session_duration", "显示会话持续时间"},
            {"show_session_duration_tooltip", "在迷你窗口中显示会话持续时间"},
            {"window_click_through", "窗口点击穿透"},
            {"window_click_through_tooltip", "允许通过迷你窗口点击到游戏"},

            // Main Window Settings
            {"main_window", "主窗口"},
            {"click_through", "点击穿透"},
            {"click_through_tooltip", "允许通过主窗口点击到游戏"},

            // Advanced UI Settings
            {"advanced_ui_settings", "高级UI设置"},
            {"no_advanced_ui_settings", "（无可用的高级UI设置）"},

            // Display Settings
            {"display_settings", "显示设置"},
            {"show_item_icons", "显示物品图标"},
            {"show_item_icons_tooltip", "在列表中显示物品图标"},
            {"show_rarity_border", "显示稀有度边框"},
            {"show_rarity_border_tooltip", "根据物品稀有度显示彩色边框"},
            {"enable_grid_view", "启用网格视图"},
            {"enable_grid_view_tooltip", "以网格布局显示物品而非列表"},
            {"grid_icon_size", "网格图标大小"},
            {"grid_icon_size_tooltip", "网格视图中图标的大小"},

            // Count Display Settings
            {"count_display_settings", "数量显示设置"},
            {"count_text_color", "数量文本颜色"},
            {"count_text_color_tooltip", "数量文本的颜色"},
            {"count_background_color", "数量背景颜色"},
            {"count_background_color_tooltip", "数量背景的颜色"},
            {"count_font_size", "数量字体大小"},
            {"count_font_size_tooltip", "数量字体的大小"},
            {"count_horizontal_alignment", "数量水平对齐"},
            {"count_horizontal_alignment_tooltip", "数量文本的水平对齐"},

            // Gradient Background Settings
            {"gradient_background_settings", "渐变背景设置"},
            {"enable_gradient_backgrounds", "启用渐变背景"},
            {"enable_gradient_backgrounds_tooltip", "为窗口启用渐变背景"},
            {"gradient_top_color", "渐变顶部颜色"},
            {"gradient_top_color_tooltip", "渐变背景的顶部颜色"},
            {"gradient_bottom_color", "渐变底部颜色"},
            {"gradient_bottom_color_tooltip", "渐变背景的底部颜色"},

            // Custom Profit System
            {"custom_profit_system", "自定义利润系统"},
            {"enable_custom_profit", "启用自定义利润"},
            {"enable_custom_profit_tooltip", "为物品启用自定义利润值"},

            // Search
            {"search_settings", "搜索"},
            {"enable_search", "启用搜索"},
            {"enable_search_tooltip", "启用搜索功能"},

            // Ignored Items
            {"ignored_items_settings", "已忽略物品"},
            {"enable_ignored_items", "启用已忽略物品"},
            {"enable_ignored_items_tooltip", "启用已忽略物品功能"},

            // Auto Reset
            {"auto_reset_settings", "自动重置"},
            {"enable_auto_reset", "启用自动重置"},
            {"enable_auto_reset_tooltip", "在持续时间后自动重置farming会话"},
            {"auto_reset_duration", "自动重置持续时间（分钟）"},
            {"auto_reset_duration_tooltip", "自动重置前的持续时间（分钟）"},

            // DRF Settings
            {"drf_settings", "DRF设置"},
            {"drf_token", "DRF令牌"},
            {"drf_token_tooltip", "您的DRF认证令牌"},
            {"edit_token", "编辑令牌"},
            {"save_token", "保存令牌"},

            // GW2 API Settings
            {"gw2_api_settings", "GW2 API设置"},
            {"gw2_api_key", "GW2 API密钥"},
            {"gw2_api_key_tooltip", "您的GW2 API密钥用于物品详情"},
            {"edit_key", "编辑密钥"},
            {"save_key", "保存密钥"},

            // Language Settings
            {"language_settings", "语言"},
            {"language_tooltip", "选择界面语言"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "未配置账户"},
            {"no_profiles_created", "尚未创建配置文件"},
            {"count_label", "数量:"},
            {"profit_label", "利润:"},
            {"no_profit", "无利润"},
            {"vendor_value_label", "商人价值:"},
            {"tp_sell_gross_label", "TP出售（毛）:"},
            {"tp_sell_net_label", "TP出售（净）:"},
            {"tp_buy_gross_label", "TP购买（毛）:"},
            {"tp_buy_net_label", "TP购买（净）:"},
            {"ignored_items_label", "已忽略物品:"},
            {"ignored_currencies_label", "已忽略货币:"},
            {"total_items_label", "总物品数:"},
            {"total_currencies_label", "总货币数:"},
            {"total_profit_label", "总利润:"},
            {"tp_sell_profit_label", "TP出售利润:"},
            {"vendor_profit_label", "商人出售利润:"},
            {"profit_per_hour_label", "每小时利润:"},
            {"opportunity_cost_profit_label", "机会成本利润:"},
            {"opportunity_cost_profit_per_hour_label", "机会成本利润/小时:"},
            {"custom_profit_feature_placeholder", "功能已实现 - UI 待定"},
            {"custom_profit_items_header", "具有自定义利润的物品"},
            {"custom_profit_currencies_header", "具有自定义利润的货币"},
            {"add_custom_profit_item", "为物品添加自定义利润"},
            {"add_custom_profit_currency", "为货币添加自定义利润"},
            {"custom_profit_set_profit", "设置利润"},
            {"custom_profit_remove", "移除"},
            {"custom_profit_value", "利润值（铜币）"},
            {"custom_profit_set_tooltip", "为此物品设置自定义利润值"},
            {"custom_profit_remove_tooltip", "移除此物品的自定义利润值"},
            {"no_custom_profit_items", "（没有具有自定义利润的物品）"},
            {"no_custom_profit_currencies", "（没有具有自定义利润的货币）"},
            {"clear_all_custom_profits", "清除所有自定义利润"},
            {"clear_all_custom_profits_tooltip", "清除所有自定义利润值"},
            {"tabs_settings", "其他标签页"},
            {"tabs_description", "显示或隐藏其他标签页"},
            {"enable_ignored_tab", "启用忽略标签页"},
            {"enable_ignored_tab_tooltip", "在主视图中显示忽略标签页"},
            {"custom_profit_settings", "自定义利润"},
            {"overview_label", "概览:"},
            {"total_profit_label_simple", "总利润"},
            {"total_items_label_simple", "总物品数"},
            {"total_currencies_label_simple", "总货币数"},
            {"profit_per_hour_label_simple", "每小时利润"},
            {"session_duration_label_simple", "会话持续时间"},
            {"export_label", "导出:"},
            {"quick_actions", "快速操作:"},
            {"reset_confirm", "您确定要将所有设置重置为默认值吗?"},
            {"reset_warning", "此操作无法撤销。"},
            {"export_settings", "将设置导出到文件:"},
            {"import_settings", "从文件导入设置:"},
            {"edit_account", "编辑账户: %s"},
            {"account_name", "账户名称:"},
            {"drf_token_label", "DRF令牌:"},
            {"gw2_api_key_label", "GW2 API密钥:"},
            {"reload_config", "重新加载配置:"},
            {"auto_reset_label", "自动重置:"},
            {"next_reset_utc", "下次计划重置(UTC): %s"},
            {"favorites_ui", "收藏UI:"},
            {"favorites_colors", "收藏颜色:"},
            {"visual_enhancements", "视觉增强:"},
            {"show_profit_sparkline", "显示利润趋势线"},
            {"show_profit_sparkline_tooltip", "显示显示每小时利润趋势的小型折线图"},
            {"mini_window_widget", "迷你窗口（覆盖小部件）:"},
            {"main_window_label", "主窗口:"},
            {"profiles_description", "配置文件允许您保存不同的配置并快速切换。"},
            {"create_new_profile", "创建新配置文件:"},
            {"current_profile", "当前配置文件: %s"},
            {"auto_backup", "在重大更改前自动备份设置"},
            {"notifications", "配置游戏内重要事件通知"},
            {"profit_goal", "利润目标:"},
            {"reset_warning_label", "重置警告:"},
            {"session_complete", "会话完成:"},
            {"manage_ignored_items", "管理已忽略物品"},
            {"manage_ignored_currencies", "管理已忽略货币"},
            {"rarity_label", "稀有度: %s"},
            {"type_label", "类型: %d"},
            {"account_bound_label", "账号绑定: %s"},
            {"nosell_label", "不可出售: %s"},
            {"sell_method_filters_label", "出售方式过滤器:"},
            {"api_knowledge_filters_label", "API知识过滤器:"},
            {"additional_filters_label", "附加过滤器:"},
            {"item_type_filters_label", "物品类型过滤器:"},
            {"currency_filters_label", "货币过滤器:"},
            {"price_range", "价格范围(铜):"},
            {"quantity_range", "数量范围:"},
            {"debug_info", "调试信息"},
            {"drf_status", "DRF状态: %s"},
            {"drf_reconnect_count", "DRF重连次数: %d"},
            {"gw2_api_status", "GW2 API状态: %s"},
            {"gw2_api_reconnect_count", "GW2 API重连次数: %d"},
            {"session_duration_debug", "会话持续时间: %s"},
            {"gw2_memory", "GW2进程内存: %zu MB"},
            {"gw2_api_request_count", "GW2 API请求次数: %d"},
            {"ignored_items_count", "已忽略物品: %d"},
            {"ignored_currencies_count", "已忽略货币: %d"},
            {"drf_logs", "DRF日志:"},
            {"last_100_entries", "(最近100条记录)"},
            {"gw2_api_logs", "GW2 API日志:"},
            {"item_currency_details", "物品/货币详情(前5个):"},
            {"item_label", "物品 %d: %s (数量: "},
            {"loaded_label", ", 已加载: %s)"},
            {"currency_label", "货币 %d: %s (数量: "},
            {"custom_profit_items", "自定义利润物品(前5个):"},
            {"custom_profit_item", "物品 %d: %s (自定义利润: "},
            {"no_custom_profit_items", "(无自定义利润物品)"},
            {"ignored_items_debug", "已忽略物品(前5个):"},
            {"yes_label", "是"},
            {"no_label", "否"},
            {"profits_label", "利润:"},
            {"profits_tooltip", "Farming总利润"},
            {"approx_profits_label", "近似利润:"},
            {"approx_profits_tooltip", "自定义利润值的总利润"},
            {"approx_gold_per_hour_label", "近似每小时金币:"},
            {"approx_gold_per_hour_tooltip", "基于会话持续时间的每小时利润"},
            {"trading_profits_label", "交易利润:"},
            {"trading_profits_tooltip", "在交易行出售物品的利润"},
            {"approx_trading_profits_listings_label", "近似交易利润(列表):"},
            {"approx_trading_profits_listings_tooltip", "通过TP列表出售的总利润"},
            {"approx_trading_profits_instant_label", "近似交易利润(即时出售):"},
            {"approx_trading_profits_instant_tooltip", "通过TP即时购买订单出售的总利润"},
            {"trading_details_label", "交易详情(机会成本):"},
            {"trading_details_tooltip", "未通过TP列表出售而损失的利润"},
            {"lost_profit_vs_tp_sell_label", "损失利润(对比TP出售):"},
            {"lost_profit_vs_tp_sell_tooltip", "金色=损失利润,红色=对比TP出售获得利润"},
            {"lost_profit_per_hour_vs_tp_sell_label", "每小时损失利润(对比TP出售):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "每小时机会成本"},
            {"session_duration_debug_label", "会话持续时间: %s"},
            {"session_duration_debug_tooltip", "当前Farming会话持续时间"},
            {"tab_items", "物品"},
            {"manage_ignored_items", "管理已忽略物品"},
            {"clear_all_ignored_items", "清除所有已忽略物品"},
            {"unignore_item", "取消忽略物品"},
            {"tab_currencies", "货币"},
            {"manage_ignored_currencies", "管理已忽略货币"},
            {"clear_all_ignored_currencies", "清除所有已忽略货币"},
            {"unignore_currency", "取消忽略货币"},
            {"sell_method_filters_label", "出售方式过滤器:"},
            {"api_knowledge_filters_label", "API知识过滤器:"},
            {"additional_filters_label", "附加过滤器:"},
            {"item_type_filters_label", "物品类型过滤器:"},
            {"currency_filters_label", "货币过滤器:"},
            {"price_range", "价格范围(铜):"},
            {"quantity_range", "数量范围:"},
            {"debug_information", "调试信息"},
            {"drf_status_label", "DRF状态: %s"},
            {"drf_status_tooltip", "当前DRF连接状态"},
            {"drf_reconnect_count_label", "DRF重连次数: %d"},
            {"drf_reconnect_count_tooltip", "DRF重连尝试次数"},
            {"gw2_api_status_label", "GW2 API状态: %s"},
            {"gw2_api_status_tooltip", "当前GW2 API连接状态"},
            {"gw2_api_reconnect_count_label", "GW2 API重连次数: %d"},
            {"gw2_api_reconnect_count_tooltip", "GW2 API重连尝试次数"},
            {"session_duration_debug", "会话持续时间: %s"},
            {"session_duration_debug_tooltip", "当前Farming会话持续时间"},
            {"gw2_process_memory_label", "GW2进程内存: %zu MB"},
            {"gw2_process_memory_tooltip", "当前GW2进程内存使用"},
            {"gw2_api_request_count_label", "GW2 API请求次数: %d"},
            {"gw2_api_request_count_tooltip", "GW2 API请求总数"},
            {"ignored_items_debug_label", "已忽略物品: %d"},
            {"ignored_items_debug_tooltip", "已忽略物品数量"},
            {"ignored_currencies_debug_label", "已忽略货币: %d"},
            {"ignored_currencies_debug_tooltip", "已忽略货币数量"},
            {"drf_logs_label", "DRF日志:"},
            {"clear_drf_logs", "清除DRF日志"},
            {"clear_drf_logs_tooltip", "清除所有DRF日志条目"},
            {"last_100_entries", "(最近100条条目)"},
            {"gw2_api_logs_label", "GW2 API日志:"},
            {"clear_gw2_logs", "清除GW2日志"},
            {"clear_gw2_logs_tooltip", "清除所有GW2 API日志条目"},
            {"settings_label", "设置:"},
            {"api_key_label", "API密钥: %s"},
            {"api_key_tooltip", "GW2 API密钥状态"},
            {"not_set", "未设置"},
            {"set", "已设置"},
            {"drf_token_label", "DRF令牌: %s"},
            {"drf_token_tooltip", "DRF令牌状态"},
            {"toggle_hotkey_label", "切换热键: %s"},
            {"toggle_hotkey_tooltip", "主窗口切换热键"},
            {"auto_reset_mode_label", "自动重置模式: %d"},
            {"auto_reset_mode_tooltip", "当前自动重置模式"},
            {"next_reset_label", "下次重置: %s"},
            {"next_reset_tooltip", "下次计划重置时间(UTC)"},
            {"fake_drf_server_label", "假DRF服务器:"},
            {"use_fake_drf_server", "使用假DRF服务器"},
            {"use_fake_drf_server_tooltip", "仅用于测试目的"},
            {"reset_all_data", "重置所有数据"},
            {"reset_all_data_tooltip", "重置所有Farming数据"},
            {"coin", "金币"},
            {"rarity_label", "稀有度: %s"},
            {"nosell_label", "NoSell: %s"},
            {"item_id_label", "物品ID: %d"},
            {"currency_id_label", "货币ID: %d"},
            {"context_menu_add_favorites", "添加到收藏"},
            {"context_menu_remove_favorites", "从收藏移除"},
            {"context_menu_ignore", "忽略物品"},
            {"context_menu_unignore", "从忽略移除"},
            {"context_menu_copy_name", "复制名称"},
            {"context_menu_copy_id", "复制ID"},
            {"sell_method_filters_label", "销售方式过滤器:"},
            {"no_label", "否"},
            {"sort_price_down", "排序：物品价格降序"},
            {"sort_price_up", "排序：物品价格升序"},
            {"sort_count_high", "排序：|数量|高"},
            {"sort_count_low", "排序：|数量|低"},
            {"sort_name_az", "排序：名称A–Z"},
            {"sort_tooltip", "按数量、ID或名称排序物品"},
            {"rarity_all", "稀有度：全部"},
            {"rarity_basic", "稀有度：基础+"},
            {"rarity_fine", "稀有度：精良+"},
            {"rarity_masterwork", "稀有度：大师+"},
            {"rarity_rare", "稀有度：稀有+"},
            {"rarity_exotic", "稀有度：异色+"},
            {"rarity_ascended", "稀有度：升华+"},
            {"rarity_legendary", "稀有度：仅传说"},
            {"rarity_tooltip", "按最低稀有度过滤物品"},
            {"search_items_hint", "搜索物品..."},
            {"column_icon", "图标"},
            {"column_name", "名称"},
            {"column_count", "数量"},
            {"column_profit", "利润"},
            {"column_favorite", "收藏"},
            {"column_ignore", "忽略"},
            {"toggle_favorite", "切换收藏"},
            {"toggle_ignore", "切换忽略"},
            {"vendor_value_format", "商人价值：%s"},
            {"tp_sell_gross_format", "TP出售（毛利）：%s"},
            {"tp_sell_net_format", "TP出售（净利）：%s"},
            {"tp_buy_gross_format", "TP购买（毛利）：%s"},
            {"tp_buy_net_format", "TP购买（净利）：%s"},
            
            // Favorites Settings
            {"favorites_settings", "收藏设置"},
            {"favorites_first", "收藏优先"},
            {"favorites_first_tooltip", "在物品/货币列表中优先显示收藏"},
            {"enable_favorite_text_color", "启用收藏文本颜色"},
            {"enable_favorite_text_color_tooltip", "使用自定义文本颜色高亮收藏物品/货币"},
            {"text_color", "文本颜色"},
            {"enable_favorite_row_color", "启用收藏行颜色"},
            {"enable_favorite_row_color_tooltip", "使用自定义行背景颜色高亮收藏物品/货币"},
            {"row_color", "行颜色"},
            
            // Filter - Additional
            {"filter_favorite", "收藏"},
            {"filter_favorite_tooltip", "显示收藏物品（收藏标签页之外）"},
            {"filter_not_favorite", "非收藏"},
            {"filter_not_favorite_tooltip", "显示非收藏物品"},
            {"filter_research_notes", "研究笔记"},
            {"filter_research_notes_tooltip", "显示研究笔记货币"},
            {"range_filters", "范围过滤器"},
            {"range_filters_tooltip", "显示价格和数量范围过滤器"},
            {"filter_min_price", "最低价格"},
            {"filter_min_price_tooltip", "最低价格过滤器（0 = 禁用）"},
            {"filter_max_price", "最高价格"},
            {"filter_max_price_tooltip", "最高价格过滤器（0 = 禁用）"},
            {"filter_min_quantity", "最低数量"},
            {"filter_max_quantity", "最高数量"},
            {"gold", "金币"},
            {"silver", "银币"},
            {"copper", "铜币"},
            
            // Summary Tab - Table Columns
            {"column_label", "标签"},
            {"column_value", "值"},
            {"column_item", "物品"},
            {"column_count", "数量"},
            {"column_currency", "货币"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "按利润排名的物品"},
            {"top_items_count_header", "按数量排名的物品"},
            {"top_currencies_count_header", "按数量排名的货币"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "按利润值排名的前10个物品"},
            {"top_items_count_tooltip", "按数量排名的前10个物品"},
            {"top_currencies_count_tooltip", "按数量排名的前10个货币"},
            
            // Settings Tab - General
            {"show_main_window", "显示主窗口"},
            {"reset_all", "全部重置"},
            {"reset_all_tooltip", "将所有设置重置为默认值"},
            {"export", "导出"},
            {"export_tooltip", "将设置导出到JSON文件"},
            {"import", "导入"},
            {"import_tooltip", "从JSON文件导入设置"},
            {"save", "保存"},
            {"save_tooltip", "保存当前设置"},
            {"general_settings", "常规设置"},
            {"account_management", "账户管理"},
            {"add_account", "+ 添加账户"},
            {"remove_account", "- 删除账户"},
            {"save_account", "保存账户"},
            {"reload_drf_token", "重新加载DRF令牌"},
            {"reload_gw2_api_key", "重新加载GW2 API密钥"},
            {"reset_settings", "自动重置"},
            {"visual_settings", "视觉设置"},
            {"gradient_backgrounds", "渐变背景"},
            {"gradient_backgrounds_tooltip", "启用平滑渐变背景以获得更现代的外观"},
            {"top_gradient_color", "顶部渐变颜色"},
            {"top_gradient_color_tooltip", "顶部渐变颜色"},
            {"bottom_gradient_color", "底部渐变颜色"},
            {"bottom_gradient_color_tooltip", "底部渐变颜色"},
            {"show_item_icons", "显示物品图标（GW2渲染）"},
            {"show_item_icons_tooltip", "通过Nexus从render.guildwars2.com加载图标。"},
            {"icon_size", "图标大小"},
            {"icon_size_tooltip", "物品图标大小（像素）（16-96）"},
            {"show_rarity_borders", "显示稀有度边框"},
            {"show_rarity_borders_tooltip", "根据物品稀有度在图标周围显示彩色边框"},
            {"rarity_border_thickness", "稀有度边框粗细"},
            {"rarity_border_thickness_tooltip", "调整稀有度边框的粗细（1.0 - 10.0）"},
            {"enable_grid_view_items", "启用网格视图（物品）"},
            {"enable_grid_view_items_tooltip", "在物品选项卡中切换列表和网格视图"},
            {"grid_icon_size_items", "网格图标大小（物品）"},
            {"grid_icon_size_items_tooltip", "物品网格视图中的图标大小（16-128）"},
            {"enable_grid_view_currencies", "启用网格视图（货币）"},
            {"enable_grid_view_currencies_tooltip", "在货币选项卡中切换列表和网格视图"},
            {"grid_icon_size_currencies", "网格图标大小（货币）"},
            {"grid_icon_size_currencies_tooltip", "货币网格视图中的图标大小（16-128）"},
            {"show_mini_window", "显示迷你窗口"},
            {"show_mini_window_tooltip", "显示一个带有关键统计信息的小型覆盖小部件"},
            {"mini_window_show_profit", "显示利润"},
            {"mini_window_show_profit_tooltip", "在迷你窗口中显示总利润"},
            {"mini_window_show_profit_per_hour", "显示利润/小时"},
            {"mini_window_show_profit_per_hour_tooltip", "在迷你窗口中显示每小时利润"},
            {"mini_window_show_tp_sell", "显示TP出售（列表）"},
            {"mini_window_show_tp_sell_tooltip", "在迷你窗口中显示TP出售利润（列表）"},
            {"mini_window_show_tp_instant", "显示TP即时出售"},
            {"mini_window_show_tp_instant_tooltip", "在迷你窗口中显示TP即时出售利润"},
            {"mini_window_show_total_items", "显示物品总数"},
            {"mini_window_show_total_items_tooltip", "在迷你窗口中显示物品总数"},
            {"mini_window_show_session_duration", "显示会话持续时间"},
            {"mini_window_show_session_duration_tooltip", "在迷你窗口中显示会话持续时间"},
            {"mini_window_click_through", "窗口点击穿透"},
            {"mini_window_click_through_tooltip", "允许通过迷你窗口点击到游戏"},
            {"main_window_click_through", "点击穿透"},
            {"main_window_click_through_tooltip", "允许通过主窗口点击到游戏"},
            {"settings_profiles", "设置配置文件"},
            {"select_profile", "选择配置文件以应用其设置"},
            {"create_new_profile", "创建新配置文件"},
            {"create_new_profile_tooltip", "使用当前设置创建新配置文件"},
            {"create", "创建"},
            {"update_profile", "更新配置文件"},
            {"update_profile_tooltip", "使用当前设置更新当前配置文件"},
            {"delete_profile", "删除配置文件"},
            {"delete_profile_tooltip", "删除当前配置文件"},
            {"automatic_backups", "自动备份"},
            {"enable_automatic_backups", "启用自动备份"},
            {"enable_automatic_backups_tooltip", "在更改之前自动创建备份"},
            {"backup_frequency", "备份频率"},
            {"backup_frequency_tooltip", "创建自动备份的频率"},
            {"max_backups", "最大备份数"},
            {"max_backups_tooltip", "要保留的最大备份数（1-20）"},
            {"notification_settings", "通知设置"},
            {"enable_notifications", "启用通知"},
            {"enable_notifications_tooltip", "启用游戏内通知"},
            {"notify_profit_goal", "达到利润目标时通知"},
            {"notify_profit_goal_tooltip", "当您达到利润目标时通知"},
            {"profit_goal_gold", "利润目标（金币）"},
            {"profit_goal_gold_tooltip", "金币形式的利润目标（1-1000）"},
            {"notify_reset_warning", "重置前通知"},
            {"notify_reset_warning_tooltip", "在自动重置发生之前通知"},
            {"reset_warning_minutes", "重置警告（分钟）"},
            {"reset_warning_minutes_tooltip", "重置前显示警告的分钟数（1-60）"},
            {"notify_session_complete", "会话持续时间后通知"},
            {"notify_session_complete_tooltip", "在特定持续时间后通知"},
            {"session_complete_hours", "会话完成（小时）"},
            {"session_complete_hours_tooltip", "通知前的采集小时数（1-24）"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "可出售给商人"},
            {"filter_sellable_to_vendor_tooltip", "显示可出售给商人的物品"},
            {"filter_sellable_on_tp", "可在TP出售"},
            {"filter_sellable_on_tp_tooltip", "显示可在交易行出售的物品"},
            {"filter_custom_profit", "自定义利润"},
            {"filter_custom_profit_tooltip", "显示具有自定义利润的物品"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "API已知"},
            {"filter_known_by_api_tooltip", "显示GW2 API已知的物品"},
            {"filter_unknown_by_api", "API未知"},
            {"filter_unknown_by_api_tooltip", "显示GW2 API未知的物品"},
            
            // Filter - Additional
            {"show_ignored_items", "显示已忽略的物品"},
            {"show_ignored_items_tooltip", "在物品和货币标签页中显示忽略的物品/货币（禁用以隐藏）。与“忽略”过滤器的区别：此过滤器控制物品/货币标签页中的显示，“忽略”过滤器控制过滤器标签页中的显示。"},
            {"filter_ignored", "已忽略"},
            {"filter_ignored_tooltip", "显示已忽略的物品"},
            {"filter_not_ignored", "未忽略"},
            {"filter_not_ignored_tooltip", "显示未忽略的物品"},
            
            // Filter - Item Types
            {"filter_type_armor", "护甲"},
            {"filter_type_armor_tooltip", "显示护甲物品"},
            {"filter_type_backpack", "背包"},
            {"filter_type_backpack_tooltip", "显示背包物品"},
            {"filter_type_bag", "包"},
            {"filter_type_bag_tooltip", "显示包"},
            {"filter_type_container", "容器"},
            {"filter_type_container_tooltip", "显示容器"},
            {"filter_type_consumable", "消耗品"},
            {"filter_type_consumable_tooltip", "显示消耗品"},
            {"filter_type_crafting_material", "制作材料"},
            {"filter_type_crafting_material_tooltip", "显示制作材料"},
            {"filter_type_gathering_tool", "采集工具"},
            {"filter_type_gathering_tool_tooltip", "显示采集工具"},
            {"filter_type_gizmo", "装置"},
            {"filter_type_gizmo_tooltip", "显示装置物品"},
            {"filter_type_gizmo_container", "装置容器"},
            {"filter_type_gizmo_container_tooltip", "显示装置容器物品"},
            {"filter_type_mini_pet", "迷你宠物"},
            {"filter_type_mini_pet_tooltip", "显示迷你宠物"},
            {"filter_type_tool", "工具"},
            {"filter_type_tool_tooltip", "显示工具物品"},
            {"filter_type_trinket", "饰品"},
            {"filter_type_trinket_tooltip", "显示饰品物品"},
            {"filter_type_trophy", "战利品"},
            {"filter_type_trophy_tooltip", "显示战利品物品"},
            {"filter_type_unlock", "解锁"},
            {"filter_type_unlock_tooltip", "显示解锁物品"},
            {"filter_type_upgrade_component", "升级组件"},
            {"filter_type_upgrade_component_tooltip", "显示升级组件"},
            {"filter_type_weapon", "武器"},
            {"filter_type_weapon_tooltip", "显示武器物品"},
            
            // Filter - Currencies
            {"filter_karma", "业力"},
            {"filter_karma_tooltip", "显示业力货币"},
            {"filter_laurel", "月桂"},
            {"filter_laurel_tooltip", "显示月桂货币"},
            {"filter_gem", "宝石"},
            {"filter_gem_tooltip", "显示宝石货币"},
            {"filter_fractal_relic", "碎层遗物"},
            {"filter_fractal_relic_tooltip", "显示碎层遗物货币"},
            {"filter_badge_of_honor", "荣誉徽章"},
            {"filter_badge_of_honor_tooltip", "显示荣誉徽章货币"},
            {"filter_guild_commendation", "公会嘉奖"},
            {"filter_guild_commendation_tooltip", "显示公会嘉奖货币"},
            {"filter_transmutation_charge", "幻化石"},
            {"filter_transmutation_charge_tooltip", "显示幻化石货币"},
            {"filter_spirit_shards", "灵石碎片"},
            {"filter_spirit_shards_tooltip", "显示灵石碎片货币"},
            {"filter_unbound_magic", "未绑定魔法"},
            {"filter_unbound_magic_tooltip", "显示未绑定魔法货币"},
            {"filter_volatile_magic", "易变魔法"},
            {"filter_volatile_magic_tooltip", "显示易变魔法货币"},
            {"filter_airship_parts", "飞艇零件"},
            {"filter_airship_parts_tooltip", "显示飞艇零件货币"},
            {"filter_geode", "晶洞"},
            {"filter_geode_tooltip", "显示晶洞货币"},
            {"filter_ley_line_crystals", "地脉水晶"},
            {"filter_ley_line_crystals_tooltip", "显示地脉水晶货币"},
            {"filter_trade_contracts", "贸易契约"},
            {"filter_trade_contracts_tooltip", "显示贸易契约货币"},
            {"filter_elegy_mosaic", "挽歌马赛克"},
            {"filter_elegy_mosaic_tooltip", "显示挽歌马赛克货币"},
            {"filter_uncommon_coins", "稀有硬币"},
            {"filter_uncommon_coins_tooltip", "显示稀有硬币货币"},
            {"filter_astral_acclaim", "星界赞誉"},
            {"filter_astral_acclaim_tooltip", "显示星界赞誉货币"},
            
            // Debug Tab
            {"total_tracked_items", "追踪的物品总数"},
            {"total_tracked_items_tooltip", "追踪的物品总数"},
            {"total_tracked_currencies", "追踪的货币总数"},
            {"total_tracked_currencies_tooltip", "追踪的货币总数"},
            {"total_custom_profit", "自定义利润总计"},
            {"total_custom_profit_tooltip", "自定义利润总计"},
            {"total_tp_sell_profit", "TP出售利润总计"},
            {"total_tp_sell_profit_tooltip", "TP出售利润总计"},
            {"total_vendor_sell_profit", "商人出售利润总计"},
            {"total_vendor_sell_profit_tooltip", "商人出售利润总计"},
            {"profit_per_hour_calculation", "每小时利润计算"},
            {"profit_per_hour_calculation_tooltip", "每小时利润计算"},
            {"opportunity_cost_vs_tp_sell", "机会成本vs TP出售"},
            {"opportunity_cost_vs_tp_sell_tooltip", "机会成本vs TP出售"},
            {"opportunity_cost_per_hour", "每小时机会成本"},
            {"opportunity_cost_per_hour_tooltip", "每小时机会成本"},
            {"first_5_tracked_items", "前5个追踪的物品和货币及其详细信息"},
            {"first_5_tracked_items_tooltip", "前5个追踪的物品和货币及其详细信息"},
            {"first_5_custom_profit", "前5个具有自定义利润的物品"},
            {"first_5_custom_profit_tooltip", "前5个具有自定义利润的物品"},
            {"first_5_ignored_items", "前5个忽略物品"},
            {"first_5_ignored_items_tooltip", "前5个忽略物品"},
            
            // Debug Settings
            {"debug_settings", "调试设置"},
            {"enable_debug_tab", "启用调试标签"},
            {"enable_debug_tab_tooltip", "显示带有附加信息的调试标签"},
            
            // Currencies Tab
            {"gold_format", "金币: %lld"},
            {"count_format", "数量: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "切换收藏"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "切换忽略"},
            
            // Additional Filters
            {"filter_account_bound", "账号绑定"},
            {"filter_account_bound_tooltip", "显示账号绑定的物品"},
            {"filter_not_account_bound", "非账号绑定"},
            {"filter_not_account_bound_tooltip", "显示非账号绑定的物品"},
            {"filter_nosell", "不可出售"},
            {"filter_nosell_tooltip", "显示不可出售的物品"},
            {"filter_not_nosell", "可出售"},
            {"filter_not_nosell_tooltip", "显示可出售的物品"},
            {"filter_ignored", "已忽略"},
            {"filter_ignored_tooltip", "显示已忽略的物品"},
            {"filter_not_ignored", "未忽略"},
            {"filter_not_ignored_tooltip", "显示未忽略的物品"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "原始碎层遗物"},
            {"filter_pristine_fractal_relics_tooltip", "显示原始碎层遗物货币"},
            {"filter_unstable_fractal_essence", "不稳定碎层精华"},
            {"filter_unstable_fractal_essence_tooltip", "显示不稳定碎层精华货币"},
            {"filter_magnetite_shards", "磁石碎片"},
            {"filter_magnetite_shards_tooltip", "显示磁石碎片货币"},
            {"filter_gaeting_crystals", "盖廷水晶"},
            {"filter_gaeting_crystals_tooltip", "显示盖廷水晶货币"},
            {"filter_prophet_shards", "先知碎片"},
            {"filter_prophet_shards_tooltip", "显示先知碎片货币"},
            {"filter_green_prophet_shards", "绿色先知碎片"},
            {"filter_green_prophet_shards_tooltip", "显示绿色先知碎片货币"},
            {"filter_wvw_skirmish_tickets", "世界战冲突票"},
            {"filter_wvw_skirmish_tickets_tooltip", "显示世界战冲突票货币"},
            {"filter_proofs_of_heroics", "英雄证明"},
            {"filter_proofs_of_heroics_tooltip", "显示英雄证明货币"},
            {"filter_pvp_league_tickets", "PvP联赛票"},
            {"filter_pvp_league_tickets_tooltip", "显示PvP联赛票货币"},
            {"filter_ascended_shards_of_glory", "升华荣耀碎片"},
            {"filter_ascended_shards_of_glory_tooltip", "显示升华荣耀碎片货币"},
            {"filter_tyrian_defense_seal", "泰瑞亚防御印"},
            {"filter_tyrian_defense_seal_tooltip", "显示泰瑞亚防御印货币"},
            {"filter_testimony_of_desert_heroics", "沙漠英雄证明"},
            {"filter_testimony_of_desert_heroics_tooltip", "显示沙漠英雄证明货币"},
            {"filter_testimony_of_jade_heroics", "玉碎英雄证明"},
            {"filter_testimony_of_jade_heroics_tooltip", "显示玉碎英雄证明货币"},
            {"filter_testimony_of_castoran_heroics", "卡斯特兰英雄证明"},
            {"filter_testimony_of_castoran_heroics_tooltip", "显示卡斯特兰英雄证明货币"},
            {"filter_legendary_insight", "传奇洞察"},
            {"filter_legendary_insight_tooltip", "显示传奇洞察货币"},
            {"filter_tales_of_dungeon_delving", "地牢探索故事"},
            {"filter_tales_of_dungeon_delving_tooltip", "显示地牢探索故事货币"},
            {"filter_imperial_favor", "帝国恩宠"},
            {"filter_imperial_favor_tooltip", "显示帝国恩宠货币"},
            {"filter_canach_coins", "卡纳克币"},
            {"filter_canach_coins_tooltip", "显示卡纳克币货币"},
            {"filter_ancient_coin", "古代硬币"},
            {"filter_ancient_coin_tooltip", "显示古代硬币货币"},
            {"filter_unusual_coin", "不寻常硬币"},
            {"filter_unusual_coin_tooltip", "显示不寻常硬币货币"},
            {"filter_jade_sliver", "玉片"},
            {"filter_jade_sliver_tooltip", "显示玉片货币"},
            {"filter_static_charge", "静电电荷"},
            {"filter_static_charge_tooltip", "显示静电电荷货币"},
            {"filter_pinch_of_stardust", "一撮星尘"},
            {"filter_pinch_of_stardust_tooltip", "显示一撮星尘货币"},
            {"filter_calcified_gasp", "钙化喘息"},
            {"filter_calcified_gasp_tooltip", "显示钙化喘息货币"},
            {"filter_ursus_oblige", "乌尔苏斯奥布利格"},
            {"filter_ursus_oblige_tooltip", "显示乌尔苏斯奥布利格货币"},
            {"filter_gaeting_crystal_janthir", "盖廷水晶（詹瑟）"},
            {"filter_gaeting_crystal_janthir_tooltip", "显示盖廷水晶（詹瑟）货币"},
            {"filter_antiquated_ducat", "古老杜卡特"},
            {"filter_antiquated_ducat_tooltip", "显示古老杜卡特货币"},
            {"filter_aether_rich_sap", "以太丰富树液"},
            {"filter_aether_rich_sap_tooltip", "显示以太丰富树液货币"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "重置所有"},
            {"reset_all_tooltip", "将所有设置重置为默认值"},
            {"reset_confirm", "您确定要重置所有设置吗？"},
            {"reset_warning", "此操作无法撤销。"},
            {"yes_reset", "是，重置"},
            {"cancel", "取消"},
            {"export", "导出"},
            {"export_tooltip", "将设置导出到JSON文件"},
            {"export_settings", "导出设置"},
            {"import", "导入"},
            {"import_settings", "导入设置"},
            {"save", "保存"},
            {"save_tooltip", "保存当前设置"},
            
            // Settings Tab - General
            {"general_settings", "常规设置"},
            {"account_management", "账户管理"},
            {"account_prefix", "账户"},
            {"remove_account", "- 删除账户"},
            {"save_account", "保存账户"},
            {"reconnect_drf_token", "使用当前令牌重新连接DRF"},
            {"reload_gw2_api_key_tooltip", "重新加载GW2 API密钥以获取物品数据"},
            {"reset_settings", "自动重置"},
            
            // Auto Reset Modes
            {"auto_reset_never", "从不（仅手动重置）"},
            {"auto_reset_on_load", "加载插件时"},
            {"auto_reset_daily", "每日重置（00:00 UTC）"},
            {"auto_reset_weekly", "每周（周一 07:30 UTC）"},
            {"auto_reset_weekly_na_wvw", "每周NA WvW（周六 02:00 UTC）"},
            {"auto_reset_weekly_eu_wvw", "每周EU WvW（周五 18:00 UTC）"},
            {"auto_reset_weekly_map_bonus", "每周地图奖励（周四 20:00 UTC）"},
            {"auto_reset_minutes_unload", "上次卸载后分钟数"},
            {"auto_reset_custom_days", "自定义（天）"},
            {"auto_reset_tooltip", "何时自动重置耕种计数器"},
            {"minutes_after_unload_tooltip", "插件卸载后自动重置前的分钟数"},
            {"reset_interval_days", "重置间隔（天）"},
            {"reset_interval_days_tooltip", "自定义重置间隔天数（1-30天）"},
            
            // Visual Settings
            {"top_gradient_color", "顶部"},
            {"top_gradient_color_tooltip", "顶部渐变颜色"},
            {"bottom_gradient_color", "底部"},
            {"bottom_gradient_color_tooltip", "底部渐变颜色"},
            {"icon_size", "图标大小"},
            {"icon_size_tooltip", "物品图标大小（像素）（16-96）"},
            {"border_size", "边框大小"},
            {"border_size_tooltip", "调整稀有度边框粗细（1.0 - 10.0）"},
            {"enable_grid_view_items_tooltip", "在物品选项卡中切换列表和网格视图"},
            {"grid_icon_size_items", "网格图标大小（物品）"},
            {"grid_icon_size_items_tooltip", "物品网格视图中的图标大小（16-128）"},
            {"grid_icon_size_currencies", "网格图标大小（货币）"},
            {"grid_icon_size_currencies_tooltip", "货币网格视图中的图标大小（16-128）"},
            
            // Mini Window
            {"show_mini_window", "显示迷你窗口"},
            {"show_mini_window_tooltip", "显示带有关键统计信息的小型覆盖窗口"},
            {"mini_window_show_profit", "显示利润"},
            {"mini_window_show_profit_tooltip", "在迷你窗口中显示总利润"},
            {"mini_window_show_profit_per_hour", "显示利润/小时"},
            {"mini_window_show_profit_per_hour_tooltip", "在迷你窗口中显示每小时利润"},
            {"mini_window_show_tp_sell", "显示TP出售（列表）"},
            {"mini_window_show_tp_sell_tooltip", "在迷你窗口中显示TP出售利润（列表）"},
            {"mini_window_show_tp_instant", "显示TP即时出售"},
            {"mini_window_show_tp_instant_tooltip", "在迷你窗口中显示TP即时出售利润"},
            {"mini_window_show_total_items", "显示物品总数"},
            {"mini_window_show_total_items_tooltip", "在迷你窗口中显示物品总数"},
            {"mini_window_show_session_duration", "显示会话持续时间"},
            {"mini_window_show_session_duration_tooltip", "在迷你窗口中显示会话持续时间"},
            {"mini_window_click_through", "窗口可点击"},
            {"mini_window_click_through_tooltip", "允许通过迷你窗口点击到游戏"},
            
            // Main Window
            {"main_window_label", "主窗口"},
            {"main_window_click_through", "可点击"},
            {"main_window_click_through_tooltip", "允许通过主窗口点击到游戏"},
            
            // Settings Profiles
            {"settings_profiles", "设置配置文件"},
            {"default_no_profile", "默认（无配置文件）"},
            {"select_profile_tooltip", "选择配置文件以应用其设置"},
            {"create", "创建"},
            {"create_tooltip", "使用当前设置创建新配置文件"},
            {"update_profile", "更新配置文件"},
            {"update_profile_tooltip", "使用当前设置更新当前配置文件"},
            {"delete_profile", "删除配置文件"},
            {"delete_profile_tooltip", "删除当前配置文件"},
            
            // Automatic Backups
            {"automatic_backups", "自动备份"},
            {"enable_automatic_backups", "启用自动备份"},
            {"enable_automatic_backups_tooltip", "在更改前自动创建备份"},
            {"backup_frequency", "备份频率"},
            {"backup_frequency_tooltip", "创建自动备份的频率"},
            {"backup_manual_only", "仅手动"},
            {"backup_daily", "每日"},
            {"backup_weekly", "每周"},
            {"max_backup_count", "最大备份数"},
            {"max_backup_count_tooltip", "要保留的最大备份数（1-20）"},
            
            // Notification Settings
            {"notification_settings", "通知设置"},
            {"enable_notifications", "启用通知"},
            {"enable_notifications_tooltip", "启用游戏内通知"},
            {"profit_goal", "利润目标"},
            {"notify_profit_goal", "达到利润目标时通知"},
            {"notify_profit_goal_tooltip", "当您达到利润目标时通知"},
            {"profit_goal_gold", "利润目标（金币）"},
            {"profit_goal_gold_tooltip", "金币利润目标（1-1000）"},
            {"reset_warning_label", "重置警告"},
            {"notify_reset_warning", "重置前通知"},
            {"notify_reset_warning_tooltip", "自动重置发生前通知"},
            {"warning_minutes", "警告分钟"},
            {"warning_minutes_tooltip", "重置前显示警告的分钟数（1-60）"},
            {"session_complete", "会话完成"},
            {"notify_session_complete", "会话持续时间后通知"},
            {"notify_session_complete_tooltip", "耕种一定时间后通知"},
            {"session_hours", "会话小时"},
            {"session_hours_tooltip", "通知前的耕种小时数（1-24）"},
            
            // Currencies Tab
            {"search_currencies_hint", "搜索货币..."},
            {"clear_search", "清除"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "搜索收藏物品..."},
            {"search_favorite_currencies_hint", "搜索收藏货币..."},
            {"clear_search_favorites", "清除"},
        };
        return translations;
    }
}
