// ---------------------------------------------------------------------------
// localization_de.cpp – German translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetGermanTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Getrennt"},
            {"status_connecting", "Verbinde..."},
            {"status_connected", "Verbunden"},
            {"status_auth_failed", "Auth fehlgeschlagen – Token prüfen"},
            {"status_reconnecting", "Verbinde neu..."},
            {"status_error", "Fehler"},
            {"status_unknown", "Unbekannt"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Gewinn"},
            {"profit_per_hour", "Gewinn/Stunde"},
            {"tp_sell", "TP Verkauf"},
            {"tp_instant", "TP Sofortverkauf"},
            {"total_items", "Gesamt Items"},
            {"session", "Sitzung"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "GW2 API"},
            {"session_time_label", "Sitzungszeit"},
            {"reset_button", "Zurücksetzen"},
            {"reset_tooltip", "Alle Farming-Zähler zurücksetzen (manuell)"},

            // Tabs
            {"tab_summary", "Übersicht"},
            {"tab_items", "Items"},
            {"tab_currencies", "Währungen"},
            {"tab_profit", "Gewinn"},
            {"tab_favorites", "Favoriten"},
            {"tab_ignored", "Ignoriert"},
            {"tab_filter", "Filter"},
            {"tab_custom_profit", "Benutzerdefinierter Gewinn"},
            {"tab_debug", "Debuggen"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF nicht verbunden"},
            {"warning_drf_not_connected_desc", "Dieses Plugin benötigt DRF für die Datenübertragung."},
            {"warning_drf_install", "Installiere DRF über Nexus Addon Manager oder https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ DRF Token ungültig"},
            {"warning_drf_token_invalid_desc", "Bitte prüfe deinen DRF Token in den Einstellungen."},
            {"warning_gw2_api_key_not_set", "⚠️ GW2 API Key nicht gesetzt"},
            {"warning_gw2_api_key_not_set_desc", "Bitte setze deinen GW2 API Key in den Einstellungen für Item-Details."},
            {"overview", "Übersicht"},
            {"overview_tooltip", "Aktuelle Farming-Sitzungsübersicht"},
            {"total_profit", "Gesamtwinn"},
            {"total_profit_tooltip", "Gesamter benutzerdefinierter Gewinn von allen Gegenständen"},
            {"total_items_count", "Gesamt Items"},
            {"total_items_tooltip", "Gesamtzahl der einzigartigen Gegenstände"},
            {"total_currencies", "Gesamt Währungen"},
            {"total_currencies_tooltip", "Gesamtzahl der einzigartigen Währungen"},
            {"profit_per_hour_label", "Gewinn pro Stunde"},
            {"profit_per_hour_tooltip", "Gewinn pro Stunde basierend auf Sitzungsdauer"},
            {"session_duration", "Sitzungsdauer"},
            {"session_duration_tooltip", "Aktuelle Farming-Sitzungsdauer"},
            {"top_items_profit", "Top Gegenstände (Gewinn)"},
            {"top_items_profit_tooltip", "Top 5 Gegenstände nach Gewinnwert"},
            {"loading", "Lade..."},
            {"coin", "Münze"},
            {"top_items_count", "Top Gegenstände (Anzahl)"},
            {"top_items_count_tooltip", "Top 5 Gegenstände nach Anzahl"},
            {"top_currencies", "Top Währungen"},
            {"top_currencies_tooltip", "Top 5 Währungen nach Anzahl"},
            {"quick_statistics", "Schnellstatistiken"},
            {"quick_statistics_tooltip", "Übersicht der Farming-Statistiken"},
            {"average_item_value", "Durchschnittlicher Item-Wert"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Gesamt einzigartige Gegenstände"},
            {"warning_no_data", "⚠️ Keine Daten geladen"},
            {"warning_no_data_desc", "Warte auf DRF-Daten..."},
            {"export", "Exportieren"},
            {"export_tooltip", "Farming-Daten in Datei exportieren"},
            {"export_json", "Als JSON exportieren"},
            {"export_csv", "Als CSV exportieren"},

            // Items Tab
            {"search_hint", "Gegenstände suchen..."},
            {"clear", "Löschen"},
            {"sort_count_high", "Sortieren: |Anz| hoch"},
            {"sort_count_low", "Sortieren: |Anz| runter"},
            {"sort_id_up", "Sortieren: Gegenstand-ID hoch"},
            {"sort_id_down", "Sortieren: Gegenstand-ID runter"},
            {"sort_name_az", "Sortieren: Name A–Z"},
            {"sort_tooltip", "Gegenstände nach Anzahl, ID oder Name sortieren"},
            {"rarity_all", "Seltenheit: alle"},
            {"rarity_basic", "Seltenheit: Gewöhnlich+"},
            {"rarity_fine", "Seltenheit: Fein+"},
            {"rarity_masterwork", "Seltenheit: Meisterwerk+"},
            {"rarity_rare", "Seltenheit: Selten+"},
            {"rarity_exotic", "Seltenheit: Exotisch+"},
            {"rarity_ascended", "Seltenheit: Aufgestiegen+"},
            {"rarity_legendary", "Seltenheit: Nur Legendär"},
            {"rarity_tooltip", "Items nach Mindest-Seltenheit filtern"},
            {"rarity", "Seltenheit"},
            {"type", "Typ"},
            {"vendor_value", "Händlerwert"},
            {"tp_buy_net", "TP Kauf (Netto)"},
            {"account_bound", "Account-gebunden"},
            {"yes", "Ja"},
            {"no", "Nein"},
            {"nosell", "Nicht verkäuflich"},
            {"favorite", "Favorit"},
            {"ignore", "Ignorieren"},

            // Currencies Tab
            {"search_currencies_hint", "Währungen suchen..."},
            {"api_id", "API ID"},
            {"currency_name", "Währungsname"},
            {"count", "Anzahl"},

            // Profit Tab
            {"profits", "Gewinne"},
            {"profits_tooltip", "Gesamte Gewinne aus Farming"},
            {"approx_profits", "Ungefähr Gewinne"},
            {"approx_gold_per_hour", "Ungefähr Gold pro Stunde"},
            {"trading_profits", "Handelsgewinne"},
            {"trading_profits_tooltip", "Gewinne vom Handelsposten"},
            {"approx_trading_profits_listings", "Ungefähr Handelsgewinne (Listen)"},
            {"approx_trading_profits_instant", "Ungefähr Handelsgewinne (Sofortverkauf)"},
            {"trading_details", "Handelsdetails (Opportunitätskosten)"},
            {"trading_details_tooltip", "Opportunitätskosten bei Verwendung von Items statt Verkauf"},
            {"lost_profit_vs_tp_sell", "Verlorener Gewinn (vs TP Verkauf)"},
            {"lost_profit_per_hour_vs_tp_sell", "Verlorener Gewinn pro Stunde (vs TP Verkauf)"},
            {"session_duration_label", "Sitzungsdauer"},
            {"session_duration_tooltip", "Aktuelle Farming-Sitzungsdauer"},

            // Filter Tab
            {"sell_method_filters", "Verkaufsmethode-Filter"},
            {"sellable_to_vendor", "An Händler verkaufbar"},
            {"sellable_to_vendor_tooltip", "Zeige Gegenstände, die an Händler verkauft werden können"},
            {"sellable_on_tp", "Auf TP verkaufbar"},
            {"sellable_on_tp_tooltip", "Zeige Items, die auf dem Handelsposten verkauft werden können"},
            {"has_custom_profit", "Hat benutzerdefinierten Gewinn"},
            {"has_custom_profit_tooltip", "Zeige Gegenstände mit benutzerdefinierten Gewinnwerten"},
            {"api_knowledge_filters", "API-Wissens-Filter"},
            {"known_by_api", "Von API bekannt"},
            {"known_by_api_tooltip", "Zeige Gegenstände, die von der GW2 API bekannt sind"},
            {"unknown_by_api", "Von API unbekannt"},
            {"unknown_by_api_tooltip", "Zeige Items, die nicht von der GW2 API bekannt sind"},
            {"item_type_filters", "Item-Typ-Filter"},
            {"type_armor", "Rüstung"},
            {"type_armor_tooltip", "Zeige Rüstungs-Items"},
            {"type_weapon", "Waffe"},
            {"type_weapon_tooltip", "Zeige Waffen-Gegenstände"},
            {"type_trinket", "Schmuck"},
            {"type_trinket_tooltip", "Zeige Schmuck-Items"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Zeige Gizmo-Gegenstände"},
            {"type_crafting_material", "Handwerksmaterial"},
            {"type_crafting_material_tooltip", "Zeige Handwerksmaterialien"},
            {"type_consumable", "Verbrauchsgut"},
            {"type_consumable_tooltip", "Zeige Verbrauchsgüter"},
            {"type_gathering_tool", "Sammelwerkzeug"},
            {"type_gathering_tool_tooltip", "Zeige Sammelwerkzeuge"},
            {"type_bag", "Tasche"},
            {"type_bag_tooltip", "Zeige Taschen"},
            {"type_container", "Behälter"},
            {"type_container_tooltip", "Zeige Behälter"},
            {"type_mini_pet", "Mini-Haustier"},
            {"type_mini_pet_tooltip", "Zeige Mini-Haustiere"},
            {"currency_filters_label", "Währungsfilter"},
            {"currency_main", "Hauptwährungen"},
            {"currency_fractal", "Fraktal/Raid/Dungeon-Währungen"},
            {"currency_wvw_pvp", "WvW/PvP-Währungen"},
            {"currency_map", "Kartenspezifische Währungen"},
            {"filter_karma", "Karma"},
            {"currency_karma_tooltip", "Zeige Karma-Währung"},
            {"currency_laurel", "Lorbeer"},
            {"currency_laurel_tooltip", "Zeige Lorbeer-Währung"},
            {"currency_gem", "Edelstein"},
            {"currency_gem_tooltip", "Zeige Edelstein-Währung"},
            {"currency_fractal_relic", "Fraktal-Relikt"},
            {"currency_fractal_relic_tooltip", "Zeige Fraktal-Relikt-Währung"},
            {"currency_badge_of_honor", "Ehrenabzeichen"},
            {"currency_badge_of_honor_tooltip", "Zeige Ehrenabzeichen-Währung"},
            {"currency_guild_commendation", "Gilden-Lob"},
            {"currency_guild_commendation_tooltip", "Zeige Gilden-Lob-Währung"},
            {"currency_transmutation_charge", "Transmutationsladung"},
            {"currency_transmutation_charge_tooltip", "Zeige Transmutationsladung-Währung"},
            {"currency_spirit_shards", "Geisterscherben"},
            {"currency_spirit_shards_tooltip", "Zeige Geisterscherben-Währung"},
            {"currency_unbound_magic", "Ungebundene Magie"},
            {"currency_unbound_magic_tooltip", "Zeige Ungebundene Magie-Währung"},
            {"currency_volatile_magic", "Flüchtige Magie"},
            {"currency_volatile_magic_tooltip", "Zeige Flüchtige Magie-Währung"},
            {"currency_airship_parts", "Luftschiffteile"},
            {"currency_airship_parts_tooltip", "Zeige Luftschiffteile-Währung"},
            {"currency_geode", "Geode"},
            {"currency_geode_tooltip", "Zeige Geode-Währung"},
            {"currency_ley_line_crystals", "Leitlinienkristalle"},
            {"currency_ley_line_crystals_tooltip", "Zeige Leitlinienkristalle-Währung"},
            {"currency_trade_contracts", "Handelsverträge"},
            {"currency_trade_contracts_tooltip", "Zeige Handelsverträge-Währung"},
            {"currency_elegy_mosaic", "Elegie-Mosaik"},
            {"currency_elegy_mosaic_tooltip", "Zeige Elegie-Mosaik-Währung"},
            {"currency_uncommon_coins", "Ungewöhnliche Münzen"},
            {"currency_uncommon_coins_tooltip", "Zeige Ungewöhnliche Münzen-Währung"},
            {"currency_astral_acclaim", "Astraler Beifall"},
            {"currency_astral_acclaim_tooltip", "Zeige Astraler Beifall-Währung"},
            {"currency_pristine_fractal_relics", "Makellose Fraktal-Relikte"},
            {"currency_pristine_fractal_relics_tooltip", "Zeige Makellose Fraktal-Relikte-Währung"},
            {"currency_unstable_fractal_essence", "Instabile Fraktal-Essenz"},
            {"currency_unstable_fractal_essence_tooltip", "Zeige Instabile Fraktal-Essenz-Währung"},
            {"currency_magnetite_shards", "Magnetitscherben"},
            {"currency_magnetite_shards_tooltip", "Zeige Magnetitscherben-Währung"},
            {"currency_gaeting_crystals", "Gaeting-Kristalle"},
            {"currency_gaeting_crystals_tooltip", "Zeige Gaeting-Kristalle-Währung"},
            {"currency_prophet_shards", "Prophetenscherben"},
            {"currency_prophet_shards_tooltip", "Zeige Prophetenscherben-Währung"},
            {"currency_green_prophet_shards", "Grüne Prophetenscherben"},
            {"currency_green_prophet_shards_tooltip", "Zeige Grüne Prophetenscherben-Währung"},
            {"currency_wvw_skirmish_tickets", "WvW-Gefechtstickets"},
            {"currency_wvw_skirmish_tickets_tooltip", "Zeige WvW-Gefechtstickets-Währung"},
            {"currency_proofs_of_heroics", "Heldenbeweise"},
            {"currency_proofs_of_heroics_tooltip", "Zeige Heldenbeweise-Währung"},
            {"currency_pvp_league_tickets", "PvP-Liga-Tickets"},
            {"currency_pvp_league_tickets_tooltip", "Zeige PvP-Liga-Tickets-Währung"},
            {"currency_ascended_shards_of_glory", "Aufgestiegene Ruhmscherben"},
            {"currency_ascended_shards_of_glory_tooltip", "Zeige Aufgestiegene Ruhmscherben-Währung"},
            {"currency_research_notes", "Forschungsnotizen"},
            {"currency_research_notes_tooltip", "Zeige Forschungsnotizen-Währung"},
            {"currency_tyrian_defense_seal", "Tyrianisches Verteidigungssiegel"},
            {"currency_tyrian_defense_seal_tooltip", "Zeige Tyrianisches Verteidigungssiegel-Währung"},
            {"currency_testimony_of_desert_heroics", "Zeugnis der Wüstenheldentaten"},
            {"currency_testimony_of_desert_heroics_tooltip", "Zeige Zeugnis der Wüstenheldentaten-Währung"},
            {"currency_testimony_of_jade_heroics", "Zeugnis der Jadeheldentaten"},
            {"currency_testimony_of_jade_heroics_tooltip", "Zeige Zeugnis der Jadeheldentaten-Währung"},
            {"currency_testimony_of_castoran_heroics", "Zeugnis der Castoran-Heldentaten"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Zeige Zeugnis der Castoran-Heldentaten-Währung"},
            {"currency_legendary_insight", "Legendäre Einsicht"},
            {"currency_legendary_insight_tooltip", "Zeige Legendäre Einsicht-Währung"},
            {"currency_tales_of_dungeon_delving", "Geschichten des Dungeon-Tiefgangs"},
            {"currency_tales_of_dungeon_delving_tooltip", "Zeige Geschichten des Dungeon-Tiefgangs-Währung"},
            {"currency_imperial_favor", "Kaiserliche Gunst"},
            {"currency_imperial_favor_tooltip", "Zeige Kaiserliche Gunst-Währung"},
            {"currency_canach_coins", "Canach-Münzen"},
            {"currency_canach_coins_tooltip", "Zeige Canach-Münzen-Währung"},
            {"currency_ancient_coin", "Antike Münze"},
            {"currency_ancient_coin_tooltip", "Zeige Antike Münze-Währung"},
            {"currency_unusual_coin", "Ungewöhnliche Münze"},
            {"currency_unusual_coin_tooltip", "Zeige Ungewöhnliche Münze-Währung"},
            {"currency_jade_sliver", "Jadesplitter"},
            {"currency_jade_sliver_tooltip", "Zeige Jadesplitter-Währung"},
            {"currency_static_charge", "Statische Ladung"},
            {"currency_static_charge_tooltip", "Zeige Statische Ladung-Währung"},
            {"currency_pinch_of_stardust", "Prise Sternenstaub"},
            {"currency_pinch_of_stardust_tooltip", "Zeige Prise Sternenstaub-Währung"},
            {"currency_calcified_gasp", "Verkalkter Atem"},
            {"currency_calcified_gasp_tooltip", "Zeige Verkalkter Atem-Währung"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Zeige Ursus Oblige-Währung"},
            {"currency_gaeting_crystal_janthir", "Gaeting-Kristall (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Zeige Gaeting-Kristall (Janthir)-Währung"},
            {"currency_antiquated_ducat", "Antiker Dukaten"},
            {"currency_antiquated_ducat_tooltip", "Zeige Antiker Dukaten-Währung"},
            {"currency_aether_rich_sap", "Ätherreicher Saft"},
            {"currency_aether_rich_sap_tooltip", "Zeige Ätherreicher Saft-Währung"},

            // Additional Filters
            {"additional_filters", "Zusätzliche Filter"},
            {"account_bound", "Account-gebunden"},
            {"account_bound_tooltip", "Zeige Account-gebundene Items"},
            {"not_account_bound", "Nicht Account-gebunden"},
            {"not_account_bound_tooltip", "Zeige nicht Account-gebundene Gegenstände"},
            {"nosell_items", "Nicht verkäuflich"},
            {"nosell_items_tooltip", "Zeige Nicht verkäufliche Gegenstände"},
            {"not_nosell", "Verkäuflich"},
            {"not_nosell_tooltip", "Zeige verkaufbare Gegenstände"},
            {"favorite_items", "Favorit"},
            {"favorite_items_tooltip", "Zeige Favoriten-Items"},
            {"not_favorite", "Kein Favorit"},
            {"not_favorite_tooltip", "Zeige nicht-Favoriten-Items"},
            {"ignored_items", "Ignoriert"},
            {"ignored_items_tooltip", "Zeige ignorierte Items"},
            {"not_ignored", "Nicht ignoriert"},
            {"not_ignored_tooltip", "Zeige nicht-ignorierte Gegenstände"},

            // Range Filters
            {"range_filters", "Bereichsfilter"},
            {"show_range_filters", "Bereichsfilter anzeigen"},
            {"filter_min_price", "Filter Mindestpreis"},
            {"filter_max_price", "Filter Höchstpreis"},
            {"filter_min_quantity", "Filter Mindestmenge"},
            {"filter_max_quantity", "Filter Höchstmenge"},

            // Mini Window Settings
            {"mini_window_settings", "Mini-Fenster"},
            {"show_profit", "Gewinn anzeigen"},
            {"show_profit_tooltip", "Gesamtwinn im Mini-Fenster anzeigen"},
            {"show_profit_per_hour", "Gewinn/Stunde anzeigen"},
            {"show_profit_per_hour_tooltip", "Gewinn pro Stunde im Mini-Fenster anzeigen"},
            {"show_tp_sell", "TP Verkauf (Listen) anzeigen"},
            {"show_tp_sell_tooltip", "TP-Verkaufsgewinn (Listen) im Mini-Fenster anzeigen"},
            {"show_tp_instant", "TP Sofortverkauf anzeigen"},
            {"show_tp_instant_tooltip", "TP-Sofortverkaufsgewinn im Mini-Fenster anzeigen"},
            {"show_total_items", "Gesamt Items anzeigen"},
            {"show_total_items_tooltip", "Gesamt Gegenstand-Anzahl im Mini-Fenster anzeigen"},
            {"show_session_duration", "Sitzungsdauer anzeigen"},
            {"show_session_duration_tooltip", "Sitzungsdauer im Mini-Fenster anzeigen"},
            {"window_click_through", "Fenster-Durchklicken"},
            {"window_click_through_tooltip", "Ermöglicht das Durchklicken durch das Mini-Fenster zum Spiel"},

            // Main Window Settings
            {"main_window", "Hauptfenster"},
            {"click_through", "Durchklicken"},
            {"click_through_tooltip", "Ermöglicht das Durchklicken durch das Hauptfenster zum Spiel"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Erweiterte UI-Einstellungen"},
            {"no_advanced_ui_settings", "(Keine erweiterten UI-Einstellungen verfügbar)"},

            // Display Settings
            {"display_settings", "Anzeigeeinstellungen"},
            {"show_item_icons", "Item-Icons anzeigen"},
            {"show_item_icons_tooltip", "Gegenstand-Icons in der Liste anzeigen"},
            {"show_rarity_border", "Seltenheitsrand anzeigen"},
            {"show_rarity_border_tooltip", "Farbigen Rand basierend auf Item-Seltenheit anzeigen"},
            {"enable_grid_view", "Rasteransicht aktivieren"},
            {"enable_grid_view_tooltip", "Items in Rasterlayout statt Liste anzeigen"},
            {"grid_icon_size", "Raster-Icon-Größe"},
            {"grid_icon_size_tooltip", "Größe der Icons in Rasteransicht"},

            // Count Display Settings
            {"count_display_settings", "Anzahl-Anzeigeeinstellungen"},
            {"count_text_color", "Anzahl-Textfarbe"},
            {"count_text_color_tooltip", "Farbe des Anzahl-Textes"},
            {"count_background_color", "Anzahl-Hintergrundfarbe"},
            {"count_background_color_tooltip", "Farbe des Anzahl-Hintergrunds"},
            {"count_font_size", "Anzahl-Schriftgröße"},
            {"count_font_size_tooltip", "Größe der Anzahl-Schrift"},
            {"count_horizontal_alignment", "Anzahl-Horizontalausrichtung"},
            {"count_horizontal_alignment_tooltip", "Horizontale Ausrichtung des Anzahl-Textes"},

            // Gradient Background Settings
            {"gradient_background_settings", "Verlaufshintergrund-Einstellungen"},
            {"enable_gradient_backgrounds", "Verlaufshintergründe aktivieren"},
            {"enable_gradient_backgrounds_tooltip", "Verlaufshintergrund für Fenster aktivieren"},
            {"gradient_top_color", "Verlauf-Oben-Farbe"},
            {"gradient_top_color_tooltip", "Obere Farbe des Verlaufshintergrunds"},
            {"gradient_bottom_color", "Verlauf-Unten-Farbe"},
            {"gradient_bottom_color_tooltip", "Untere Farbe des Verlaufshintergrunds"},

            // Custom Profit System
            {"custom_profit_system", "Benutzerdefiniertes Gewinnsystem"},
            {"enable_custom_profit", "Benutzerdefinierten Gewinn aktivieren"},
            {"enable_custom_profit_tooltip", "Benutzerdefinierte Gewinnwerte für Gegenstände aktivieren"},

            // Search
            {"search_settings", "Suche"},
            {"enable_search", "Suche aktivieren"},
            {"enable_search_tooltip", "Suchfunktionalität aktivieren"},

            // Ignored Items
            {"ignored_items_settings", "Ignorierte Items"},
            {"enable_ignored_items", "Ignorierte Items aktivieren"},
            {"enable_ignored_items_tooltip", "Ignorierte Gegenstände-Funktionalität aktivieren"},

            // Auto Reset
            {"auto_reset_settings", "Auto-Reset"},
            {"enable_auto_reset", "Auto-Reset aktivieren"},
            {"enable_auto_reset_tooltip", "Farming-Sitzung automatisch nach einer Dauer zurücksetzen"},
            {"auto_reset_duration", "Auto-Reset-Dauer (Minuten)"},
            {"auto_reset_duration_tooltip", "Dauer in Minuten vor Auto-Reset"},

            // DRF Settings
            {"drf_settings", "DRF-Einstellungen"},
            {"drf_token", "DRF Token"},
            {"drf_token_tooltip", "Dein DRF-Authentifizierungs-Token"},
            {"edit_token", "Token bearbeiten"},
            {"save_token", "Token speichern"},

            // GW2 API Settings
            {"gw2_api_settings", "GW2 API-Einstellungen"},
            {"gw2_api_key", "GW2 API Key"},
            {"gw2_api_key_tooltip", "Dein GW2 API Key für Item-Details"},
            {"edit_key", "Key bearbeiten"},
            {"save_key", "Key speichern"},

            // Language Settings
            {"language_settings", "Sprache"},
            {"language_tooltip", "Oberflächensprache auswählen"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "Keine Accounts konfiguriert"},
            {"no_profiles_created", "Noch keine Profile erstellt"},
            {"count_label", "Anzahl:"},
            {"profit_label", "Gewinn:"},
            {"no_profit", "Kein Gewinn"},
            {"vendor_value_label", "Händlerwert:"},
            {"tp_sell_gross_label", "TP Verkauf (Brutto):"},
            {"tp_sell_net_label", "TP Verkauf (Netto):"},
            {"tp_buy_gross_label", "TP Kauf (Brutto):"},
            {"tp_buy_net_label", "TP Kauf (Netto):"},
            {"ignored_items_label", "Ignorierte Items:"},
            {"ignored_currencies_label", "Ignorierte Währungen:"},
            {"total_items_label", "Gesamt Items:"},
            {"total_currencies_label", "Gesamt Währungen:"},
            {"total_profit_label", "Gesamtwinn:"},
            {"tp_sell_profit_label", "TP-Verkaufsgewinn:"},
            {"vendor_profit_label", "Händlerverkaufsgewinn:"},
            {"profit_per_hour_label", "Gewinn pro Stunde:"},
            {"opportunity_cost_profit_label", "Opportunitätskosten-Gewinn:"},
            {"opportunity_cost_profit_per_hour_label", "Opportunitätskosten-Gewinn/Stunde:"},
            {"custom_profit_feature_placeholder", "Feature implementiert - UI folgt"},
            {"custom_profit_items_header", "Gegenstände mit benutzerdefiniertem Gewinn"},
            {"custom_profit_currencies_header", "Währungen mit benutzerdefiniertem Gewinn"},
            {"add_custom_profit_item", "Benutzerdefinierten Gewinn für Gegenstand hinzufügen"},
            {"add_custom_profit_currency", "Benutzerdefinierten Gewinn für Währung hinzufügen"},
            {"custom_profit_set_profit", "Gewinn setzen"},
            {"custom_profit_remove", "Entfernen"},
            {"custom_profit_value", "Gewinnwert (Kupfer)"},
            {"custom_profit_set_tooltip", "Benutzerdefinierten Gewinnwert für dieses Element setzen"},
            {"custom_profit_remove_tooltip", "Benutzerdefinierten Gewinnwert für dieses Element entfernen"},
            {"no_custom_profit_items", "(Keine Gegenstände mit benutzerdefiniertem Gewinn)"},
            {"no_custom_profit_currencies", "(Keine Währungen mit benutzerdefiniertem Gewinn)"},
            {"clear_all_custom_profits", "Alle benutzerdefinierten Gewinne löschen"},
            {"clear_all_custom_profits_tooltip", "Alle benutzerdefinierten Gewinnwerte löschen"},
            {"tabs_settings", "Andere Tabs"},
            {"tabs_description", "Andere Tabs ein- und ausblenden"},
            {"enable_ignored_tab", "Ignored Tab aktivieren"},
            {"enable_ignored_tab_tooltip", "Ignored Tab in der Hauptansicht anzeigen"},
            {"custom_profit_settings", "Benutzerdefinierter Gewinn"},
            {"overview_label", "Übersicht:"},
            {"total_profit_label_simple", "Gesamtwinn"},
            {"total_items_label_simple", "Gesamt Gegenstände"},
            {"total_currencies_label_simple", "Gesamt Währungen"},
            {"profit_per_hour_label_simple", "Gewinn pro Stunde"},
            {"session_duration_label_simple", "Sitzungsdauer"},
            {"export_label", "Export:"},
            {"quick_actions", "Schnellaktionen:"},
            {"reset_confirm", "Möchten Sie alle Einstellungen auf Standard zurücksetzen?"},
            {"reset_warning", "Diese Aktion kann nicht rückgängig gemacht werden."},
            {"export_settings", "Einstellungen in Datei exportieren:"},
            {"import_settings", "Einstellungen aus Datei importieren:"},
            {"edit_account", "Account bearbeiten: %s"},
            {"account_name", "Account-Name:"},
            {"drf_token_label", "DRF Token:"},
            {"gw2_api_key_label", "GW2 API Key:"},
            {"reload_config", "Konfiguration neu laden:"},
            {"auto_reset_label", "Automatischer Reset:"},
            {"next_reset_utc", "Nächster geplanter Reset (UTC): %s"},
            {"favorites_ui", "Favoriten UI:"},
            {"favorites_colors", "Favoriten-Farben:"},
            {"visual_enhancements", "Visuelle Verbesserungen:"},
            {"mini_window_widget", "Mini-Fenster (Overlay Widget):"},
            {"main_window_label", "Hauptfenster:"},
            {"profiles_description", "Profile ermöglichen es, verschiedene Konfigurationen zu speichern und schnell zwischen ihnen zu wechseln."},
            {"create_new_profile", "Neues Profil erstellen:"},
            {"current_profile", "Aktuelles Profil: %s"},
            {"auto_backup", "Einstellungen vor wichtigen Änderungen automatisch sichern"},
            {"notifications", "In-Game-Benachrichtigungen für wichtige Ereignisse konfigurieren"},
            {"profit_goal", "Gewinnziel:"},
            {"reset_warning_label", "Reset-Warnung:"},
            {"session_complete", "Sitzung abgeschlossen:"},
            {"manage_ignored_items", "Ignorierte Items verwalten"},
            {"manage_ignored_currencies", "Ignorierte Währungen verwalten"},
            {"rarity_label", "Seltenheit: %s"},
            {"type_label", "Typ: %d"},
            {"account_bound_label", "Account-gebunden: %s"},
            {"nosell_label", "NoSell: %s"},
            {"item_id_label", "Item ID: %d"},
            {"currency_id_label", "Währungs-ID: %d"},
            {"rarity_tooltip", "Items nach Mindest-Seltenheit filtern"},
            {"api_knowledge_filters_label", "API-Wissens-Filter:"},
            {"additional_filters_label", "Zusätzliche Filter:"},
            {"item_type_filters_label", "Item-Typ-Filter:"},
            {"currency_filters_label", "Währungsfilter:"},
            {"price_range", "Preisbereich (Kupfer):"},
            {"quantity_range", "Mengenbereich:"},
            {"debug_info", "Debug-Informationen"},
            {"drf_status", "DRF Status: %s"},
            {"drf_reconnect_count", "DRF Reconnect-Anzahl: %d"},
            {"gw2_api_status", "GW2 API Status: %s"},
            {"gw2_api_reconnect_count", "GW2 API Reconnect-Anzahl: %d"},
            {"session_duration_debug", "Sitzungsdauer: %s"},
            {"gw2_memory", "GW2 Prozess-Speicher: %zu MB"},
            {"gw2_api_request_count", "GW2 API Request-Anzahl: %d"},
            {"ignored_items_count", "Ignorierte Gegenstände: %d"},
            {"ignored_currencies_count", "Ignorierte Währungen: %d"},
            {"drf_logs", "DRF Logs:"},
            {"last_100_entries", "(Letzte 100 Einträge)"},
            {"gw2_api_logs", "GW2 API Logs:"},
            {"item_currency_details", "Item/Währungs-Details (Erste 5):"},
            {"item_label", "Gegenstand %d: %s (Anzahl: "},
            {"loaded_label", ", Geladen: %s)"},
            {"currency_label", "Währung %d: %s (Anzahl: "},
            {"custom_profit_items", "Gegenstände mit benutzerdefiniertem Gewinn (Erste 5):"},
            {"custom_profit_item", "Gegenstand %d: %s (Benutzerdefinierter Gewinn: "},
            {"no_custom_profit_items", "(Keine Gegenstände mit benutzerdefiniertem Gewinn)"},
            {"ignored_items_debug", "Ignorierte Items (Erste 5):"},
            {"yes_label", "Ja"},
            {"no_label", "Nein"},
            {"profits_label", "Gewinne:"},
            {"profits_tooltip", "Gesamtwinn aus Farming"},
            {"approx_profits_label", "Ungefährer Gewinn:"},
            {"approx_profits_tooltip", "Gesamtwinn aus Custom Profit Werten"},
            {"approx_gold_per_hour_label", "Ungefährer Gold/Stunde:"},
            {"approx_gold_per_hour_tooltip", "Gewinn pro Stunde basierend auf Sitzungsdauer"},
            {"trading_profits_label", "Handelsgewinne:"},
            {"trading_profits_tooltip", "Gewinne aus Verkauf auf Trading Post"},
            {"approx_trading_profits_listings_label", "Ungefährer Handelsgewinn (Listen):"},
            {"approx_trading_profits_listings_tooltip", "Gesamtwenn bei Verkauf über TP Listings"},
            {"approx_trading_profits_instant_label", "Ungefährer Handelsgewinn (Sofortverkauf):"},
            {"approx_trading_profits_instant_tooltip", "Gesamtwenn bei Verkauf über TP Instant Buy Orders"},
            {"trading_details_label", "Handelsdetails (Opportunitätskosten):"},
            {"trading_details_tooltip", "Verlorener Gewinn durch Nicht-Verkauf über TP Listings"},
            {"lost_profit_vs_tp_sell_label", "Verlorener Gewinn (vs TP Verkauf):"},
            {"lost_profit_vs_tp_sell_tooltip", "Gold = verlorener Gewinn, Rot = gewonnener Gewinn vs TP Verkauf"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Verlorener Gewinn/Stunde (vs TP Verkauf):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Opportunitätskosten pro Stunde"},
            {"session_duration_debug_label", "Sitzungsdauer: %s"},
            {"session_duration_debug_tooltip", "Aktuelle Farming-Sitzungsdauer"},
            {"tab_items", "Items"},
            {"manage_ignored_items", "Ignorierte Items verwalten"},
            {"clear_all_ignored_items", "Alle ignorierten Gegenstände löschen"},
            {"unignore_item", "Item nicht mehr ignorieren"},
            {"tab_currencies", "Währungen"},
            {"manage_ignored_currencies", "Ignorierte Währungen verwalten"},
            {"clear_all_ignored_currencies", "Alle ignorierten Währungen löschen"},
            {"unignore_currency", "Währung nicht mehr ignorieren"},
            {"sell_method_filters_label", "Verkaufsmethode-Filter:"},
            {"api_knowledge_filters_label", "API-Wissens-Filter:"},
            {"additional_filters_label", "Zusätzliche Filter:"},
            {"item_type_filters_label", "Item-Typ-Filter:"},
            {"currency_filters_label", "Währungs-Filter:"},
            {"price_range", "Preisbereich (Kupfer):"},
            {"quantity_range", "Mengenbereich:"},
            {"debug_information", "Debug-Informationen"},
            {"drf_status_label", "DRF Status: %s"},
            {"drf_status_tooltip", "Aktuelle DRF-Verbindungsstatus"},
            {"drf_reconnect_count_label", "DRF Reconnect-Anzahl: %d"},
            {"drf_reconnect_count_tooltip", "Anzahl der DRF Reconnect-Versuche"},
            {"gw2_api_status_label", "GW2 API Status: %s"},
            {"gw2_api_status_tooltip", "Aktueller GW2 API-Verbindungsstatus"},
            {"gw2_api_reconnect_count_label", "GW2 API Reconnect-Anzahl: %d"},
            {"gw2_api_reconnect_count_tooltip", "Anzahl der GW2 API Reconnect-Versuche"},
            {"session_duration_debug", "Sitzungsdauer: %s"},
            {"session_duration_debug_tooltip", "Aktuelle Farming-Sitzungsdauer"},
            {"gw2_process_memory_label", "GW2 Prozess-Speicher: %zu MB"},
            {"gw2_process_memory_tooltip", "Aktueller GW2 Prozess-Speicherverbrauch"},
            {"gw2_api_request_count_label", "GW2 API Request-Anzahl: %d"},
            {"gw2_api_request_count_tooltip", "Gesamtanzahl der GW2 API-Anfragen"},
            {"ignored_items_debug_label", "Ignorierte Items: %d"},
            {"ignored_items_debug_tooltip", "Anzahl der ignorierten Gegenstände"},
            {"ignored_currencies_debug_label", "Ignorierte Währungen: %d"},
            {"ignored_currencies_debug_tooltip", "Anzahl der ignorierten Währungen"},
            {"drf_logs_label", "DRF-Protokolle:"},
            {"clear_drf_logs", "DRF Logs löschen"},
            {"clear_drf_logs_tooltip", "Alle DRF Log-Einträge löschen"},
            {"last_100_entries", "(Letzte 100 Einträge)"},
            {"gw2_api_logs_label", "GW2 API-Protokolle:"},
            {"clear_gw2_logs", "GW2 Logs löschen"},
            {"clear_gw2_logs_tooltip", "Alle GW2 API Log-Einträge löschen"},
            {"settings_label", "Einstellungen:"},
            {"api_key_label", "API Key: %s"},
            {"api_key_tooltip", "GW2 API-Schlüssel-Status"},
            {"not_set", "Nicht gesetzt"},
            {"set", "Gesetzt"},
            {"drf_token_label", "DRF Token: %s"},
            {"drf_token_tooltip", "DRF Token Status"},
            {"toggle_hotkey_label", "Umschalt-Hotkey: %s"},
            {"toggle_hotkey_tooltip", "Hotkey für Hauptfenster-Umschaltung"},
            {"auto_reset_mode_label", "Auto-Reset Modus: %d"},
            {"auto_reset_mode_tooltip", "Aktueller Auto-Reset Modus"},
            {"next_reset_label", "Nächster Reset: %s"},
            {"next_reset_tooltip", "Nächster geplanter Reset-Zeitpunkt (UTC)"},
            {"fake_drf_server_label", "Fake DRF Server:"},
            {"use_fake_drf_server", "Fake DRF Server verwenden"},
            {"use_fake_drf_server_tooltip", "Nur zu Testzwecken"},
            {"reset_all_data", "Alle Daten zurücksetzen"},
            {"reset_all_data_tooltip", "Alle Farming-Daten zurücksetzen"},
            {"coin", "Münze"},
            {"rarity_label", "Seltenheit: %s"},
            {"type_label", "Typ: %d"},
            {"account_bound_label", "Account-gebunden: %s"},
            {"nosell_label", "Nicht verkäuflich: %s"},
            {"yes_label", "Ja"},
            {"no_label", "Nein"},
            {"sort_price_down", "Sortieren: Gegenstandspreis absteigend"},
            {"sort_price_up", "Sortieren: Gegenstandspreis aufsteigend"},
            {"sort_count_high", "Sortieren: |Anzahl| hoch"},
            {"sort_count_low", "Sortieren: |Anzahl| niedrig"},
            {"sort_name_az", "Sortieren: Name A–Z"},
            {"sort_tooltip", "Gegenstände nach Anzahl, ID oder Name sortieren"},
            {"rarity_all", "Seltenheit: alle"},
            {"rarity_basic", "Seltenheit: Gewöhnlich+"},
            {"rarity_fine", "Seltenheit: Fein+"},
            {"rarity_masterwork", "Seltenheit: Meisterwerk+"},
            {"rarity_rare", "Seltenheit: Selten+"},
            {"rarity_exotic", "Seltenheit: Exotisch+"},
            {"rarity_ascended", "Seltenheit: Aufgestiegen+"},
            {"rarity_legendary", "Seltenheit: Nur Legendär"},
            {"rarity_tooltip", "Gegenstände nach minimaler Seltenheit filtern"},
            {"search_items_hint", "Gegenstände suchen..."},
            {"column_icon", "Symbol"},
            {"column_name", "Name"},
            {"column_count", "Anzahl"},
            {"column_profit", "Gewinn"},
            {"column_favorite", "Favorit"},
            {"column_ignore", "Ignorieren"},
            {"toggle_favorite", "Favorit umschalten"},
            {"toggle_ignore", "Ignorieren umschalten"},
            {"vendor_value_format", "Händlerwert: %s"},
            {"tp_sell_gross_format", "TP-Verkauf (Brutto): %s"},
            {"tp_sell_net_format", "TP-Verkauf (Netto): %s"},
            {"tp_buy_gross_format", "TP-Kauf (Brutto): %s"},
            {"tp_buy_net_format", "TP-Kauf (Netto): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Favoriten-Einstellungen"},
            {"favorites_first", "Favoriten zuerst"},
            {"favorites_first_tooltip", "Zeigt Favoriten zuerst in Gegenstand/Währungslisten"},
            {"enable_favorite_text_color", "Favoriten-Textfarbe aktivieren"},
            {"enable_favorite_text_color_tooltip", "Hebt Favoriten-Gegenstände/Währungen mit benutzerdefinierter Textfarbe hervor"},
            {"text_color", "Textfarbe"},
            {"enable_favorite_row_color", "Favoriten-Zeilenfarbe aktivieren"},
            {"enable_favorite_row_color_tooltip", "Hebt Favoriten-Gegenstände/Währungen mit benutzerdefinierter Zeilenhintergrundfarbe hervor"},
            {"row_color", "Zeilenfarbe"},
            
            // Filter - Additional
            {"filter_favorite", "Favorit"},
            {"filter_favorite_tooltip", "Zeige Favoriten-Gegenstände (außerhalb des Favorites Tab)"},
            {"filter_not_favorite", "Kein Favorit"},
            {"filter_not_favorite_tooltip", "Zeige nicht-Favoriten-Gegenstände"},
            {"filter_research_notes", "Forschungsnotizen"},
            {"filter_research_notes_tooltip", "Zeige Forschungsnotizen-Währung"},
            {"range_filters", "Bereichsfilter"},
            {"range_filters_tooltip", "Zeige Preis- und Mengenbereichsfilter"},
            {"filter_min_price", "Min Preis"},
            {"filter_min_price_tooltip", "Minimaler Preisfilter (0 = deaktiviert)"},
            {"filter_max_price", "Max Preis"},
            {"filter_max_price_tooltip", "Maximaler Preisfilter (0 = deaktiviert)"},
            {"gold", "Gold"},
            {"silver", "Silber"},
            {"copper", "Kupfer"},
            {"quantity_range", "Mengenbereich"},
            {"filter_min_quantity", "Min Menge"},
            {"filter_max_quantity", "Max Menge"},
            
            // Summary Tab - Table Columns
            {"column_label", "Label"},
            {"column_value", "Wert"},
            {"column_item", "Gegenstand"},
            {"column_count", "Anzahl"},
            {"column_currency", "Währung"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Gegenstände nach Gewinn"},
            {"top_items_count_header", "Top Gegenstände (Anzahl)"},
            {"top_currencies_count_header", "Top Währungen (Anzahl)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 Gegenstände nach Gewinnwert"},
            {"top_items_count_tooltip", "Top 10 Gegenstände nach Anzahl"},
            {"top_currencies_count_tooltip", "Top 10 Währungen nach Anzahl"},
            
            // Settings Tab - General
            {"show_main_window", "Hauptfenster anzeigen"},
            {"reset_all", "Alles zurücksetzen"},
            {"reset_all_tooltip", "Alle Einstellungen auf Standardwerte zurücksetzen"},
            {"export", "Exportieren"},
            {"export_tooltip", "Einstellungen in eine JSON-Datei exportieren"},
            {"import", "Importieren"},
            {"import_tooltip", "Einstellungen aus einer JSON-Datei importieren"},
            {"save", "Speichern"},
            {"save_tooltip", "Aktuelle Einstellungen speichern"},
            {"general_settings", "Allgemeine Einstellungen"},
            {"account_management", "Kontoverwaltung"},
            {"add_account", "+ Konto hinzufügen"},
            {"remove_account", "- Konto entfernen"},
            {"save_account", "Konto speichern"},
            {"reload_drf_token", "DRF-Token neu laden"},
            {"reload_gw2_api_key", "GW2-API-Schlüssel neu laden"},
            {"reset_settings", "Auto-Reset"},
            {"visual_settings", "Visuelle Einstellungen"},
            {"gradient_backgrounds", "Verlaufshintergründe"},
            {"gradient_backgrounds_tooltip", "Aktiviert sanfte Verlaufshintergründe für ein moderneres Aussehen"},
            {"top_gradient_color", "Obere Verlaufsfarbe"},
            {"top_gradient_color_tooltip", "Obere Verlaufsfarbe"},
            {"bottom_gradient_color", "Untere Verlaufsfarbe"},
            {"bottom_gradient_color_tooltip", "Untere Verlaufsfarbe"},
            {"show_item_icons", "Gegenstandssymbole anzeigen (GW2-Render)"},
            {"show_item_icons_tooltip", "Lädt Symbole von render.guildwars2.com über Nexus."},
            {"icon_size", "Symbolgröße"},
            {"icon_size_tooltip", "Größe der Gegenstandssymbole in Pixeln (16-96)"},
            {"show_rarity_borders", "Seltenheitsränder anzeigen"},
            {"show_rarity_borders_tooltip", "Zeigt farbige Ränder um Symbole basierend auf der Seltenheit"},
            {"rarity_border_thickness", "Seltenheitsrandstärke"},
            {"rarity_border_thickness_tooltip", "Stärke der Seltenheitsränder anpassen (1.0 - 10.0)"},
            {"enable_grid_view_items", "Rasteransicht aktivieren (Gegenstände)"},
            {"enable_grid_view_items_tooltip", "Zwischen Listen- und Rasteransicht im Gegenstände-Tab umschalten"},
            {"grid_icon_size_items", "Raster-Symbolgröße (Gegenstände)"},
            {"grid_icon_size_items_tooltip", "Größe der Symbole in der Rasteransicht für Gegenstände (16-128)"},
            {"enable_grid_view_currencies", "Rasteransicht aktivieren (Währungen)"},
            {"enable_grid_view_currencies_tooltip", "Zwischen Listen- und Rasteransicht im Währungen-Tab umschalten"},
            {"grid_icon_size_currencies", "Raster-Symbolgröße (Währungen)"},
            {"grid_icon_size_currencies_tooltip", "Größe der Symbole in der Rasteransicht für Währungen (16-128)"},
            {"show_mini_window", "Mini-Fenster anzeigen"},
            {"show_mini_window_tooltip", "Zeigt ein kleines Overlay-Widget mit wichtigen Statistiken"},
            {"mini_window_show_profit", "Gewinn anzeigen"},
            {"mini_window_show_profit_tooltip", "Gesamtgewinn im Mini-Fenster anzeigen"},
            {"mini_window_show_profit_per_hour", "Gewinn/Stunde anzeigen"},
            {"mini_window_show_profit_per_hour_tooltip", "Gewinn pro Stunde im Mini-Fenster anzeigen"},
            {"mini_window_show_tp_sell", "TP-Verkauf anzeigen (Listen)"},
            {"mini_window_show_tp_sell_tooltip", "TP-Verkaufsgewinn (Listen) im Mini-Fenster anzeigen"},
            {"mini_window_show_tp_instant", "TP-Sofortverkauf anzeigen"},
            {"mini_window_show_tp_instant_tooltip", "TP-Sofortverkaufsgewinn im Mini-Fenster anzeigen"},
            {"mini_window_show_total_items", "Gesamtgegenstände anzeigen"},
            {"mini_window_show_total_items_tooltip", "Gesamtanzahl der Gegenstände im Mini-Fenster anzeigen"},
            {"mini_window_show_session_duration", "Sitzungsdauer anzeigen"},
            {"mini_window_show_session_duration_tooltip", "Sitzungsdauer im Mini-Fenster anzeigen"},
            {"mini_window_click_through", "Fenster durchklickbar"},
            {"mini_window_click_through_tooltip", "Erlaubt das Durchklicken durch das Mini-Fenster zum Spiel"},
            {"main_window_click_through", "Durchklickbar"},
            {"main_window_click_through_tooltip", "Erlaubt das Durchklicken durch das Hauptfenster zum Spiel"},
            {"settings_profiles", "Einstellungsprofile"},
            {"select_profile", "Wählen Sie ein Profil aus, um dessen Einstellungen anzuwenden"},
            {"create_new_profile", "Neues Profil erstellen"},
            {"create_new_profile_tooltip", "Erstellt ein neues Profil mit den aktuellen Einstellungen"},
            {"create", "Erstellen"},
            {"update_profile", "Profil aktualisieren"},
            {"update_profile_tooltip", "Aktualisiert das aktuelle Profil mit den aktuellen Einstellungen"},
            {"delete_profile", "Profil löschen"},
            {"delete_profile_tooltip", "Löscht das aktuelle Profil"},
            {"automatic_backups", "Automatische Sicherungen"},
            {"enable_automatic_backups", "Automatische Sicherungen aktivieren"},
            {"enable_automatic_backups_tooltip", "Erstellt automatisch Sicherungen vor Änderungen"},
            {"backup_frequency", "Sicherungshäufigkeit"},
            {"backup_frequency_tooltip", "Wie oft automatische Sicherungen erstellt werden"},
            {"max_backups", "Maximale Sicherungen"},
            {"max_backups_tooltip", "Maximale Anzahl der zu behaltenden Sicherungen (1-20)"},
            {"notification_settings", "Benachrichtigungseinstellungen"},
            {"enable_notifications", "Benachrichtigungen aktivieren"},
            {"enable_notifications_tooltip", "In-Game-Benachrichtigungen aktivieren"},
            {"notify_profit_goal", "Benachrichtigen bei Erreichen des Gewinnziels"},
            {"notify_profit_goal_tooltip", "Benachrichtigen, wenn das Gewinnziel erreicht wird"},
            {"profit_goal_gold", "Gewinnziel (Gold)"},
            {"profit_goal_gold_tooltip", "Gewinnziel in Goldmünzen (1-1000)"},
            {"notify_reset_warning", "Vor Reset benachrichtigen"},
            {"notify_reset_warning_tooltip", "Benachrichtigen, bevor ein automatischer Reset erfolgt"},
            {"reset_warning_minutes", "Reset-Warnung (Minuten)"},
            {"reset_warning_minutes_tooltip", "Minuten vor dem Reset, um die Warnung anzuzeigen (1-60)"},
            {"notify_session_complete", "Nach Sitzungsdauer benachrichtigen"},
            {"notify_session_complete_tooltip", "Benachrichtigen nach einer bestimmten Farm-Dauer"},
            {"session_complete_hours", "Sitzung abgeschlossen (Stunden)"},
            {"session_complete_hours_tooltip", "Stunden des Farmens vor der Benachrichtigung (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "An Händler verkaufbar"},
            {"filter_sellable_to_vendor_tooltip", "Zeigt an Händler verkaufbare Gegenstände"},
            {"filter_sellable_on_tp", "Auf TP verkaufbar"},
            {"filter_sellable_on_tp_tooltip", "Zeigt auf Handelsposten verkaufbare Gegenstände"},
            {"filter_custom_profit", "Benutzerdefinierter Gewinn"},
            {"filter_custom_profit_tooltip", "Zeigt Gegenstände mit benutzerdefiniertem Gewinn"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Von API bekannt"},
            {"filter_known_by_api_tooltip", "Zeigt von der GW2-API bekannte Gegenstände"},
            {"filter_unknown_by_api", "Von API unbekannt"},
            {"filter_unknown_by_api_tooltip", "Zeigt von der GW2-API unbekannte Gegenstände"},
            
            // Filter - Additional
            {"show_ignored_items", "Ignorierte Gegenstände anzeigen"},
            {"show_ignored_items_tooltip", "Zeigt ignorierte Gegenstände/Währungen in den Tabs Gegenstände und Währungen (deaktivieren zum Ausblenden). Unterschied zu 'Ignorierte' Filter: Dieser Filter steuert die Anzeige in Items/Currencies Tabs, der 'Ignorierte' Filter steuert die Anzeige im Filter Tab."},
            
            // Filter - Item Types
            {"filter_type_armor", "Rüstung"},
            {"filter_type_armor_tooltip", "Zeigt Rüstungsgegenstände"},
            {"filter_type_backpack", "Rucksack"},
            {"filter_type_backpack_tooltip", "Zeigt Rucksackgegenstände"},
            {"filter_type_bag", "Tasche"},
            {"filter_type_bag_tooltip", "Zeigt Taschen"},
            {"filter_type_container", "Behälter"},
            {"filter_type_container_tooltip", "Zeigt Behälter"},
            {"filter_type_consumable", "Verbrauchsgut"},
            {"filter_type_consumable_tooltip", "Zeigt Verbrauchsgüter"},
            {"filter_type_crafting_material", "Handwerksmaterial"},
            {"filter_type_crafting_material_tooltip", "Zeigt Handwerksmaterialien"},
            {"filter_type_gathering_tool", "Sammelwerkzeug"},
            {"filter_type_gathering_tool_tooltip", "Zeigt Sammelwerkzeuge"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Zeigt Gizmo-Gegenstände"},
            {"filter_type_gizmo_container", "Gizmo-Container"},
            {"filter_type_gizmo_container_tooltip", "Zeigt Gizmo-Container-Gegenstände"},
            {"filter_type_mini_pet", "Mini-Haustier"},
            {"filter_type_mini_pet_tooltip", "Zeigt Mini-Haustiere"},
            {"filter_type_tool", "Werkzeug"},
            {"filter_type_tool_tooltip", "Zeigt Werkzeuggegenstände"},
            {"filter_type_trinket", "Schmuck"},
            {"filter_type_trinket_tooltip", "Zeigt Schmuckgegenstände"},
            {"filter_type_trophy", "Trophäe"},
            {"filter_type_trophy_tooltip", "Zeigt Trophäengegenstände"},
            {"filter_type_unlock", "Freischaltung"},
            {"filter_type_unlock_tooltip", "Zeigt Freischaltungsgegenstände"},
            {"filter_type_upgrade_component", "Upgrade-Komponente"},
            {"filter_type_upgrade_component_tooltip", "Zeigt Upgrade-Komponenten"},
            {"filter_type_weapon", "Waffe"},
            {"filter_type_weapon_tooltip", "Zeigt Waffengegenstände"},
            
            // Filter - Currencies
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Zeigt Karma-Währung"},
            {"filter_laurel", "Lorbeer"},
            {"filter_laurel_tooltip", "Zeigt Lorbeer-Währung"},
            {"filter_gem", "Edelstein"},
            {"filter_gem_tooltip", "Zeigt Edelstein-Währung"},
            {"filter_fractal_relic", "Fraktal-Relikt"},
            {"filter_fractal_relic_tooltip", "Zeigt Fraktal-Relikt-Währung"},
            {"filter_badge_of_honor", "Ehrenabzeichen"},
            {"filter_badge_of_honor_tooltip", "Zeigt Ehrenabzeichen-Währung"},
            {"filter_guild_commendation", "Gilden-Lob"},
            {"filter_guild_commendation_tooltip", "Zeigt Gilden-Lob-Währung"},
            {"filter_transmutation_charge", "Transmutationsladung"},
            {"filter_transmutation_charge_tooltip", "Zeigt Transmutationsladung-Währung"},
            {"filter_spirit_shards", "Geistscherben"},
            {"filter_spirit_shards_tooltip", "Zeigt Geistscherben-Währung"},
            {"filter_unbound_magic", "Ungebundene Magie"},
            {"filter_unbound_magic_tooltip", "Zeigt Ungebundene-Magie-Währung"},
            {"filter_volatile_magic", "Flüchtige Magie"},
            {"filter_volatile_magic_tooltip", "Zeigt Flüchtige-Magie-Währung"},
            {"filter_airship_parts", "Luftschiffteile"},
            {"filter_airship_parts_tooltip", "Zeigt Luftschiffteile-Währung"},
            {"filter_geode", "Geode"},
            {"filter_geode_tooltip", "Zeigt Geode-Währung"},
            {"filter_ley_line_crystals", "Linienerz-Kristalle"},
            {"filter_ley_line_crystals_tooltip", "Zeigt Linienerz-Kristall-Währung"},
            {"filter_trade_contracts", "Handelsverträge"},
            {"filter_trade_contracts_tooltip", "Zeigt Handelsvertrags-Währung"},
            {"filter_elegy_mosaic", "Elegie-Mosaik"},
            {"filter_elegy_mosaic_tooltip", "Zeigt Elegie-Mosaik-Währung"},
            {"filter_uncommon_coins", "Ungewöhnliche Münzen"},
            {"filter_uncommon_coins_tooltip", "Zeigt Ungewöhnliche-Münzen-Währung"},
            {"filter_astral_acclaim", "Astraler Beifall"},
            {"filter_astral_acclaim_tooltip", "Zeigt Astraler-Beifall-Währung"},
            
            // Debug Tab
            {"total_tracked_items", "Gesamtzahl der verfolgten Gegenstände"},
            {"total_tracked_items_tooltip", "Gesamtzahl der verfolgten Gegenstände"},
            {"total_tracked_currencies", "Gesamtzahl der verfolgten Währungen"},
            {"total_tracked_currencies_tooltip", "Gesamtzahl der verfolgten Währungen"},
            {"total_custom_profit", "Gesamt benutzerdefinierter Gewinn"},
            {"total_custom_profit_tooltip", "Gesamt benutzerdefinierter Gewinn"},
            {"total_tp_sell_profit", "Gesamt TP-Verkaufsgewinn"},
            {"total_tp_sell_profit_tooltip", "Gesamt TP-Verkaufsgewinn"},
            {"total_vendor_sell_profit", "Gesamt Händler-Verkaufsgewinn"},
            {"total_vendor_sell_profit_tooltip", "Gesamt Händler-Verkaufsgewinn"},
            {"profit_per_hour_calculation", "Gewinn pro Stunde Berechnung"},
            {"profit_per_hour_calculation_tooltip", "Gewinn pro Stunde Berechnung"},
            {"opportunity_cost_vs_tp_sell", "Opportunitätskosten vs TP-Verkauf"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Opportunitätskosten vs TP-Verkauf"},
            {"opportunity_cost_per_hour", "Opportunitätskosten pro Stunde"},
            {"opportunity_cost_per_hour_tooltip", "Opportunitätskosten pro Stunde"},
            {"first_5_tracked_items", "Erste 5 verfolgte Gegenstände und Währungen mit Details"},
            {"first_5_tracked_items_tooltip", "Erste 5 verfolgte Gegenstände und Währungen mit Details"},
            {"first_5_custom_profit", "Erste 5 Gegenstände mit benutzerdefiniertem Gewinn"},
            {"first_5_custom_profit_tooltip", "Erste 5 Gegenstände mit benutzerdefiniertem Gewinn"},
            {"first_5_ignored_items", "Erste 5 ignorierte Gegenstände"},
            {"first_5_ignored_items_tooltip", "Erste 5 ignorierte Gegenstände"},
            
            // Debug Settings
            {"debug_settings", "Debug-Einstellungen"},
            {"enable_debug_tab", "Debug-Tab aktivieren"},
            {"enable_debug_tab_tooltip", "Zeigt den Debug-Tab mit zusätzlichen Informationen"},
            
            // Currencies Tab
            {"gold_format", "Gold: %lld"},
            {"count_format", "Anzahl: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Favorit umschalten"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Ignorieren umschalten"},
            
            // Additional Filters
            {"filter_account_bound", "Account-gebunden"},
            {"filter_account_bound_tooltip", "Account-gebundene Gegenstände anzeigen"},
            {"filter_not_account_bound", "Nicht Account-gebunden"},
            {"filter_not_account_bound_tooltip", "Nicht account-gebundene Gegenstände anzeigen"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "NoSell-Gegenstände anzeigen"},
            {"filter_not_nosell", "Nicht NoSell"},
            {"filter_not_nosell_tooltip", "Verkaufbare Gegenstände anzeigen"},
            {"filter_ignored", "Ignoriert"},
            {"filter_ignored_tooltip", "Ignorierte Gegenstände anzeigen"},
            {"filter_not_ignored", "Nicht Ignoriert"},
            {"filter_not_ignored_tooltip", "Nicht ignorierte Gegenstände anzeigen"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Lose Fraktal-Relikte"},
            {"filter_pristine_fractal_relics_tooltip", "Lose Fraktal-Relikte-Währung anzeigen"},
            {"filter_unstable_fractal_essence", "Instabile Fraktal-Essenz"},
            {"filter_unstable_fractal_essence_tooltip", "Instabile Fraktal-Essenz-Währung anzeigen"},
            {"filter_magnetite_shards", "Magnetit-Splitter"},
            {"filter_magnetite_shards_tooltip", "Magnetit-Splitter-Währung anzeigen"},
            {"filter_gaeting_crystals", "Gaeting-Kristalle"},
            {"filter_gaeting_crystals_tooltip", "Gaeting-Kristalle-Währung anzeigen"},
            {"filter_prophet_shards", "Propheten-Splitter"},
            {"filter_prophet_shards_tooltip", "Propheten-Splitter-Währung anzeigen"},
            {"filter_green_prophet_shards", "Grüne Propheten-Splitter"},
            {"filter_green_prophet_shards_tooltip", "Grüne Propheten-Splitter-Währung anzeigen"},
            {"filter_wvw_skirmish_tickets", "WvW-Scharmützel-Tickets"},
            {"filter_wvw_skirmish_tickets_tooltip", "WvW-Scharmützel-Tickets-Währung anzeigen"},
            {"filter_proofs_of_heroics", "Heldentum-Nachweise"},
            {"filter_proofs_of_heroics_tooltip", "Heldentum-Nachweise-Währung anzeigen"},
            {"filter_pvp_league_tickets", "PvP-Liga-Tickets"},
            {"filter_pvp_league_tickets_tooltip", "PvP-Liga-Tickets-Währung anzeigen"},
            {"filter_ascended_shards_of_glory", "Aufgestiegene Ruhm-Splitter"},
            {"filter_ascended_shards_of_glory_tooltip", "Aufgestiegene Ruhm-Splitter-Währung anzeigen"},
            {"filter_tyrian_defense_seal", "Tyrianisches Verteidigungssiegel"},
            {"filter_tyrian_defense_seal_tooltip", "Tyrianisches Verteidigungssiegel-Währung anzeigen"},
            {"filter_testimony_of_desert_heroics", "Zeugnis der Wüstenhelden"},
            {"filter_testimony_of_desert_heroics_tooltip", "Zeugnis der Wüstenhelden-Währung anzeigen"},
            {"filter_testimony_of_jade_heroics", "Zeugnis der Jadehelden"},
            {"filter_testimony_of_jade_heroics_tooltip", "Zeugnis der Jadehelden-Währung anzeigen"},
            {"filter_testimony_of_castoran_heroics", "Zeugnis der Castoran-Helden"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Zeugnis der Castoran-Helden-Währung anzeigen"},
            {"filter_legendary_insight", "Legendäre Einsicht"},
            {"filter_legendary_insight_tooltip", "Legendäre Einsicht-Währung anzeigen"},
            {"filter_tales_of_dungeon_delving", "Geschichten des Dungeon-Tauchens"},
            {"filter_tales_of_dungeon_delving_tooltip", "Geschichten des Dungeon-Tauchens-Währung anzeigen"},
            {"filter_imperial_favor", "Kaiserliche Gunst"},
            {"filter_imperial_favor_tooltip", "Kaiserliche Gunst-Währung anzeigen"},
            {"filter_canach_coins", "Canach-Münzen"},
            {"filter_canach_coins_tooltip", "Canach-Münzen-Währung anzeigen"},
            {"filter_ancient_coin", "Antike Münze"},
            {"filter_ancient_coin_tooltip", "Antike Münze-Währung anzeigen"},
            {"filter_unusual_coin", "Ungewöhnliche Münze"},
            {"filter_unusual_coin_tooltip", "Ungewöhnliche Münze-Währung anzeigen"},
            {"filter_jade_sliver", "Jade-Splitter"},
            {"filter_jade_sliver_tooltip", "Jade-Splitter-Währung anzeigen"},
            {"filter_static_charge", "Statische Ladung"},
            {"filter_static_charge_tooltip", "Statische Ladung-Währung anzeigen"},
            {"filter_pinch_of_stardust", "Prise Sternenstaub"},
            {"filter_pinch_of_stardust_tooltip", "Prise Sternenstaub-Währung anzeigen"},
            {"filter_calcified_gasp", "Verkalkter Atemzug"},
            {"filter_calcified_gasp_tooltip", "Verkalkter Atemzug-Währung anzeigen"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Ursus Oblige-Währung anzeigen"},
            {"filter_gaeting_crystal_janthir", "Gaeting-Kristall (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Gaeting-Kristall (Janthir)-Währung anzeigen"},
            {"filter_antiquated_ducat", "Veralteter Dukat"},
            {"filter_antiquated_ducat_tooltip", "Veralteter Dukat-Währung anzeigen"},
            {"filter_aether_rich_sap", "Ätherreicher Saft"},
            {"filter_aether_rich_sap_tooltip", "Ätherreicher Saft-Währung anzeigen"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Alles zurücksetzen"},
            {"reset_all_tooltip", "Alle Einstellungen auf Standardwerte zurücksetzen"},
            {"reset_confirm", "Möchten Sie wirklich alle Einstellungen zurücksetzen?"},
            {"reset_warning", "Diese Aktion kann nicht rückgängig gemacht werden."},
            {"yes_reset", "Ja, zurücksetzen"},
            {"cancel", "Abbrechen"},
            {"export", "Export"},
            {"export_tooltip", "Einstellungen in eine JSON-Datei exportieren"},
            {"export_settings", "Einstellungen exportieren"},
            {"import", "Import"},
            {"import_settings", "Einstellungen importieren"},
            {"save", "Speichern"},
            {"save_tooltip", "Aktuelle Einstellungen speichern"},
            
            // Settings Tab - General
            {"general_settings", "Allgemeine Einstellungen"},
            {"account_management", "Kontoverwaltung"},
            {"account_prefix", "Konto"},
            {"remove_account", "- Konto entfernen"},
            {"save_account", "Konto speichern"},
            {"reconnect_drf_token", "Mit DRF mit dem aktuellen Token neu verbinden"},
            {"reload_gw2_api_key_tooltip", "GW2 API-Schlüssel für das Abrufen von Item-Daten neu laden"},
            {"reset_settings", "Auto-Reset"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Nie (nur manuelles Zurücksetzen)"},
            {"auto_reset_on_load", "Beim Addon-Start"},
            {"auto_reset_daily", "Tägliches Zurücksetzen (00:00 UTC)"},
            {"auto_reset_weekly", "Wöchentlich (Mo 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Wöchentlich NA WvW (Sa 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Wöchentlich EU WvW (Fr 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Wöchentlich Kartenbonus (Do 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minuten nach dem letzten Entladen"},
            {"auto_reset_custom_days", "Benutzerdefiniert (Tage)"},
            {"auto_reset_tooltip", "Wann automatisch Farming-Zähler zurückgesetzt werden"},
            {"minutes_after_unload_tooltip", "Minuten nach dem Entladen des Addons vor dem automatischen Zurücksetzen"},
            {"reset_interval_days", "Zurücksetzintervall (Tage)"},
            {"reset_interval_days_tooltip", "Benutzerdefiniertes Zurücksetzintervall in Tagen (1-30 Tage)"},
            
            // Visual Settings
            {"top_gradient_color", "Oben"},
            {"top_gradient_color_tooltip", "Oberer Farbverlauf"},
            {"bottom_gradient_color", "Unten"},
            {"bottom_gradient_color_tooltip", "Unterer Farbverlauf"},
            {"icon_size", "Icon-Größe"},
            {"icon_size_tooltip", "Größe der Item-Icons in Pixeln (16-96)"},
            {"border_size", "Rahmengröße"},
            {"border_size_tooltip", "Dicke der Seltenheits-Rahmen anpassen (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Zwischen Listen- und Rasteransicht auf der Items-Registerkarte umschalten"},
            {"grid_icon_size_items", "Raster-Icon-Größe (Items)"},
            {"grid_icon_size_items_tooltip", "Größe der Icons in der Rasteransicht für Items (16-128)"},
            {"grid_icon_size_currencies", "Raster-Icon-Größe (Währungen)"},
            {"grid_icon_size_currencies_tooltip", "Größe der Icons in der Rasteransicht für Währungen (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Mini-Fenster anzeigen"},
            {"show_mini_window_tooltip", "Zeigt ein kleines Overlay-Widget mit wichtigen Statistiken"},
            {"mini_window_show_profit", "Gewinn anzeigen"},
            {"mini_window_show_profit_tooltip", "Gesamtgewinn im Mini-Fenster anzeigen"},
            {"mini_window_show_profit_per_hour", "Gewinn/Stunde anzeigen"},
            {"mini_window_show_profit_per_hour_tooltip", "Gewinn pro Stunde im Mini-Fenster anzeigen"},
            {"mini_window_show_tp_sell", "TP-Verkauf (Listen) anzeigen"},
            {"mini_window_show_tp_sell_tooltip", "TP-Verkaufsgewinn (Listen) im Mini-Fenster anzeigen"},
            {"mini_window_show_tp_instant", "TP-Sofortverkauf anzeigen"},
            {"mini_window_show_tp_instant_tooltip", "TP-Sofortverkaufsgewinn im Mini-Fenster anzeigen"},
            {"mini_window_show_total_items", "Gesamtanzahl Items anzeigen"},
            {"mini_window_show_total_items_tooltip", "Gesamtanzahl der Items im Mini-Fenster anzeigen"},
            {"mini_window_show_session_duration", "Sitzungsdauer anzeigen"},
            {"mini_window_show_session_duration_tooltip", "Sitzungsdauer im Mini-Fenster anzeigen"},
            {"mini_window_click_through", "Fenster klickbar"},
            {"mini_window_click_through_tooltip", "Ermöglicht das Klicken durch das Mini-Fenster zum Spiel"},
            
            // Main Window
            {"main_window_label", "Hauptfenster"},
            {"main_window_click_through", "Klickbar"},
            {"main_window_click_through_tooltip", "Ermöglicht das Klicken durch das Hauptfenster zum Spiel"},
            
            // Settings Profiles
            {"settings_profiles", "Einstellungsprofile"},
            {"default_no_profile", "Standard (Kein Profil)"},
            {"select_profile_tooltip", "Wählen Sie ein Profil aus, um dessen Einstellungen anzuwenden"},
            {"create", "Erstellen"},
            {"create_tooltip", "Neues Profil mit aktuellen Einstellungen erstellen"},
            {"update_profile", "Profil aktualisieren"},
            {"update_profile_tooltip", "Aktuelles Profil mit aktuellen Einstellungen aktualisieren"},
            {"delete_profile", "Profil löschen"},
            {"delete_profile_tooltip", "Aktuelles Profil löschen"},
            
            // Automatic Backups
            {"automatic_backups", "Automatische Sicherungen"},
            {"enable_automatic_backups", "Automatische Sicherungen aktivieren"},
            {"enable_automatic_backups_tooltip", "Automatisch Sicherungen vor Änderungen erstellen"},
            {"backup_frequency", "Sicherungshäufigkeit"},
            {"backup_frequency_tooltip", "Wie oft automatische Sicherungen erstellt werden"},
            {"backup_manual_only", "Nur manuell"},
            {"backup_daily", "Täglich"},
            {"backup_weekly", "Wöchentlich"},
            {"max_backup_count", "Max. Anzahl Sicherungen"},
            {"max_backup_count_tooltip", "Maximale Anzahl der zu speichernden Sicherungen (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Benachrichtigungseinstellungen"},
            {"enable_notifications", "Benachrichtigungen aktivieren"},
            {"enable_notifications_tooltip", "In-Game-Benachrichtigungen aktivieren"},
            {"profit_goal", "Gewinnziel"},
            {"notify_profit_goal", "Benachrichtigen bei Erreichen des Gewinnziels"},
            {"notify_profit_goal_tooltip", "Benachrichtigen, wenn das Gewinnziel erreicht wird"},
            {"profit_goal_gold", "Gewinnziel (Gold)"},
            {"profit_goal_gold_tooltip", "Gewinnziel in Goldmünzen (1-1000)"},
            {"reset_warning_label", "Zurücksetzen-Warnung"},
            {"notify_reset_warning", "Vor dem Zurücksetzen benachrichtigen"},
            {"notify_reset_warning_tooltip", "Benachrichtigen, bevor das automatische Zurücksetzen erfolgt"},
            {"warning_minutes", "Warnungsminuten"},
            {"warning_minutes_tooltip", "Minuten vor dem Zurücksetzen für die Warnung (1-60)"},
            {"session_complete", "Sitzung abgeschlossen"},
            {"notify_session_complete", "Nach Sitzungsdauer benachrichtigen"},
            {"notify_session_complete_tooltip", "Benachrichtigen nach einer bestimmten Farming-Dauer"},
            {"session_hours", "Sitzungsstunden"},
            {"session_hours_tooltip", "Stunden des Farmings vor der Benachrichtigung (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Währungen suchen..."},
            {"clear_search", "Löschen"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Favoriten-Gegenstände suchen..."},
            {"search_favorite_currencies_hint", "Favoriten-Währungen suchen..."},
            {"clear_search_favorites", "Löschen"},
        };
        return translations;
    }
}
