// ---------------------------------------------------------------------------
// localization_es.cpp – Spanish translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetSpanishTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Desconectado"},
            {"status_connecting", "Conectando..."},
            {"status_connected", "Conectado"},
            {"status_auth_failed", "Fallo de autenticación – verifica el token"},
            {"status_reconnecting", "Reconectando..."},
            {"status_error", "Error"},
            {"status_unknown", "Desconocido"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Ganancia"},
            {"profit_per_hour", "Ganancia/Hora"},
            {"tp_sell", "Venta TP"},
            {"tp_instant", "Venta Instantánea TP"},
            {"total_items", "Total de Objetos"},
            {"session", "Sesión"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "API GW2"},
            {"session_time_label", "Tiempo de Sesión"},
            {"reset_button", "Reiniciar"},
            {"reset_tooltip", "Reiniciar todos los contadores de farming (reinicio manual)"},

            // Tabs
            {"tab_summary", "Resumen"},
            {"tab_items", "Objetos"},
            {"tab_currencies", "Monedas"},
            {"tab_profit", "Ganancia"},
            {"tab_favorites", "Favoritos"},
            {"tab_ignored", "Ignorados"},
            {"tab_filter", "Filtro"},
            {"tab_custom_profit", "Ganancia Personalizada"},
            {"tab_debug", "Depuración"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF no conectado"},
            {"warning_drf_not_connected_desc", "Este plugin requiere DRF para la transmisión de datos."},
            {"warning_drf_install", "Instala DRF vía Nexus Addon Manager o https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ Token DRF inválido"},
            {"warning_drf_token_invalid_desc", "Por favor verifica tu Token DRF en Configuración."},
            {"warning_gw2_api_key_not_set", "⚠️ Clave API GW2 no configurada"},
            {"warning_gw2_api_key_not_set_desc", "Por favor configura tu Clave API GW2 en Configuración para detalles de objetos."},
            {"overview", "Resumen"},
            {"overview_tooltip", "Resumen de la sesión de farming actual"},
            {"total_profit", "Ganancia Total"},
            {"total_profit_tooltip", "Ganancia personalizada total de todos los objetos"},
            {"total_items_count", "Total de Objetos"},
            {"total_items_tooltip", "Número total de objetos únicos rastreados"},
            {"total_currencies", "Total de Monedas"},
            {"total_currencies_tooltip", "Número total de monedas únicas rastreadas"},
            {"profit_per_hour_label", "Ganancia Por Hora"},
            {"profit_per_hour_tooltip", "Ganancia por hora basada en la duración de la sesión"},
            {"session_duration", "Duración de Sesión"},
            {"session_duration_tooltip", "Duración de la sesión de farming actual"},
            {"top_items_profit", "Top Objetos (Ganancia)"},
            {"top_items_profit_tooltip", "Top 5 objetos por valor de ganancia"},
            {"loading", "Cargando..."},
            {"coin", "Moneda"},
            {"top_items_count", "Top Objetos (Cantidad)"},
            {"top_items_count_tooltip", "Top 5 objetos por cantidad"},
            {"top_currencies", "Top Monedas"},
            {"top_currencies_tooltip", "Top 5 monedas por cantidad"},
            {"quick_statistics", "Estadísticas Rápidas"},
            {"quick_statistics_tooltip", "Resumen de estadísticas de farming"},
            {"average_item_value", "Valor Promedio del Objeto"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Total de Objetos Únicos"},
            {"warning_no_data", "⚠️ No hay datos cargados"},
            {"warning_no_data_desc", "Esperando datos de DRF..."},
            {"export", "Exportar"},
            {"export_tooltip", "Exportar datos de farming a archivo"},
            {"export_json", "Exportar como JSON"},
            {"export_csv", "Exportar como CSV"},

            // Items Tab
            {"search_hint", "Buscar objetos..."},
            {"clear", "Limpiar"},
            {"sort_count_high", "Orden: |Cant| alto"},
            {"sort_count_low", "Orden: |Cant| bajo"},
            {"sort_id_up", "Orden: ID Objeto alto"},
            {"sort_id_down", "Orden: ID Objeto bajo"},
            {"sort_name_az", "Orden: Nombre A–Z"},
            {"sort_tooltip", "Ordenar objetos por cantidad, ID o nombre"},
            {"rarity_all", "Rareza: todas"},
            {"rarity_basic", "Rareza: Básico+"},
            {"rarity_fine", "Rareza: Fino+"},
            {"rarity_masterwork", "Rareza: Maestro+"},
            {"rarity_rare", "Rareza: Raro+"},
            {"rarity_exotic", "Rareza: Exótico+"},
            {"rarity_ascended", "Rareza: Ascendido+"},
            {"rarity_legendary", "Rareza: Solo Legendario"},
            {"rarity_tooltip", "Filtrar objetos por rareza mínima"},
            {"rarity", "Rareza"},
            {"type", "Tipo"},
            {"vendor_value", "Valor Vendedor"},
            {"tp_buy_net", "Compra TP (Neto)"},
            {"account_bound", "Vinculado a la cuenta"},
            {"yes", "Sí"},
            {"no", "No"},
            {"nosell", "No vendible"},
            {"favorite", "Favorito"},
            {"ignore", "Ignorar"},

            // Currencies Tab
            {"search_currencies_hint", "Buscar monedas..."},
            {"api_id", "ID API"},
            {"currency_name", "Nombre de Moneda"},
            {"count", "Cantidad"},

            // Profit Tab
            {"profits", "Ganancias"},
            {"profits_tooltip", "Ganancias totales del farming"},
            {"approx_profits", "Ganancias Aprox."},
            {"approx_gold_per_hour", "Oro Aprox. Por Hora"},
            {"trading_profits", "Ganancias de Comercio"},
            {"trading_profits_tooltip", "Ganancias del Puesto de Comercio"},
            {"approx_trading_profits_listings", "Ganancias de Comercio Aprox. (Listados)"},
            {"approx_trading_profits_instant", "Ganancias de Comercio Aprox. (Venta Instantánea)"},
            {"trading_details", "Detalles de Comercio (Costo de Oportunidad)"},
            {"trading_details_tooltip", "Costo de oportunidad de usar objetos en lugar de venderlos"},
            {"lost_profit_vs_tp_sell", "Ganancia Perdida (vs Venta TP)"},
            {"lost_profit_per_hour_vs_tp_sell", "Ganancia Perdida Por Hora (vs Venta TP)"},
            {"session_duration_label", "Duración de sesión"},
            {"session_duration_tooltip", "Duración de la sesión de farming actual"},

            // Filter Tab
            {"sell_method_filters", "Filtros de Método de Venta"},
            {"sellable_to_vendor", "Vendible al vendedor"},
            {"sellable_to_vendor_tooltip", "Mostrar objetos vendibles al vendedor"},
            {"sellable_on_tp", "Vendible en TP"},
            {"sellable_on_tp_tooltip", "Mostrar objetos vendibles en el Puesto de Comercio"},
            {"has_custom_profit", "Tiene ganancia personalizada"},
            {"has_custom_profit_tooltip", "Mostrar objetos con valores de ganancia personalizada"},
            {"api_knowledge_filters", "Filtros de Conocimiento API"},
            {"known_by_api", "Conocido por API"},
            {"known_by_api_tooltip", "Mostrar objetos conocidos por la API GW2"},
            {"unknown_by_api", "Desconocido por API"},
            {"unknown_by_api_tooltip", "Mostrar objetos no conocidos por la API GW2"},
            {"item_type_filters", "Filtros de Tipo de Objeto"},
            {"type_armor", "Armadura"},
            {"type_armor_tooltip", "Mostrar objetos de armadura"},
            {"type_weapon", "Arma"},
            {"type_weapon_tooltip", "Mostrar objetos de arma"},
            {"type_trinket", "Abalorio"},
            {"type_trinket_tooltip", "Mostrar objetos de abalorio"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Mostrar objetos gizmo"},
            {"type_crafting_material", "Material de Artesanía"},
            {"type_crafting_material_tooltip", "Mostrar materiales de artesanía"},
            {"type_consumable", "Consumible"},
            {"type_consumable_tooltip", "Mostrar consumibles"},
            {"type_gathering_tool", "Herramienta de Recolección"},
            {"type_gathering_tool_tooltip", "Mostrar herramientas de recolección"},
            {"type_bag", "Bolsa"},
            {"type_bag_tooltip", "Mostrar bolsas"},
            {"type_container", "Contenedor"},
            {"type_container_tooltip", "Mostrar contenedores"},
            {"type_mini_pet", "Mini Mascota"},
            {"type_mini_pet_tooltip", "Mostrar mini mascotas"},
            {"currency_filters_label", "Filtros de Monedas"},
            {"currency_main", "Monedas Principales"},
            {"currency_fractal", "Monedas Fractales/Raid/Mazmorra"},
            {"currency_wvw_pvp", "Monedas WvW/PvP"},
            {"currency_map", "Monedas Específicas del Mapa"},
            {"filter_karma", "Karma"},
            {"currency_karma_tooltip", "Mostrar moneda Karma"},
            {"currency_laurel", "Laurel"},
            {"currency_laurel_tooltip", "Mostrar moneda Laurel"},
            {"currency_gem", "Gema"},
            {"currency_gem_tooltip", "Mostrar moneda Gema"},
            {"currency_fractal_relic", "Reliquia Fractal"},
            {"currency_fractal_relic_tooltip", "Mostrar moneda Reliquia Fractal"},
            {"currency_badge_of_honor", "Insignia de Honor"},
            {"currency_badge_of_honor_tooltip", "Mostrar moneda Insignia de Honor"},
            {"currency_guild_commendation", "Encomienda de Gremio"},
            {"currency_guild_commendation_tooltip", "Mostrar moneda Encomienda de Gremio"},
            {"currency_transmutation_charge", "Carga de Transmutación"},
            {"currency_transmutation_charge_tooltip", "Mostrar moneda Carga de Transmutación"},
            {"currency_spirit_shards", "Fragmentos de Espíritu"},
            {"currency_spirit_shards_tooltip", "Mostrar moneda Fragmentos de Espíritu"},
            {"currency_unbound_magic", "Magia No Vinculada"},
            {"currency_unbound_magic_tooltip", "Mostrar moneda Magia No Vinculada"},
            {"currency_volatile_magic", "Magia Volátil"},
            {"currency_volatile_magic_tooltip", "Mostrar moneda Magia Volátil"},
            {"currency_airship_parts", "Partes de Dirigible"},
            {"currency_airship_parts_tooltip", "Mostrar moneda Partes de Dirigible"},
            {"currency_geode", "Geoda"},
            {"currency_geode_tooltip", "Mostrar moneda Geoda"},
            {"currency_ley_line_crystals", "Cristales de Línea Ley"},
            {"currency_ley_line_crystals_tooltip", "Mostrar moneda Cristales de Línea Ley"},
            {"currency_trade_contracts", "Contratos Comerciales"},
            {"currency_trade_contracts_tooltip", "Mostrar moneda Contratos Comerciales"},
            {"currency_elegy_mosaic", "Mosaico de Elegía"},
            {"currency_elegy_mosaic_tooltip", "Mostrar moneda Mosaico de Elegía"},
            {"currency_uncommon_coins", "Monedas Poco Comunes"},
            {"currency_uncommon_coins_tooltip", "Mostrar moneda Monedas Poco Comunes"},
            {"currency_astral_acclaim", "Aplauso Astral"},
            {"currency_astral_acclaim_tooltip", "Mostrar moneda Aplauso Astral"},
            {"currency_pristine_fractal_relics", "Reliquias Fractales Prístinas"},
            {"currency_pristine_fractal_relics_tooltip", "Mostrar moneda Reliquias Fractales Prístinas"},
            {"currency_unstable_fractal_essence", "Esencia Fractal Inestable"},
            {"currency_unstable_fractal_essence_tooltip", "Mostrar moneda Esencia Fractal Inestable"},
            {"currency_magnetite_shards", "Fragmentos de Magnetita"},
            {"currency_magnetite_shards_tooltip", "Mostrar moneda Fragmentos de Magnetita"},
            {"currency_gaeting_crystals", "Cristales Gaeting"},
            {"currency_gaeting_crystals_tooltip", "Mostrar moneda Cristales Gaeting"},
            {"currency_prophet_shards", "Fragmentos de Profeta"},
            {"currency_prophet_shards_tooltip", "Mostrar moneda Fragmentos de Profeta"},
            {"currency_green_prophet_shards", "Fragmentos de Profeta Verdes"},
            {"currency_green_prophet_shards_tooltip", "Mostrar moneda Fragmentos de Profeta Verdes"},
            {"currency_wvw_skirmish_tickets", "Boletos de Escaramuza WvW"},
            {"currency_wvw_skirmish_tickets_tooltip", "Mostrar moneda Boletos de Escaramuza WvW"},
            {"currency_proofs_of_heroics", "Pruebas de Heroísmo"},
            {"currency_proofs_of_heroics_tooltip", "Mostrar moneda Pruebas de Heroísmo"},
            {"currency_pvp_league_tickets", "Boletos de Liga PvP"},
            {"currency_pvp_league_tickets_tooltip", "Mostrar moneda Boletos de Liga PvP"},
            {"currency_ascended_shards_of_glory", "Fragmentos de Gloria Ascendidos"},
            {"currency_ascended_shards_of_glory_tooltip", "Mostrar moneda Fragmentos de Gloria Ascendidos"},
            {"currency_research_notes", "Notas de Investigación"},
            {"currency_research_notes_tooltip", "Mostrar moneda Notas de Investigación"},
            {"currency_tyrian_defense_seal", "Sello de Defensa Tirenio"},
            {"currency_tyrian_defense_seal_tooltip", "Mostrar moneda Sello de Defensa Tirenio"},
            {"currency_testimony_of_desert_heroics", "Testimonio de Heroísmo del Desierto"},
            {"currency_testimony_of_desert_heroics_tooltip", "Mostrar moneda Testimonio de Heroísmo del Desierto"},
            {"currency_testimony_of_jade_heroics", "Testimonio de Heroísmo de Jade"},
            {"currency_testimony_of_jade_heroics_tooltip", "Mostrar moneda Testimonio de Heroísmo de Jade"},
            {"currency_testimony_of_castoran_heroics", "Testimonio de Heroísmo Castorano"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Mostrar moneda Testimonio de Heroísmo Castorano"},
            {"currency_legendary_insight", "Perspectiva Legendaria"},
            {"currency_legendary_insight_tooltip", "Mostrar moneda Perspectiva Legendaria"},
            {"currency_tales_of_dungeon_delving", "Cuentos de Exploración de Mazmorra"},
            {"currency_tales_of_dungeon_delving_tooltip", "Mostrar moneda Cuentos de Exploración de Mazmorra"},
            {"currency_imperial_favor", "Favor Imperial"},
            {"currency_imperial_favor_tooltip", "Mostrar moneda Favor Imperial"},
            {"currency_canach_coins", "Monedas Canach"},
            {"currency_canach_coins_tooltip", "Mostrar moneda Monedas Canach"},
            {"currency_ancient_coin", "Moneda Antigua"},
            {"currency_ancient_coin_tooltip", "Mostrar moneda Moneda Antigua"},
            {"currency_unusual_coin", "Moneda Inusual"},
            {"currency_unusual_coin_tooltip", "Mostrar moneda Moneda Inusual"},
            {"currency_jade_sliver", "Astilla de Jade"},
            {"currency_jade_sliver_tooltip", "Mostrar moneda Astilla de Jade"},
            {"currency_static_charge", "Carga Estática"},
            {"currency_static_charge_tooltip", "Mostrar moneda Carga Estática"},
            {"currency_pinch_of_stardust", "Pizca de Polvo Estelar"},
            {"currency_pinch_of_stardust_tooltip", "Mostrar moneda Pizca de Polvo Estelar"},
            {"currency_calcified_gasp", "Jadeo Calcificado"},
            {"currency_calcified_gasp_tooltip", "Mostrar moneda Jadeo Calcificado"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Mostrar moneda Ursus Oblige"},
            {"currency_gaeting_crystal_janthir", "Cristal Gaeting (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Mostrar moneda Cristal Gaeting (Janthir)"},
            {"currency_antiquated_ducat", "Ducado Antiguo"},
            {"currency_antiquated_ducat_tooltip", "Mostrar moneda Ducado Antiguo"},
            {"currency_aether_rich_sap", "Savia Rica en Éter"},
            {"currency_aether_rich_sap_tooltip", "Mostrar moneda Savia Rica en Éter"},

            // Additional Filters
            {"additional_filters", "Filtros Adicionales"},
            {"account_bound", "Vinculado a la cuenta"},
            {"account_bound_tooltip", "Mostrar objetos vinculados a la cuenta"},
            {"not_account_bound", "No Vinculado a la cuenta"},
            {"not_account_bound_tooltip", "Mostrar objetos no vinculados a la cuenta"},
            {"nosell_items", "No vendible"},
            {"nosell_items_tooltip", "Mostrar objetos no vendibles"},
            {"not_nosell", "Vendible"},
            {"not_nosell_tooltip", "Mostrar objetos vendibles"},
            {"favorite_items", "Favorito"},
            {"favorite_items_tooltip", "Mostrar objetos favoritos"},
            {"not_favorite", "No Favorito"},
            {"not_favorite_tooltip", "Mostrar objetos no favoritos"},
            {"ignored_items", "Ignorado"},
            {"ignored_items_tooltip", "Mostrar objetos ignorados"},
            {"not_ignored", "No Ignorado"},
            {"not_ignored_tooltip", "Mostrar objetos no ignorados"},

            // Range Filters
            {"range_filters", "Filtros de Rango"},
            {"show_range_filters", "Mostrar Filtros de Rango"},
            {"filter_min_price", "Filtro Precio Mín"},
            {"filter_max_price", "Filtro Precio Máx"},
            {"filter_min_quantity", "Filtro Cantidad Mín"},
            {"filter_max_quantity", "Filtro Cantidad Máx"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Ventana"},
            {"show_profit", "Mostrar Ganancia"},
            {"show_profit_tooltip", "Mostrar ganancia total en la mini ventana"},
            {"show_profit_per_hour", "Mostrar Ganancia/Hora"},
            {"show_profit_per_hour_tooltip", "Mostrar ganancia por hora en la mini ventana"},
            {"show_tp_sell", "Mostrar Venta TP (Listados)"},
            {"show_tp_sell_tooltip", "Mostrar ganancia de venta TP (listados) en la mini ventana"},
            {"show_tp_instant", "Mostrar Venta Instantánea TP"},
            {"show_tp_instant_tooltip", "Mostrar ganancia de venta instantánea TP en la mini ventana"},
            {"show_total_items", "Mostrar Total de Objetos"},
            {"show_total_items_tooltip", "Mostrar cantidad total de objetos en la mini ventana"},
            {"show_session_duration", "Mostrar Duración de Sesión"},
            {"show_session_duration_tooltip", "Mostrar duración de sesión en la mini ventana"},
            {"window_click_through", "Clic a través de ventana"},
            {"window_click_through_tooltip", "Permite hacer clic a través de la mini ventana hacia el juego"},

            // Main Window Settings
            {"main_window", "Ventana Principal"},
            {"click_through", "Clic a través"},
            {"click_through_tooltip", "Permite hacer clic a través de la ventana principal hacia el juego"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Configuración UI Avanzada"},
            {"no_advanced_ui_settings", "(Sin configuración UI avanzada disponible)"},

            // Display Settings
            {"display_settings", "Configuración de Visualización"},
            {"show_item_icons", "Mostrar Iconos de Objetos"},
            {"show_item_icons_tooltip", "Mostrar iconos de objetos en la lista"},
            {"show_rarity_border", "Mostrar Borde de Rareza"},
            {"show_rarity_border_tooltip", "Mostrar borde coloreado basado en rareza del objeto"},
            {"enable_grid_view", "Activar Vista de Cuadrícula"},
            {"enable_grid_view_tooltip", "Mostrar objetos en diseño de cuadrícula en lugar de lista"},
            {"grid_icon_size", "Tamaño de Icono de Cuadrícula"},
            {"grid_icon_size_tooltip", "Tamaño de iconos en vista de cuadrícula"},

            // Count Display Settings
            {"count_display_settings", "Configuración de Visualización de Cantidad"},
            {"count_text_color", "Color de Texto de Cantidad"},
            {"count_text_color_tooltip", "Color del texto de cantidad"},
            {"count_background_color", "Color de Fondo de Cantidad"},
            {"count_background_color_tooltip", "Color del fondo de cantidad"},
            {"count_font_size", "Tamaño de Fuente de Cantidad"},
            {"count_font_size_tooltip", "Tamaño de la fuente de cantidad"},
            {"count_horizontal_alignment", "Alineación Horizontal de Cantidad"},
            {"count_horizontal_alignment_tooltip", "Alineación horizontal del texto de cantidad"},

            // Gradient Background Settings
            {"gradient_background_settings", "Configuración de Fondo Degradado"},
            {"enable_gradient_backgrounds", "Activar Fondos Degradados"},
            {"enable_gradient_backgrounds_tooltip", "Activar fondo degradado para ventanas"},
            {"gradient_top_color", "Color Superior del Degradado"},
            {"gradient_top_color_tooltip", "Color superior del fondo degradado"},
            {"gradient_bottom_color", "Color Inferior del Degradado"},
            {"gradient_bottom_color_tooltip", "Color inferior del fondo degradado"},

            // Custom Profit System
            {"custom_profit_system", "Sistema de Ganancia Personalizada"},
            {"enable_custom_profit", "Activar Ganancia Personalizada"},
            {"enable_custom_profit_tooltip", "Activar valores de ganancia personalizada para objetos"},

            // Search
            {"search_settings", "Búsqueda"},
            {"enable_search", "Activar Búsqueda"},
            {"enable_search_tooltip", "Activar funcionalidad de búsqueda"},

            // Ignored Items
            {"ignored_items_settings", "Objetos Ignorados"},
            {"enable_ignored_items", "Activar Objetos Ignorados"},
            {"enable_ignored_items_tooltip", "Activar funcionalidad de objetos ignorados"},

            // Auto Reset
            {"auto_reset_settings", "Reinicio Auto"},
            {"enable_auto_reset", "Activar Reinicio Auto"},
            {"enable_auto_reset_tooltip", "Reiniciar automáticamente la sesión de farming después de una duración"},
            {"auto_reset_duration", "Duración de Reinicio Auto (minutos)"},
            {"auto_reset_duration_tooltip", "Duración en minutos antes del reinicio auto"},

            // DRF Settings
            {"drf_settings", "Configuración DRF"},
            {"drf_token", "Token DRF"},
            {"drf_token_tooltip", "Tu token de autenticación DRF"},
            {"edit_token", "Editar Token"},
            {"save_token", "Guardar Token"},

            // GW2 API Settings
            {"gw2_api_settings", "Configuración API GW2"},
            {"gw2_api_key", "Clave API GW2"},
            {"gw2_api_key_tooltip", "Tu clave API GW2 para detalles de objetos"},
            {"edit_key", "Editar Clave"},
            {"save_key", "Guardar Clave"},

            // Language Settings
            {"language_settings", "Idioma"},
            {"language_tooltip", "Seleccionar idioma de la interfaz"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "No hay cuentas configuradas"},
            {"no_profiles_created", "Aún no se han creado perfiles"},
            {"count_label", "Cantidad:"},
            {"profit_label", "Ganancia:"},
            {"no_profit", "Sin ganancia"},
            {"vendor_value_label", "Valor Vendedor:"},
            {"tp_sell_gross_label", "Venta TP (Bruto):"},
            {"tp_sell_net_label", "Venta TP (Neto):"},
            {"tp_buy_gross_label", "Compra TP (Bruto):"},
            {"tp_buy_net_label", "Compra TP (Neto):"},
            {"ignored_items_label", "Objetos Ignorados:"},
            {"ignored_currencies_label", "Monedas Ignoradas:"},
            {"total_items_label", "Total Objetos:"},
            {"total_currencies_label", "Total Monedas:"},
            {"total_profit_label", "Ganancia Total:"},
            {"tp_sell_profit_label", "Ganancia de Venta TP:"},
            {"vendor_profit_label", "Ganancia de Venta Vendedor:"},
            {"profit_per_hour_label", "Ganancia Por Hora:"},
            {"opportunity_cost_profit_label", "Ganancia de Costo de Oportunidad:"},
            {"opportunity_cost_profit_per_hour_label", "Ganancia de Costo de Oportunidad/Hora:"},
            {"custom_profit_feature_placeholder", "Funcionalidad implementada - UI pendiente"},
            {"custom_profit_items_header", "Objetos con Beneficio Personalizado"},
            {"custom_profit_currencies_header", "Monedas con Beneficio Personalizado"},
            {"add_custom_profit_item", "Añadir Beneficio Personalizado para Objeto"},
            {"add_custom_profit_currency", "Añadir Beneficio Personalizado para Moneda"},
            {"custom_profit_set_profit", "Establecer Beneficio"},
            {"custom_profit_remove", "Eliminar"},
            {"custom_profit_value", "Valor del Beneficio (Cobre)"},
            {"custom_profit_set_tooltip", "Establecer valor de beneficio personalizado para este objeto"},
            {"custom_profit_remove_tooltip", "Eliminar valor de beneficio personalizado para este objeto"},
            {"no_custom_profit_items", "(Sin objetos con beneficio personalizado)"},
            {"no_custom_profit_currencies", "(Sin monedas con beneficio personalizado)"},
            {"clear_all_custom_profits", "Limpiar todos los beneficios personalizados"},
            {"clear_all_custom_profits_tooltip", "Limpiar todos los valores de beneficio personalizados"},
            {"tabs_settings", "Otras Pestañas"},
            {"tabs_description", "Mostrar u ocultar otras pestañas"},
            {"enable_ignored_tab", "Activar pestaña ignorados"},
            {"enable_ignored_tab_tooltip", "Mostrar la pestaña de objetos ignorados"},
            {"enable_summaries_tab", "Activar pestaña resúmenes"},
            {"enable_summaries_tab_tooltip", "Mostrar la pestaña de resúmenes diario/semanal/mensual en el historial de sesiones"},
            {"custom_profit_settings", "Beneficio Personalizado"},
            {"overview_label", "Resumen:"},
            {"total_profit_label_simple", "Ganancia Total"},
            {"total_items_label_simple", "Total de Objetos"},
            {"total_currencies_label_simple", "Total de Monedas"},
            {"profit_per_hour_label_simple", "Ganancia Por Hora"},
            {"session_duration_label_simple", "Duración de Sesión"},
            {"export_label", "Exportar:"},
            {"quick_actions", "Acciones Rápidas:"},
            {"reset_confirm", "¿Estás seguro de que quieres restablecer todos los ajustes a los valores predeterminados?"},
            {"reset_warning", "Esta acción no se puede deshacer."},
            {"export_settings", "Exportar Ajustes a Archivo:"},
            {"import_settings", "Importar Ajustes desde Archivo:"},
            {"edit_account", "Editar Cuenta: %s"},
            {"account_name", "Nombre de Cuenta:"},
            {"drf_token_label", "Token DRF:"},
            {"gw2_api_key_label", "Clave API GW2:"},
            {"reload_config", "Recargar Configuración:"},
            {"auto_reset_label", "Reinicio Automático:"},
            {"next_reset_utc", "Próximo reinicio programado (UTC): %s"},
            {"favorites_ui", "UI de Favoritos:"},
            {"favorites_colors", "Colores de Favoritos:"},
            {"visual_enhancements", "Mejoras visuales:"},
            {"show_profit_sparkline", "Mostrar Sparkline de Beneficio"},
            {"show_profit_sparkline_tooltip", "Muestra un pequeño gráfico de líneas con la tendencia de beneficio por hora"},
            {"mini_window_widget", "Mini ventana (Widget de superposición):"},
            {"main_window_label", "Ventana Principal:"},
            {"profiles_description", "Los perfiles te permiten guardar diferentes configuraciones y cambiar rápidamente entre ellas."},
            {"create_new_profile", "Crear Nuevo Perfil:"},
            {"current_profile", "Perfil Actual: %s"},
            {"auto_backup", "Hacer copia de seguridad automática de tus ajustes antes de cambios importantes"},
            {"notifications", "Configurar notificaciones en el juego para eventos importantes"},
            {"profit_goal", "Objetivo de Ganancia:"},
            {"reset_warning_label", "Advertencia de Reinicio:"},
            {"session_complete", "Sesión Completada:"},
            {"manage_ignored_items", "Gestionar objetos ignorados"},
            {"manage_ignored_currencies", "Gestionar monedas ignoradas"},
            {"rarity_label", "Rareza: %s"},
            {"type_label", "Tipo: %d"},
            {"account_bound_label", "Vinculado a la Cuenta: %s"},
            {"nosell_label", "NoSell: %s"},
            {"item_id_label", "ID del objeto: %d"},
            {"currency_id_label", "ID de moneda: %d"},
            {"rarity_tooltip", "Filtrar objetos por rareza mínima"},
            {"api_knowledge_filters_label", "Filtros de Conocimiento API:"},
            {"additional_filters_label", "Filtros Adicionales:"},
            {"item_type_filters_label", "Filtros de Tipo de Objeto:"},
            {"currency_filters_label", "Filtros de Monedas:"},
            {"price_range", "Rango de Precio (Cobre):"},
            {"quantity_range", "Rango de Cantidad:"},
            {"debug_info", "Información de Depuración"},
            {"drf_status", "Estado DRF: %s"},
            {"drf_reconnect_count", "Conteo de Reconexiones DRF: %d"},
            {"gw2_api_status", "Estado API GW2: %s"},
            {"gw2_api_reconnect_count", "Conteo de Reconexiones API GW2: %d"},
            {"session_duration_debug", "Duración de Sesión: %s"},
            {"gw2_memory", "Memoria de Proceso GW2: %zu MB"},
            {"gw2_api_request_count", "Conteo de Solicitudes API GW2: %d"},
            {"ignored_items_count", "Objetos Ignorados: %d"},
            {"ignored_currencies_count", "Monedas Ignoradas: %d"},
            {"drf_logs", "Logs DRF:"},
            {"last_100_entries", "(Últimas 100 entradas)"},
            {"gw2_api_logs", "Logs API GW2:"},
            {"item_currency_details", "Detalles de Objeto/Moneda (Primeros 5):"},
            {"item_label", "Objeto %d: %s (Cantidad: "},
            {"loaded_label", ", Cargado: %s)"},
            {"currency_label", "Moneda %d: %s (Cantidad: "},
            {"custom_profit_items", "Objets de Ganancia Personalizada (Primeros 5):"},
            {"custom_profit_item", "Objeto %d: %s (Ganancia Personalizada: "},
            {"no_custom_profit_items", "(Sin objetos de ganancia personalizada)"},
            {"ignored_items_debug", "Objetos Ignorados (Primeros 5):"},
            {"yes_label", "Sí"},
            {"no_label", "No"},
            {"profits_label", "Ganancias:"},
            {"profits_tooltip", "Ganancias totales del farming"},
            {"approx_profits_label", "Ganancias Aproximadas:"},
            {"approx_profits_tooltip", "Ganancia total de valores de ganancia personalizada"},
            {"approx_gold_per_hour_label", "Oro Por Hora Aproximado:"},
            {"approx_gold_per_hour_tooltip", "Ganancia por hora basada en duración de sesión"},
            {"trading_profits_label", "Ganancias de Trading:"},
            {"trading_profits_tooltip", "Ganancias de venta de objetos en Trading Post"},
            {"approx_trading_profits_listings_label", "Ganancias de Trading Aproximadas (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Ganancia total si se vende via TP listings"},
            {"approx_trading_profits_instant_label", "Ganancias de Trading Aproximadas (Venta Instantánea):"},
            {"approx_trading_profits_instant_tooltip", "Ganancia total si se vende via TP buy orders instantáneos"},
            {"trading_details_label", "Detalles de Trading (Costo de Oportunidad):"},
            {"trading_details_tooltip", "Ganancia perdida por no vender via TP listings"},
            {"lost_profit_vs_tp_sell_label", "Ganancia Perdida (vs Venta TP):"},
            {"lost_profit_vs_tp_sell_tooltip", "Oro = ganancia perdida, Rojo = ganancia ganada vs venta TP"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Ganancia Perdida Por Hora (vs Venta TP):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Costo de oportunidad por hora"},
            {"session_duration_debug_label", "Duración de sesión: %s"},
            {"session_duration_debug_tooltip", "Duración de sesión de farming actual"},
            {"tab_items", "Objetos"},
            {"manage_ignored_items", "Gestionar objetos ignorados"},
            {"clear_all_ignored_items", "Limpiar todos los objetos ignorados"},
            {"unignore_item", "Dejar de ignorar objeto"},
            {"tab_currencies", "Monedas"},
            {"manage_ignored_currencies", "Gestionar monedas ignoradas"},
            {"clear_all_ignored_currencies", "Limpiar todas las monedas ignoradas"},
            {"unignore_currency", "Dejar de ignorar moneda"},
            {"sell_method_filters_label", "Filtros de Método de Venta:"},
            {"api_knowledge_filters_label", "Filtros de Conocimiento API:"},
            {"additional_filters_label", "Filtros Adicionales:"},
            {"item_type_filters_label", "Filtros de Tipo de Objeto:"},
            {"currency_filters_label", "Filtros de Monedas:"},
            {"price_range", "Rango de Precio (Cobre):"},
            {"quantity_range", "Rango de Cantidad:"},
            {"debug_information", "Información de Depuración"},
            {"drf_status_label", "Estado DRF: %s"},
            {"drf_status_tooltip", "Estado de conexión DRF actual"},
            {"drf_reconnect_count_label", "Contador de Reconexiones DRF: %d"},
            {"drf_reconnect_count_tooltip", "Número de intentos de reconexión DRF"},
            {"gw2_api_status_label", "Estado API GW2: %s"},
            {"gw2_api_status_tooltip", "Estado de conexión API GW2 actual"},
            {"gw2_api_reconnect_count_label", "Contador de Reconexiones API GW2: %d"},
            {"gw2_api_reconnect_count_tooltip", "Número de intentos de reconexión API GW2"},
            {"session_duration_debug", "Duración de Sesión: %s"},
            {"session_duration_debug_tooltip", "Duración de sesión de farming actual"},
            {"gw2_process_memory_label", "Memoria Proceso GW2: %zu MB"},
            {"gw2_process_memory_tooltip", "Uso de memoria proceso GW2 actual"},
            {"gw2_api_request_count_label", "Contador de Solicitudes API GW2: %d"},
            {"gw2_api_request_count_tooltip", "Número total de solicitudes API GW2 realizadas"},
            {"ignored_items_debug_label", "Objetos Ignorados: %d"},
            {"ignored_items_debug_tooltip", "Número de objetos ignorados"},
            {"ignored_currencies_debug_label", "Monedas Ignoradas: %d"},
            {"ignored_currencies_debug_tooltip", "Número de monedas ignoradas"},
            {"drf_logs_label", "Logs DRF:"},
            {"clear_drf_logs", "Limpiar Logs DRF"},
            {"clear_drf_logs_tooltip", "Limpiar todas las entradas de logs DRF"},
            {"last_100_entries", "(Últimas 100 entradas)"},
            {"gw2_api_logs_label", "Logs API GW2:"},
            {"clear_gw2_logs", "Limpiar Logs GW2"},
            {"clear_gw2_logs_tooltip", "Limpiar todas las entradas de logs API GW2"},
            {"settings_label", "Configuración:"},
            {"api_key_label", "Clave API: %s"},
            {"api_key_tooltip", "Estado de clave API GW2"},
            {"not_set", "No establecida"},
            {"set", "Establecida"},
            {"drf_token_label", "Token DRF: %s"},
            {"drf_token_tooltip", "Estado de token DRF"},
            {"toggle_hotkey_label", "Tecla de Alternar: %s"},
            {"toggle_hotkey_tooltip", "Tecla de alternar ventana principal"},
            {"auto_reset_mode_label", "Modo Auto-Reset: %d"},
            {"auto_reset_mode_tooltip", "Modo de reinicio automático actual"},
            {"next_reset_label", "Próximo Reset: %s"},
            {"next_reset_tooltip", "Hora de reinicio programado siguiente (UTC)"},
            {"fake_drf_server_label", "Servidor DRF Falso:"},
            {"use_fake_drf_server", "Usar servidor DRF falso"},
            {"use_fake_drf_server_tooltip", "Solo para propósitos de prueba"},
            {"reset_all_data", "Reiniciar Todos los Datos"},
            {"reset_all_data_tooltip", "Reiniciar todos los datos de farming"},
            {"coin", "Moneda"},
            {"rarity_label", "Rareza: %s"},
            {"type_label", "Tipo: %d"},
            {"account_bound_label", "Vinculado a la cuenta: %s"},
            {"nosell_label", "No vendible: %s"},
            {"yes_label", "Sí"},
            {"no_label", "No"},
            {"sort_price_down", "Ordenar: Precio de objeto descendente"},
            {"sort_price_up", "Ordenar: Precio de objeto ascendente"},
            {"sort_count_high", "Ordenar: |Cuenta| alto"},
            {"sort_count_low", "Ordenar: |Cuenta| bajo"},
            {"sort_name_az", "Ordenar: Nombre A–Z"},
            {"sort_name_za", "Ordenar: Nombre Z–A"},
            {"sort_profit_high", "Ordenar: Profit alto"},
            {"sort_profit_low", "Ordenar: Profit bajo"},
            {"sort_rarity_high", "Ordenar: Rareza alta a baja"},
            {"sort_rarity_low", "Ordenar: Rareza baja a alta"},
            {"sort_tooltip", "Ordenar objetos por cuenta, ID o nombre"},
            {"group_by_rarity", "Agrupar por rareza"},
            {"show_rarity_as_tabs", "Mostrar como pestañas"},
            {"rarity_name_junk", "Basura"},
            {"rarity_name_basic", "Básico"},
            {"rarity_name_fine", "Fino"},
            {"rarity_name_masterwork", "Maestría"},
            {"rarity_name_rare", "Raro"},
            {"rarity_name_exotic", "Exótico"},
            {"rarity_name_ascended", "Ascendido"},
            {"rarity_name_legendary", "Legendario"},
            {"rarity_name_unknown", "Desconocido"},
            {"accent_color", "Color de acento"},
            {"accent_color_tooltip", "Color de acento para botones, pestañas y elementos de la interfaz"},
            {"main_window_opacity", "Transparencia ventana principal"},
            {"main_window_opacity_tooltip", "Transparencia del fondo de la ventana principal (0-100%)"},
            {"mini_window_opacity", "Transparencia mini ventana"},
            {"mini_window_opacity_tooltip", "Transparencia del fondo de la mini ventana (0-100%)"},
            {"session_history", "Historial de sesiones"},
            {"tab_sessions", "Sesiones"},
            {"tab_summaries", "Resúmenes"},
            {"summaries_coming_soon", "Función resúmenes próximamente..."},
            {"summaries_label", "Resúmenes"},
            {"summaries_tooltip", "Resúmenes de ganancia diario/semanal/mensual"},
            {"show_summaries", "Mostrar resúmenes"},
            {"show_summaries_tooltip", "Mostrar resúmenes de ganancia diario/semanal/mensual"},
            {"best_drop", "Mejor drop"},
            {"best_drop_tooltip", "Drop más valioso de la sesión actual"},
            {"enable_best_drop_highlight", "Resaltar mejor drop"},
            {"enable_best_drop_highlight_tooltip", "Resalta el drop más valioso con un borde dorado en la pestaña Items"},
            {"enable_best_drop_in_mini_window", "Mostrar mejor drop en mini-ventana"},
            {"enable_best_drop_in_mini_window_tooltip", "Muestra el drop más valioso en la mini-ventana overlay"},
            {"export_history", "Exportar historial"},
            {"export_history_tooltip", "Exportar el historial de sesiones a un archivo JSON"},
            {"import_history", "Importar historial"},
            {"import_history_tooltip", "Importar el historial de sesiones desde un archivo JSON"},
            {"full_backup", "Copia de seguridad completa"},
            {"full_backup_tooltip", "Respaldar todos los datos (ajustes, historial de sesiones, favoritos, elementos ignorados, ganancia personalizada) en un archivo JSON"},
            {"full_restore", "Restauración completa"},
            {"full_restore_tooltip", "Restaurar todos los datos desde un archivo JSON de respaldo"},
            {"backup", "Respaldar"},
            {"restore", "Restaurar"},
            {"summary_period", "Período:"},
            {"summary_today", "Hoy"},
            {"summary_this_week", "Esta semana"},
            {"summary_this_month", "Este mes"},
            {"total_profit", "Ganancia Total"},
            {"profit_per_hour", "Ganancia/Hora"},
            {"total_drops", "Total Drops"},
            {"session_count", "Cantidad de sesiones"},
            {"total_duration", "Duración total"},
            {"comparison_previous_period", "Comparación con período anterior:"},
            {"profit_change", "Cambio de ganancia"},
            {"top_drops", "Top Drops"},
            {"item", "Objeto"},
            {"count", "Cantidad"},
            {"value", "Valor"},
            {"enable_session_history", "Activar historial de sesiones"},
            {"enable_session_history_tooltip", "Guardar historial de sesiones de farming para visualización posterior"},
            {"sessions_stored", "Sesiones guardadas"},
            {"max_session_history", "Máx. Sesiones"},
            {"max_session_history_tooltip", "Número máximo de sesiones a guardar (1-50)"},
            {"overwrite_session_history", "Sobrescribir sesiones"},
            {"overwrite_session_history_tooltip", "Si está activado, la sesión más antigua se elimina cuando se alcanza el límite"},
            {"save_all_items_in_history", "Guardar todos los objetos"},
            {"save_all_items_in_history_tooltip", "Guardar todos los objetos obtenidos (aumenta el tamaño del archivo)"},
            {"save_all_items_confirm", "¿Guardar todos los objetos en el historial?"},
            {"save_all_items_warning", "¡Esto aumentará significativamente el tamaño del archivo!"},
            {"yes_enable", "Sí, Activar"},
            {"date", "Fecha"},
            {"duration", "Duración"},
            {"drops", "Objetos"},
            {"map", "Mapa"},
            {"clear_history", "Borrar historial"},
            {"clear_history_tooltip", "Eliminar todo el historial de sesiones"},
            {"clear_history_confirm", "¿Borrar todo el historial de sesiones?"},
            {"clear_history_warning", "¡Esta acción no se puede deshacer!"},
            {"yes_clear", "Sí, borrar"},
            {"no_sessions_recorded", "Aún no hay sesiones registradas."},
            {"unknown_map", "Desconocido"},
            {"tab_session_history", "Historial de sesiones"},
            {"save_current_session", "Guardar sesión actual"},
            {"save_current_session_tooltip", "Guardar la sesión de farming actual sin reiniciar"},
            {"rarity_all", "Rareza: todos"},
            {"rarity_basic", "Rareza: Básico+"},
            {"rarity_fine", "Rareza: Fino+"},
            {"rarity_masterwork", "Rareza: Maestría+"},
            {"rarity_rare", "Rareza: Raro+"},
            {"rarity_exotic", "Rareza: Exótico+"},
            {"rarity_ascended", "Rareza: Ascendido+"},
            {"rarity_legendary", "Rareza: Solo legendario"},
            {"rarity_tooltip", "Filtrar objetos por rareza mínima"},
            {"search_items_hint", "Buscar objetos..."},
            {"column_icon", "Icono"},
            {"column_name", "Nombre"},
            {"column_count", "Cuenta"},
            {"column_profit", "Beneficio"},
            {"column_favorite", "Favorito"},
            {"column_ignore", "Ignorar"},
            {"toggle_favorite", "Alternar favorito"},
            {"toggle_ignore", "Alternar ignorar"},
            {"vendor_value_format", "Valor del vendedor: %s"},
            {"tp_sell_gross_format", "Venta TP (Bruto): %s"},
            {"tp_sell_net_format", "Venta TP (Neto): %s"},
            {"tp_buy_gross_format", "Compra TP (Bruto): %s"},
            {"tp_buy_net_format", "Compra TP (Neto): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Configuración de Favoritos"},
            {"favorites_first", "Favoritos primero"},
            {"favorites_first_tooltip", "Muestra favoritos primero en listas de objetos/monedas"},
            {"enable_favorite_text_color", "Activar color de texto favorito"},
            {"enable_favorite_text_color_tooltip", "Resalta objetos/monedas favoritos con color de texto personalizado"},
            {"text_color", "Color de Texto"},
            {"enable_favorite_row_color", "Activar color de fila favorito"},
            {"enable_favorite_row_color_tooltip", "Resalta objetos/monedas favoritos con color de fondo de fila personalizado"},
            {"row_color", "Color de Fila"},
            
            // Filter - Additional
            {"filter_favorite", "Favorito"},
            {"filter_favorite_tooltip", "Mostrar objetos favoritos (fuera de la pestaña Favoritos)"},
            {"filter_not_favorite", "No Favorito"},
            {"filter_not_favorite_tooltip", "Mostrar objetos no favoritos"},
            {"filter_research_notes", "Notas de Investigación"},
            {"filter_research_notes_tooltip", "Mostrar moneda notas de investigación"},
            {"range_filters", "Filtros de Rango"},
            {"range_filters_tooltip", "Mostrar filtros de rango de precio y cantidad"},
            {"filter_min_price_tooltip", "Filtro de precio mínimo (0 = desactivado)"},
            {"filter_max_price_tooltip", "Filtro de precio máximo (0 = desactivado)"},
            {"filter_min_quantity_tooltip", "Filtro de cantidad mínimo (0 = desactivado)"},
            {"filter_max_quantity_tooltip", "Filtro de cantidad máximo (0 = desactivado)"},
            {"filter_min_price", "Precio Min"},
            {"filter_max_price", "Precio Max"},
            {"filter_min_quantity", "Cantidad Min"},
            {"filter_max_quantity", "Cantidad Max"},
            {"gold", "Oro"},
            {"silver", "Plata"},
            {"copper", "Cobre"},
            
            // Summary Tab - Table Columns
            {"column_label", "Etiqueta"},
            {"column_value", "Valor"},
            {"column_item", "Objeto"},
            {"column_count", "Cantidad"},
            {"column_currency", "Moneda"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Objetos por Ganancia"},
            {"top_items_count_header", "Top Objetos (Cantidad)"},
            {"top_currencies_count_header", "Top Monedas (Cantidad)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 objetos por valor de ganancia"},
            {"top_items_count_tooltip", "Top 10 objetos por cantidad"},
            {"top_currencies_count_tooltip", "Top 10 monedas por cantidad"},
            
            // Settings Tab - General
            {"show_main_window", "Mostrar ventana principal"},
            {"reset_all", "Restablecer todo"},
            {"reset_all_tooltip", "Restablecer todos los ajustes a valores predeterminados"},
            {"export", "Exportar"},
            {"export_tooltip", "Exportar ajustes a un archivo JSON"},
            {"import", "Importar"},
            {"import_tooltip", "Importar ajustes desde un archivo JSON"},
            {"save", "Guardar"},
            {"save_tooltip", "Guardar ajustes actuales"},
            {"general_settings", "Ajustes generales"},
            {"account_management", "Gestión de cuentas"},
            {"add_account", "+ Agregar cuenta"},
            {"remove_account", "- Eliminar cuenta"},
            {"save_account", "Guardar cuenta"},
            {"reload_drf_token", "Recargar token DRF"},
            {"reload_gw2_api_key", "Recargar clave API GW2"},
            {"reset_settings", "Auto Reset"},
            {"visual_settings", "Ajustes visuales"},
            {"gradient_backgrounds", "Fondos degradados"},
            {"gradient_backgrounds_tooltip", "Activa fondos degradados suaves para un aspecto más moderno"},
            {"top_gradient_color", "Color degradado superior"},
            {"top_gradient_color_tooltip", "Color degradado superior"},
            {"bottom_gradient_color", "Color degradado inferior"},
            {"bottom_gradient_color_tooltip", "Color degradado inferior"},
            {"show_item_icons", "Mostrar iconos de objetos (renderizado GW2)"},
            {"show_item_icons_tooltip", "Carga iconos desde render.guildwars2.com vía Nexus."},
            {"icon_size", "Tamaño de icono"},
            {"icon_size_tooltip", "Tamaño de iconos de objetos en píxeles (16-96)"},
            {"show_rarity_borders", "Mostrar bordes de rareza"},
            {"show_rarity_borders_tooltip", "Muestra bordes coloreados alrededor de iconos basados en rareza"},
            {"rarity_border_thickness", "Grosor de borde de rareza"},
            {"rarity_border_thickness_tooltip", "Ajustar el grosor de bordes de rareza (1.0 - 10.0)"},
            {"enable_grid_view_items", "Activar vista de cuadrícula (Objetos)"},
            {"enable_grid_view_items_tooltip", "Alternar entre vista de lista y cuadrícula en pestaña Objetos"},
            {"grid_icon_size_items", "Tamaño de icono de cuadrícula (Objetos)"},
            {"grid_icon_size_items_tooltip", "Tamaño de iconos en vista de cuadrícula para Objetos (16-128)"},
            {"enable_grid_view_currencies", "Activar vista de cuadrícula (Monedas)"},
            {"enable_grid_view_currencies_tooltip", "Alternar entre vista de lista y cuadrícula en pestaña Monedas"},
            {"grid_icon_size_currencies", "Tamaño de icono de cuadrícula (Monedas)"},
            {"grid_icon_size_currencies_tooltip", "Tamaño de iconos en vista de cuadrícula para Monedas (16-128)"},
            {"show_mini_window", "Mostrar mini ventana"},
            {"show_mini_window_tooltip", "Muestra un widget de superposición pequeño con estadísticas clave"},
            {"mini_window_show_profit", "Mostrar ganancia"},
            {"mini_window_show_profit_tooltip", "Mostrar ganancia total en mini ventana"},
            {"mini_window_show_profit_per_hour", "Mostrar ganancia/hora"},
            {"mini_window_show_profit_per_hour_tooltip", "Mostrar ganancia por hora en mini ventana"},
            {"mini_window_show_tp_sell", "Mostrar venta TP (Listas)"},
            {"mini_window_show_tp_sell_tooltip", "Mostrar ganancia de venta TP (listas) en mini ventana"},
            {"mini_window_show_tp_instant", "Mostrar venta instantánea TP"},
            {"mini_window_show_tp_instant_tooltip", "Mostrar ganancia de venta instantánea TP en mini ventana"},
            {"mini_window_show_total_items", "Mostrar total de objetos"},
            {"mini_window_show_total_items_tooltip", "Mostrar cantidad total de objetos en mini ventana"},
            {"mini_window_show_session_duration", "Mostrar duración de sesión"},
            {"mini_window_show_session_duration_tooltip", "Mostrar duración de sesión en mini ventana"},
            {"mini_window_click_through", "Mini-ventana click through"},
            {"mini_window_click_through_tooltip", "Permite hacer clic a través de la mini-ventana hacia el juego"},
            {"main_window_click_through", "Ventana principal click through"},
            {"main_window_click_through_tooltip", "Permite hacer clic a través de la ventana principal hacia el juego"},
            {"settings_profiles", "Perfiles de ajustes"},
            {"select_profile", "Seleccionar un perfil para aplicar sus ajustes"},
            {"create_new_profile", "Crear nuevo perfil"},
            {"create_new_profile_tooltip", "Crear un nuevo perfil con ajustes actuales"},
            {"create", "Crear"},
            {"update_profile", "Actualizar perfil"},
            {"update_profile_tooltip", "Actualizar perfil actual con ajustes actuales"},
            {"delete_profile", "Eliminar perfil"},
            {"delete_profile_tooltip", "Eliminar perfil actual"},
            {"automatic_backups", "Copias de seguridad automáticas"},
            {"enable_automatic_backups", "Activar copias de seguridad automáticas"},
            {"enable_automatic_backups_tooltip", "Crear automáticamente copias de seguridad antes de cambios"},
            {"backup_frequency", "Frecuencia de copia de seguridad"},
            {"backup_frequency_tooltip", "Con qué frecuencia crear copias de seguridad automáticas"},
            {"max_backups", "Copias de seguridad máximas"},
            {"max_backups_tooltip", "Número máximo de copias de seguridad a mantener (1-20)"},
            {"notification_settings", "Ajustes de notificación"},
            {"enable_notifications", "Activar notificaciones"},
            {"enable_notifications_tooltip", "Activar notificaciones en el juego"},
            {"notify_profit_goal", "Notificar cuando se alcance el objetivo de ganancia"},
            {"notify_profit_goal_tooltip", "Notificar cuando alcances tu objetivo de ganancia"},
            {"profit_goal_gold", "Objetivo de ganancia (Oro)"},
            {"profit_goal_gold_tooltip", "Objetivo de ganancia en monedas de oro (1-1000)"},
            {"notify_reset_warning", "Notificar antes de restablecer"},
            {"notify_reset_warning_tooltip", "Notificar antes de que ocurra un restablecimiento automático"},
            {"reset_warning_minutes", "Advertencia de restablecimiento (Minutos)"},
            {"reset_warning_minutes_tooltip", "Minutos antes del restablecimiento para mostrar advertencia (1-60)"},
            {"notify_session_complete", "Notificar después de duración de sesión"},
            {"notify_session_complete_tooltip", "Notificar después de farmear durante una duración específica"},
            {"session_complete_hours", "Sesión completada (Horas)"},
            {"session_complete_hours_tooltip", "Horas de farmeo antes de notificación (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Vendible al vendedor"},
            {"filter_sellable_to_vendor_tooltip", "Mostrar objetos vendibles al vendedor"},
            {"filter_sellable_on_tp", "Vendible en TP"},
            {"filter_sellable_on_tp_tooltip", "Mostrar objetos vendibles en el Puesto de Comercio"},
            {"filter_custom_profit", "Ganancia personalizada"},
            {"filter_custom_profit_tooltip", "Mostrar objetos con ganancia personalizada"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Conocido por API"},
            {"filter_known_by_api_tooltip", "Mostrar objetos conocidos por la API GW2"},
            {"filter_unknown_by_api", "Desconocido por API"},
            {"filter_unknown_by_api_tooltip", "Mostrar objetos desconocidos por la API GW2"},
            
            // Filter - Additional
            {"show_ignored_items", "Mostrar objetos ignorados"},
            {"show_ignored_items_tooltip", "Mostrar objetos/monedas ignorados en las pestañas Objetos y Monedas (desactivar para ocultar). Diferencia con el filtro 'Ignorados': Este filtro controla la visualización en las pestañas Objetos/Monedas, el filtro 'Ignorados' controla la visualización en la pestaña Filtro."},
            
            // Filter - Item Types
            {"filter_type_armor", "Armadura"},
            {"filter_type_armor_tooltip", "Mostrar objetos de armadura"},
            {"filter_type_backpack", "Mochila"},
            {"filter_type_backpack_tooltip", "Mostrar objetos de mochila"},
            {"filter_type_bag", "Bolsa"},
            {"filter_type_bag_tooltip", "Mostrar bolsas"},
            {"filter_type_container", "Contenedor"},
            {"filter_type_container_tooltip", "Mostrar contenedores"},
            {"filter_type_consumable", "Consumible"},
            {"filter_type_consumable_tooltip", "Mostrar consumibles"},
            {"filter_type_crafting_material", "Material de artesanía"},
            {"filter_type_crafting_material_tooltip", "Mostrar materiales de artesanía"},
            {"filter_type_gathering_tool", "Herramienta de recolección"},
            {"filter_type_gathering_tool_tooltip", "Mostrar herramientas de recolección"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Mostrar objetos gizmo"},
            {"filter_type_gizmo_container", "Contenedor Gizmo"},
            {"filter_type_gizmo_container_tooltip", "Mostrar objetos contenedor gizmo"},
            {"filter_type_mini_pet", "Mini Mascota"},
            {"filter_type_mini_pet_tooltip", "Mostrar mini mascotas"},
            {"filter_type_tool", "Herramienta"},
            {"filter_type_tool_tooltip", "Mostrar objetos herramienta"},
            {"filter_type_trinket", "Abalorio"},
            {"filter_type_trinket_tooltip", "Mostrar objetos de abalorio"},
            {"filter_type_trophy", "Trofeo"},
            {"filter_type_trophy_tooltip", "Mostrar objetos trofeo"},
            {"filter_type_unlock", "Desbloqueo"},
            {"filter_type_unlock_tooltip", "Mostrar objetos de desbloqueo"},
            {"filter_type_upgrade_component", "Componente de mejora"},
            {"filter_type_upgrade_component_tooltip", "Mostrar componentes de mejora"},
            {"filter_type_weapon", "Arma"},
            {"filter_type_weapon_tooltip", "Mostrar objetos de arma"},
            
            // Filter - Currencies
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Mostrar moneda Karma"},
            {"filter_laurel", "Laurel"},
            {"filter_laurel_tooltip", "Mostrar moneda Laurel"},
            {"filter_gem", "Gema"},
            {"filter_gem_tooltip", "Mostrar moneda Gema"},
            {"filter_fractal_relic", "Reliquia fractal"},
            {"filter_fractal_relic_tooltip", "Mostrar moneda Reliquia fractal"},
            {"filter_badge_of_honor", "Insignia de honor"},
            {"filter_badge_of_honor_tooltip", "Mostrar moneda Insignia de honor"},
            {"filter_guild_commendation", "Recomendación de gremio"},
            {"filter_guild_commendation_tooltip", "Mostrar moneda Recomendación de gremio"},
            {"filter_transmutation_charge", "Carga de transmutación"},
            {"filter_transmutation_charge_tooltip", "Mostrar moneda Carga de transmutación"},
            {"filter_spirit_shards", "Fragmentos de espíritu"},
            {"filter_spirit_shards_tooltip", "Mostrar moneda Fragmentos de espíritu"},
            {"filter_unbound_magic", "Magia sin vincular"},
            {"filter_unbound_magic_tooltip", "Mostrar moneda Magia sin vincular"},
            {"filter_volatile_magic", "Magia volátil"},
            {"filter_volatile_magic_tooltip", "Mostrar moneda Magia volátil"},
            {"filter_airship_parts", "Partes de dirigible"},
            {"filter_airship_parts_tooltip", "Mostrar moneda Partes de dirigible"},
            {"filter_geode", "Geoda"},
            {"filter_geode_tooltip", "Mostrar moneda Geoda"},
            {"filter_ley_line_crystals", "Cristales de líneas ley"},
            {"filter_ley_line_crystals_tooltip", "Mostrar moneda Cristales de líneas ley"},
            {"filter_trade_contracts", "Contratos comerciales"},
            {"filter_trade_contracts_tooltip", "Mostrar moneda Contratos comerciales"},
            {"filter_elegy_mosaic", "Mosaico de elegía"},
            {"filter_elegy_mosaic_tooltip", "Mostrar moneda Mosaico de elegía"},
            {"filter_uncommon_coins", "Monedas poco comunes"},
            {"filter_uncommon_coins_tooltip", "Mostrar moneda Monedas poco comunes"},
            {"filter_astral_acclaim", "Aplauso astral"},
            {"filter_astral_acclaim_tooltip", "Mostrar moneda Aplauso astral"},
            
            // Debug Tab
            {"total_tracked_items", "Número total de objetos rastreados"},
            {"total_tracked_items_tooltip", "Número total de objetos rastreados"},
            {"total_tracked_currencies", "Número total de monedas rastreadas"},
            {"total_tracked_currencies_tooltip", "Número total de monedas rastreadas"},
            {"total_custom_profit", "Ganancia personalizada total"},
            {"total_custom_profit_tooltip", "Ganancia personalizada total"},
            {"total_tp_sell_profit", "Ganancia de venta TP total"},
            {"total_tp_sell_profit_tooltip", "Ganancia de venta TP total"},
            {"total_vendor_sell_profit", "Ganancia de venta vendedor total"},
            {"total_vendor_sell_profit_tooltip", "Ganancia de venta vendedor total"},
            {"profit_per_hour_calculation", "Cálculo de ganancia por hora"},
            {"profit_per_hour_calculation_tooltip", "Cálculo de ganancia por hora"},
            {"opportunity_cost_vs_tp_sell", "Costo de oportunidad vs venta TP"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Costo de oportunidad vs venta TP"},
            {"opportunity_cost_per_hour", "Costo de oportunidad por hora"},
            {"opportunity_cost_per_hour_tooltip", "Costo de oportunidad por hora"},
            {"first_5_tracked_items", "Primeros 5 objetos y monedas rastreados con detalles"},
            {"first_5_tracked_items_tooltip", "Primeros 5 objetos y monedas rastreados con detalles"},
            {"first_5_custom_profit", "Primeros 5 objetos con ganancia personalizada"},
            {"first_5_custom_profit_tooltip", "Primeros 5 objetos con ganancia personalizada"},
            {"first_5_ignored_items", "Primeros 5 objetos ignorados"},
            {"first_5_ignored_items_tooltip", "Primeros 5 objetos ignorados"},
            
            // Debug Settings
            {"debug_settings", "Configuración de Depuración"},
            {"enable_debug_tab", "Activar Pestaña de Depuración"},
            {"enable_debug_tab_tooltip", "Muestra la pestaña de depuración con información adicional"},
            
            // Currencies Tab
            {"gold_format", "Oro: %lld"},
            {"count_format", "Cantidad: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Alternar favorito"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Alternar ignorar"},
            
            // Additional Filters
            {"filter_account_bound", "Vinculado a la cuenta"},
            {"filter_account_bound_tooltip", "Mostrar objetos vinculados a la cuenta"},
            {"filter_not_account_bound", "No vinculado a la cuenta"},
            {"filter_not_account_bound_tooltip", "Mostrar objetos no vinculados a la cuenta"},
            {"filter_nosell", "NoVender"},
            {"filter_nosell_tooltip", "Mostrar objetos NoVender"},
            {"filter_not_nosell", "No NoVender"},
            {"filter_not_nosell_tooltip", "Mostrar objetos vendibles"},
            {"filter_ignored", "Ignorado"},
            {"filter_ignored_tooltip", "Mostrar objetos ignorados"},
            {"filter_not_ignored", "No Ignorado"},
            {"filter_not_ignored_tooltip", "Mostrar objetos no ignorados"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Reliquias fractales prístinas"},
            {"filter_pristine_fractal_relics_tooltip", "Mostrar moneda Reliquias fractales prístinas"},
            {"filter_unstable_fractal_essence", "Esencia fractal inestable"},
            {"filter_unstable_fractal_essence_tooltip", "Mostrar moneda Esencia fractal inestable"},
            {"filter_magnetite_shards", "Fragmentos de magnetita"},
            {"filter_magnetite_shards_tooltip", "Mostrar moneda Fragmentos de magnetita"},
            {"filter_gaeting_crystals", "Cristales Gaeting"},
            {"filter_gaeting_crystals_tooltip", "Mostrar moneda Cristales Gaeting"},
            {"filter_prophet_shards", "Fragmentos de profeta"},
            {"filter_prophet_shards_tooltip", "Mostrar moneda Fragmentos de profeta"},
            {"filter_green_prophet_shards", "Fragmentos de profeta verdes"},
            {"filter_green_prophet_shards_tooltip", "Mostrar moneda Fragmentos de profeta verdes"},
            {"filter_wvw_skirmish_tickets", "Boletos de escaramuza WvW"},
            {"filter_wvw_skirmish_tickets_tooltip", "Mostrar moneda Boletos de escaramuza WvW"},
            {"filter_proofs_of_heroics", "Pruebas de heroísmo"},
            {"filter_proofs_of_heroics_tooltip", "Mostrar moneda Pruebas de heroísmo"},
            {"filter_pvp_league_tickets", "Boletos de liga PvP"},
            {"filter_pvp_league_tickets_tooltip", "Mostrar moneda Boletos de liga PvP"},
            {"filter_ascended_shards_of_glory", "Fragmentos de gloria ascendidos"},
            {"filter_ascended_shards_of_glory_tooltip", "Mostrar moneda Fragmentos de gloria ascendidos"},
            {"filter_tyrian_defense_seal", "Sello de defensa tirio"},
            {"filter_tyrian_defense_seal_tooltip", "Mostrar moneda Sello de defensa tirio"},
            {"filter_testimony_of_desert_heroics", "Testimonio de heroísmo del desierto"},
            {"filter_testimony_of_desert_heroics_tooltip", "Mostrar moneda Testimonio de heroísmo del desierto"},
            {"filter_testimony_of_jade_heroics", "Testimonio de heroísmo de jade"},
            {"filter_testimony_of_jade_heroics_tooltip", "Mostrar moneda Testimonio de heroísmo de jade"},
            {"filter_testimony_of_castoran_heroics", "Testimonio de heroísmo castorano"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Mostrar moneda Testimonio de heroísmo castorano"},
            {"filter_legendary_insight", "Perspectiva legendaria"},
            {"filter_legendary_insight_tooltip", "Mostrar moneda Perspectiva legendaria"},
            {"filter_tales_of_dungeon_delving", "Relatos de exploración de mazmorras"},
            {"filter_tales_of_dungeon_delving_tooltip", "Mostrar moneda Relatos de exploración de mazmorras"},
            {"filter_imperial_favor", "Favor imperial"},
            {"filter_imperial_favor_tooltip", "Mostrar moneda Favor imperial"},
            {"filter_canach_coins", "Monedas Canach"},
            {"filter_canach_coins_tooltip", "Mostrar moneda Monedas Canach"},
            {"filter_ancient_coin", "Moneda antigua"},
            {"filter_ancient_coin_tooltip", "Mostrar moneda Moneda antigua"},
            {"filter_unusual_coin", "Moneda inusual"},
            {"filter_unusual_coin_tooltip", "Mostrar moneda Moneda inusual"},
            {"filter_jade_sliver", "Fragmento de jade"},
            {"filter_jade_sliver_tooltip", "Mostrar moneda Fragmento de jade"},
            {"filter_static_charge", "Carga estática"},
            {"filter_static_charge_tooltip", "Mostrar moneda Carga estática"},
            {"filter_pinch_of_stardust", "Pizca de polvo estelar"},
            {"filter_pinch_of_stardust_tooltip", "Mostrar moneda Pizca de polvo estelar"},
            {"filter_calcified_gasp", "Jadeo calcificado"},
            {"filter_calcified_gasp_tooltip", "Mostrar moneda Jadeo calcificado"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Mostrar moneda Ursus Oblige"},
            {"filter_gaeting_crystal_janthir", "Cristal Gaeting (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Mostrar moneda Cristal Gaeting (Janthir)"},
            {"filter_antiquated_ducat", "Ducado anticuado"},
            {"filter_antiquated_ducat_tooltip", "Mostrar moneda Ducado anticuado"},
            {"filter_aether_rich_sap", "Savia rica en éter"},
            {"filter_aether_rich_sap_tooltip", "Mostrar moneda Savia rica en éter"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Restablecer todo"},
            {"reset_all_tooltip", "Restablecer todos los ajustes a valores predeterminados"},
            {"reset_confirm", "¿Está seguro de que desea restablecer todos los ajustes?"},
            {"reset_warning", "Esta acción no se puede deshacer."},
            {"yes_reset", "Sí, restablecer"},
            {"cancel", "Cancelar"},
            {"export", "Exportar"},
            {"export_tooltip", "Exportar ajustes a un archivo JSON"},
            {"export_settings", "Exportar ajustes"},
            {"import", "Importar"},
            {"import_settings", "Importar ajustes"},
            {"save", "Guardar"},
            {"save_tooltip", "Guardar ajustes actuales"},
            
            // Settings Tab - General
            {"general_settings", "Ajustes generales"},
            {"account_management", "Gestión de cuentas"},
            {"account_prefix", "Cuenta"},
            {"remove_account", "- Eliminar cuenta"},
            {"save_account", "Guardar cuenta"},
            {"reconnect_drf_token", "Reconectar a DRF con el token actual"},
            {"reload_gw2_api_key_tooltip", "Recargar clave API GW2 para obtener datos de objetos"},
            {"reset_settings", "Auto Reset"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Nunca (solo restablecimiento manual)"},
            {"auto_reset_on_load", "Al cargar el addon"},
            {"auto_reset_daily", "Restablecimiento diario (00:00 UTC)"},
            {"auto_reset_weekly", "Semanal (Lun 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Semanal NA WvW (Sáb 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Semanal EU WvW (Vie 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Semanal bono de mapa (Jue 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minutos después de la última descarga"},
            {"auto_reset_custom_days", "Personalizado (días)"},
            {"auto_reset_tooltip", "Cuándo restablecer automáticamente los contadores de farming"},
            {"minutes_after_unload_tooltip", "Minutos después de la descarga del addon antes del restablecimiento automático"},
            {"reset_interval_days", "Intervalo de restablecimiento (días)"},
            {"reset_interval_days_tooltip", "Intervalo de restablecimiento personalizado en días (1-30 días)"},
            
            // Visual Settings
            {"top_gradient_color", "Superior"},
            {"top_gradient_color_tooltip", "Color de gradiente superior"},
            {"bottom_gradient_color", "Inferior"},
            {"bottom_gradient_color_tooltip", "Color de gradiente inferior"},
            {"icon_size", "Tamaño de icono"},
            {"icon_size_tooltip", "Tamaño de iconos de objetos en píxeles (16-96)"},
            {"border_size", "Tamaño de borde"},
            {"border_size_tooltip", "Ajustar el grosor de bordes de rareza (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Alternar entre vista de lista y cuadrícula en pestaña Objetos"},
            {"grid_icon_size_items", "Tamaño de icono de cuadrícula (Objetos)"},
            {"grid_icon_size_items_tooltip", "Tamaño de iconos en vista de cuadrícula para Objetos (16-128)"},
            {"grid_icon_size_currencies", "Tamaño de icono de cuadrícula (Monedas)"},
            {"grid_icon_size_currencies_tooltip", "Tamaño de iconos en vista de cuadrícula para Monedas (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Mostrar mini ventana"},
            {"show_mini_window_tooltip", "Muestra un pequeño widget de superposición con estadísticas clave"},
            {"mini_window_show_profit", "Mostrar ganancia"},
            {"mini_window_show_profit_tooltip", "Mostrar ganancia total en mini ventana"},
            {"mini_window_show_profit_per_hour", "Mostrar ganancia/hora"},
            {"mini_window_show_profit_per_hour_tooltip", "Mostrar ganancia por hora en mini ventana"},
            {"mini_window_show_tp_sell", "Mostrar venta TP (Listas)"},
            {"mini_window_show_tp_sell_tooltip", "Mostrar ganancia de venta TP (listas) en mini ventana"},
            {"mini_window_show_tp_instant", "Mostrar venta instantánea TP"},
            {"mini_window_show_tp_instant_tooltip", "Mostrar ganancia de venta instantánea TP en mini ventana"},
            {"mini_window_show_total_items", "Mostrar total de objetos"},
            {"mini_window_show_total_items_tooltip", "Mostrar cantidad total de objetos en mini ventana"},
            {"mini_window_show_session_duration", "Mostrar duración de sesión"},
            {"mini_window_show_session_duration_tooltip", "Mostrar duración de sesión en mini ventana"},
            {"mini_window_click_through", "Ventana clickeable"},
            {"mini_window_click_through_tooltip", "Permite hacer clic a través de la mini ventana al juego"},
            
            // Main Window
            {"main_window_label", "Ventana principal"},
            {"main_window_click_through", "Clickeable"},
            {"main_window_click_through_tooltip", "Permite hacer clic a través de la ventana principal al juego"},
            
            // Settings Profiles
            {"settings_profiles", "Perfiles de ajustes"},
            {"default_no_profile", "Predeterminado (Sin perfil)"},
            {"select_profile_tooltip", "Seleccionar un perfil para aplicar sus ajustes"},
            {"create", "Crear"},
            {"create_tooltip", "Crear un nuevo perfil con ajustes actuales"},
            {"update_profile", "Actualizar perfil"},
            {"update_profile_tooltip", "Actualizar perfil actual con ajustes actuales"},
            {"delete_profile", "Eliminar perfil"},
            {"delete_profile_tooltip", "Eliminar perfil actual"},
            
            // Automatic Backups
            {"automatic_backups", "Copias de seguridad automáticas"},
            {"enable_automatic_backups", "Activar copias de seguridad automáticas"},
            {"enable_automatic_backups_tooltip", "Crear automáticamente copias de seguridad antes de cambios"},
            {"backup_frequency", "Frecuencia de copia de seguridad"},
            {"backup_frequency_tooltip", "Con qué frecuencia crear copias de seguridad automáticas"},
            {"backup_manual_only", "Solo manual"},
            {"backup_daily", "Diario"},
            {"backup_weekly", "Semanal"},
            {"max_backup_count", "Máximo de copias"},
            {"max_backup_count_tooltip", "Número máximo de copias de seguridad a mantener (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Ajustes de notificación"},
            {"enable_notifications", "Activar notificaciones"},
            {"enable_notifications_tooltip", "Activar notificaciones en el juego"},
            {"profit_goal", "Objetivo de ganancia"},
            {"notify_profit_goal", "Notificar cuando se alcance el objetivo de ganancia"},
            {"notify_profit_goal_tooltip", "Notificar cuando alcance su objetivo de ganancia"},
            {"profit_goal_gold", "Objetivo de ganancia (oro)"},
            {"profit_goal_gold_tooltip", "Objetivo de ganancia en monedas de oro (1-1000)"},
            {"reset_warning_label", "Advertencia de restablecimiento"},
            {"notify_reset_warning", "Notificar antes del restablecimiento"},
            {"notify_reset_warning_tooltip", "Notificar antes de que ocurra el restablecimiento automático"},
            {"warning_minutes", "Minutos de advertencia"},
            {"warning_minutes_tooltip", "Minutos antes del restablecimiento para mostrar advertencia (1-60)"},
            {"session_complete", "Sesión completada"},
            {"notify_session_complete", "Notificar después de la duración de sesión"},
            {"notify_session_complete_tooltip", "Notificar después de farming durante una cierta duración"},
            {"session_hours", "Horas de sesión"},
            {"session_hours_tooltip", "Horas de farming antes de la notificación (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Buscar monedas..."},
            {"clear_search", "Borrar"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Buscar objetos favoritos..."},
            {"search_favorite_currencies_hint", "Buscar monedas favoritas..."},
            {"clear_search_favorites", "Borrar"},
        };
        return translations;
    }
}
