// ---------------------------------------------------------------------------
// localization_fr.cpp – French translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetFrenchTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Déconnecté"},
            {"status_connecting", "Connexion..."},
            {"status_connected", "Connecté"},
            {"status_auth_failed", "Échec de l'authentification – vérifiez le jeton"},
            {"status_reconnecting", "Reconnexion..."},
            {"status_error", "Erreur"},
            {"status_unknown", "Inconnu"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Profit"},
            {"profit_per_hour", "Profit/Heure"},
            {"tp_sell", "Vente TP"},
            {"tp_instant", "Vente Instantanée TP"},
            {"total_items", "Total Objets"},
            {"session", "Session"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "API GW2"},
            {"session_time_label", "Temps de Session"},
            {"reset_button", "Réinitialiser"},
            {"reset_tooltip", "Réinitialiser tous les compteurs de farming (réinitialisation manuelle)"},

            // Tabs
            {"tab_summary", "Aperçu"},
            {"tab_items", "Objets"},
            {"tab_currencies", "Devises"},
            {"tab_profit", "Profit"},
            {"tab_favorites", "Favoris"},
            {"tab_ignored", "Ignorés"},
            {"tab_filter", "Filtre"},
            {"tab_custom_profit", "Profit Personnalisé"},
            {"tab_debug", "Debug"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF non connecté"},
            {"warning_drf_not_connected_desc", "Ce plugin nécessite DRF pour la transmission de données."},
            {"warning_drf_install", "Installez DRF via le Gestionnaire d'Addons Nexus ou https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ Jeton DRF invalide"},
            {"warning_drf_token_invalid_desc", "Veuillez vérifier votre jeton DRF dans les paramètres."},
            {"warning_gw2_api_key_not_set", "⚠️ Clé API GW2 non définie"},
            {"warning_gw2_api_key_not_set_desc", "Veuillez définir votre clé API GW2 dans les paramètres pour les détails des objets."},
            {"overview", "Aperçu"},
            {"overview_tooltip", "Aperçu de la session de farming actuelle"},
            {"total_profit", "Profit Total"},
            {"total_profit_tooltip", "Profit personnalisé total de tous les objets"},
            {"total_items_count", "Total Objets"},
            {"total_items_tooltip", "Nombre total d'objets uniques suivis"},
            {"total_currencies", "Total Devises"},
            {"total_currencies_tooltip", "Nombre total de devises uniques suivies"},
            {"profit_per_hour_label", "Profit Par Heure"},
            {"profit_per_hour_tooltip", "Profit par heure basé sur la durée de la session"},
            {"session_duration", "Durée de Session"},
            {"session_duration_tooltip", "Durée de la session de farming actuelle"},
            {"top_items_profit", "Top Objets (Profit)"},
            {"top_items_profit_tooltip", "Top 5 objets par valeur de profit"},
            {"loading", "Chargement..."},
            {"coin", "Pièce"},
            {"top_items_count", "Top Objets (Nombre)"},
            {"top_items_count_tooltip", "Top 5 objets par nombre"},
            {"top_currencies", "Top Devises"},
            {"top_currencies_tooltip", "Top 5 devises par nombre"},
            {"quick_statistics", "Statistiques Rapides"},
            {"quick_statistics_tooltip", "Aperçu des statistiques de farming"},
            {"average_item_value", "Valeur Moyenne de l'Objet"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Total Objets Uniques"},
            {"warning_no_data", "⚠️ Aucune donnée chargée"},
            {"warning_no_data_desc", "En attente des données DRF..."},
            {"export", "Exporter"},
            {"export_tooltip", "Exporter les données de farming vers un fichier"},
            {"export_json", "Exporter en JSON"},
            {"export_csv", "Exporter en CSV"},

            // Items Tab
            {"search_hint", "Rechercher des objets..."},
            {"clear", "Effacer"},
            {"sort_count_high", "Tri: |Nbr| haut"},
            {"sort_count_low", "Tri: |Nbr| bas"},
            {"sort_id_up", "Tri: ID Objet haut"},
            {"sort_id_down", "Tri: ID Objet bas"},
            {"sort_name_az", "Tri: Nom A–Z"},
            {"sort_tooltip", "Trier les objets par nombre, ID ou nom"},
            {"rarity_all", "Rareté: toutes"},
            {"rarity_basic", "Rareté: Base+"},
            {"rarity_fine", "Rareté: Fin+"},
            {"rarity_masterwork", "Rareté: Chef-d'œuvre+"},
            {"rarity_rare", "Rareté: Rare+"},
            {"rarity_exotic", "Rareté: Exotique+"},
            {"rarity_ascended", "Rareté: Ascension+"},
            {"rarity_legendary", "Rareté: Légendaire uniquement"},
            {"rarity_tooltip", "Filtrer les objets par rareté minimale"},
            {"rarity", "Rareté"},
            {"type", "Type"},
            {"vendor_value", "Valeur Marchand"},
            {"tp_buy_net", "Achat TP (Net)"},
            {"account_bound", "Lié au compte"},
            {"yes", "Oui"},
            {"no", "Non"},
            {"nosell", "Non vendable"},
            {"favorite", "Favori"},
            {"ignore", "Ignorer"},

            // Currencies Tab
            {"search_currencies_hint", "Rechercher des devises..."},
            {"api_id", "ID API"},
            {"currency_name", "Nom de la Devise"},
            {"count", "Nombre"},

            // Profit Tab
            {"profits", "Profits"},
            {"profits_tooltip", "Profits totaux du farming"},
            {"approx_profits", "Profits Approx."},
            {"approx_gold_per_hour", "Or Approx. Par Heure"},
            {"trading_profits", "Profits d'Échange"},
            {"trading_profits_tooltip", "Profits du Poste d'Échange"},
            {"approx_trading_profits_listings", "Profits d'Échange Approx. (Listes)"},
            {"approx_trading_profits_instant", "Profits d'Échange Approx. (Vente Instantanée)"},
            {"trading_details", "Détails d'Échange (Coût d'Opportunité)"},
            {"trading_details_tooltip", "Coût d'opportunité d'utiliser les objets au lieu de les vendre"},
            {"lost_profit_vs_tp_sell", "Profit Perdu (vs Vente TP)"},
            {"lost_profit_per_hour_vs_tp_sell", "Profit Perdu Par Heure (vs Vente TP)"},
            {"session_duration_label", "Durée de session"},
            {"session_duration_tooltip", "Durée de la session de farming actuelle"},

            // Filter Tab
            {"sell_method_filters", "Filtres de Méthode de Vente"},
            {"sellable_to_vendor", "Vendable au marchand"},
            {"sellable_to_vendor_tooltip", "Afficher les objets vendables au marchand"},
            {"sellable_on_tp", "Vendable sur TP"},
            {"sellable_on_tp_tooltip", "Afficher les objets vendables sur le Poste d'Échange"},
            {"has_custom_profit", "A un profit personnalisé"},
            {"has_custom_profit_tooltip", "Afficher les objets avec des valeurs de profit personnalisées"},
            {"api_knowledge_filters", "Filtres de Connaissance API"},
            {"known_by_api", "Connu par l'API"},
            {"known_by_api_tooltip", "Afficher les objets connus par l'API GW2"},
            {"unknown_by_api", "Inconnu par l'API"},
            {"unknown_by_api_tooltip", "Afficher les objets inconnus par l'API GW2"},
            {"item_type_filters", "Filtres de Type d'Objet"},
            {"type_armor", "Armure"},
            {"type_armor_tooltip", "Afficher les objets d'armure"},
            {"type_weapon", "Arme"},
            {"type_weapon_tooltip", "Afficher les objets d'arme"},
            {"type_trinket", "Bijou"},
            {"type_trinket_tooltip", "Afficher les objets de bijou"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Afficher les objets gizmo"},
            {"type_crafting_material", "Matériau d'Artisanat"},
            {"type_crafting_material_tooltip", "Afficher les matériaux d'artisanat"},
            {"type_consumable", "Consommable"},
            {"type_consumable_tooltip", "Afficher les consommables"},
            {"type_gathering_tool", "Outil de Récolte"},
            {"type_gathering_tool_tooltip", "Afficher les outils de récolte"},
            {"type_bag", "Sac"},
            {"type_bag_tooltip", "Afficher les sacs"},
            {"type_container", "Conteneur"},
            {"type_container_tooltip", "Afficher les conteneurs"},
            {"type_mini_pet", "Mini Familiar"},
            {"type_mini_pet_tooltip", "Afficher les mini familiers"},
            {"currency_filters_label", "Filtres de Devises"},
            {"currency_main", "Devises Principales"},
            {"currency_fractal", "Devises Fractales/Raid/Donjon"},
            {"currency_wvw_pvp", "Devises WvW/PvP"},
            {"currency_map", "Devises Spécifiques aux Cartes"},
            {"filter_karma", "Karma"},
            {"currency_karma_tooltip", "Afficher la devise Karma"},
            {"currency_laurel", "Laurier"},
            {"currency_laurel_tooltip", "Afficher la devise Laurier"},
            {"currency_gem", "Gemme"},
            {"currency_gem_tooltip", "Afficher la devise Gemme"},
            {"currency_fractal_relic", "Relique Fractale"},
            {"currency_fractal_relic_tooltip", "Afficher la devise Relique Fractale"},
            {"currency_badge_of_honor", "Insigne d'Honneur"},
            {"currency_badge_of_honor_tooltip", "Afficher la devise Insigne d'Honneur"},
            {"currency_guild_commendation", "Commendation de Guilde"},
            {"currency_guild_commendation_tooltip", "Afficher la devise Commendation de Guilde"},
            {"currency_transmutation_charge", "Charge de Transmutation"},
            {"currency_transmutation_charge_tooltip", "Afficher la devise Charge de Transmutation"},
            {"currency_spirit_shards", "Éclats d'Esprit"},
            {"currency_spirit_shards_tooltip", "Afficher la devise Éclats d'Esprit"},
            {"currency_unbound_magic", "Magie Non Liée"},
            {"currency_unbound_magic_tooltip", "Afficher la devise Magie Non Liée"},
            {"currency_volatile_magic", "Magie Volatile"},
            {"currency_volatile_magic_tooltip", "Afficher la devise Magie Volatile"},
            {"currency_airship_parts", "Pièces de Dirigeable"},
            {"currency_airship_parts_tooltip", "Afficher la devise Pièces de Dirigeable"},
            {"currency_geode", "Géode"},
            {"currency_geode_tooltip", "Afficher la devise Géode"},
            {"currency_ley_line_crystals", "Cristaux de Ligne Ley"},
            {"currency_ley_line_crystals_tooltip", "Afficher la devise Cristaux de Ligne Ley"},
            {"currency_trade_contracts", "Contrats Commerciaux"},
            {"currency_trade_contracts_tooltip", "Afficher la devise Contrats Commerciaux"},
            {"currency_elegy_mosaic", "Mosaïque d'Élégie"},
            {"currency_elegy_mosaic_tooltip", "Afficher la devise Mosaïque d'Élégie"},
            {"currency_uncommon_coins", "Pièces Rares"},
            {"currency_uncommon_coins_tooltip", "Afficher la devise Pièces Rares"},
            {"currency_astral_acclaim", "Acclamation Astrale"},
            {"currency_astral_acclaim_tooltip", "Afficher la devise Acclamation Astrale"},
            {"currency_pristine_fractal_relics", "Reliques Fractales Pures"},
            {"currency_pristine_fractal_relics_tooltip", "Afficher la devise Reliques Fractales Pures"},
            {"currency_unstable_fractal_essence", "Essence Fractale Instable"},
            {"currency_unstable_fractal_essence_tooltip", "Afficher la devise Essence Fractale Instable"},
            {"currency_magnetite_shards", "Éclats de Magnétite"},
            {"currency_magnetite_shards_tooltip", "Afficher la devise Éclats de Magnétite"},
            {"currency_gaeting_crystals", "Cristaux Gaeting"},
            {"currency_gaeting_crystals_tooltip", "Afficher la devise Cristaux Gaeting"},
            {"currency_prophet_shards", "Éclats de Prophète"},
            {"currency_prophet_shards_tooltip", "Afficher la devise Éclats de Prophète"},
            {"currency_green_prophet_shards", "Éclats de Prophète Verts"},
            {"currency_green_prophet_shards_tooltip", "Afficher la devise Éclats de Prophète Verts"},
            {"currency_wvw_skirmish_tickets", "Billets d'Escarmouche WvW"},
            {"currency_wvw_skirmish_tickets_tooltip", "Afficher la devise Billets d'Escarmouche WvW"},
            {"currency_proofs_of_heroics", "Preuves d'Héroïsme"},
            {"currency_proofs_of_heroics_tooltip", "Afficher la devise Preuves d'Héroïsme"},
            {"currency_pvp_league_tickets", "Billets de Ligue PvP"},
            {"currency_pvp_league_tickets_tooltip", "Afficher la devise Billets de Ligue PvP"},
            {"currency_ascended_shards_of_glory", "Éclats de Gloire Ascendus"},
            {"currency_ascended_shards_of_glory_tooltip", "Afficher la devise Éclats de Gloire Ascendus"},
            {"currency_research_notes", "Notes de Recherche"},
            {"currency_research_notes_tooltip", "Afficher la devise Notes de Recherche"},
            {"currency_tyrian_defense_seal", "Sceau de Défense Tyrien"},
            {"currency_tyrian_defense_seal_tooltip", "Afficher la devise Sceau de Défense Tyrien"},
            {"currency_testimony_of_desert_heroics", "Témoignage des Héros du Désert"},
            {"currency_testimony_of_desert_heroics_tooltip", "Afficher la devise Témoignage des Héros du Désert"},
            {"currency_testimony_of_jade_heroics", "Témoignage des Héros de Jade"},
            {"currency_testimony_of_jade_heroics_tooltip", "Afficher la devise Témoignage des Héros de Jade"},
            {"currency_testimony_of_castoran_heroics", "Témoignage des Héros Castorans"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Afficher la devise Témoignage des Héros Castorans"},
            {"currency_legendary_insight", "Perspective Légendaire"},
            {"currency_legendary_insight_tooltip", "Afficher la devise Perspective Légendaire"},
            {"currency_tales_of_dungeon_delving", "Contes d'Exploration de Donjon"},
            {"currency_tales_of_dungeon_delving_tooltip", "Afficher la devise Contes d'Exploration de Donjon"},
            {"currency_imperial_favor", "Faveur Impériale"},
            {"currency_imperial_favor_tooltip", "Afficher la devise Faveur Impériale"},
            {"currency_canach_coins", "Pièces Canach"},
            {"currency_canach_coins_tooltip", "Afficher la devise Pièces Canach"},
            {"currency_ancient_coin", "Pièce Antique"},
            {"currency_ancient_coin_tooltip", "Afficher la devise Pièce Antique"},
            {"currency_unusual_coin", "Pièce Inhabituelle"},
            {"currency_unusual_coin_tooltip", "Afficher la devise Pièce Inhabituelle"},
            {"currency_jade_sliver", "Éclat de Jade"},
            {"currency_jade_sliver_tooltip", "Afficher la devise Éclat de Jade"},
            {"currency_static_charge", "Charge Statique"},
            {"currency_static_charge_tooltip", "Afficher la devise Charge Statique"},
            {"currency_pinch_of_stardust", "Pincée de Poussière d'Étoile"},
            {"currency_pinch_of_stardust_tooltip", "Afficher la devise Pincée de Poussière d'Étoile"},
            {"currency_calcified_gasp", "Soupir Calcifié"},
            {"currency_calcified_gasp_tooltip", "Afficher la devise Soupir Calcifié"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Afficher la devise Ursus Oblige"},
            {"currency_gaeting_crystal_janthir", "Cristal Gaeting (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Afficher la devise Cristal Gaeting (Janthir)"},
            {"currency_antiquated_ducat", "Ducat Antique"},
            {"currency_antiquated_ducat_tooltip", "Afficher la devise Ducat Antique"},
            {"currency_aether_rich_sap", "Sève Riche en Éther"},
            {"currency_aether_rich_sap_tooltip", "Afficher la devise Sève Riche en Éther"},

            // Additional Filters
            {"additional_filters", "Filtres Additionnels"},
            {"account_bound", "Lié au compte"},
            {"account_bound_tooltip", "Afficher les objets liés au compte"},
            {"not_account_bound", "Non Lié au compte"},
            {"not_account_bound_tooltip", "Afficher les objets non liés au compte"},
            {"nosell_items", "Non vendable"},
            {"nosell_items_tooltip", "Afficher les objets non vendables"},
            {"not_nosell", "Vendable"},
            {"not_nosell_tooltip", "Afficher les objets vendables"},
            {"favorite_items", "Favori"},
            {"favorite_items_tooltip", "Afficher les objets favoris"},
            {"not_favorite", "Non Favori"},
            {"not_favorite_tooltip", "Afficher les objets non favoris"},
            {"ignored_items", "Ignoré"},
            {"ignored_items_tooltip", "Afficher les objets ignorés"},
            {"not_ignored", "Non Ignoré"},
            {"not_ignored_tooltip", "Afficher les objets non ignorés"},

            // Range Filters
            {"range_filters", "Filtres de Plage"},
            {"show_range_filters", "Afficher les Filtres de Plage"},
            {"filter_min_price", "Filtre Prix Min"},
            {"filter_max_price", "Filtre Prix Max"},
            {"filter_min_quantity", "Filtre Quantité Min"},
            {"filter_max_quantity", "Filtre Quantité Max"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Fenêtre"},
            {"show_profit", "Afficher le Profit"},
            {"show_profit_tooltip", "Afficher le profit total dans la mini fenêtre"},
            {"show_profit_per_hour", "Afficher le Profit/Heure"},
            {"show_profit_per_hour_tooltip", "Afficher le profit par heure dans la mini fenêtre"},
            {"show_tp_sell", "Afficher la Vente TP (Listes)"},
            {"show_tp_sell_tooltip", "Afficher le profit de vente TP (listes) dans la mini fenêtre"},
            {"show_tp_instant", "Afficher la Vente Instantanée TP"},
            {"show_tp_instant_tooltip", "Afficher le profit de vente instantanée TP dans la mini fenêtre"},
            {"show_total_items", "Afficher le Total d'Objets"},
            {"show_total_items_tooltip", "Afficher le nombre total d'objets dans la mini fenêtre"},
            {"show_session_duration", "Afficher la Durée de Session"},
            {"show_session_duration_tooltip", "Afficher la durée de session dans la mini fenêtre"},
            {"window_click_through", "Clic au travers de la fenêtre"},
            {"window_click_through_tooltip", "Permet de cliquer au travers de la mini fenêtre vers le jeu"},

            // Main Window Settings
            {"main_window", "Fenêtre Principale"},
            {"click_through", "Clic au travers"},
            {"click_through_tooltip", "Permet de cliquer au travers de la fenêtre principale vers le jeu"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Paramètres UI Avancés"},
            {"no_advanced_ui_settings", "(Aucun paramètre UI avancé disponible)"},

            // Display Settings
            {"display_settings", "Paramètres d'Affichage"},
            {"show_item_icons", "Afficher les Icônes d'Objets"},
            {"show_item_icons_tooltip", "Afficher les icônes d'objets dans la liste"},
            {"show_rarity_border", "Afficher la Bordure de Rareté"},
            {"show_rarity_border_tooltip", "Afficher une bordure colorée basée sur la rareté de l'objet"},
            {"enable_grid_view", "Activer la Vue en Grille"},
            {"enable_grid_view_tooltip", "Afficher les objets en disposition grille au lieu de liste"},
            {"grid_icon_size", "Taille d'Icône de Grille"},
            {"grid_icon_size_tooltip", "Taille des icônes en vue grille"},

            // Count Display Settings
            {"count_display_settings", "Paramètres d'Affichage du Nombre"},
            {"count_text_color", "Couleur de Texte du Nombre"},
            {"count_text_color_tooltip", "Couleur du texte du nombre"},
            {"count_background_color", "Couleur d'Arrière-plan du Nombre"},
            {"count_background_color_tooltip", "Couleur de l'arrière-plan du nombre"},
            {"count_font_size", "Taille de Police du Nombre"},
            {"count_font_size_tooltip", "Taille de la police du nombre"},
            {"count_horizontal_alignment", "Alignement Horizontal du Nombre"},
            {"count_horizontal_alignment_tooltip", "Alignement horizontal du texte du nombre"},

            // Gradient Background Settings
            {"gradient_background_settings", "Paramètres d'Arrière-plan en Dégradé"},
            {"enable_gradient_backgrounds", "Activer les Arrière-plans en Dégradé"},
            {"enable_gradient_backgrounds_tooltip", "Activer l'arrière-plan en dégradé pour les fenêtres"},
            {"gradient_top_color", "Couleur Supérieure du Dégradé"},
            {"gradient_top_color_tooltip", "Couleur supérieure de l'arrière-plan en dégradé"},
            {"gradient_bottom_color", "Couleur Inférieure du Dégradé"},
            {"gradient_bottom_color_tooltip", "Couleur inférieure de l'arrière-plan en dégradé"},

            // Custom Profit System
            {"custom_profit_system", "Système de Profit Personnalisé"},
            {"enable_custom_profit", "Activer le Profit Personnalisé"},
            {"enable_custom_profit_tooltip", "Activer les valeurs de profit personnalisé pour les objets"},

            // Search
            {"search_settings", "Recherche"},
            {"enable_search", "Activer la Recherche"},
            {"enable_search_tooltip", "Activer la fonctionnalité de recherche"},

            // Ignored Items
            {"ignored_items_settings", "Objets Ignorés"},
            {"enable_ignored_items", "Activer les Objets Ignorés"},
            {"enable_ignored_items_tooltip", "Activer la fonctionnalité d'objets ignorés"},

            // Auto Reset
            {"auto_reset_settings", "Réinitialisation Auto"},
            {"enable_auto_reset", "Activer la Réinitialisation Auto"},
            {"enable_auto_reset_tooltip", "Réinitialiser automatiquement la session de farming après une durée"},
            {"auto_reset_duration", "Durée de Réinitialisation Auto (minutes)"},
            {"auto_reset_duration_tooltip", "Durée en minutes avant la réinitialisation auto"},

            // DRF Settings
            {"drf_settings", "Paramètres DRF"},
            {"drf_token", "Jeton DRF"},
            {"drf_token_tooltip", "Votre jeton d'authentification DRF"},
            {"edit_token", "Modifier le Jeton"},
            {"save_token", "Sauvegarder le Jeton"},

            // GW2 API Settings
            {"gw2_api_settings", "Paramètres API GW2"},
            {"gw2_api_key", "Clé API GW2"},
            {"gw2_api_key_tooltip", "Votre clé API GW2 pour les détails des objets"},
            {"edit_key", "Modifier la Clé"},
            {"save_key", "Sauvegarder la Clé"},

            // Language Settings
            {"language_settings", "Langue"},
            {"language_tooltip", "Sélectionner la langue de l'interface"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "Aucun compte configuré"},
            {"no_profiles_created", "Aucun profil créé pour le moment"},
            {"count_label", "Nombre:"},
            {"profit_label", "Profit:"},
            {"no_profit", "Aucun profit"},
            {"vendor_value_label", "Valeur Marchand:"},
            {"tp_sell_gross_label", "Vente TP (Brut):"},
            {"tp_sell_net_label", "Vente TP (Net):"},
            {"tp_buy_gross_label", "Achat TP (Brut):"},
            {"tp_buy_net_label", "Achat TP (Net):"},
            {"ignored_items_label", "Objets Ignorés:"},
            {"ignored_currencies_label", "Devises Ignorées:"},
            {"total_items_label", "Total Objets:"},
            {"total_currencies_label", "Total Devises:"},
            {"total_profit_label", "Profit Total:"},
            {"tp_sell_profit_label", "Profit de Vente TP:"},
            {"vendor_profit_label", "Profit de Vente Marchand:"},
            {"profit_per_hour_label", "Profit Par Heure:"},
            {"opportunity_cost_profit_label", "Profit de Coût d'Opportunité:"},
            {"opportunity_cost_profit_per_hour_label", "Profit de Coût d'Opportunité/Heure:"},
            {"custom_profit_feature_placeholder", "Fonctionnalité implémentée - UI à ajouter"},
            {"custom_profit_items_header", "Objets avec Profit Personnalisé"},
            {"custom_profit_currencies_header", "Devises avec Profit Personnalisé"},
            {"add_custom_profit_item", "Ajouter Profit Personnalisé pour Objet"},
            {"add_custom_profit_currency", "Ajouter Profit Personnalisé pour Devise"},
            {"custom_profit_set_profit", "Définir Profit"},
            {"custom_profit_remove", "Supprimer"},
            {"custom_profit_value", "Valeur du Profit (Cuivre)"},
            {"custom_profit_set_tooltip", "Définir une valeur de profit personnalisée pour cet objet"},
            {"custom_profit_remove_tooltip", "Supprimer la valeur de profit personnalisée pour cet objet"},
            {"no_custom_profit_items", "(Aucun objet avec profit personnalisé)"},
            {"no_custom_profit_currencies", "(Aucune devise avec profit personnalisé)"},
            {"clear_all_custom_profits", "Effacer tous les profits personnalisés"},
            {"clear_all_custom_profits_tooltip", "Effacer toutes les valeurs de profit personnalisées"},
            {"tabs_settings", "Autres Onglets"},
            {"tabs_description", "Afficher ou masquer les autres onglets"},
            {"enable_ignored_tab", "Activer l'onglet Ignorés"},
            {"enable_ignored_tab_tooltip", "Afficher l'onglet Ignorés dans la vue principale"},
            {"custom_profit_settings", "Profit Personnalisé"},
            {"overview_label", "Aperçu:"},
            {"total_profit_label_simple", "Profit Total"},
            {"total_items_label_simple", "Total Objets"},
            {"total_currencies_label_simple", "Total Devises"},
            {"profit_per_hour_label_simple", "Profit Par Heure"},
            {"session_duration_label_simple", "Durée de Session"},
            {"export_label", "Exporter:"},
            {"quick_actions", "Actions Rapides:"},
            {"reset_confirm", "Voulez-vous vraiment réinitialiser tous les paramètres par défaut?"},
            {"reset_warning", "Cette action ne peut pas être annulée."},
            {"export_settings", "Exporter les Paramètres dans un Fichier:"},
            {"import_settings", "Importer les Paramètres depuis un Fichier:"},
            {"edit_account", "Modifier le Compte: %s"},
            {"account_name", "Nom du Compte:"},
            {"drf_token_label", "Jeton DRF:"},
            {"gw2_api_key_label", "Clé API GW2:"},
            {"reload_config", "Recharger la Configuration:"},
            {"auto_reset_label", "Réinitialisation Auto:"},
            {"next_reset_utc", "Prochaine réinitialisation planifiée (UTC): %s"},
            {"favorites_ui", "UI Favoris:"},
            {"favorites_colors", "Couleurs Favoris:"},
            {"visual_enhancements", "Améliorations Visuelles:"},
            {"mini_window_widget", "Mini Fenêtre (Widget Overlay):"},
            {"main_window_label", "Fenêtre Principale:"},
            {"profiles_description", "Les profils permettent de sauvegarder différentes configurations et de basculer rapidement entre elles."},
            {"create_new_profile", "Créer un Nouveau Profil:"},
            {"current_profile", "Profil Actuel: %s"},
            {"auto_backup", "Sauvegarder automatiquement vos paramètres avant les changements majeurs"},
            {"notifications", "Configurer les notifications en jeu pour les événements importants"},
            {"profit_goal", "Objectif de Profit:"},
            {"reset_warning_label", "Avertissement de Réinitialisation:"},
            {"session_complete", "Session Terminée:"},
            {"manage_ignored_items", "Gérer les objets ignorés"},
            {"manage_ignored_currencies", "Gérer les devises ignorées"},
            {"rarity_label", "Rareté: %s"},
            {"type_label", "Type: %d"},
            {"account_bound_label", "Lié au compte: %s"},
            {"nosell_label", "Non vendable: %s"},
            {"sell_method_filters_label", "Filtres de Méthode de Vente:"},
            {"api_knowledge_filters_label", "Filtres de Connaissance API:"},
            {"additional_filters_label", "Filtres Additionnels:"},
            {"item_type_filters_label", "Filtres de Type d'Objet:"},
            {"currency_filters_label", "Filtres de Devises:"},
            {"price_range", "Plage de Prix (Cuivre):"},
            {"quantity_range", "Plage de Quantité:"},
            {"debug_info", "Informations de Debug"},
            {"drf_status", "Statut DRF: %s"},
            {"drf_reconnect_count", "Nombre de Reconnexions DRF: %d"},
            {"gw2_api_status", "Statut API GW2: %s"},
            {"gw2_api_reconnect_count", "Nombre de Reconnexions API GW2: %d"},
            {"session_duration_debug", "Durée de Session: %s"},
            {"gw2_memory", "Mémoire Processus GW2: %zu MB"},
            {"gw2_api_request_count", "Nombre de Requêtes API GW2: %d"},
            {"ignored_items_count", "Objets Ignorés: %d"},
            {"ignored_currencies_count", "Devises Ignorées: %d"},
            {"drf_logs", "Logs DRF:"},
            {"last_100_entries", "(100 dernières entrées)"},
            {"gw2_api_logs", "Logs API GW2:"},
            {"item_currency_details", "Détails Objet/Devise (Premiers 5):"},
            {"item_label", "Objet %d: %s (Quantité: "},
            {"loaded_label", ", Chargé: %s)"},
            {"currency_label", "Devise %d: %s (Quantité: "},
            {"custom_profit_items", "Objets Profit Personnalisé (Premiers 5):"},
            {"custom_profit_item", "Objet %d: %s (Profit Personnalisé: "},
            {"no_custom_profit_items", "(Aucun objet profit personnalisé)"},
            {"ignored_items_debug", "Objets Ignorés (Premiers 5):"},
            {"yes_label", "Oui"},
            {"no_label", "Non"},
            {"profits_label", "Profits:"},
            {"profits_tooltip", "Profits totaux du farming"},
            {"approx_profits_label", "Profits Approximés:"},
            {"approx_profits_tooltip", "Profit total des valeurs de profit personnalisé"},
            {"approx_gold_per_hour_label", "Or Par Heure Approximatif:"},
            {"approx_gold_per_hour_tooltip", "Profit par heure basé sur la durée de session"},
            {"trading_profits_label", "Profits de Trading:"},
            {"trading_profits_tooltip", "Profits de la vente d'objets sur le Trading Post"},
            {"approx_trading_profits_listings_label", "Profits de Trading Approximés (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Profit total si vendu via TP listings"},
            {"approx_trading_profits_instant_label", "Profits de Trading Approximés (Vente Instantanée):"},
            {"approx_trading_profits_instant_tooltip", "Profit total si vendu via TP buy orders instantanés"},
            {"trading_details_label", "Détails de Trading (Coût d'Opportunité):"},
            {"trading_details_tooltip", "Profit perdu en ne vendant pas via TP listings"},
            {"lost_profit_vs_tp_sell_label", "Profit Perdu (vs Vente TP):"},
            {"lost_profit_vs_tp_sell_tooltip", "Or = profit perdu, Rouge = profit gagné vs vente TP"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Profit Perdu Par Heure (vs Vente TP):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Coût d'opportunité par heure"},
            {"session_duration_debug_label", "Durée de session: %s"},
            {"session_duration_debug_tooltip", "Durée de session de farming actuelle"},
            {"tab_items", "Objets"},
            {"manage_ignored_items", "Gérer les objets ignorés"},
            {"clear_all_ignored_items", "Effacer tous les objets ignorés"},
            {"unignore_item", "Ne plus ignorer l'objet"},
            {"tab_currencies", "Devises"},
            {"manage_ignored_currencies", "Gérer les devises ignorées"},
            {"clear_all_ignored_currencies", "Effacer toutes les devises ignorées"},
            {"unignore_currency", "Ne plus ignorer la devise"},
            {"sell_method_filters_label", "Filtres de Méthode de Vente:"},
            {"api_knowledge_filters_label", "Filtres de Connaissance API:"},
            {"additional_filters_label", "Filtres Additionnels:"},
            {"item_type_filters_label", "Filtres de Type d'Objet:"},
            {"currency_filters_label", "Filtres de Devises:"},
            {"price_range", "Plage de Prix (Cuivre):"},
            {"quantity_range", "Plage de Quantité:"},
            {"debug_information", "Informations de Debug"},
            {"drf_status_label", "Statut DRF: %s"},
            {"drf_status_tooltip", "Statut de connexion DRF actuel"},
            {"drf_reconnect_count_label", "Nombre de Reconnexions DRF: %d"},
            {"drf_reconnect_count_tooltip", "Nombre de tentatives de reconnexion DRF"},
            {"gw2_api_status_label", "Statut API GW2: %s"},
            {"gw2_api_status_tooltip", "Statut de connexion API GW2 actuel"},
            {"gw2_api_reconnect_count_label", "Nombre de Reconnexions API GW2: %d"},
            {"gw2_api_reconnect_count_tooltip", "Nombre de tentatives de reconnexion API GW2"},
            {"session_duration_debug", "Durée de Session: %s"},
            {"session_duration_debug_tooltip", "Durée de session de farming actuelle"},
            {"gw2_process_memory_label", "Mémoire Processus GW2: %zu MB"},
            {"gw2_process_memory_tooltip", "Utilisation mémoire processus GW2 actuelle"},
            {"gw2_api_request_count_label", "Nombre de Requêtes API GW2: %d"},
            {"gw2_api_request_count_tooltip", "Nombre total de requêtes API GW2 effectuées"},
            {"ignored_items_debug_label", "Objets Ignorés: %d"},
            {"ignored_items_debug_tooltip", "Nombre d'objets ignorés"},
            {"ignored_currencies_debug_label", "Devises Ignorées: %d"},
            {"ignored_currencies_debug_tooltip", "Nombre de devises ignorées"},
            {"drf_logs_label", "Logs DRF:"},
            {"clear_drf_logs", "Effacer Logs DRF"},
            {"clear_drf_logs_tooltip", "Effacer tous les entrées de logs DRF"},
            {"last_100_entries", "(Derniers 100 entrées)"},
            {"gw2_api_logs_label", "Logs API GW2:"},
            {"clear_gw2_logs", "Effacer Logs GW2"},
            {"clear_gw2_logs_tooltip", "Effacer tous les entrées de logs API GW2"},
            {"settings_label", "Paramètres:"},
            {"api_key_label", "Clé API: %s"},
            {"api_key_tooltip", "Statut de clé API GW2"},
            {"not_set", "Non défini"},
            {"set", "Défini"},
            {"drf_token_label", "Jeton DRF: %s"},
            {"drf_token_tooltip", "Statut de jeton DRF"},
            {"toggle_hotkey_label", "Raccourci de Basculement: %s"},
            {"toggle_hotkey_tooltip", "Raccourci de basculement de fenêtre principale"},
            {"auto_reset_mode_label", "Mode Auto-Reset: %d"},
            {"auto_reset_mode_tooltip", "Mode de réinitialisation automatique actuel"},
            {"next_reset_label", "Prochain Reset: %s"},
            {"next_reset_tooltip", "Heure de réinitialisation planifiée suivante (UTC)"},
            {"fake_drf_server_label", "Serveur DRF Faux:"},
            {"use_fake_drf_server", "Utiliser serveur DRF faux"},
            {"use_fake_drf_server_tooltip", "Uniquement à des fins de test"},
            {"reset_all_data", "Réinitialiser Toutes les Données"},
            {"reset_all_data_tooltip", "Réinitialiser toutes les données de farming"},
            {"coin", "Pièce"},
            {"rarity_label", "Rareté: %s"},
            {"type_label", "Type: %d"},
            {"account_bound_label", "Lié au Compte: %s"},
            {"nosell_label", "NoSell: %s"},
            {"item_id_label", "ID d'Objet: %d"},
            {"currency_id_label", "ID de Devise: %d"},
            {"rarity_tooltip", "Filtrer les objets par rareté minimum"},
            {"sort_price_down", "Trier: Prix d'objet décroissant"},
            {"sort_price_up", "Trier: Prix d'objet croissant"},
            {"sort_count_high", "Trier: |Compte| élevé"},
            {"sort_count_low", "Trier: |Compte| faible"},
            {"sort_name_az", "Trier: Nom A–Z"},
            {"sort_tooltip", "Trier les objets par compte, ID ou nom"},
            {"rarity_all", "Rareté: tous"},
            {"rarity_basic", "Rareté: Basique+"},
            {"rarity_fine", "Rareté: Fin+"},
            {"rarity_masterwork", "Rareté: Chef-d'œuvre+"},
            {"rarity_rare", "Rareté: Rare+"},
            {"rarity_exotic", "Rareté: Exotique+"},
            {"rarity_ascended", "Rareté: Ascension+"},
            {"rarity_legendary", "Rareté: Légendaire uniquement"},
            {"rarity_tooltip", "Filtrer les objets par rareté minimale"},
            {"search_items_hint", "Rechercher des objets..."},
            {"column_icon", "Icône"},
            {"column_name", "Nom"},
            {"column_count", "Compte"},
            {"column_profit", "Profit"},
            {"column_favorite", "Favori"},
            {"column_ignore", "Ignorer"},
            {"toggle_favorite", "Basculer favori"},
            {"toggle_ignore", "Basculer ignorer"},
            {"vendor_value_format", "Valeur du vendeur: %s"},
            {"tp_sell_gross_format", "Vente TP (Brut): %s"},
            {"tp_sell_net_format", "Vente TP (Net): %s"},
            {"tp_buy_gross_format", "Achat TP (Brut): %s"},
            {"tp_buy_net_format", "Achat TP (Net): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Paramètres Favoris"},
            {"favorites_first", "Favoris d'abord"},
            {"favorites_first_tooltip", "Affiche les favoris en premier dans les listes d'objets/devises"},
            {"enable_favorite_text_color", "Activer la couleur de texte favori"},
            {"enable_favorite_text_color_tooltip", "Met en surbrillance les objets/devises favoris avec une couleur de texte personnalisée"},
            {"text_color", "Couleur de Texte"},
            {"enable_favorite_row_color", "Activer la couleur de ligne favori"},
            {"enable_favorite_row_color_tooltip", "Met en surbrillance les objets/devises favoris avec une couleur d'arrière-plan de ligne personnalisée"},
            {"row_color", "Couleur de Ligne"},
            
            // Filter - Additional
            {"filter_favorite", "Favori"},
            {"filter_favorite_tooltip", "Afficher les objets favoris (en dehors de l'onglet Favoris)"},
            {"filter_not_favorite", "Non Favori"},
            {"filter_not_favorite_tooltip", "Afficher les objets non favoris"},
            {"filter_research_notes", "Notes de Recherche"},
            {"filter_research_notes_tooltip", "Afficher la devise notes de recherche"},
            {"range_filters", "Filtres de Plage"},
            {"range_filters_tooltip", "Afficher les filtres de plage de prix et de quantité"},
            {"filter_min_price_tooltip", "Filtre de prix minimum (0 = désactivé)"},
            {"filter_max_price_tooltip", "Filtre de prix maximum (0 = désactivé)"},
            {"filter_min_quantity_tooltip", "Filtre de quantité minimum (0 = désactivé)"},
            {"filter_max_quantity_tooltip", "Filtre de quantité maximum (0 = désactivé)"},
            {"filter_min_price", "Prix Min"},
            {"filter_max_price", "Prix Max"},
            {"filter_min_quantity", "Quantité Min"},
            {"filter_max_quantity", "Quantité Max"},
            {"gold", "Or"},
            {"silver", "Argent"},
            {"copper", "Cuivre"},
            
            // Summary Tab - Table Columns
            {"column_label", "Étiquette"},
            {"column_value", "Valeur"},
            {"column_item", "Objet"},
            {"column_count", "Quantité"},
            {"column_currency", "Devise"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Objets par Profit"},
            {"top_items_count_header", "Top Objets (Quantité)"},
            {"top_currencies_count_header", "Top Devises (Quantité)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 objets par valeur de profit"},
            {"top_items_count_tooltip", "Top 10 objets par quantité"},
            {"top_currencies_count_tooltip", "Top 10 devises par quantité"},
            
            // Settings Tab - General
            {"show_main_window", "Afficher la fenêtre principale"},
            {"reset_all", "Tout réinitialiser"},
            {"reset_all_tooltip", "Réinitialiser tous les paramètres aux valeurs par défaut"},
            {"export", "Exporter"},
            {"export_tooltip", "Exporter les paramètres vers un fichier JSON"},
            {"import", "Importer"},
            {"import_tooltip", "Importer les paramètres depuis un fichier JSON"},
            {"save", "Enregistrer"},
            {"save_tooltip", "Enregistrer les paramètres actuels"},
            {"general_settings", "Paramètres généraux"},
            {"account_management", "Gestion des comptes"},
            {"add_account", "+ Ajouter un compte"},
            {"remove_account", "- Supprimer un compte"},
            {"save_account", "Enregistrer le compte"},
            {"reload_drf_token", "Recharger le jeton DRF"},
            {"reload_gw2_api_key", "Recharger la clé API GW2"},
            {"reset_settings", "Auto Reset"},
            {"visual_settings", "Paramètres visuels"},
            {"gradient_backgrounds", "Arrière-plans en dégradé"},
            {"gradient_backgrounds_tooltip", "Active des arrière-plans en dégradé pour un look plus moderne"},
            {"top_gradient_color", "Couleur de dégradé supérieure"},
            {"top_gradient_color_tooltip", "Couleur de dégradé supérieure"},
            {"bottom_gradient_color", "Couleur de dégradé inférieure"},
            {"bottom_gradient_color_tooltip", "Couleur de dégradé inférieure"},
            {"show_item_icons", "Afficher les icônes d'objets (rendu GW2)"},
            {"show_item_icons_tooltip", "Charge les icônes depuis render.guildwars2.com via Nexus."},
            {"icon_size", "Taille des icônes"},
            {"icon_size_tooltip", "Taille des icônes d'objets en pixels (16-96)"},
            {"show_rarity_borders", "Afficher les bordures de rareté"},
            {"show_rarity_borders_tooltip", "Affiche des bordures colorées autour des icônes basées sur la rareté"},
            {"rarity_border_thickness", "Épaisseur des bordures de rareté"},
            {"rarity_border_thickness_tooltip", "Ajuster l'épaisseur des bordures de rareté (1.0 - 10.0)"},
            {"enable_grid_view_items", "Activer la vue en grille (Objets)"},
            {"enable_grid_view_items_tooltip", "Basculer entre la vue en liste et en grille dans l'onglet Objets"},
            {"grid_icon_size_items", "Taille des icônes en grille (Objets)"},
            {"grid_icon_size_items_tooltip", "Taille des icônes en vue en grille pour les objets (16-128)"},
            {"enable_grid_view_currencies", "Activer la vue en grille (Devises)"},
            {"enable_grid_view_currencies_tooltip", "Basculer entre la vue en liste et en grille dans l'onglet Devises"},
            {"grid_icon_size_currencies", "Taille des icônes en grille (Devises)"},
            {"grid_icon_size_currencies_tooltip", "Taille des icônes en vue en grille pour les devises (16-128)"},
            {"show_mini_window", "Afficher la mini-fenêtre"},
            {"show_mini_window_tooltip", "Affiche un petit widget de superposition avec des statistiques clés"},
            {"mini_window_show_profit", "Afficher le profit"},
            {"mini_window_show_profit_tooltip", "Afficher le profit total dans la mini-fenêtre"},
            {"mini_window_show_profit_per_hour", "Afficher le profit/heure"},
            {"mini_window_show_profit_per_hour_tooltip", "Afficher le profit par heure dans la mini-fenêtre"},
            {"mini_window_show_tp_sell", "Afficher la vente TP (Listes)"},
            {"mini_window_show_tp_sell_tooltip", "Afficher le profit de vente TP (listes) dans la mini-fenêtre"},
            {"mini_window_show_tp_instant", "Afficher la vente instantanée TP"},
            {"mini_window_show_tp_instant_tooltip", "Afficher le profit de vente instantanée TP dans la mini-fenêtre"},
            {"mini_window_show_total_items", "Afficher le total des objets"},
            {"mini_window_show_total_items_tooltip", "Afficher le nombre total d'objets dans la mini-fenêtre"},
            {"mini_window_show_session_duration", "Afficher la durée de session"},
            {"mini_window_show_session_duration_tooltip", "Afficher la durée de session dans la mini-fenêtre"},
            {"mini_window_click_through", "Fenêtre cliquable"},
            {"mini_window_click_through_tooltip", "Permet de cliquer à travers la mini-fenêtre vers le jeu"},
            {"main_window_click_through", "Cliquable"},
            {"main_window_click_through_tooltip", "Permet de cliquer à travers la fenêtre principale vers le jeu"},
            {"settings_profiles", "Profils de paramètres"},
            {"select_profile", "Sélectionner un profil pour appliquer ses paramètres"},
            {"create_new_profile", "Créer un nouveau profil"},
            {"create_new_profile_tooltip", "Créer un nouveau profil avec les paramètres actuels"},
            {"create", "Créer"},
            {"update_profile", "Mettre à jour le profil"},
            {"update_profile_tooltip", "Mettre à jour le profil actuel avec les paramètres actuels"},
            {"delete_profile", "Supprimer le profil"},
            {"delete_profile_tooltip", "Supprimer le profil actuel"},
            {"automatic_backups", "Sauvegardes automatiques"},
            {"enable_automatic_backups", "Activer les sauvegardes automatiques"},
            {"enable_automatic_backups_tooltip", "Créer automatiquement des sauvegardes avant les modifications"},
            {"backup_frequency", "Fréquence de sauvegarde"},
            {"backup_frequency_tooltip", "Fréquence de création des sauvegardes automatiques"},
            {"max_backups", "Sauvegardes maximales"},
            {"max_backups_tooltip", "Nombre maximum de sauvegardes à conserver (1-20)"},
            {"notification_settings", "Paramètres de notification"},
            {"enable_notifications", "Activer les notifications"},
            {"enable_notifications_tooltip", "Activer les notifications en jeu"},
            {"notify_profit_goal", "Notifier lorsque l'objectif de profit est atteint"},
            {"notify_profit_goal_tooltip", "Notifier lorsque vous atteignez votre objectif de profit"},
            {"profit_goal_gold", "Objectif de profit (Or)"},
            {"profit_goal_gold_tooltip", "Objectif de profit en pièces d'or (1-1000)"},
            {"notify_reset_warning", "Notifier avant réinitialisation"},
            {"notify_reset_warning_tooltip", "Notifier avant qu'une réinitialisation automatique ne se produise"},
            {"reset_warning_minutes", "Avertissement de réinitialisation (Minutes)"},
            {"reset_warning_minutes_tooltip", "Minutes avant la réinitialisation pour afficher l'avertissement (1-60)"},
            {"notify_session_complete", "Notifier après la durée de session"},
            {"notify_session_complete_tooltip", "Notifier après avoir farmé pendant une certaine durée"},
            {"session_complete_hours", "Session terminée (Heures)"},
            {"session_complete_hours_tooltip", "Heures de farm avant la notification (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Vendable au marchand"},
            {"filter_sellable_to_vendor_tooltip", "Afficher les objets vendables au marchand"},
            {"filter_sellable_on_tp", "Vendable sur TP"},
            {"filter_sellable_on_tp_tooltip", "Afficher les objets vendables sur le poste de commerce"},
            {"filter_custom_profit", "Profit personnalisé"},
            {"filter_custom_profit_tooltip", "Afficher les objets avec un profit personnalisé"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Connu par l'API"},
            {"filter_known_by_api_tooltip", "Afficher les objets connus par l'API GW2"},
            {"filter_unknown_by_api", "Inconnu par l'API"},
            {"filter_unknown_by_api_tooltip", "Afficher les objets inconnus par l'API GW2"},
            
            // Filter - Additional
            {"show_ignored_items", "Afficher les objets ignorés"},
            {"show_ignored_items_tooltip", "Afficher les objets/devises ignorés dans les onglets Objets et Devises (désactiver pour masquer). Différence avec le filtre 'Ignorés': Ce filtre contrôle l'affichage dans les onglets Objets/Devises, le filtre 'Ignorés' contrôle l'affichage dans l'onglet Filtre."},
            
            // Filter - Item Types
            {"filter_type_armor", "Armure"},
            {"filter_type_armor_tooltip", "Afficher les objets d'armure"},
            {"filter_type_backpack", "Sac à dos"},
            {"filter_type_backpack_tooltip", "Afficher les objets sac à dos"},
            {"filter_type_bag", "Sac"},
            {"filter_type_bag_tooltip", "Afficher les sacs"},
            {"filter_type_container", "Conteneur"},
            {"filter_type_container_tooltip", "Afficher les conteneurs"},
            {"filter_type_consumable", "Consommable"},
            {"filter_type_consumable_tooltip", "Afficher les consommables"},
            {"filter_type_crafting_material", "Matériau d'artisanat"},
            {"filter_type_crafting_material_tooltip", "Afficher les matériaux d'artisanat"},
            {"filter_type_gathering_tool", "Outil de récolte"},
            {"filter_type_gathering_tool_tooltip", "Afficher les outils de récolte"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Afficher les objets gizmo"},
            {"filter_type_gizmo_container", "Conteneur Gizmo"},
            {"filter_type_gizmo_container_tooltip", "Afficher les objets conteneur gizmo"},
            {"filter_type_mini_pet", "Mini Familier"},
            {"filter_type_mini_pet_tooltip", "Afficher les mini familiers"},
            {"filter_type_tool", "Outil"},
            {"filter_type_tool_tooltip", "Afficher les objets outil"},
            {"filter_type_trinket", "Bijou"},
            {"filter_type_trinket_tooltip", "Afficher les objets de bijou"},
            {"filter_type_trophy", "Trophée"},
            {"filter_type_trophy_tooltip", "Afficher les objets trophée"},
            {"filter_type_unlock", "Déblocage"},
            {"filter_type_unlock_tooltip", "Afficher les objets de déblocage"},
            {"filter_type_upgrade_component", "Composant d'amélioration"},
            {"filter_type_upgrade_component_tooltip", "Afficher les composants d'amélioration"},
            {"filter_type_weapon", "Arme"},
            {"filter_type_weapon_tooltip", "Afficher les objets d'arme"},
            
            // Filter - Currencies
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Afficher la devise Karma"},
            {"filter_laurel", "Laurier"},
            {"filter_laurel_tooltip", "Afficher la devise Laurier"},
            {"filter_gem", "Gemme"},
            {"filter_gem_tooltip", "Afficher la devise Gemme"},
            {"filter_fractal_relic", "Relique fractale"},
            {"filter_fractal_relic_tooltip", "Afficher la devise Relique fractale"},
            {"filter_badge_of_honor", "Insigne d'honneur"},
            {"filter_badge_of_honor_tooltip", "Afficher la devise Insigne d'honneur"},
            {"filter_guild_commendation", "Recommandation de guilde"},
            {"filter_guild_commendation_tooltip", "Afficher la devise Recommandation de guilde"},
            {"filter_transmutation_charge", "Charge de transmutation"},
            {"filter_transmutation_charge_tooltip", "Afficher la devise Charge de transmutation"},
            {"filter_spirit_shards", "Éclats d'esprit"},
            {"filter_spirit_shards_tooltip", "Afficher la devise Éclats d'esprit"},
            {"filter_unbound_magic", "Magie non liée"},
            {"filter_unbound_magic_tooltip", "Afficher la devise Magie non liée"},
            {"filter_volatile_magic", "Magie volatile"},
            {"filter_volatile_magic_tooltip", "Afficher la devise Magie volatile"},
            {"filter_airship_parts", "Pièces de dirigeable"},
            {"filter_airship_parts_tooltip", "Afficher la devise Pièces de dirigeable"},
            {"filter_geode", "Géode"},
            {"filter_geode_tooltip", "Afficher la devise Géode"},
            {"filter_ley_line_crystals", "Cristaux de lignes telluriques"},
            {"filter_ley_line_crystals_tooltip", "Afficher la devise Cristaux de lignes telluriques"},
            {"filter_trade_contracts", "Contrats commerciaux"},
            {"filter_trade_contracts_tooltip", "Afficher la devise Contrats commerciaux"},
            {"filter_elegy_mosaic", "Mosaïque d'élégie"},
            {"filter_elegy_mosaic_tooltip", "Afficher la devise Mosaïque d'élégie"},
            {"filter_uncommon_coins", "Pièces inhabituelles"},
            {"filter_uncommon_coins_tooltip", "Afficher la devise Pièces inhabituelles"},
            {"filter_astral_acclaim", "Acclamation astrale"},
            {"filter_astral_acclaim_tooltip", "Afficher la devise Acclamation astrale"},
            
            // Debug Tab
            {"total_tracked_items", "Nombre total d'objets suivis"},
            {"total_tracked_items_tooltip", "Nombre total d'objets suivis"},
            {"total_tracked_currencies", "Nombre total de devises suivies"},
            {"total_tracked_currencies_tooltip", "Nombre total de devises suivies"},
            {"total_custom_profit", "Profit personnalisé total"},
            {"total_custom_profit_tooltip", "Profit personnalisé total"},
            {"total_tp_sell_profit", "Profit de vente TP total"},
            {"total_tp_sell_profit_tooltip", "Profit de vente TP total"},
            {"total_vendor_sell_profit", "Profit de vente marchand total"},
            {"total_vendor_sell_profit_tooltip", "Profit de vente marchand total"},
            {"profit_per_hour_calculation", "Calcul du profit par heure"},
            {"profit_per_hour_calculation_tooltip", "Calcul du profit par heure"},
            {"opportunity_cost_vs_tp_sell", "Coût d'opportunité vs vente TP"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Coût d'opportunité vs vente TP"},
            {"opportunity_cost_per_hour", "Coût d'opportunité par heure"},
            {"opportunity_cost_per_hour_tooltip", "Coût d'opportunité par heure"},
            {"first_5_tracked_items", "Premiers 5 objets et devises suivis avec détails"},
            {"first_5_tracked_items_tooltip", "Premiers 5 objets et devises suivis avec détails"},
            {"first_5_custom_profit", "Premiers 5 objets avec profit personnalisé"},
            {"first_5_custom_profit_tooltip", "Premiers 5 objets avec profit personnalisé"},
            {"first_5_ignored_items", "Premiers 5 objets ignorés"},
            {"first_5_ignored_items_tooltip", "Premiers 5 objets ignorés"},
            
            // Debug Settings
            {"debug_settings", "Paramètres de Debug"},
            {"enable_debug_tab", "Activer l'onglet Debug"},
            {"enable_debug_tab_tooltip", "Affiche l'onglet debug avec des informations supplémentaires"},
            
            // Currencies Tab
            {"gold_format", "Or: %lld"},
            {"count_format", "Quantité: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Basculer favori"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Basculer ignorer"},
            
            // Additional Filters
            {"filter_account_bound", "Lié au compte"},
            {"filter_account_bound_tooltip", "Afficher les objets liés au compte"},
            {"filter_not_account_bound", "Non lié au compte"},
            {"filter_not_account_bound_tooltip", "Afficher les objets non liés au compte"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "Afficher les objets NoSell"},
            {"filter_not_nosell", "Non NoSell"},
            {"filter_not_nosell_tooltip", "Afficher les objets vendables"},
            {"filter_ignored", "Ignoré"},
            {"filter_ignored_tooltip", "Afficher les objets ignorés"},
            {"filter_not_ignored", "Non Ignoré"},
            {"filter_not_ignored_tooltip", "Afficher les objets non ignorés"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Reliques fractales immaculées"},
            {"filter_pristine_fractal_relics_tooltip", "Afficher la devise Reliques fractales immaculées"},
            {"filter_unstable_fractal_essence", "Essence fractale instable"},
            {"filter_unstable_fractal_essence_tooltip", "Afficher la devise Essence fractale instable"},
            {"filter_magnetite_shards", "Éclats de magnétite"},
            {"filter_magnetite_shards_tooltip", "Afficher la devise Éclats de magnétite"},
            {"filter_gaeting_crystals", "Cristaux Gaeting"},
            {"filter_gaeting_crystals_tooltip", "Afficher la devise Cristaux Gaeting"},
            {"filter_prophet_shards", "Éclats de prophète"},
            {"filter_prophet_shards_tooltip", "Afficher la devise Éclats de prophète"},
            {"filter_green_prophet_shards", "Éclats de prophète verts"},
            {"filter_green_prophet_shards_tooltip", "Afficher la devise Éclats de prophète verts"},
            {"filter_wvw_skirmish_tickets", "Billets d'escarmouche WvW"},
            {"filter_wvw_skirmish_tickets_tooltip", "Afficher la devise Billets d'escarmouche WvW"},
            {"filter_proofs_of_heroics", "Preuves d'héroïsme"},
            {"filter_proofs_of_heroics_tooltip", "Afficher la devise Preuves d'héroïsme"},
            {"filter_pvp_league_tickets", "Billets de ligue PvP"},
            {"filter_pvp_league_tickets_tooltip", "Afficher la devise Billets de ligue PvP"},
            {"filter_ascended_shards_of_glory", "Éclats de gloire ascendants"},
            {"filter_ascended_shards_of_glory_tooltip", "Afficher la devise Éclats de gloire ascendants"},
            {"filter_tyrian_defense_seal", "Sceau de défense tyrien"},
            {"filter_tyrian_defense_seal_tooltip", "Afficher la devise Sceau de défense tyrien"},
            {"filter_testimony_of_desert_heroics", "Témoignage d'héroïsme du désert"},
            {"filter_testimony_of_desert_heroics_tooltip", "Afficher la devise Témoignage d'héroïsme du désert"},
            {"filter_testimony_of_jade_heroics", "Témoignage d'héroïsme de jade"},
            {"filter_testimony_of_jade_heroics_tooltip", "Afficher la devise Témoignage d'héroïsme de jade"},
            {"filter_testimony_of_castoran_heroics", "Témoignage d'héroïsme castoran"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Afficher la devise Témoignage d'héroïsme castoran"},
            {"filter_legendary_insight", "Perspective légendaire"},
            {"filter_legendary_insight_tooltip", "Afficher la devise Perspective légendaire"},
            {"filter_tales_of_dungeon_delving", "Contes d'exploration de donjon"},
            {"filter_tales_of_dungeon_delving_tooltip", "Afficher la devise Contes d'exploration de donjon"},
            {"filter_imperial_favor", "Faveur impériale"},
            {"filter_imperial_favor_tooltip", "Afficher la devise Faveur impériale"},
            {"filter_canach_coins", "Pièces Canach"},
            {"filter_canach_coins_tooltip", "Afficher la devise Pièces Canach"},
            {"filter_ancient_coin", "Pièce ancienne"},
            {"filter_ancient_coin_tooltip", "Afficher la devise Pièce ancienne"},
            {"filter_unusual_coin", "Pièce inhabituelle"},
            {"filter_unusual_coin_tooltip", "Afficher la devise Pièce inhabituelle"},
            {"filter_jade_sliver", "Éclat de jade"},
            {"filter_jade_sliver_tooltip", "Afficher la devise Éclat de jade"},
            {"filter_static_charge", "Charge statique"},
            {"filter_static_charge_tooltip", "Afficher la devise Charge statique"},
            {"filter_pinch_of_stardust", "Pincée de poussière d'étoile"},
            {"filter_pinch_of_stardust_tooltip", "Afficher la devise Pincée de poussière d'étoile"},
            {"filter_calcified_gasp", "Soupir calcifié"},
            {"filter_calcified_gasp_tooltip", "Afficher la devise Soupir calcifié"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Afficher la devise Ursus Oblige"},
            {"filter_gaeting_crystal_janthir", "Cristal Gaeting (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Afficher la devise Cristal Gaeting (Janthir)"},
            {"filter_antiquated_ducat", "Ducat antique"},
            {"filter_antiquated_ducat_tooltip", "Afficher la devise Ducat antique"},
            {"filter_aether_rich_sap", "Sève riche en éther"},
            {"filter_aether_rich_sap_tooltip", "Afficher la devise Sève riche en éther"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Réinitialiser tout"},
            {"reset_all_tooltip", "Réinitialiser tous les paramètres aux valeurs par défaut"},
            {"reset_confirm", "Voulez-vous vraiment réinitialiser tous les paramètres ?"},
            {"reset_warning", "Cette action ne peut pas être annulée."},
            {"yes_reset", "Oui, réinitialiser"},
            {"cancel", "Annuler"},
            {"export", "Exporter"},
            {"export_tooltip", "Exporter les paramètres vers un fichier JSON"},
            {"export_settings", "Exporter les paramètres"},
            {"import", "Importer"},
            {"import_settings", "Importer les paramètres"},
            {"save", "Enregistrer"},
            {"save_tooltip", "Enregistrer les paramètres actuels"},
            
            // Settings Tab - General
            {"general_settings", "Paramètres généraux"},
            {"account_management", "Gestion des comptes"},
            {"account_prefix", "Compte"},
            {"remove_account", "- Supprimer le compte"},
            {"save_account", "Enregistrer le compte"},
            {"reconnect_drf_token", "Reconnecter à DRF avec le jeton actuel"},
            {"reload_gw2_api_key_tooltip", "Recharger la clé API GW2 pour la récupération des données d'objets"},
            {"reset_settings", "Auto Reset"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Jamais (réinitialisation manuelle uniquement)"},
            {"auto_reset_on_load", "Au chargement de l'addon"},
            {"auto_reset_daily", "Réinitialisation quotidienne (00:00 UTC)"},
            {"auto_reset_weekly", "Hebdomadaire (Lun 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Hebdomadaire NA WvW (Sam 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Hebdomadaire EU WvW (Ven 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Hebdomadaire bonus de carte (Jeu 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minutes après le dernier déchargement"},
            {"auto_reset_custom_days", "Personnalisé (jours)"},
            {"auto_reset_tooltip", "Quand réinitialiser automatiquement les compteurs de farming"},
            {"minutes_after_unload_tooltip", "Minutes après le déchargement de l'addon avant la réinitialisation automatique"},
            {"reset_interval_days", "Intervalle de réinitialisation (jours)"},
            {"reset_interval_days_tooltip", "Intervalle de réinitialisation personnalisé en jours (1-30 jours)"},
            
            // Visual Settings
            {"top_gradient_color", "Haut"},
            {"top_gradient_color_tooltip", "Couleur de dégradé supérieur"},
            {"bottom_gradient_color", "Bas"},
            {"bottom_gradient_color_tooltip", "Couleur de dégradé inférieur"},
            {"icon_size", "Taille de l'icône"},
            {"icon_size_tooltip", "Taille des icônes d'objets en pixels (16-96)"},
            {"border_size", "Taille de la bordure"},
            {"border_size_tooltip", "Ajuster l'épaisseur des bordures de rareté (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Basculer entre la vue liste et grille dans l'onglet Objets"},
            {"grid_icon_size_items", "Taille de l'icône de grille (Objets)"},
            {"grid_icon_size_items_tooltip", "Taille des icônes dans la vue grille pour Objets (16-128)"},
            {"grid_icon_size_currencies", "Taille de l'icône de grille (Devises)"},
            {"grid_icon_size_currencies_tooltip", "Taille des icônes dans la vue grille pour Devises (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Afficher la mini-fenêtre"},
            {"show_mini_window_tooltip", "Affiche un petit widget de superposition avec des statistiques clés"},
            {"mini_window_show_profit", "Afficher le profit"},
            {"mini_window_show_profit_tooltip", "Afficher le profit total dans la mini-fenêtre"},
            {"mini_window_show_profit_per_hour", "Afficher le profit/heure"},
            {"mini_window_show_profit_per_hour_tooltip", "Afficher le profit par heure dans la mini-fenêtre"},
            {"mini_window_show_tp_sell", "Afficher la vente TP (Listes)"},
            {"mini_window_show_tp_sell_tooltip", "Afficher le profit de vente TP (listes) dans la mini-fenêtre"},
            {"mini_window_show_tp_instant", "Afficher la vente instantanée TP"},
            {"mini_window_show_tp_instant_tooltip", "Afficher le profit de vente instantanée TP dans la mini-fenêtre"},
            {"mini_window_show_total_items", "Afficher le total des objets"},
            {"mini_window_show_total_items_tooltip", "Afficher le nombre total d'objets dans la mini-fenêtre"},
            {"mini_window_show_session_duration", "Afficher la durée de session"},
            {"mini_window_show_session_duration_tooltip", "Afficher la durée de session dans la mini-fenêtre"},
            {"mini_window_click_through", "Fenêtre cliquable"},
            {"mini_window_click_through_tooltip", "Permet de cliquer à travers la mini-fenêtre vers le jeu"},
            
            // Main Window
            {"main_window_label", "Fenêtre principale"},
            {"main_window_click_through", "Cliquable"},
            {"main_window_click_through_tooltip", "Permet de cliquer à travers la fenêtre principale vers le jeu"},
            
            // Settings Profiles
            {"settings_profiles", "Profils de paramètres"},
            {"default_no_profile", "Par défaut (Aucun profil)"},
            {"select_profile_tooltip", "Sélectionner un profil pour appliquer ses paramètres"},
            {"create", "Créer"},
            {"create_tooltip", "Créer un nouveau profil avec les paramètres actuels"},
            {"update_profile", "Mettre à jour le profil"},
            {"update_profile_tooltip", "Mettre à jour le profil actuel avec les paramètres actuels"},
            {"delete_profile", "Supprimer le profil"},
            {"delete_profile_tooltip", "Supprimer le profil actuel"},
            
            // Automatic Backups
            {"automatic_backups", "Sauvegardes automatiques"},
            {"enable_automatic_backups", "Activer les sauvegardes automatiques"},
            {"enable_automatic_backups_tooltip", "Créer automatiquement des sauvegardes avant les modifications"},
            {"backup_frequency", "Fréquence de sauvegarde"},
            {"backup_frequency_tooltip", "Fréquence de création des sauvegardes automatiques"},
            {"backup_manual_only", "Manuel uniquement"},
            {"backup_daily", "Quotidien"},
            {"backup_weekly", "Hebdomadaire"},
            {"max_backup_count", "Nombre max de sauvegardes"},
            {"max_backup_count_tooltip", "Nombre maximum de sauvegardes à conserver (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Paramètres de notification"},
            {"enable_notifications", "Activer les notifications"},
            {"enable_notifications_tooltip", "Activer les notifications en jeu"},
            {"profit_goal", "Objectif de profit"},
            {"notify_profit_goal", "Notifier lorsque l'objectif de profit est atteint"},
            {"notify_profit_goal_tooltip", "Notifier lorsque vous atteignez votre objectif de profit"},
            {"profit_goal_gold", "Objectif de profit (or)"},
            {"profit_goal_gold_tooltip", "Objectif de profit en pièces d'or (1-1000)"},
            {"reset_warning_label", "Avertissement de réinitialisation"},
            {"notify_reset_warning", "Notifier avant la réinitialisation"},
            {"notify_reset_warning_tooltip", "Notifier avant que la réinitialisation automatique ne se produise"},
            {"warning_minutes", "Minutes d'avertissement"},
            {"warning_minutes_tooltip", "Minutes avant la réinitialisation pour afficher l'avertissement (1-60)"},
            {"session_complete", "Session terminée"},
            {"notify_session_complete", "Notifier après la durée de session"},
            {"notify_session_complete_tooltip", "Notifier après avoir farmé pendant une certaine durée"},
            {"session_hours", "Heures de session"},
            {"session_hours_tooltip", "Heures de farming avant la notification (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Rechercher des devises..."},
            {"clear_search", "Effacer"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Rechercher des objets favoris..."},
            {"search_favorite_currencies_hint", "Rechercher des devises favorites..."},
            {"clear_search_favorites", "Effacer"},
        };
        return translations;
    }
}
