// ---------------------------------------------------------------------------
// localization_en.cpp – English translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetEnglishTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Disconnected"},
            {"status_connecting", "Connecting..."},
            {"status_connected", "Connected"},
            {"status_auth_failed", "Auth Failed – check token"},
            {"status_reconnecting", "Reconnecting..."},
            {"status_error", "Error"},
            {"status_unknown", "Unknown"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Profit"},
            {"profit_per_hour", "Profit/Hour"},
            {"tp_sell", "TP Sell"},
            {"tp_instant", "TP Instant Sell"},
            {"total_items", "Total Items"},
            {"session", "Session"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "GW2 API"},
            {"session_time_label", "Session Time"},
            {"reset_button", "Reset"},
            {"reset_tooltip", "Reset all farming counters (manual)"},

            // Tabs
            {"tab_summary", "Dashboard"},
            {"tab_drops", "Drops"},
            {"tab_loot_filter", "Loot Filter"},
            {"tab_dashboard", "Dashboard"},
            {"tab_items", "Items"},
            {"tab_currencies", "Currencies"},
            {"tab_favorites", "Favorites"},
            {"tab_ignored", "Ignored"},
            {"tab_timeline", "Timeline"},
            {"timeline_profit_hour_listings", "Approx. Trading Profits Per Hour (Listings)"},
            {"timeline_profit_hour_instant", "Approx. Trading Profits Per Hour (Instant Sell)"},
            {"timeline_no_drops", "No drops recorded in this session yet."},
            {"timeline_item_drops", "Item Drops"},
            {"timeline_currencies", "Currencies"},
            {"tab_filter", "Filter"},
            {"tab_custom_profit", "Custom Profit"},
            {"tab_debug", "Debug"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF not connected"},
            {"warning_drf_not_connected_desc", "This plugin requires DRF for data transmission."},
            {"warning_drf_install", "Install DRF via Nexus Addon Manager or https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ DRF Token invalid"},
            {"warning_drf_token_invalid_desc", "Please check your DRF Token in Settings."},
            {"warning_gw2_api_key_not_set", "⚠️ GW2 API Key not set"},
            {"warning_gw2_api_key_not_set_desc", "Please set your GW2 API Key in Settings for item details."},
            {"gold", "Gold"},
            {"silver", "Silver"},
            {"copper", "Copper"},
            {"total_profit", "Total Profit"},
            {"total_profit_tooltip", "Total custom profit from all items"},
            {"total_items_count", "Total Items"},
            {"total_items_tooltip", "Total number of unique items tracked"},
            {"total_currencies", "Total Currencies"},
            {"total_currencies_tooltip", "Total number of unique currencies"},
            {"profit_per_hour_label", "Profit Per Hour"},
            {"profit_per_hour_tooltip", "Profit per hour based on session duration"},
            {"magic_find", "Magic Find"},
            {"magic_find_tooltip", "Current or last recorded Magic Find from DRF"},
            {"session_duration", "Session Duration"},
            {"session_duration_tooltip", "Current farming session duration"},
            {"date_tooltip", "Session start time"},
            {"duration_tooltip", "Session duration"},
            {"profit_tooltip", "Total session profit"},
            {"profit_per_hour_tooltip", "Profit per hour"},
            {"drops_tooltip", "Number of drops"},
            {"best_drop_tooltip", "Most valuable drop of the session"},
            {"best_drop_single", "Best Drop (Single Value)"},
            {"best_drop_total", "Best Drop (Total Value)"},
            {"unit_value", "Unit Value"},
            {"total_value", "Total Value"},
            {"mini_window_show_best_drop_single", "Show Best Drop (Single Value)"},
            {"mini_window_show_best_drop_total", "Show Best Drop (Total Value)"},
            {"top_items_profit", "Top Items (Profit)"},
            {"top_items_profit_tooltip", "Top 5 items by profit value"},
            {"loading", "Loading..."},
            {"coin", "Coin"},
            {"top_items_count", "Top Items (Count)"},
            {"top_items_count_tooltip", "Top 5 items by count"},
            {"top_currencies", "Top Currencies"},
            {"top_currencies_tooltip", "Top 5 currencies by count"},
            {"quick_statistics", "Quick Statistics"},
            {"quick_statistics_tooltip", "Overview of farming statistics"},
            {"average_item_value", "Average Item Value"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Total Unique Items"},
            {"warning_no_data", "⚠️ No Data Loaded"},
            {"warning_no_data_desc", "Waiting for DRF data..."},
            {"export", "Export"},
            {"export_tooltip", "Export farming data to file"},
            {"export_json", "Export as JSON"},
            {"export_csv", "Export as CSV"},
            {"import_json", "Import from JSON"},

            // Items Tab
            {"search_hint", "Search items..."},
            {"clear", "Clear"},
            {"sort_count_high", "Sort: Count high"},
            {"sort_count_low", "Sort: Count low"},
            {"sort_id_up", "Sort: Item ID up"},
            {"sort_id_down", "Sort: Item ID down"},
            {"sort_name_az", "Sort: Name A–Z"},
            {"sort_tooltip", "Sort items by count, ID, or name"},
            {"rarity_all", "Rarity: all"},
            {"rarity_basic", "Rarity: Basic+"},
            {"rarity_fine", "Rarity: Fine+"},
            {"rarity_masterwork", "Rarity: Masterwork+"},
            {"rarity_rare", "Rarity: Rare+"},
            {"rarity_exotic", "Rarity: Exotic+"},
            {"rarity_ascended", "Rarity: Ascended+"},
            {"rarity_legendary", "Rarity: Legendary Only"},
            {"rarity_tooltip", "Filter items by minimum rarity"},
            {"rarity", "Rarity"},
            {"type", "Type"},
            {"vendor_value", "Vendor Value"},
            {"tp_buy_net", "TP Buy (Net)"},
            {"account_bound", "Account Bound"},
            {"yes", "Yes"},
            {"no", "No"},
            {"nosell", "NoSell"},
            {"favorite", "Favorite"},
            {"ignore", "Ignore"},

            // Currencies Tab
            {"search_currencies_hint", "Search currencies..."},
            {"api_id", "API ID"},
            {"currency_name", "Currency Name"},
            {"count", "Count"},

            // Profit Tab
            {"profits", "Profits"},
            {"profits_tooltip", "Total profits from farming"},
            {"approx_profits", "Approx. Profits"},
            {"approx_gold_per_hour", "Approx. Gold Per Hour"},
            {"trading_profits", "Trading Profits"},
            {"trading_profits_tooltip", "Profits from Trading Post"},
            {"approx_trading_profits_listings", "Approx. Trading Profits (Listings)"},
            {"approx_trading_profits_instant", "Approx. Trading Profits (Instant Sell)"},
            {"trading_details", "Trading Details (Opportunity Cost)"},
            {"trading_details_tooltip", "Opportunity cost when using items instead of selling"},
            {"lost_profit_vs_tp_sell", "Lost Profit (vs TP Sell)"},
            {"lost_profit_per_hour_vs_tp_sell", "Lost Profit Per Hour (vs TP Sell)"},
            {"efficiency_score", "Efficiency Score"},
            {"efficiency_score_label", "Efficiency Score:"},
            {"efficiency_score_tooltip", "How much of the maximum possible profit you achieved (Instant Sell vs. TP Listings)."},
            {"efficiency_score_desc", "You achieved %.1f%% of the maximum profit!"},
            {"session_duration_label", "Session Duration"},
            {"session_duration_tooltip", "Current farming session duration"},

            // Filter Tab
            {"sell_method_filters", "Sell Method Filters"},
            {"sellable_to_vendor", "Sellable to Vendor"},
            {"sellable_to_vendor_tooltip", "Show items that can be sold to vendors"},
            {"sellable_on_tp", "Sellable on TP"},
            {"sellable_on_tp_tooltip", "Show items that can be sold on the Trading Post"},
            {"has_custom_profit", "Has Custom Profit"},
            {"has_custom_profit_tooltip", "Show items with custom profit values"},
            {"api_knowledge_filters", "API Knowledge Filters"},
            {"known_by_api", "Known by API"},
            {"known_by_api_tooltip", "Show items known by the GW2 API"},
            {"unknown_by_api", "Unknown by API"},
            {"unknown_by_api_tooltip", "Show items not known by the GW2 API"},
            {"item_type_filters", "Item Type Filters"},
            {"type_armor", "Armor"},
            {"type_armor_tooltip", "Show armor items"},
            {"type_weapon", "Weapon"},
            {"type_weapon_tooltip", "Show weapon items"},
            {"type_trinket", "Trinket"},
            {"type_trinket_tooltip", "Show trinket items"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Show gizmo items"},
            {"type_crafting_material", "Crafting Material"},
            {"type_crafting_material_tooltip", "Show crafting materials"},
            {"type_consumable", "Consumable"},
            {"type_consumable_tooltip", "Show consumables"},
            {"type_gathering_tool", "Gathering Tool"},
            {"type_gathering_tool_tooltip", "Show gathering tools"},
            {"type_bag", "Bag"},
            {"type_bag_tooltip", "Show bags"},
            {"type_container", "Container"},
            {"type_container_tooltip", "Show containers"},
            {"type_mini_pet", "Mini Pet"},
            {"type_mini_pet_tooltip", "Show mini pets"},
            {"currency_filters_label", "Currency Filters"},
            {"currency_general", "General"},
            {"currency_main", "Main Currencies"},
            {"currency_fractal", "Fractal/Raid/Dungeon Currencies"},
            {"currency_wvw_pvp", "WvW/PvP Currencies"},
            {"currency_map", "Map-Specific Currencies"},
            {"filter_karma", "Karma"},
            {"currency_karma_tooltip", "Show Karma currency"},
            {"currency_laurel", "Laurel"},
            {"currency_laurel_tooltip", "Show Laurel currency"},
            {"currency_gem", "Gem"},
            {"currency_gem_tooltip", "Show Gem currency"},
            {"currency_fractal_relic", "Fractal Relic"},
            {"currency_fractal_relic_tooltip", "Show Fractal Relic currency"},
            {"currency_badge_of_honor", "Badge of Honor"},
            {"currency_badge_of_honor_tooltip", "Show Badge of Honor currency"},
            {"currency_guild_commendation", "Guild Commendation"},
            {"currency_guild_commendation_tooltip", "Show Guild Commendation currency"},
            {"currency_transmutation_charge", "Transmutation Charge"},
            {"currency_transmutation_charge_tooltip", "Show Transmutation Charge currency"},
            {"currency_spirit_shards", "Spirit Shards"},
            {"currency_spirit_shards_tooltip", "Show Spirit Shards currency"},
            {"currency_unbound_magic", "Unbound Magic"},
            {"currency_unbound_magic_tooltip", "Show Unbound Magic currency"},
            {"currency_volatile_magic", "Volatile Magic"},
            {"currency_volatile_magic_tooltip", "Show Volatile Magic currency"},
            {"currency_airship_parts", "Airship Parts"},
            {"currency_airship_parts_tooltip", "Show Airship Parts currency"},
            {"currency_geode", "Geode"},
            {"currency_geode_tooltip", "Show Geode currency"},
            {"currency_ley_line_crystals", "Ley-Line Crystals"},
            {"currency_ley_line_crystals_tooltip", "Show Ley-Line Crystals currency"},
            {"currency_trade_contracts", "Trade Contracts"},
            {"currency_trade_contracts_tooltip", "Show Trade Contracts currency"},
            {"currency_elegy_mosaic", "Elegy Mosaic"},
            {"currency_elegy_mosaic_tooltip", "Show Elegy Mosaic currency"},
            {"currency_uncommon_coins", "Uncommon Coins"},
            {"currency_uncommon_coins_tooltip", "Show Uncommon Coins currency"},
            {"currency_astral_acclaim", "Astral Acclaim"},
            {"currency_astral_acclaim_tooltip", "Show Astral Acclaim currency"},
            {"currency_pristine_fractal_relics", "Pristine Fractal Relics"},
            {"currency_pristine_fractal_relics_tooltip", "Show Pristine Fractal Relics currency"},
            {"currency_unstable_fractal_essence", "Unstable Fractal Essence"},
            {"currency_unstable_fractal_essence_tooltip", "Show Unstable Fractal Essence currency"},
            {"currency_magnetite_shards", "Magnetite Shards"},
            {"currency_magnetite_shards_tooltip", "Show Magnetite Shards currency"},
            {"currency_gaeting_crystals", "Gaeting Crystals"},
            {"currency_gaeting_crystals_tooltip", "Show Gaeting Crystals currency"},
            {"currency_prophet_shards", "Prophet Shards"},
            {"currency_prophet_shards_tooltip", "Show Prophet Shards currency"},
            {"currency_green_prophet_shards", "Green Prophet Shards"},
            {"currency_green_prophet_shards_tooltip", "Show Green Prophet Shards currency"},
            {"currency_wvw_skirmish_tickets", "WvW Skirmish Tickets"},
            {"currency_wvw_skirmish_tickets_tooltip", "Show WvW Skirmish Tickets currency"},
            {"currency_proofs_of_heroics", "Proofs of Heroics"},
            {"currency_proofs_of_heroics_tooltip", "Show Proofs of Heroics currency"},
            {"currency_pvp_league_tickets", "PvP League Tickets"},
            {"currency_pvp_league_tickets_tooltip", "Show PvP League Tickets currency"},
            {"currency_ascended_shards_of_glory", "Ascended Shards of Glory"},
            {"currency_ascended_shards_of_glory_tooltip", "Show Ascended Shards of Glory currency"},
            {"currency_research_notes", "Research Notes"},
            {"currency_research_notes_tooltip", "Show Research Notes currency"},
            {"currency_tyrian_defense_seal", "Tyrian Defense Seal"},
            {"currency_tyrian_defense_seal_tooltip", "Show Tyrian Defense Seal currency"},
            {"currency_testimony_of_desert_heroics", "Testimony of Desert Heroics"},
            {"currency_testimony_of_desert_heroics_tooltip", "Show Testimony of Desert Heroics currency"},
            {"currency_testimony_of_jade_heroics", "Testimony of Jade Heroics"},
            {"currency_testimony_of_jade_heroics_tooltip", "Show Testimony of Jade Heroics currency"},
            {"currency_testimony_of_castoran_heroics", "Testimony of Castoran Heroics"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Show Testimony of Castoran Heroics currency"},
            {"currency_legendary_insight", "Legendary Insight"},
            {"currency_legendary_insight_tooltip", "Show Legendary Insight currency"},
            {"currency_tales_of_dungeon_delving", "Tales of Dungeon Delving"},
            {"currency_tales_of_dungeon_delving_tooltip", "Show Tales of Dungeon Delving currency"},
            {"currency_imperial_favor", "Imperial Favor"},
            {"currency_imperial_favor_tooltip", "Show Imperial Favor currency"},
            {"currency_canach_coins", "Canach Coins"},
            {"currency_canach_coins_tooltip", "Show Canach Coins currency"},
            {"currency_ancient_coin", "Ancient Coin"},
            {"currency_ancient_coin_tooltip", "Show Ancient Coin currency"},
            {"currency_unusual_coin", "Unusual Coin"},
            {"currency_unusual_coin_tooltip", "Show Unusual Coin currency"},
            {"currency_jade_sliver", "Jade Sliver"},
            {"currency_jade_sliver_tooltip", "Show Jade Sliver currency"},
            {"currency_static_charge", "Static Charge"},
            {"currency_static_charge_tooltip", "Show Static Charge currency"},
            {"currency_pinch_of_stardust", "Pinch of Stardust"},
            {"currency_pinch_of_stardust_tooltip", "Show Pinch of Stardust currency"},
            {"currency_calcified_gasp", "Calcified Gasp"},
            {"currency_calcified_gasp_tooltip", "Show Calcified Gasp currency"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Show Ursus Oblige currency"},
            {"currency_gaeting_crystal_janthir", "Gaeting Crystal (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Show Gaeting Crystal (Janthir) currency"},
            {"currency_antiquated_ducat", "Antiquated Ducat"},
            {"currency_antiquated_ducat_tooltip", "Show Antiquated Ducat currency"},
            {"currency_aether_rich_sap", "Aether-Rich Sap"},
            {"currency_aether_rich_sap_tooltip", "Show Aether-Rich Sap currency"},

            // Additional Filters
            {"additional_filters", "Additional Filters"},
            {"account_bound", "Account Bound"},
            {"account_bound_tooltip", "Show account-bound items"},
            {"not_account_bound", "Not Account Bound"},
            {"not_account_bound_tooltip", "Show non-account-bound items"},
            {"nosell_items", "NoSell"},
            {"nosell_items_tooltip", "Show NoSell items"},
            {"not_nosell", "Sellable"},
            {"not_nosell_tooltip", "Show sellable items"},
            {"favorite_items", "Favorite"},
            {"favorite_items_tooltip", "Show favorite items"},
            {"not_favorite", "Not Favorite"},
            {"not_favorite_tooltip", "Show non-favorite items"},
            {"ignored_items", "Ignored"},
            {"ignored_items_tooltip", "Show ignored items"},
            {"not_ignored", "Not Ignored"},
            {"not_ignored_tooltip", "Show non-ignored items"},

            // Range Filters
            {"range_filters", "Range Filters"},
            {"show_range_filters", "Show Range Filters"},
            {"filter_min_price", "Filter Min Price"},
            {"filter_max_price", "Filter Max Price"},
            {"filter_min_quantity", "Filter Min Quantity"},
            {"filter_max_quantity", "Filter Max Quantity"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Window"},
            {"show_profit", "Show Profit"},
            {"show_profit_tooltip", "Show total profit in mini window"},
            {"show_profit_per_hour", "Show Profit/Hour"},
            {"show_profit_per_hour_tooltip", "Show profit per hour in mini window"},
            {"show_tp_sell", "Show TP Sell (Listings)"},
            {"show_tp_sell_tooltip", "Show TP sell profit (listings) in mini window"},
            {"show_tp_instant", "Show TP Instant Sell"},
            {"show_tp_instant_tooltip", "Show TP instant sell profit in mini window"},
            {"show_total_items", "Show Total Items"},
            {"show_total_items_tooltip", "Show total item count in mini window"},
            {"show_session_duration", "Show Session Duration"},
            {"show_session_duration_tooltip", "Show session duration in mini window"},
            {"window_click_through", "Window Click-Through"},
            {"window_click_through_tooltip", "Allow clicking through mini window to game"},

            // Main Window Settings
            {"main_window", "Main Window"},
            {"click_through", "Click-Through"},
            {"click_through_tooltip", "Allow clicking through main window to game"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Advanced UI Settings"},
            {"no_advanced_ui_settings", "(No advanced UI settings available)"},

            // Display Settings
            {"display_settings", "Display Settings"},
            {"show_item_icons", "Show Item Icons"},
            {"show_item_icons_tooltip", "Show item icons in the list"},
            {"show_rarity_borders", "Show Rarity Borders"},
            {"show_rarity_borders_tooltip", "Show colored borders around icons based on rarity"},
            {"enable_grid_view", "Enable Grid View"},
            {"enable_grid_view_tooltip", "Display items in grid layout instead of list"},
            {"grid_icon_size", "Grid Icon Size"},
            {"grid_icon_size_tooltip", "Size of icons in grid view"},

            // Count Display Settings
            {"count_display_settings", "Count Display Settings"},
            {"count_text_color", "Count Text Color"},
            {"count_text_color_tooltip", "Color of the count text"},
            {"count_background_color", "Count Background Color"},
            {"count_background_color_tooltip", "Color of the count background"},
            {"count_font_size", "Count Font Size"},
            {"count_font_size_tooltip", "Size of the count font"},
            {"count_horizontal_alignment", "Count Horizontal Alignment"},
            {"count_horizontal_alignment_tooltip", "Horizontal alignment of the count text"},

            // Gradient Background Settings
            {"gradient_background_settings", "Gradient Background Settings"},
            {"enable_gradient_backgrounds", "Enable Gradient Backgrounds"},
            {"enable_gradient_backgrounds_tooltip", "Enable gradient background for windows"},
            {"gradient_top_color", "Gradient Top Color"},
            {"gradient_top_color_tooltip", "Top color of gradient background"},
            {"gradient_bottom_color", "Gradient Bottom Color"},
            {"gradient_bottom_color_tooltip", "Bottom color of gradient background"},

            // Custom Profit System
            {"custom_profit_system", "Custom Profit System"},
            {"enable_custom_profit", "Enable Custom Profit"},
            {"enable_custom_profit_tooltip", "Enable custom profit values for items"},

            // Search
            {"search_settings", "Search"},
            {"enable_search", "Enable Search"},
            {"enable_search_tooltip", "Enable search functionality"},

            // Ignored Items
            {"ignored_items_settings", "Ignored Items"},
            {"enable_ignored_items", "Enable Ignored Items"},
            {"enable_ignored_items_tooltip", "Enable ignored items functionality"},

            // Auto Reset
            {"auto_reset_settings", "Auto Reset"},
            {"enable_auto_reset", "Enable Auto Reset"},
            {"enable_auto_reset_tooltip", "Automatically reset farming session after a duration"},
            {"auto_reset_duration", "Auto Reset Duration (Minutes)"},
            {"auto_reset_duration_tooltip", "Duration in minutes before auto reset"},

            // DRF Settings
            {"drf_settings", "DRF Settings"},
            {"drf_token", "DRF Token"},
            {"drf_token_label", "DRF Token:"},
            {"drf_token_tooltip", "Your DRF authentication token"},
            {"edit_token", "Edit Token"},
            {"save_token", "Save Token"},

            // GW2 API Settings
            {"gw2_api_settings", "GW2 API Settings"},
            {"gw2_api_key", "GW2 API Key"},
            {"gw2_api_key_tooltip", "Your GW2 API Key for item details"},
            {"edit_key", "Edit Key"},
            {"save_key", "Save Key"},

            // Language Settings
            {"language_settings", "Language"},
            {"language_tooltip", "Select UI language"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "No accounts configured"},
            {"no_profiles_created", "No profiles created yet"},
            {"count_label", "Count:"},
            {"profit_label", "Profit:"},
            {"no_profit", "No Profit"},
            {"vendor_value_label", "Vendor Value:"},
            {"tp_sell_gross_label", "TP Sell (Gross):"},
            {"tp_sell_net_label", "TP Sell (Net):"},
            {"tp_buy_gross_label", "TP Buy (Gross):"},
            {"tp_buy_net_label", "TP Buy (Net):"},
            {"ignored_items_label", "Ignored Items:"},
            {"ignored_currencies_label", "Ignored Currencies:"},
            {"total_items_label", "Total Items:"},
            {"total_currencies_label", "Total Currencies:"},
            {"total_profit_label", "Total Profit:"},
            {"tp_sell_profit_label", "TP Sell Profit:"},
            {"tp_sell_profit_tooltip", "Total profit if all items were sold at current TP listing prices (minus 15% fee)"},
            {"vendor_profit_label", "Vendor Sell Profit:"},
            {"profit_per_hour_label", "Profit Per Hour:"},
            {"opportunity_cost_profit_label", "Opportunity Cost Profit:"},
            {"opportunity_cost_profit_per_hour_label", "Opportunity Cost Profit/Hour:"},
            {"custom_profit_feature_placeholder", "Feature implemented - UI to follow"},
            {"custom_profit_items_header", "Items with Custom Profit"},
            {"custom_profit_currencies_header", "Currencies with Custom Profit"},
            {"add_custom_profit_item", "Add Custom Profit for Item"},
            {"add_custom_profit_currency", "Add Custom Profit for Currency"},
            {"custom_profit_set_profit", "Set Profit"},
            {"custom_profit_remove", "Remove"},
            {"custom_profit_value", "Profit Value (Copper)"},
            {"custom_profit_set_tooltip", "Set custom profit value for this item"},
            {"custom_profit_remove_tooltip", "Remove custom profit value for this item"},
            {"no_custom_profit_items", "(No items with custom profit)"},
            {"no_custom_profit_currencies", "(No currencies with custom profit)"},
            {"clear_all_custom_profits", "Clear All Custom Profits"},
            {"clear_all_custom_profits_tooltip", "Clear all custom profit values"},
            {"tabs_settings", "Other Tabs"},
            {"tabs_description", "Show and hide other tabs"},
            {"tab_settings", "Tab Settings"},
            {"tab_settings_description", "Tab ordering and behavior"},
            {"enable_dashboard_tab", "Enable Dashboard Tab"},
            {"enable_dashboard_tab_tooltip", "Show the Dashboard tab"},
            {"enable_items_tab", "Enable Items Tab"},
            {"enable_items_tab_tooltip", "Show the Items tab"},
            {"enable_currencies_tab", "Enable Currencies Tab"},
            {"enable_currencies_tab_tooltip", "Show the Currencies tab"},
            {"enable_ignored_tab", "Enable Ignored Tab"},
            {"enable_ignored_tab_tooltip", "Show the tab for ignored items"},
            {"enable_session_history_tab", "Enable Session History Tab"},
            {"enable_session_history_tab_tooltip", "Show the Session History tab"},
            {"enable_timeline_tab", "Enable Timeline Tab"},
            {"enable_timeline_tab_tooltip", "Show the Timeline tab with detailed drop history"},
            {"enable_loot_log_tab", "Enable Loot Log Tab"},
            {"enable_loot_log_tab_tooltip", "Show the Loot Log tab"},
            {"enable_filter_tab", "Enable Filter Tab"},
            {"enable_filter_tab_tooltip", "Show the Filter tab"},
            {"lock_tab_order", "Lock Tab Order"},
            {"lock_tab_order_tooltip", "Disable reordering of tabs in the main window"},
            {"enable_summaries_tab", "Enable Summaries Tab"},
            {"enable_summaries_tab_tooltip", "Show the daily/weekly/monthly summaries tab in session history"},
            {"custom_profit_settings", "Custom Profit"},
            {"total_profit_label_simple", "Total Profit"},
            {"total_items_label_simple", "Total Items"},
            {"total_currencies_label_simple", "Total Currencies"},
            {"profit_per_hour_label_simple", "Profit Per Hour"},
            {"session_duration_label_simple", "Session Duration"},
            {"next_reset_label_simple", "Next Reset"},
            {"export_label", "Export:"},
            {"quick_actions", "Quick Actions:"},
            {"reset_confirm", "Are you sure you want to reset all settings to defaults?"},
            {"reset_warning", "This action cannot be undone."},
            {"hotkeys", "Hotkeys"},
            {"mini_window_toggle_hotkey", "Mini Window Toggle Hotkey"},
            {"backup_restore", "Backup & Restore"},
            {"appearance_settings", "Appearance"},
            {"enable_tooltips", "Enable Tooltips"},
            {"enable_tooltips_tooltip", "Show tooltips when hovering over UI elements"},
            {"enable_grid_view_tooltip", "Display items in a grid layout instead of a list"},
            {"favorites_first_tooltip", "Show favorited items at the top of the list"},
            {"group_by_rarity_tooltip", "Group items by their rarity"},
            {"show_rarity_as_tabs_tooltip", "Show each rarity as a separate tab"},
            {"group_by_category_tooltip", "Group items by their category"},
            {"show_group_as_tabs_tooltip", "Show each category as a separate tab"},
            {"mass_ignore_rarity_tooltip", "Ignore all items of this rarity"},
            {"icons_borders", "Icons & Borders"},
            {"colors_gradients", "Colors & Gradients"},
            {"window_opacity", "Window Transparency"},
            {"windows_settings", "Windows"},
            {"advanced_settings", "Advanced"},
            {"export_settings", "Export settings to file:"},
            {"import_settings", "Import settings from file:"},
            {"edit_account", "Edit account: %s"},
            {"account_name", "Account Name:"},
            {"gw2_api_key_label", "GW2 API Key:"},
            {"reload_config", "Reload Configuration:"},
            {"auto_reset_label", "Auto Reset:"},
            {"next_reset_utc", "Next scheduled reset (UTC): %s"},
            {"favorites_ui", "Favorites UI:"},
            {"favorites_colors", "Favorites Colors:"},
            {"visual_enhancements", "Visual Enhancements:"},
            {"show_profit_sparkline", "Show Profit Sparkline"},
            {"show_profit_sparkline_tooltip", "Display a small line chart showing profit per hour trend"},
            {"mini_window_widget", "Mini Window (Overlay Widget):"},
            {"main_window_label", "Main Window:"},
            {"profiles_description", "Profiles allow you to save different configurations and switch between them quickly."},
            {"create_new_profile", "Create New Profile:"},
            {"current_profile", "Current Profile: %s"},
            {"auto_backup", "Automatically backup your settings before major changes"},
            {"notifications", "Configure in-game notifications for important events"},
            {"profit_goal", "Profit Goal:"},
            {"reset_warning_label", "Reset Warning:"},
            {"session_complete", "Session Complete:"},
            {"manage_ignored_items", "Manage ignored items"},
            {"manage_ignored_currencies", "Manage ignored currencies"},
            {"rarity_label", "Rarity: %s"},
            {"type_label", "Type: %d"},
            {"account_bound_label", "Account Bound: %s"},
            {"nosell_label", "NoSell: %s"},
            {"item_id_label", "Item ID: %d"},
            {"currency_id_label", "Currency ID: %d"},
            {"context_menu_add_favorites", "Add to Favorites"},
            {"context_menu_remove_favorites", "Remove from Favorites"},
            {"context_menu_ignore", "Ignore Item"},
            {"context_menu_unignore", "Unignore Item"},
            {"context_menu_copy_name", "Copy Name"},
            {"context_menu_copy_id", "Copy ID"},
            {"rarity_tooltip", "Filter items by minimum rarity"},
            {"api_knowledge_filters_label", "API Knowledge Filters:"},
            {"additional_filters_label", "Additional Filters:"},
            {"item_type_filters_label", "Item Type Filters:"},
            {"currency_filters_label", "Currency Filters:"},
            {"price_range", "Price Range (Copper):"},
            {"quantity_range", "Quantity Range:"},
            {"debug_info", "Debug Information"},
            {"drf_status", "DRF Status: %s"},
            {"drf_reconnect_count", "DRF Reconnect Count: %d"},
            {"gw2_api_status", "GW2 API Status: %s"},
            {"gw2_api_reconnect_count", "GW2 API Reconnect Count: %d"},
            {"session_duration_debug", "Session Duration"},
            {"gw2_memory", "GW2 Process Memory: %zu MB"},
            {"gw2_api_request_count", "GW2 API Request Count: %d"},
            {"ignored_items_count", "Ignored Items: %d"},
            {"ignored_currencies_count", "Ignored Currencies: %d"},
            {"drf_logs", "DRF Logs:"},
            {"last_100_entries", "(Last 100 entries)"},
            {"gw2_api_logs", "GW2 API Logs:"},
            {"item_currency_details", "Item/Currency Details (First 5):"},
            {"item_label", "Item %d: %s (Count: "},
            {"loaded_label", ", Loaded: %s)"},
            {"currency_label", "Currency %d: %s (Count: "},
            {"custom_profit_items", "Items with Custom Profit (First 5):"},
            {"custom_profit_item", "Item %d: %s (Custom Profit: "},
            {"no_custom_profit_items", "(No items with custom profit)"},
            {"ignored_items_debug", "Ignored Items (First 5):"},
            {"yes_label", "Yes"},
            {"no_label", "No"},
            {"profits_label", "Profits:"},
            {"profits_tooltip", "Total profit from farming"},
            {"approx_profits_label", "Approx. Profits:"},
            {"approx_profits_tooltip", "Total profit from MAX(Vendor, TP Sell with 15% fee) or Custom Profit"},
            {"approx_gold_per_hour_label", "Approx. Gold/Hour:"},
            {"approx_gold_per_hour_tooltip", "Profit per hour based on session duration"},
            {"trading_profits_label", "Trading Profits:"},
            {"trading_profits_tooltip", "Profits from selling on Trading Post"},
            {"approx_trading_profits_listings_label", "Approx. Trading Profit (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Total if sold via TP Listings (15% fee deducted)"},
            {"approx_trading_profits_instant_label", "Approx. Trading Profit (Instant Sell):"},
            {"approx_trading_profits_instant_tooltip", "Total if sold via TP Instant Buy Orders (15% fee deducted)"},
            {"trading_details_label", "Trading Details (Opportunity Cost):"},
            {"trading_details_tooltip", "Lost profit from not selling via TP Listings"},
            {"lost_profit_vs_tp_sell_label", "Lost Profit (vs TP Sell):"},
            {"lost_profit_vs_tp_sell_tooltip", "Opportunity cost: profit lost by not selling via TP (with 15% fee)"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Lost Profit/Hour (vs TP Sell):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Opportunity cost per hour"},
            {"session_duration_debug_label", "Session Duration: %s"},
            {"session_duration_debug_tooltip", "Current farming session duration"},
            {"tab_items", "Items"},
            {"manage_ignored_items", "Manage ignored items"},
            {"clear_all_ignored_items", "Clear all ignored items"},
            {"unignore_item", "Unignore item"},
            {"manage_favorite_items", "Manage favorite items"},
            {"favorite_items_label", "Favorite Items:"},
            {"clear_all_favorite_items", "Clear all favorite items"},
            {"tab_currencies", "Currencies"},
            {"manage_ignored_currencies", "Manage ignored currencies"},
            {"clear_all_ignored_currencies", "Clear all ignored currencies"},
            {"unignore_currency", "Unignore currency"},
            {"manage_favorite_currencies", "Manage favorite currencies"},
            {"favorite_currencies_label", "Favorite Currencies:"},
            {"clear_all_favorite_currencies", "Clear all favorite currencies"},
            {"filter_active",   "Active"},
            {"filter_inactive", "Inactive"},
            {"filter_all", "All"},
            {"filter_none", "None"},
            {"filter_reset_all", "Reset All"},
            {"filter_search_hint", "Search filter..."},
            {"filter_active_count", "%d filters active"},
            {"sell_method_filters_label", "Sell Method Filters:"},
            {"api_knowledge_filters_label", "API Knowledge Filters:"},
            {"additional_filters_label", "Additional Filters:"},
            {"item_type_filters_label", "Item Type Filters:"},
            {"currency_filters_label", "Currency Filters:"},
            {"price_range", "Price Range (Copper):"},
            {"quantity_range", "Quantity Range:"},
            {"debug_connection_status", "Connection Status"},
            {"debug_session_snapshot", "Session Snapshot"},
            {"debug_profit_breakdown", "Profit Breakdown"},
            {"debug_data_state", "Data State"},
            {"debug_logs", "Logs"},
            {"debug_favorites", "Favorites"},
            {"debug_total_session", "total this session"},
            {"debug_after_tp_fee", "after 15% fee"},
            {"debug_direct_sell", "direct sell"},
            {"debug_rolling_avg", "rolling average"},
            {"debug_vs_tp_sell", "vs TP sell"},
            {"debug_per_hour", "per hour"},
            {"settings_api_key", "API Key"},
            {"settings_drf_token", "DRF Token"},
            {"debug_information", "Debug Information"},
            {"drf_status_label", "DRF Status: %s"},
            {"drf_status_tooltip", "Current DRF connection status"},
            {"drf_reconnect_count_label", "DRF Reconnect Count: %d"},
            {"drf_reconnect_count_tooltip", "Number of DRF reconnection attempts"},
            {"gw2_api_status_label", "GW2 API Status: %s"},
            {"gw2_api_status_tooltip", "Current GW2 API connection status"},
            {"gw2_api_reconnect_count_label", "GW2 API Reconnect Count: %d"},
            {"gw2_api_reconnect_count_tooltip", "Number of GW2 API reconnection attempts"},
            {"session_duration_debug", "Session Duration"},
            {"session_duration_debug_tooltip", "Current farming session duration"},
            {"gw2_process_memory_label", "GW2 Process Memory"},
            {"gw2_process_memory_tooltip", "Current GW2 process memory usage"},
            {"gw2_api_request_count_label", "GW2 API Request Count"},
            {"gw2_api_request_count_tooltip", "Total number of GW2 API requests made"},
            {"ignored_items_debug_label", "Ignored Items: %d"},
            {"ignored_items_debug_tooltip", "Number of ignored items"},
            {"ignored_currencies_debug_label", "Ignored Currencies: %d"},
            {"ignored_currencies_debug_tooltip", "Number of ignored currencies"},
            {"drf_logs_label", "DRF Logs:"},
            {"clear_drf_logs", "Clear DRF Logs"},
            {"clear_drf_logs_tooltip", "Clear all DRF log entries"},
            {"last_100_entries", "(Last 100 entries)"},
            {"gw2_api_logs_label", "GW2 API Logs:"},
            {"clear_gw2_logs", "Clear GW2 Logs"},
            {"clear_gw2_logs_tooltip", "Clear all GW2 API log entries"},
            {"settings_label", "Settings:"},
            {"api_key_tooltip", "GW2 API Key Status"},
            {"not_set", "Not set"},
            {"set", "Set"},
            {"drf_token_tooltip", "DRF Token Status"},
            {"toggle_hotkey_label", "Toggle Hotkey: %s"},
            {"toggle_hotkey_tooltip", "Hotkey for main window toggle"},
            {"auto_reset_mode_label", "Auto Reset Mode: %d"},
            {"auto_reset_mode_tooltip", "Current auto reset mode"},
            {"next_reset_label", "Next Reset: %s"},
            {"next_reset_tooltip", "Next scheduled reset time (UTC)"},
            {"fake_drf_server_label", "Fake DRF Server:"},
            {"use_fake_drf_server", "Use fake DRF server"},
            {"use_fake_drf_server_tooltip", "For testing purposes only"},
            {"reset_all_data", "Reset All Data"},
            {"reset_all_data_tooltip", "Reset all farming data"},
            {"coin", "Coin"},
            {"info_button", "Info"},
            {"info_title", "Farming Tracker Info"},
            {"info_text", "Help text will be added here later..."},
            {"close_button", "Close"},
            {"rarity_label", "Rarity: %s"},
            {"type_label", "Type: %d"},
            {"account_bound_label", "Account Bound: %s"},
            {"nosell_label", "NoSell: %s"},
            {"yes_label", "Yes"},
            {"no_label", "No"},
            {"sort_price_down", "Sort: Item Price down"},
            {"sort_price_up", "Sort: Item Price up"},
            {"sort_count_high", "Sort: Count high"},
            {"sort_count_low", "Sort: Count low"},
            {"sort_name_az", "Sort: Name A–Z"},
            {"sort_name_za", "Sort: Name Z–A"},
            {"sort_profit_high", "Sort: Profit high"},
            {"sort_profit_low", "Sort: Profit low"},
            {"sort_rarity_high", "Sort: Rarity high to low"},
            {"sort_rarity_low", "Sort: Rarity low to high"},
            {"sort_tooltip", "Sort items by count, ID, or name"},
            {"group_by_rarity", "Group by Rarity"},
            {"group_by_type", "Group by Category"},
            {"show_type_as_tabs", "Show as Tabs"},
            {"show_rarity_as_tabs", "Show as Tabs"},
            {"enable_favorites", "Enable Favorites"},
            {"rarity_name_basic", "Basic"},
            {"rarity_name_fine", "Fine"},
            {"rarity_name_masterwork", "Masterwork"},
            {"rarity_name_rare", "Rare"},
            {"rarity_name_exotic", "Exotic"},
            {"rarity_name_ascended", "Ascended"},
            {"rarity_name_legendary", "Legendary"},
            {"rarity_name_junk", "Junk"},
            {"rarity_name_unknown", "Unknown"},
            {"main_window_opacity", "Main Window Transparency"},
            {"main_window_opacity_tooltip", "Main window background transparency (0-100%)"},
            {"mini_window_opacity", "Mini Window Transparency"},
            {"mini_window_opacity_tooltip", "Mini window background transparency (0-100%)"},
            {"accent_color", "Accent Color (Buttons, Tabs, UI)"},
            {"accent_color_tooltip", "Accent color for buttons, tabs, and UI elements"},
            {"stat_total_profit", "Total Profit"},
            {"stat_avg_profit_per_hour", "Avg Profit/h"},
            {"stat_best_session", "Best Session"},
            {"stat_total_time", "Total Time"},
            {"session_profit_trend", "Profit Trend"},
            {"session_note", "Note"},
            {"session_search_hint", "Search sessions, items, notes..."},
            {"showing", "Showing"},
            {"sessions_selected", "sessions selected"},
            {"clear_compare_selection", "Clear selection"},
            {"session_history", "Session History"},
            {"tab_sessions", "Sessions"},
            {"tab_summaries", "Summaries"},
            {"summaries_coming_soon", "Summaries feature coming soon..."},
            {"summaries_label", "Summaries"},
            {"summaries_tooltip", "Daily/Weekly/Monthly profit summaries"},
            {"show_summaries", "Show Summaries"},
            {"show_summaries_tooltip", "Show daily/weekly/monthly profit summaries"},
            {"best_drop", "Best Drop"},
            {"best_drop_tooltip", "Most valuable drop of the current session"},
            {"enable_best_drop_highlight", "Highlight Best Drop"},
            {"enable_best_drop_highlight_tooltip", "Highlight the most valuable drop with a golden border in the Items tab"},
            {"enable_best_drop_in_mini_window", "Show Best Drop in Mini Window"},
            {"enable_best_drop_in_mini_window_tooltip", "Show the most valuable drop in the mini window overlay"},
            {"export_history", "Export History"},
            {"export_history_tooltip", "Export session history to a JSON file"},
            {"import_history", "Import History"},
            {"import_history_tooltip", "Import session history from a JSON file"},
            {"full_backup", "Full Backup"},
            {"full_backup_tooltip", "Backup all data (settings, session history, favorites, ignored items, custom profit) to a JSON file"},
            {"full_restore", "Full Restore"},
            {"full_restore_tooltip", "Restore all data from a backup JSON file"},
            {"backup", "Backup"},
            {"restore", "Restore"},
            {"summary_period", "Period:"},
            {"summary_today", "Today"},
            {"summary_this_week", "This Week"},
            {"summary_this_month", "This Month"},
            {"total_profit", "Total Profit"},
            {"profit_per_hour", "Profit/Hour"},
            {"total_drops", "Total Drops"},
            {"total_time", "Total Time"},
            {"best_drop", "Best Drop"},
            {"average_profit_per_hour", "Avg Profit/h"},
            {"sessions_count", "Sessions"},
            {"export_history", "Export History"},
            {"import_history", "Import History"},
            {"settings_profiles", "Settings Profiles"},
            {"automatic_backups", "Automatic Backups"},
            {"enable_automatic_backups", "Enable automatic backups"},
            {"enable_automatic_backups_tooltip", "Automatically create backups before changes"},
            {"backup_frequency", "Backup frequency"},
            {"backup_frequency_tooltip", "How often to create automatic backups"},
            {"backup_manual_only", "Manual only"},
            {"backup_path", "Backup path"},
            {"backup_path_tooltip", "Directory where backups are stored"},
            {"backup_path_default", "Default: addon directory"},
            {"backup_path_default_tooltip", "Default: addon directory"},
            {"disable_complex_visuals", "Disable Complex Visuals on Low Performance"},
            {"disable_complex_visuals_tooltip", "Disables rarity borders, sparklines and other visual effects to improve performance"},
            {"top_gradient_color", "Top gradient color"},
            {"top_gradient_color_tooltip", "Top gradient color"},
            {"bottom_gradient_color", "Bottom gradient color"},
            {"bottom_gradient_color_tooltip", "Bottom gradient color"},
            {"enable_grid_view_items", "Enable Grid View (Items)"},
            {"enable_grid_view_items_tooltip", "Toggle between list and grid view in Items tab"},
            {"show_mini_window", "Show mini window"},
            {"show_mini_window_tooltip", "Shows a small overlay widget with key statistics"},
            {"enable_favorites_tab", "Enable Favorites Tab"},
            {"enable_favorites_tab_tooltip", "Shows a separate favorites tab"},
            {"filter_min_quantity_tooltip", "Minimum quantity filter (0 = disabled)"},
            {"filter_max_quantity_tooltip", "Maximum quantity filter (0 = disabled)"},
            {"filter_min_price_tooltip", "Minimum price filter (0 = disabled)"},
            {"filter_max_price_tooltip", "Maximum price filter (0 = disabled)"}
        };
        return translations;
    }
}
