// ---------------------------------------------------------------------------
// localization_ru.cpp – Russian translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetRussianTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Отключено"},
            {"status_connecting", "Подключение..."},
            {"status_connected", "Подключено"},
            {"status_auth_failed", "Ошибка аутентификации – проверьте токен"},
            {"status_reconnecting", "Переподключение..."},
            {"status_error", "Ошибка"},
            {"status_unknown", "Неизвестно"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Прибыль"},
            {"profit_per_hour", "Прибыль/Час"},
            {"tp_sell", "Продажа TP"},
            {"tp_instant", "Мгновенная Продажа TP"},
            {"total_items", "Всего Предметов"},
            {"session", "Сессия"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "API GW2"},
            {"session_time_label", "Время Сессии"},
            {"reset_button", "Сбросить"},
            {"reset_tooltip", "Сбросить все счётчики фарминга (ручной сброс)"},

            // Tabs
            {"tab_summary", "Обзор"},
            {"tab_items", "Предметы"},
            {"tab_currencies", "Валюты"},
            {"tab_profit", "Прибыль"},
            {"tab_favorites", "Избранное"},
            {"tab_ignored", "Игнорируемые"},
            {"tab_filter", "Фильтр"},
            {"tab_custom_profit", "Пользовательская Прибыль"},
            {"tab_debug", "Отладка"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF не подключён"},
            {"warning_drf_not_connected_desc", "Этот плагин требует DRF для передачи данных."},
            {"warning_drf_install", "Установите DRF через Nexus Addon Manager или https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ Неверный токен DRF"},
            {"warning_drf_token_invalid_desc", "Пожалуйста, проверьте ваш токен DRF в настройках."},
            {"warning_gw2_api_key_not_set", "⚠️ Ключ API GW2 не установлен"},
            {"warning_gw2_api_key_not_set_desc", "Пожалуйста, установите ваш ключ API GW2 в настройках для деталей предметов."},
            {"overview", "Обзор"},
            {"overview_tooltip", "Обзор текущей сессии фарминга"},
            {"total_profit", "Общая Прибыль"},
            {"total_profit_tooltip", "Общая пользовательская прибыль от всех предметов"},
            {"total_items_count", "Всего Предметов"},
            {"total_items_tooltip", "Общее количество уникальных отслеживаемых предметов"},
            {"total_currencies", "Всего Валют"},
            {"total_currencies_tooltip", "Общее количество уникальных отслеживаемых валют"},
            {"profit_per_hour_label", "Прибыль За Час"},
            {"profit_per_hour_tooltip", "Прибыль за час на основе длительности сессии"},
            {"session_duration", "Длительность Сессии"},
            {"session_duration_tooltip", "Длительность текущей сессии фарминга"},
            {"top_items_profit", "Топ Предметы (Прибыль)"},
            {"top_items_profit_tooltip", "Топ 5 предметов по значению прибыли"},
            {"loading", "Загрузка..."},
            {"coin", "Монета"},
            {"top_items_count", "Топ Предметы (Количество)"},
            {"top_items_count_tooltip", "Топ 5 предметов по количеству"},
            {"top_currencies", "Топ Валюты"},
            {"top_currencies_tooltip", "Топ 5 валют по количеству"},
            {"quick_statistics", "Быстрая Статистика"},
            {"quick_statistics_tooltip", "Обзор статистики фарминга"},
            {"average_item_value", "Средняя Стоимость Предмета"},
            {"average_item_value_na", "Н/Д"},
            {"total_unique_items", "Всего Уникальных Предметов"},
            {"warning_no_data", "⚠️ Данные не загружены"},
            {"warning_no_data_desc", "Ожидание данных DRF..."},
            {"export", "Экспорт"},
            {"export_tooltip", "Экспорт данных фарминга в файл"},
            {"export_json", "Экспорт как JSON"},
            {"export_csv", "Экспорт как CSV"},

            // Items Tab
            {"search_hint", "Поиск предметов..."},
            {"clear", "Очистить"},
            {"sort_count_high", "Сортировка: |Кол-во| высокое"},
            {"sort_count_low", "Сортировка: |Кол-во| низкое"},
            {"sort_id_up", "Сортировка: ID Предмета высокое"},
            {"sort_id_down", "Сортировка: ID Предмета низкое"},
            {"sort_name_az", "Сортировка: Название А–Я"},
            {"sort_tooltip", "Сортировать предметы по количеству, ID или названию"},
            {"rarity_all", "Редкость: все"},
            {"rarity_basic", "Редкость: Базовая+"},
            {"rarity_fine", "Редкость: Хороший+"},
            {"rarity_masterwork", "Редкость: Шедевр+"},
            {"rarity_rare", "Редкость: Редкий+"},
            {"rarity_exotic", "Редкость: Экзотический+"},
            {"rarity_ascended", "Редкость: Вознесённый+"},
            {"rarity_legendary", "Редкость: Только Легендарный"},
            {"rarity_tooltip", "Фильтровать предметы по минимальной редкости"},
            {"rarity", "Редкость"},
            {"type", "Тип"},
            {"vendor_value", "Стоимость Продавца"},
            {"tp_buy_net", "Покупка TP (Чистая)"},
            {"account_bound", "Привязан к Аккаунту"},
            {"yes", "Да"},
            {"no", "Нет"},
            {"nosell", "Не для продажи"},
            {"favorite", "Избранное"},
            {"ignore", "Игнорировать"},

            // Currencies Tab
            {"search_currencies_hint", "Поиск валют..."},
            {"api_id", "ID API"},
            {"currency_name", "Название Валюты"},
            {"count", "Количество"},

            // Profit Tab
            {"profits", "Прибыли"},
            {"profits_tooltip", "Общая прибыль от фарминга"},
            {"approx_profits", "Прибл. Прибыли"},
            {"approx_gold_per_hour", "Прибл. Золота За Час"},
            {"trading_profits", "Торговые Прибыли"},
            {"trading_profits_tooltip", "Прибыли от Торгового Поста"},
            {"approx_trading_profits_listings", "Прибл. Торговые Прибыли (Листинги)"},
            {"approx_trading_profits_instant", "Прибл. Торговые Прибыли (Мгновенная Продажа)"},
            {"trading_details", "Детали Торговли (Альтернативные Издержки)"},
            {"trading_details_tooltip", "Альтернативные издержки использования предметов вместо продажи"},
            {"lost_profit_vs_tp_sell", "Потерянная Прибыль (vs Продажа TP)"},
            {"lost_profit_per_hour_vs_tp_sell", "Потерянная Прибыль За Час (vs Продажа TP)"},
            {"session_duration_label", "Длительность сессии"},
            {"session_duration_tooltip", "Длительность текущей сессии фарминга"},

            // Filter Tab
            {"sell_method_filters", "Фильтры Метода Продажи"},
            {"sellable_to_vendor", "Продаваемо продавцу"},
            {"sellable_to_vendor_tooltip", "Показать предметы, продаваемые продавцу"},
            {"sellable_on_tp", "Продаваемо на TP"},
            {"sellable_on_tp_tooltip", "Показать предметы, продаваемые на Торговом Посту"},
            {"has_custom_profit", "Имеет пользовательскую прибыль"},
            {"has_custom_profit_tooltip", "Показать предметы со значениями пользовательской прибыли"},
            {"api_knowledge_filters", "Фильтры Знаний API"},
            {"known_by_api", "Известно API"},
            {"known_by_api_tooltip", "Показать предметы, известные API GW2"},
            {"unknown_by_api", "Неизвестно API"},
            {"unknown_by_api_tooltip", "Показать предметы, неизвестные API GW2"},
            {"item_type_filters", "Фильтры Типа Предмета"},
            {"type_armor", "Броня"},
            {"type_armor_tooltip", "Показать предметы брони"},
            {"type_weapon", "Оружие"},
            {"type_weapon_tooltip", "Показать предметы оружия"},
            {"type_trinket", "Аксессуар"},
            {"type_trinket_tooltip", "Показать предметы аксессуаров"},
            {"type_gizmo", "Гизмо"},
            {"type_gizmo_tooltip", "Показать предметы гизмо"},
            {"type_crafting_material", "Крафт Материал"},
            {"type_crafting_material_tooltip", "Показать крафт материалы"},
            {"type_consumable", "Расходуемый"},
            {"type_consumable_tooltip", "Показать расходуемые предметы"},
            {"type_gathering_tool", "Инструмент Сбора"},
            {"type_gathering_tool_tooltip", "Показать инструменты сбора"},
            {"type_bag", "Сумка"},
            {"type_bag_tooltip", "Показать сумки"},
            {"type_container", "Контейнер"},
            {"type_container_tooltip", "Показать контейнеры"},
            {"type_mini_pet", "Мини Питомец"},
            {"type_mini_pet_tooltip", "Показать мини питомцев"},
            {"currency_filters", "Фильтры Валют"},
            {"currency_karma", "Карма"},
            {"currency_karma_tooltip", "Показать валюту Карма"},
            {"currency_laurel", "Лавр"},
            {"currency_laurel_tooltip", "Показать валюту Лавр"},
            {"currency_gem", "Гемма"},
            {"currency_gem_tooltip", "Показать валюту Гемма"},
            {"currency_fractal_relic", "Фрактальная Реликвия"},
            {"currency_fractal_relic_tooltip", "Показать валюту Фрактальная Реликвия"},
            {"currency_badge_of_honor", "Знак Чести"},
            {"currency_badge_of_honor_tooltip", "Показать валюту Знак Чести"},
            {"currency_guild_commendation", "Рекомендация Гильдии"},
            {"currency_guild_commendation_tooltip", "Показать валюту Рекомендация Гильдии"},
            {"currency_transmutation_charge", "Заряд Трансмутации"},
            {"currency_transmutation_charge_tooltip", "Показать валюту Заряд Трансмутации"},
            {"currency_spirit_shards", "Осколки Духа"},
            {"currency_spirit_shards_tooltip", "Показать валюту Осколки Духа"},
            {"currency_unbound_magic", "Несвязанная Магия"},
            {"currency_unbound_magic_tooltip", "Показать валюту Несвязанная Магия"},
            {"currency_volatile_magic", "Нестабильная Магия"},
            {"currency_volatile_magic_tooltip", "Показать валюту Нестабильная Магия"},
            {"currency_airship_parts", "Детали Дирижабля"},
            {"currency_airship_parts_tooltip", "Показать валюту Детали Дирижабля"},
            {"currency_geode", "Геода"},
            {"currency_geode_tooltip", "Показать валюту Геода"},
            {"currency_ley_line_crystals", "Кристаллы Лей-Линий"},
            {"currency_ley_line_crystals_tooltip", "Показать валюту Кристаллы Лей-Линий"},
            {"currency_trade_contracts", "Торговые Контракты"},
            {"currency_trade_contracts_tooltip", "Показать валюту Торговые Контракты"},
            {"currency_elegy_mosaic", "Мозаика Элегии"},
            {"currency_elegy_mosaic_tooltip", "Показать валюту Мозаика Элегии"},
            {"currency_uncommon_coins", "Необычные Монеты"},
            {"currency_uncommon_coins_tooltip", "Показать валюту Необычные Монеты"},
            {"currency_astral_acclaim", "Астральные Аплодисменты"},
            {"currency_astral_acclaim_tooltip", "Показать валюту Астральные Аплодисменты"},
            {"currency_pristine_fractal_relics", "Чистые Фрактальные Реликвии"},
            {"currency_pristine_fractal_relics_tooltip", "Показать валюту Чистые Фрактальные Реликвии"},
            {"currency_unstable_fractal_essence", "Нестабильная Фрактальная Эссенция"},
            {"currency_unstable_fractal_essence_tooltip", "Показать валюту Нестабильная Фрактальная Эссенция"},
            {"currency_magnetite_shards", "Осколки Магнетита"},
            {"currency_magnetite_shards_tooltip", "Показать валюту Осколки Магнетита"},
            {"currency_gaeting_crystals", "Кристаллы Гейтинг"},
            {"currency_gaeting_crystals_tooltip", "Показать валюту Кристаллы Гейтинг"},
            {"currency_prophet_shards", "Осколки Пророка"},
            {"currency_prophet_shards_tooltip", "Показать валюту Осколки Пророка"},
            {"currency_green_prophet_shards", "Зелёные Осколки Пророка"},
            {"currency_green_prophet_shards_tooltip", "Показать валюту Зелёные Осколки Пророка"},
            {"currency_wvw_skirmish_tickets", "Билеты WvW Сражений"},
            {"currency_wvw_skirmish_tickets_tooltip", "Показать валюту Билеты WvW Сражений"},
            {"currency_proofs_of_heroics", "Доказательства Героизма"},
            {"currency_proofs_of_heroics_tooltip", "Показать валюту Доказательства Героизма"},
            {"currency_pvp_league_tickets", "Билеты PvP Лиги"},
            {"currency_pvp_league_tickets_tooltip", "Показать валюту Билеты PvP Лиги"},
            {"currency_ascended_shards_of_glory", "Вознесённые Осколки Славы"},
            {"currency_ascended_shards_of_glory_tooltip", "Показать валюту Вознесённые Осколки Славы"},
            {"currency_research_notes", "Исследовательские Заметки"},
            {"currency_research_notes_tooltip", "Показать валюту Исследовательские Заметки"},
            {"currency_tyrian_defense_seal", "Печать Обороны Тирии"},
            {"currency_tyrian_defense_seal_tooltip", "Показать валюту Печать Обороны Тирии"},
            {"currency_testimony_of_desert_heroics", "Свидетельство Героизма Пустыни"},
            {"currency_testimony_of_desert_heroics_tooltip", "Показать валюту Свидетельство Героизма Пустыни"},
            {"currency_testimony_of_jade_heroics", "Свидетельство Героизма Джейда"},
            {"currency_testimony_of_jade_heroics_tooltip", "Показать валюту Свидетельство Героизма Джейда"},
            {"currency_testimony_of_castoran_heroics", "Свидетельство Героизма Касторана"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Показать валюту Свидетельство Героизма Касторана"},
            {"currency_legendary_insight", "Легендарное Прозрение"},
            {"currency_legendary_insight_tooltip", "Показать валюту Легендарное Прозрение"},
            {"currency_tales_of_dungeon_delving", "Сказания о Подземельях"},
            {"currency_tales_of_dungeon_delving_tooltip", "Показать валюту Сказания о Подземельях"},
            {"currency_imperial_favor", "Имперская Милость"},
            {"currency_imperial_favor_tooltip", "Показать валюту Имперская Милость"},
            {"currency_canach_coins", "Монеты Канаха"},
            {"currency_canach_coins_tooltip", "Показать валюту Монеты Канаха"},
            {"currency_ancient_coin", "Древняя Монета"},
            {"currency_ancient_coin_tooltip", "Показать валюту Древняя Монета"},
            {"currency_unusual_coin", "Необычная Монета"},
            {"currency_unusual_coin_tooltip", "Показать валюту Необычная Монета"},
            {"currency_jade_sliver", "Осколок Джейда"},
            {"currency_jade_sliver_tooltip", "Показать валюту Осколок Джейда"},
            {"currency_static_charge", "Статический Заряд"},
            {"currency_static_charge_tooltip", "Показать валюту Статический Заряд"},
            {"currency_pinch_of_stardust", "Щепотка Звёздной Пыли"},
            {"currency_pinch_of_stardust_tooltip", "Показать валюту Щепотка Звёздной Пыли"},
            {"currency_calcified_gasp", "Окаменевший Вздох"},
            {"currency_calcified_gasp_tooltip", "Показать валюту Окаменевший Вздох"},
            {"currency_ursus_oblige", "Урсус Облиге"},
            {"currency_ursus_oblige_tooltip", "Показать валюту Урсус Облиге"},
            {"currency_gaeting_crystal_janthir", "Кристалл Гейтинг (Джантир)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Показать валюту Кристалл Гейтинг (Джантир)"},
            {"currency_antiquated_ducat", "Старинный Дукат"},
            {"currency_antiquated_ducat_tooltip", "Показать валюту Старинный Дукат"},
            {"currency_aether_rich_sap", "Эфиробогатый Сок"},
            {"currency_aether_rich_sap_tooltip", "Показать валюту Эфиробогатый Сок"},

            // Additional Filters
            {"additional_filters", "Дополнительные Фильтры"},
            {"account_bound", "Привязан к Аккаунту"},
            {"account_bound_tooltip", "Показать предметы, привязанные к аккаунту"},
            {"not_account_bound", "Не Привязан к Аккаунту"},
            {"not_account_bound_tooltip", "Показать предметы, не привязанные к аккаунту"},
            {"nosell_items", "Не для продажи"},
            {"nosell_items_tooltip", "Показать предметы не для продажи"},
            {"not_nosell", "Для продажи"},
            {"not_nosell_tooltip", "Показать предметы для продажи"},
            {"favorite_items", "Избранное"},
            {"favorite_items_tooltip", "Показать избранные предметы"},
            {"not_favorite", "Не Избранное"},
            {"not_favorite_tooltip", "Показать неизбранные предметы"},
            {"ignored_items", "Игнорируемые"},
            {"ignored_items_tooltip", "Показать игнорируемые предметы"},
            {"not_ignored", "Не Игнорируемые"},
            {"not_ignored_tooltip", "Показать неигнорируемые предметы"},

            // Range Filters
            {"range_filters", "Фильтры Диапазона"},
            {"show_range_filters", "Показать Фильтры Диапазона"},
            {"filter_min_price", "Фильтр Мин Цена"},
            {"filter_max_price", "Фильтр Макс Цена"},
            {"filter_min_quantity", "Фильтр Мин Количество"},
            {"filter_max_quantity", "Фильтр Макс Количество"},

            // Mini Window Settings
            {"mini_window_settings", "Мини Окно"},
            {"show_profit", "Показать Прибыль"},
            {"show_profit_tooltip", "Отображать общую прибыль в мини окне"},
            {"show_profit_per_hour", "Показать Прибыль/Час"},
            {"show_profit_per_hour_tooltip", "Отображать прибыль за час в мини окне"},
            {"show_tp_sell", "Показать Продажу TP (Листинги)"},
            {"show_tp_sell_tooltip", "Отображать прибыль продажи TP (листинги) в мини окне"},
            {"show_tp_instant", "Показать Мгновенную Продажу TP"},
            {"show_tp_instant_tooltip", "Отображать прибыль мгновенной продажи TP в мини окне"},
            {"show_total_items", "Показать Всего Предметов"},
            {"show_total_items_tooltip", "Отображать общее количество предметов в мини окне"},
            {"show_session_duration", "Показать Длительность Сессии"},
            {"show_session_duration_tooltip", "Отображать длительность сессии в мини окне"},
            {"window_click_through", "Клик Сквозь Окно"},
            {"window_click_through_tooltip", "Позволяет кликать сквозь мини окно в игру"},

            // Main Window Settings
            {"main_window", "Главное Окно"},
            {"click_through", "Клик Сквозь"},
            {"click_through_tooltip", "Позволяет кликать сквозь главное окно в игру"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Расширенные Настройки UI"},
            {"no_advanced_ui_settings", "(Нет доступных расширенных настроек UI)"},

            // Display Settings
            {"display_settings", "Настройки Отображения"},
            {"show_item_icons", "Показать Иконки Предметов"},
            {"show_item_icons_tooltip", "Отображать иконки предметов в списке"},
            {"show_rarity_border", "Показать Границу Редкости"},
            {"show_rarity_border_tooltip", "Отображать цветную границу на основе редкости предмета"},
            {"enable_grid_view", "Включить Сетку"},
            {"enable_grid_view_tooltip", "Отображать предметы в сетке вместо списка"},
            {"grid_icon_size", "Размер Иконки Сетки"},
            {"grid_icon_size_tooltip", "Размер иконок в сетке"},

            // Count Display Settings
            {"count_display_settings", "Настройки Отображения Количества"},
            {"count_text_color", "Цвет Текста Количества"},
            {"count_text_color_tooltip", "Цвет текста количества"},
            {"count_background_color", "Цвет Фона Количества"},
            {"count_background_color_tooltip", "Цвет фона количества"},
            {"count_font_size", "Размер Шрифта Количества"},
            {"count_font_size_tooltip", "Размер шрифта количества"},
            {"count_horizontal_alignment", "Горизонтальное Выравнивание Количества"},
            {"count_horizontal_alignment_tooltip", "Горизонтальное выравнивание текста количества"},

            // Gradient Background Settings
            {"gradient_background_settings", "Настройки Градиентного Фона"},
            {"enable_gradient_backgrounds", "Включить Градиентные Фоны"},
            {"enable_gradient_backgrounds_tooltip", "Включить градиентный фон для окон"},
            {"gradient_top_color", "Верхний Цвет Градиента"},
            {"gradient_top_color_tooltip", "Верхний цвет градиентного фона"},
            {"gradient_bottom_color", "Нижний Цвет Градиента"},
            {"gradient_bottom_color_tooltip", "Нижний цвет градиентного фона"},

            // Custom Profit System
            {"custom_profit_system", "Система Пользовательской Прибыли"},
            {"enable_custom_profit", "Включить Пользовательскую Прибыль"},
            {"enable_custom_profit_tooltip", "Включить значения пользовательской прибыли для предметов"},

            // Search
            {"search_settings", "Поиск"},
            {"enable_search", "Включить Поиск"},
            {"enable_search_tooltip", "Включить функцию поиска"},

            // Ignored Items
            {"ignored_items_settings", "Игнорируемые Предметы"},
            {"enable_ignored_items", "Включить Игнорируемые Предметы"},
            {"enable_ignored_items_tooltip", "Включить функцию игнорируемых предметов"},

            // Auto Reset
            {"auto_reset_settings", "Авто Сброс"},
            {"enable_auto_reset", "Включить Авто Сброс"},
            {"enable_auto_reset_tooltip", "Автоматически сбрасывать сессию фарминга после длительности"},
            {"auto_reset_duration", "Длительность Авто Сброса (минуты)"},
            {"auto_reset_duration_tooltip", "Длительность в минутах перед авто сбросом"},

            // DRF Settings
            {"drf_settings", "Настройки DRF"},
            {"drf_token", "Токен DRF"},
            {"drf_token_tooltip", "Ваш токен аутентификации DRF"},
            {"edit_token", "Редактировать Токен"},
            {"save_token", "Сохранить Токен"},

            // GW2 API Settings
            {"gw2_api_settings", "Настройки API GW2"},
            {"gw2_api_key", "Ключ API GW2"},
            {"gw2_api_key_tooltip", "Ваш ключ API GW2 для деталей предметов"},
            {"edit_key", "Редактировать Ключ"},
            {"save_key", "Сохранить Ключ"},

            // Language Settings
            {"language_settings", "Язык"},
            {"language_tooltip", "Выбрать язык интерфейса"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "Нет настроенных аккаунтов"},
            {"no_profiles_created", "Профили ещё не созданы"},
            {"count_label", "Количество:"},
            {"profit_label", "Прибыль:"},
            {"no_profit", "Нет прибыли"},
            {"vendor_value_label", "Стоимость Продавца:"},
            {"tp_sell_gross_label", "Продажа TP (Брутто):"},
            {"tp_sell_net_label", "Продажа TP (Чистая):"},
            {"tp_buy_gross_label", "Покупка TP (Брутто):"},
            {"tp_buy_net_label", "Покупка TP (Чистая):"},
            {"ignored_items_label", "Игнорируемые Предметы:"},
            {"ignored_currencies_label", "Игнорируемые Валюты:"},
            {"total_items_label", "Всего Предметов:"},
            {"total_currencies_label", "Всего Валют:"},
            {"total_profit_label", "Общая Прибыль:"},
            {"tp_sell_profit_label", "Прибыль Продажи TP:"},
            {"vendor_profit_label", "Прибыль Продажи Продавцу:"},
            {"profit_per_hour_label", "Прибыль За Час:"},
            {"opportunity_cost_profit_label", "Прибыль Альтернативных Издержек:"},
            {"opportunity_cost_profit_per_hour_label", "Прибыль Альтернативных Издержек/Час:"},
            {"custom_profit_feature_placeholder", "Функция реализована - UI будет добавлено"},
            {"overview_label", "Обзор:"},
            {"total_profit_label_simple", "Общая Прибыль"},
            {"total_items_label_simple", "Всего Предметов"},
            {"total_currencies_label_simple", "Всего Валют"},
            {"profit_per_hour_label_simple", "Прибыль За Час"},
            {"session_duration_label_simple", "Длительность Сессии"},
            {"export_label", "Экспорт:"},
            {"quick_actions", "Быстрые Действия:"},
            {"reset_confirm", "Вы уверены, что хотите сбросить все настройки по умолчанию?"},
            {"reset_warning", "Это действие нельзя отменить."},
            {"export_settings", "Экспорт Настроек в Файл:"},
            {"import_settings", "Импорт Настроек из Файла:"},
            {"edit_account", "Редактировать Аккаунт: %s"},
            {"account_name", "Имя Аккаунта:"},
            {"drf_token_label", "Токен DRF:"},
            {"gw2_api_key_label", "Ключ API GW2:"},
            {"reload_config", "Перезагрузить Конфигурацию:"},
            {"auto_reset_label", "Авто Сброс:"},
            {"next_reset_utc", "Следующий запланированный сброс (UTC): %s"},
            {"favorites_ui", "UI Избранного:"},
            {"favorites_colors", "Цвета Избранного:"},
            {"visual_enhancements", "Визуальные Улучшения:"},
            {"mini_window_widget", "Мини Окно (Виджет Оверлея):"},
            {"main_window_label", "Главное Окно:"},
            {"profiles_description", "Профили позволяют сохранять различные конфигурации и быстро переключаться между ними."},
            {"create_new_profile", "Создать Новый Профиль:"},
            {"current_profile", "Текущий Профиль: %s"},
            {"auto_backup", "Автоматически создавать резервную копию настроек перед важными изменениями"},
            {"notifications", "Настроить внутриигровые уведомления для важных событий"},
            {"profit_goal", "Цель Прибыли:"},
            {"reset_warning_label", "Предупреждение Сброса:"},
            {"session_complete", "Сессия Завершена:"},
            {"manage_ignored_items", "Управлять игнорируемыми предметами"},
            {"manage_ignored_currencies", "Управлять игнорируемыми валютами"},
            {"rarity_label", "Редкость: %s"},
            {"type_label", "Тип: %d"},
            {"account_bound_label", "Привязан к Аккаунту: %s"},
            {"nosell_label", "Не для продажи: %s"},
            {"sell_method_filters_label", "Фильтры Метода Продажи:"},
            {"api_knowledge_filters_label", "Фильтры Знаний API:"},
            {"additional_filters_label", "Дополнительные Фильтры:"},
            {"item_type_filters_label", "Фильтры Типа Предмета:"},
            {"currency_filters_label", "Фильтры Валют:"},
            {"price_range", "Диапазон Цены (Медь):"},
            {"quantity_range", "Диапазон Количества:"},
            {"debug_info", "Информация Отладки"},
            {"drf_status", "Статус DRF: %s"},
            {"drf_reconnect_count", "Количество Переподключений DRF: %d"},
            {"gw2_api_status", "Статус API GW2: %s"},
            {"gw2_api_reconnect_count", "Количество Переподключений API GW2: %d"},
            {"session_duration_debug", "Длительность Сессии: %s"},
            {"gw2_memory", "Память Процесса GW2: %zu MB"},
            {"gw2_api_request_count", "Количество Запросов API GW2: %d"},
            {"ignored_items_count", "Игнорируемые Предметы: %d"},
            {"ignored_currencies_count", "Игнорируемые Валюты: %d"},
            {"drf_logs", "Логи DRF:"},
            {"last_100_entries", "(Последние 100 записей)"},
            {"gw2_api_logs", "Логи API GW2:"},
            {"item_currency_details", "Детали Предмета/Валюты (Первые 5):"},
            {"item_label", "Предмет %d: %s (Количество: "},
            {"loaded_label", ", Загружено: %s)"},
            {"currency_label", "Валюта %d: %s (Количество: "},
            {"custom_profit_items", "Предметы Пользовательской Прибыли (Первые 5):"},
            {"custom_profit_item", "Предмет %d: %s (Пользовательская Прибыль: "},
            {"no_custom_profit_items", "(Нет предметов пользовательской прибыли)"},
            {"ignored_items_debug", "Игнорируемые Предметы (Первые 5):"},
            {"yes_label", "Да"},
            {"no_label", "Нет"},
            {"profits_label", "Прибыль:"},
            {"profits_tooltip", "Общая прибыль от фарминга"},
            {"approx_profits_label", "Приблизительная Прибыль:"},
            {"approx_profits_tooltip", "Общая прибыль от значений пользовательской прибыли"},
            {"approx_gold_per_hour_label", "Приблизительное Золото За Час:"},
            {"approx_gold_per_hour_tooltip", "Прибыль за час на основе длительности сессии"},
            {"trading_profits_label", "Прибыль от Торговли:"},
            {"trading_profits_tooltip", "Прибыль от продажи предметов на Торговом Посту"},
            {"approx_trading_profits_listings_label", "Приблизительная Прибыль от Торговли (Листинги):"},
            {"approx_trading_profits_listings_tooltip", "Общая прибыль если продано через TP листинги"},
            {"approx_trading_profits_instant_label", "Приблизительная Прибыль от Торговли (Мгновенная Продажа):"},
            {"approx_trading_profits_instant_tooltip", "Общая прибыль если продано через TP мгновенные ордера покупки"},
            {"trading_details_label", "Детали Торговли (Альтернативные Издержки):"},
            {"trading_details_tooltip", "Потерянная прибыль из-за непродажи через TP листинги"},
            {"lost_profit_vs_tp_sell_label", "Потерянная Прибыль (vs Продажа TP):"},
            {"lost_profit_vs_tp_sell_tooltip", "Золото = потерянная прибыль, Красный = полученная прибыль vs продажа TP"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Потерянная Прибыль За Час (vs Продажа TP):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Альтернативные издержки за час"},
            {"session_duration_debug_label", "Длительность сессии: %s"},
            {"session_duration_debug_tooltip", "Текущая длительность сессии фарминга"},
            {"tab_items", "Предметы"},
            {"manage_ignored_items", "Управлять игнорируемыми предметами"},
            {"clear_all_ignored_items", "Очистить все игнорируемые предметы"},
            {"unignore_item", "Перестать игнорировать предмет"},
            {"tab_currencies", "Валюты"},
            {"manage_ignored_currencies", "Управлять игнорируемыми валютами"},
            {"clear_all_ignored_currencies", "Очистить все игнорируемые валюты"},
            {"unignore_currency", "Перестать игнорировать валюту"},
            {"sell_method_filters_label", "Фильтры Метода Продажи:"},
            {"api_knowledge_filters_label", "Фильтры Знаний API:"},
            {"additional_filters_label", "Дополнительные Фильтры:"},
            {"item_type_filters_label", "Фильтры Типа Предмета:"},
            {"currency_filters_label", "Фильтры Валют:"},
            {"price_range", "Диапазон Цены (Медь):"},
            {"quantity_range", "Диапазон Количества:"},
            {"debug_information", "Отладочная Информация"},
            {"drf_status_label", "Статус DRF: %s"},
            {"drf_status_tooltip", "Текущий статус соединения DRF"},
            {"drf_reconnect_count_label", "Счетчик Переподключений DRF: %d"},
            {"drf_reconnect_count_tooltip", "Количество попыток переподключения DRF"},
            {"gw2_api_status_label", "Статус API GW2: %s"},
            {"gw2_api_status_tooltip", "Текущий статус соединения API GW2"},
            {"gw2_api_reconnect_count_label", "Счетчик Переподключений API GW2: %d"},
            {"gw2_api_reconnect_count_tooltip", "Количество попыток переподключения API GW2"},
            {"session_duration_debug", "Длительность Сессии: %s"},
            {"session_duration_debug_tooltip", "Текущая длительность сессии фарминга"},
            {"gw2_process_memory_label", "Память Процесса GW2: %zu MB"},
            {"gw2_process_memory_tooltip", "Текущее использование памяти процесса GW2"},
            {"gw2_api_request_count_label", "Счетчик Запросов API GW2: %d"},
            {"gw2_api_request_count_tooltip", "Общее количество запросов API GW2"},
            {"ignored_items_debug_label", "Игнорируемые Предметы: %d"},
            {"ignored_items_debug_tooltip", "Количество игнорируемых предметов"},
            {"ignored_currencies_debug_label", "Игнорируемые Валюты: %d"},
            {"ignored_currencies_debug_tooltip", "Количество игнорируемых валют"},
            {"drf_logs_label", "Логи DRF:"},
            {"clear_drf_logs", "Очистить Логи DRF"},
            {"clear_drf_logs_tooltip", "Очистить все записи логов DRF"},
            {"last_100_entries", "(Последние 100 записей)"},
            {"gw2_api_logs_label", "Логи API GW2:"},
            {"clear_gw2_logs", "Очистить Логи GW2"},
            {"clear_gw2_logs_tooltip", "Очистить все записи логов API GW2"},
            {"settings_label", "Настройки:"},
            {"api_key_label", "API Ключ: %s"},
            {"api_key_tooltip", "Статус ключа API GW2"},
            {"not_set", "Не установлен"},
            {"set", "Установлен"},
            {"drf_token_label", "Токен DRF: %s"},
            {"drf_token_tooltip", "Статус токена DRF"},
            {"toggle_hotkey_label", "Клавиша Переключения: %s"},
            {"toggle_hotkey_tooltip", "Клавиша переключения главного окна"},
            {"auto_reset_mode_label", "Режим Авто-Сброса: %d"},
            {"auto_reset_mode_tooltip", "Текущий режим автоматического сброса"},
            {"next_reset_label", "Следующий Сброс: %s"},
            {"next_reset_tooltip", "Время следующего запланированного сброса (UTC)"},
            {"fake_drf_server_label", "Фальшивый Сервер DRF:"},
            {"use_fake_drf_server", "Использовать фальшивый сервер DRF"},
            {"use_fake_drf_server_tooltip", "Только для целей тестирования"},
            {"reset_all_data", "Сбросить Все Данные"},
            {"reset_all_data_tooltip", "Сбросить все данные фарминга"},
            {"coin", "Монета"},
            {"rarity_label", "Редкость: %s"},
            {"type_label", "Тип: %d"},
            {"account_bound_label", "Привязано к аккаунту: %s"},
            {"nosell_label", "Не для продажи: %s"},
            {"yes_label", "Да"},
            {"no_label", "Нет"},
            {"sort_price_down", "Сортировка: Цена предмета по убыванию"},
            {"sort_price_up", "Сортировка: Цена предмета по возрастанию"},
            {"sort_count_high", "Сортировка: |Количество| высокое"},
            {"sort_count_low", "Сортировка: |Количество| низкое"},
            {"sort_name_az", "Сортировка: Название А–Я"},
            {"sort_tooltip", "Сортировать предметы по количеству, ID или названию"},
            {"rarity_all", "Редкость: все"},
            {"rarity_basic", "Редкость: Базовая+"},
            {"rarity_fine", "Редкость: Хорошие+"},
            {"rarity_masterwork", "Редкость: Ремесленные+"},
            {"rarity_rare", "Редкость: Редкие+"},
            {"rarity_exotic", "Редкость: Экзотические+"},
            {"rarity_ascended", "Редкость: Вознесенные+"},
            {"rarity_legendary", "Редкость: Только легендарные"},
            {"rarity_tooltip", "Фильтровать предметы по минимальной редкости"},
            {"search_items_hint", "Поиск предметов..."},
            {"column_icon", "Иконка"},
            {"column_name", "Название"},
            {"column_count", "Количество"},
            {"column_profit", "Прибыль"},
            {"column_favorite", "Избранное"},
            {"column_ignore", "Игнорировать"},
            {"toggle_favorite", "Переключить избранное"},
            {"toggle_ignore", "Переключить игнорировать"},
            {"vendor_value_format", "Значение продавца: %s"},
            {"tp_sell_gross_format", "Продажа ТП (Брутто): %s"},
            {"tp_sell_net_format", "Продажа ТП (Нетто): %s"},
            {"tp_buy_gross_format", "Покупка ТП (Брутто): %s"},
            {"tp_buy_net_format", "Покупка ТП (Нетто): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Настройки Избранного"},
            {"favorites_first", "Избранное сначала"},
            {"favorites_first_tooltip", "Показывает избранное первым в списках предметов/валют"},
            {"enable_favorite_text_color", "Включить цвет текста избранного"},
            {"enable_favorite_text_color_tooltip", "Выделяет избранные предметы/валюты пользовательским цветом текста"},
            {"text_color", "Цвет Текста"},
            {"enable_favorite_row_color", "Включить цвет строки избранного"},
            {"enable_favorite_row_color_tooltip", "Выделяет избранные предметы/валюты пользовательским цветом фона строки"},
            {"row_color", "Цвет Строки"},
            
            // Filter - Additional
            {"filter_favorite", "Избранное"},
            {"filter_favorite_tooltip", "Показать избранные предметы"},
            {"filter_not_favorite", "Не избранное"},
            {"filter_not_favorite_tooltip", "Показать неизбранные предметы"},
            {"filter_research_notes", "Заметки Исследования"},
            {"filter_research_notes_tooltip", "Показать валюту заметки исследования"},
            {"range_filters", "Фильтры Диапазона"},
            {"range_filters_tooltip", "Показать фильтры диапазона цены и количества"},
            {"filter_min_price_tooltip", "Фильтр минимальной цены (0 = отключено)"},
            {"filter_max_price_tooltip", "Фильтр максимальной цены (0 = отключено)"},
            {"filter_min_quantity_tooltip", "Фильтр минимального количества (0 = отключено)"},
            {"filter_max_quantity_tooltip", "Фильтр максимального количества (0 = отключено)"},
            {"filter_min_price", "Мин Цена"},
            {"filter_max_price", "Макс Цена"},
            {"filter_min_quantity", "Мин Кол-во"},
            {"filter_max_quantity", "Макс Кол-во"},
            
            // Summary Tab - Table Columns
            {"column_label", "Метка"},
            {"column_value", "Значение"},
            {"column_item", "Предмет"},
            {"column_count", "Количество"},
            {"column_currency", "Валюта"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Топ предметов по прибыли"},
            {"top_items_count_header", "Топ предметов (Количество)"},
            {"top_currencies_count_header", "Топ валют (Количество)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Топ 10 предметов по значению прибыли"},
            {"top_items_count_tooltip", "Топ 10 предметов по количеству"},
            {"top_currencies_count_tooltip", "Топ 10 валют по количеству"},
            
            // Settings Tab - General
            {"show_main_window", "Показать главное окно"},
            {"reset_all", "Сбросить всё"},
            {"reset_all_tooltip", "Сбросить все настройки до значений по умолчанию"},
            {"export", "Экспорт"},
            {"export_tooltip", "Экспорт настроек в файл JSON"},
            {"import", "Импорт"},
            {"import_tooltip", "Импорт настроек из файла JSON"},
            {"save", "Сохранить"},
            {"save_tooltip", "Сохранить текущие настройки"},
            {"general_settings", "Общие настройки"},
            {"account_management", "Управление аккаунтами"},
            {"add_account", "+ Добавить аккаунт"},
            {"remove_account", "- Удалить аккаунт"},
            {"save_account", "Сохранить аккаунт"},
            {"reload_drf_token", "Перезагрузить токен DRF"},
            {"reload_gw2_api_key", "Перезагрузить ключ API GW2"},
            {"reset_settings", "Авто Сброс"},
            {"visual_settings", "Визуальные настройки"},
            {"gradient_backgrounds", "Градиентные фоны"},
            {"gradient_backgrounds_tooltip", "Включает плавные градиентные фоны для более современного вида"},
            {"top_gradient_color", "Верхний цвет градиента"},
            {"top_gradient_color_tooltip", "Верхний цвет градиента"},
            {"bottom_gradient_color", "Нижний цвет градиента"},
            {"bottom_gradient_color_tooltip", "Нижний цвет градиента"},
            {"show_item_icons", "Показать иконки предметов (рендер GW2)"},
            {"show_item_icons_tooltip", "Загружает иконки с render.guildwars2.com через Nexus."},
            {"icon_size", "Размер иконки"},
            {"icon_size_tooltip", "Размер иконок предметов в пикселях (16-96)"},
            {"show_rarity_borders", "Показать границы редкости"},
            {"show_rarity_borders_tooltip", "Показывает цветные границы вокруг иконок на основе редкости"},
            {"rarity_border_thickness", "Толщина границы редкости"},
            {"rarity_border_thickness_tooltip", "Настройка толщины границ редкости (1.0 - 10.0)"},
            {"enable_grid_view_items", "Включить сетку (Предметы)"},
            {"enable_grid_view_items_tooltip", "Переключение между списком и сеткой на вкладке Предметы"},
            {"grid_icon_size_items", "Размер иконки сетки (Предметы)"},
            {"grid_icon_size_items_tooltip", "Размер иконок в сетке для Предметов (16-128)"},
            {"enable_grid_view_currencies", "Включить сетку (Валюты)"},
            {"enable_grid_view_currencies_tooltip", "Переключение между списком и сеткой на вкладке Валюты"},
            {"grid_icon_size_currencies", "Размер иконки сетки (Валюты)"},
            {"grid_icon_size_currencies_tooltip", "Размер иконок в сетке для Валют (16-128)"},
            {"show_mini_window", "Показать мини-окно"},
            {"show_mini_window_tooltip", "Показывает маленький виджет наложения с ключевой статистикой"},
            {"mini_window_show_profit", "Показать прибыль"},
            {"mini_window_show_profit_tooltip", "Показать общую прибыль в мини-окне"},
            {"mini_window_show_profit_per_hour", "Показать прибыль/час"},
            {"mini_window_show_profit_per_hour_tooltip", "Показать прибыль в час в мини-окне"},
            {"mini_window_show_tp_sell", "Показать продажу TP (Списки)"},
            {"mini_window_show_tp_sell_tooltip", "Показать прибыль продажи TP (списки) в мини-окне"},
            {"mini_window_show_tp_instant", "Показать мгновенную продажу TP"},
            {"mini_window_show_tp_instant_tooltip", "Показать прибыль мгновенной продажи TP в мини-окне"},
            {"mini_window_show_total_items", "Показать общее количество предметов"},
            {"mini_window_show_total_items_tooltip", "Показать общее количество предметов в мини-окне"},
            {"mini_window_show_session_duration", "Показать длительность сессии"},
            {"mini_window_show_session_duration_tooltip", "Показать длительность сессии в мини-окне"},
            {"mini_window_click_through", "Окно кликабельное"},
            {"mini_window_click_through_tooltip", "Позволяет кликать через мини-окно в игру"},
            {"main_window_click_through", "Кликабельное"},
            {"main_window_click_through_tooltip", "Позволяет кликать через главное окно в игру"},
            {"settings_profiles", "Профили настроек"},
            {"select_profile", "Выберите профиль для применения его настроек"},
            {"create_new_profile", "Создать новый профиль"},
            {"create_new_profile_tooltip", "Создать новый профиль с текущими настройками"},
            {"create", "Создать"},
            {"update_profile", "Обновить профиль"},
            {"update_profile_tooltip", "Обновить текущий профиль с текущими настройками"},
            {"delete_profile", "Удалить профиль"},
            {"delete_profile_tooltip", "Удалить текущий профиль"},
            {"automatic_backups", "Автоматические резервные копии"},
            {"enable_automatic_backups", "Включить автоматические резервные копии"},
            {"enable_automatic_backups_tooltip", "Автоматически создавать резервные копии перед изменениями"},
            {"backup_frequency", "Частота резервного копирования"},
            {"backup_frequency_tooltip", "Как часто создавать автоматические резервные копии"},
            {"max_backups", "Максимум резервных копий"},
            {"max_backups_tooltip", "Максимальное количество резервных копий для хранения (1-20)"},
            {"notification_settings", "Настройки уведомлений"},
            {"enable_notifications", "Включить уведомления"},
            {"enable_notifications_tooltip", "Включить уведомления в игре"},
            {"notify_profit_goal", "Уведомить при достижении цели прибыли"},
            {"notify_profit_goal_tooltip", "Уведомить, когда вы достигнете цели прибыли"},
            {"profit_goal_gold", "Цель прибыли (Золото)"},
            {"profit_goal_gold_tooltip", "Цель прибыли в золотых монетах (1-1000)"},
            {"notify_reset_warning", "Уведомить перед сбросом"},
            {"notify_reset_warning_tooltip", "Уведомить перед автоматическим сбросом"},
            {"reset_warning_minutes", "Предупреждение сброса (Минуты)"},
            {"reset_warning_minutes_tooltip", "Минуты до сброса для показа предупреждения (1-60)"},
            {"notify_session_complete", "Уведомить после длительности сессии"},
            {"notify_session_complete_tooltip", "Уведомить после фарминга в течение определенного времени"},
            {"session_complete_hours", "Сессия завершена (Часы)"},
            {"session_complete_hours_tooltip", "Часы фарминга до уведомления (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Продаваемое торговцу"},
            {"filter_sellable_to_vendor_tooltip", "Показать предметы, продаваемые торговцу"},
            {"filter_sellable_on_tp", "Продаваемое на TP"},
            {"filter_sellable_on_tp_tooltip", "Показать предметы, продаваемые на Торговом посту"},
            {"filter_custom_profit", "Пользовательская прибыль"},
            {"filter_custom_profit_tooltip", "Показать предметы с пользовательской прибылью"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Известно API"},
            {"filter_known_by_api_tooltip", "Показать предметы, известные API GW2"},
            {"filter_unknown_by_api", "Неизвестно API"},
            {"filter_unknown_by_api_tooltip", "Показать предметы, неизвестные API GW2"},
            
            // Filter - Additional
            {"show_ignored_items", "Показать игнорируемые предметы"},
            {"show_ignored_items_tooltip", "Показать игнорируемые предметы/валюты на вкладках Предметы и Валюты (снимите флажок, чтобы скрыть)"},
            
            // Filter - Item Types
            {"filter_type_armor", "Броня"},
            {"filter_type_armor_tooltip", "Показать предметы брони"},
            {"filter_type_weapon", "Оружие"},
            {"filter_type_weapon_tooltip", "Показать предметы оружия"},
            {"filter_type_trinket", "Аксессуар"},
            {"filter_type_trinket_tooltip", "Показать предметы аксессуаров"},
            {"filter_type_gizmo", "Гизмо"},
            {"filter_type_gizmo_tooltip", "Показать предметы гизмо"},
            {"filter_type_crafting_material", "Материал крафта"},
            {"filter_type_crafting_material_tooltip", "Показать материалы крафта"},
            {"filter_type_consumable", "Расходуемый предмет"},
            {"filter_type_consumable_tooltip", "Показать расходуемые предметы"},
            {"filter_type_gathering_tool", "Инструмент сбора"},
            {"filter_type_gathering_tool_tooltip", "Показать инструменты сбора"},
            {"filter_type_bag", "Сумка"},
            {"filter_type_bag_tooltip", "Показать сумки"},
            {"filter_type_container", "Контейнер"},
            {"filter_type_container_tooltip", "Показать контейнеры"},
            {"filter_type_mini_pet", "Мини-питомец"},
            {"filter_type_mini_pet_tooltip", "Показать мини-питомцев"},
            
            // Filter - Currencies
            {"filter_karma", "Карма"},
            {"filter_karma_tooltip", "Показать валюту Карма"},
            {"filter_laurel", "Лавр"},
            {"filter_laurel_tooltip", "Показать валюту Лавр"},
            {"filter_gem", "Гем"},
            {"filter_gem_tooltip", "Показать валюту Гем"},
            {"filter_fractal_relic", "Реликвия фрактала"},
            {"filter_fractal_relic_tooltip", "Показать валюту Реликвия фрактала"},
            {"filter_badge_of_honor", "Знак чести"},
            {"filter_badge_of_honor_tooltip", "Показать валюту Знак чести"},
            {"filter_guild_commendation", "Рекомендация гильдии"},
            {"filter_guild_commendation_tooltip", "Показать валюту Рекомендация гильдии"},
            {"filter_transmutation_charge", "Заряд трансмутации"},
            {"filter_transmutation_charge_tooltip", "Показать валюту Заряд трансмутации"},
            {"filter_spirit_shards", "Осколки духа"},
            {"filter_spirit_shards_tooltip", "Показать валюту Осколки духа"},
            {"filter_unbound_magic", "Несвязанная магия"},
            {"filter_unbound_magic_tooltip", "Показать валюту Несвязанная магия"},
            {"filter_volatile_magic", "Летучая магия"},
            {"filter_volatile_magic_tooltip", "Показать валюту Летучая магия"},
            {"filter_airship_parts", "Части дирижабля"},
            {"filter_airship_parts_tooltip", "Показать валюту Части дирижабля"},
            {"filter_geode", "Геода"},
            {"filter_geode_tooltip", "Показать валюту Геода"},
            {"filter_ley_line_crystals", "Кристаллы линий лей"},
            {"filter_ley_line_crystals_tooltip", "Показать валюту Кристаллы линий лей"},
            {"filter_trade_contracts", "Торговые контракты"},
            {"filter_trade_contracts_tooltip", "Показать валюту Торговые контракты"},
            {"filter_elegy_mosaic", "Мозаика элегии"},
            {"filter_elegy_mosaic_tooltip", "Показать валюту Мозаика элегии"},
            {"filter_uncommon_coins", "Редкие монеты"},
            {"filter_uncommon_coins_tooltip", "Показать валюту Редкие монеты"},
            {"filter_astral_acclaim", "Астральные аплодисменты"},
            {"filter_astral_acclaim_tooltip", "Показать валюту Астральные аплодисменты"},
            
            // Debug Tab
            {"total_tracked_items", "Общее количество отслеживаемых предметов"},
            {"total_tracked_items_tooltip", "Общее количество отслеживаемых предметов"},
            {"total_tracked_currencies", "Общее количество отслеживаемых валют"},
            {"total_tracked_currencies_tooltip", "Общее количество отслеживаемых валют"},
            {"total_custom_profit", "Общая пользовательская прибыль"},
            {"total_custom_profit_tooltip", "Общая пользовательская прибыль"},
            {"total_tp_sell_profit", "Общая прибыль продажи TP"},
            {"total_tp_sell_profit_tooltip", "Общая прибыль продажи TP"},
            {"total_vendor_sell_profit", "Общая прибыль продажи торговцу"},
            {"total_vendor_sell_profit_tooltip", "Общая прибыль продажи торговцу"},
            {"profit_per_hour_calculation", "Расчет прибыли в час"},
            {"profit_per_hour_calculation_tooltip", "Расчет прибыли в час"},
            {"opportunity_cost_vs_tp_sell", "Альтернативные издержки vs продажа TP"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Альтернативные издержки vs продажа TP"},
            {"opportunity_cost_per_hour", "Альтернативные издержки в час"},
            {"opportunity_cost_per_hour_tooltip", "Альтернативные издержки в час"},
            {"first_5_tracked_items", "Первые 5 отслеживаемых предметов и валют с деталями"},
            {"first_5_tracked_items_tooltip", "Первые 5 отслеживаемых предметов и валют с деталями"},
            {"first_5_custom_profit", "Первые 5 предметов с пользовательской прибылью"},
            {"first_5_custom_profit_tooltip", "Первые 5 предметов с пользовательской прибылью"},
            {"first_5_ignored_items", "Первые 5 игнорируемых предметов"},
            {"first_5_ignored_items_tooltip", "Первые 5 игнорируемых предметов"},
            
            // Debug Settings
            {"debug_settings", "Настройки Отладки"},
            {"enable_debug_tab", "Включить вкладку отладки"},
            {"enable_debug_tab_tooltip", "Показывает вкладку отладки с дополнительной информацией"},
            
            // Currencies Tab
            {"gold_format", "Золото: %lld"},
            {"count_format", "Количество: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Переключить избранное"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Переключить игнорировать"},
            
            // Additional Filters
            {"filter_account_bound", "Привязано к аккаунту"},
            {"filter_account_bound_tooltip", "Показать предметы, привязанные к аккаунту"},
            {"filter_not_account_bound", "Не привязано к аккаунту"},
            {"filter_not_account_bound_tooltip", "Показать предметы, не привязанные к аккаунту"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "Показать предметы NoSell"},
            {"filter_not_nosell", "Не NoSell"},
            {"filter_not_nosell_tooltip", "Показать продаваемые предметы"},
            {"filter_ignored", "Игнорируемые"},
            {"filter_ignored_tooltip", "Показать игнорируемые предметы"},
            {"filter_not_ignored", "Не Игнорируемые"},
            {"filter_not_ignored_tooltip", "Показать неигнорируемые предметы"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Чистые фрактальные реликвии"},
            {"filter_pristine_fractal_relics_tooltip", "Показать валюту Чистые фрактальные реликвии"},
            {"filter_unstable_fractal_essence", "Нестабильная фрактальная сущность"},
            {"filter_unstable_fractal_essence_tooltip", "Показать валюту Нестабильная фрактальная сущность"},
            {"filter_magnetite_shards", "Осколки магнетита"},
            {"filter_magnetite_shards_tooltip", "Показать валюту Осколки магнетита"},
            {"filter_gaeting_crystals", "Кристаллы Гэйтинг"},
            {"filter_gaeting_crystals_tooltip", "Показать валюту Кристаллы Гэйтинг"},
            {"filter_prophet_shards", "Осколки пророка"},
            {"filter_prophet_shards_tooltip", "Показать валюту Осколки пророка"},
            {"filter_green_prophet_shards", "Зеленые осколки пророка"},
            {"filter_green_prophet_shards_tooltip", "Показать валюту Зеленые осколки пророка"},
            {"filter_wvw_skirmish_tickets", "Билеты стычек WvW"},
            {"filter_wvw_skirmish_tickets_tooltip", "Показать валюту Билеты стычек WvW"},
            {"filter_proofs_of_heroics", "Доказательства героизма"},
            {"filter_proofs_of_heroics_tooltip", "Показать валюту Доказательства героизма"},
            {"filter_pvp_league_tickets", "Билеты лиги PvP"},
            {"filter_pvp_league_tickets_tooltip", "Показать валюту Билеты лиги PvP"},
            {"filter_ascended_shards_of_glory", "Возносящиеся осколки славы"},
            {"filter_ascended_shards_of_glory_tooltip", "Показать валюту Возносящиеся осколки славы"},
            {"filter_tyrian_defense_seal", "Печать защиты Тирии"},
            {"filter_tyrian_defense_seal_tooltip", "Показать валюту Печать защиты Тирии"},
            {"filter_testimony_of_desert_heroics", "Свидетельство героизма пустыни"},
            {"filter_testimony_of_desert_heroics_tooltip", "Показать валюту Свидетельство героизма пустыни"},
            {"filter_testimony_of_jade_heroics", "Свидетельство героизма нефрита"},
            {"filter_testimony_of_jade_heroics_tooltip", "Показать валюту Свидетельство героизма нефрита"},
            {"filter_testimony_of_castoran_heroics", "Свидетельство героизма касторан"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Показать валюту Свидетельство героизма касторан"},
            {"filter_legendary_insight", "Легендарное прозрение"},
            {"filter_legendary_insight_tooltip", "Показать валюту Легендарное прозрение"},
            {"filter_tales_of_dungeon_delving", "Истории исследования подземелий"},
            {"filter_tales_of_dungeon_delving_tooltip", "Показать валюту Истории исследования подземелий"},
            {"filter_imperial_favor", "Имперская милость"},
            {"filter_imperial_favor_tooltip", "Показать валюту Имперская милость"},
            {"filter_canach_coins", "Монеты Канаха"},
            {"filter_canach_coins_tooltip", "Показать валюту Монеты Канаха"},
            {"filter_ancient_coin", "Древняя монета"},
            {"filter_ancient_coin_tooltip", "Показать валюту Древняя монета"},
            {"filter_unusual_coin", "Необычная монета"},
            {"filter_unusual_coin_tooltip", "Показать валюту Необычная монета"},
            {"filter_jade_sliver", "Осколок нефрита"},
            {"filter_jade_sliver_tooltip", "Показать валюту Осколок нефрита"},
            {"filter_static_charge", "Статический заряд"},
            {"filter_static_charge_tooltip", "Показать валюту Статический заряд"},
            {"filter_pinch_of_stardust", "Щепоть звездной пыли"},
            {"filter_pinch_of_stardust_tooltip", "Показать валюту Щепоть звездной пыли"},
            {"filter_calcified_gasp", "Окаменевший вздох"},
            {"filter_calcified_gasp_tooltip", "Показать валюту Окаменевший вздох"},
            {"filter_ursus_oblige", "Урсус Облиг"},
            {"filter_ursus_oblige_tooltip", "Показать валюту Урсус Облиг"},
            {"filter_gaeting_crystal_janthir", "Кристалл Гэйтинг (Джантир)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Показать валюту Кристалл Гэйтинг (Джантир)"},
            {"filter_antiquated_ducat", "Устаревший дукат"},
            {"filter_antiquated_ducat_tooltip", "Показать валюту Устаревший дукат"},
            {"filter_aether_rich_sap", "Эфирный сок"},
            {"filter_aether_rich_sap_tooltip", "Показать валюту Эфирный сок"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Сбросить все"},
            {"reset_all_tooltip", "Сбросить все настройки к значениям по умолчанию"},
            {"reset_confirm", "Вы уверены, что хотите сбросить все настройки?"},
            {"reset_warning", "Это действие нельзя отменить."},
            {"yes_reset", "Да, сбросить"},
            {"cancel", "Отмена"},
            {"export", "Экспорт"},
            {"export_tooltip", "Экспортировать настройки в файл JSON"},
            {"export_settings", "Экспортировать настройки"},
            {"import", "Импорт"},
            {"import_settings", "Импортировать настройки"},
            {"save", "Сохранить"},
            {"save_tooltip", "Сохранить текущие настройки"},
            
            // Settings Tab - General
            {"general_settings", "Общие настройки"},
            {"account_management", "Управление аккаунтами"},
            {"account_prefix", "Аккаунт"},
            {"remove_account", "- Удалить аккаунт"},
            {"save_account", "Сохранить аккаунт"},
            {"reconnect_drf_token", "Переподключиться к DRF с текущим токеном"},
            {"reload_gw2_api_key_tooltip", "Перезагрузить ключ API GW2 для получения данных предметов"},
            {"reset_settings", "Авто Сброс"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Никогда (только ручной сброс)"},
            {"auto_reset_on_load", "При загрузке аддона"},
            {"auto_reset_daily", "Ежедневный сброс (00:00 UTC)"},
            {"auto_reset_weekly", "Еженедельно (Пн 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Еженедельно NA WvW (Сб 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Еженедельно EU WvW (Пт 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Еженедельно бонус карты (Чт 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Минуты после последней выгрузки"},
            {"auto_reset_custom_days", "Пользовательский (дни)"},
            {"auto_reset_tooltip", "Когда автоматически сбрасывать счетчики фарминга"},
            {"minutes_after_unload_tooltip", "Минуты после выгрузки аддона перед автоматическим сбросом"},
            {"reset_interval_days", "Интервал сброса (дни)"},
            {"reset_interval_days_tooltip", "Пользовательский интервал сброса в днях (1-30 дней)"},
            
            // Visual Settings
            {"top_gradient_color", "Верх"},
            {"top_gradient_color_tooltip", "Верхний цвет градиента"},
            {"bottom_gradient_color", "Низ"},
            {"bottom_gradient_color_tooltip", "Нижний цвет градиента"},
            {"icon_size", "Размер иконки"},
            {"icon_size_tooltip", "Размер иконок предметов в пикселях (16-96)"},
            {"border_size", "Размер границы"},
            {"border_size_tooltip", "Настроить толщину границ редкости (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Переключение между видом списка и сетки на вкладке Предметы"},
            {"grid_icon_size_items", "Размер иконки сетки (Предметы)"},
            {"grid_icon_size_items_tooltip", "Размер иконок в виде сетки для Предметов (16-128)"},
            {"grid_icon_size_currencies", "Размер иконки сетки (Валюты)"},
            {"grid_icon_size_currencies_tooltip", "Размер иконок в виде сетки для Валют (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Показать мини-окно"},
            {"show_mini_window_tooltip", "Показывает небольшой виджет наложения с ключевыми статистиками"},
            {"mini_window_show_profit", "Показать прибыль"},
            {"mini_window_show_profit_tooltip", "Показать общую прибыль в мини-окне"},
            {"mini_window_show_profit_per_hour", "Показать прибыль/час"},
            {"mini_window_show_profit_per_hour_tooltip", "Показать прибыль в час в мини-окне"},
            {"mini_window_show_tp_sell", "Показать продажу TP (Списки)"},
            {"mini_window_show_tp_sell_tooltip", "Показать прибыль продажи TP (списки) в мини-окне"},
            {"mini_window_show_tp_instant", "Показать мгновенную продажу TP"},
            {"mini_window_show_tp_instant_tooltip", "Показать прибыль мгновенной продажи TP в мини-окне"},
            {"mini_window_show_total_items", "Показать общее количество предметов"},
            {"mini_window_show_total_items_tooltip", "Показать общее количество предметов в мини-окне"},
            {"mini_window_show_session_duration", "Показать длительность сессии"},
            {"mini_window_show_session_duration_tooltip", "Показать длительность сессии в мини-окне"},
            {"mini_window_click_through", "Окно кликабельное"},
            {"mini_window_click_through_tooltip", "Позволяет кликать через мини-окно в игру"},
            
            // Main Window
            {"main_window_label", "Главное окно"},
            {"main_window_click_through", "Кликабельное"},
            {"main_window_click_through_tooltip", "Позволяет кликать через главное окно в игру"},
            
            // Settings Profiles
            {"settings_profiles", "Профили настроек"},
            {"default_no_profile", "По умолчанию (Без профиля)"},
            {"select_profile_tooltip", "Выбрать профиль для применения его настроек"},
            {"create", "Создать"},
            {"create_tooltip", "Создать новый профиль с текущими настройками"},
            {"update_profile", "Обновить профиль"},
            {"update_profile_tooltip", "Обновить текущий профиль с текущими настройками"},
            {"delete_profile", "Удалить профиль"},
            {"delete_profile_tooltip", "Удалить текущий профиль"},
            
            // Automatic Backups
            {"automatic_backups", "Автоматические резервные копии"},
            {"enable_automatic_backups", "Включить автоматические резервные копии"},
            {"enable_automatic_backups_tooltip", "Автоматически создавать резервные копии перед изменениями"},
            {"backup_frequency", "Частота резервного копирования"},
            {"backup_frequency_tooltip", "Как часто создавать автоматические резервные копии"},
            {"backup_manual_only", "Только вручную"},
            {"backup_daily", "Ежедневно"},
            {"backup_weekly", "Еженедельно"},
            {"max_backup_count", "Макс. количество копий"},
            {"max_backup_count_tooltip", "Максимальное количество резервных копий для хранения (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Настройки уведомлений"},
            {"enable_notifications", "Включить уведомления"},
            {"enable_notifications_tooltip", "Включить уведомления в игре"},
            {"profit_goal", "Цель прибыли"},
            {"notify_profit_goal", "Уведомить при достижении цели прибыли"},
            {"notify_profit_goal_tooltip", "Уведомить, когда вы достигнете цели прибыли"},
            {"profit_goal_gold", "Цель прибыли (золото)"},
            {"profit_goal_gold_tooltip", "Цель прибыли в золотых монетах (1-1000)"},
            {"reset_warning_label", "Предупреждение сброса"},
            {"notify_reset_warning", "Уведомить перед сбросом"},
            {"notify_reset_warning_tooltip", "Уведомить перед автоматическим сбросом"},
            {"warning_minutes", "Минуты предупреждения"},
            {"warning_minutes_tooltip", "Минуты до сброса для показа предупреждения (1-60)"},
            {"session_complete", "Сессия завершена"},
            {"notify_session_complete", "Уведомить после длительности сессии"},
            {"notify_session_complete_tooltip", "Уведомить после фарминга в течение определенного времени"},
            {"session_hours", "Часы сессии"},
            {"session_hours_tooltip", "Часы фарминга перед уведомлением (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Поиск валют..."},
            {"clear_search", "Очистить"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Поиск избранных предметов..."},
            {"search_favorite_currencies_hint", "Поиск избранных валют..."},
            {"clear_search_favorites", "Очистить"},
        };
        return translations;
    }
}
