// ---------------------------------------------------------------------------
// localization_pl.cpp – Polish translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetPolishTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Rozłączony"},
            {"status_connecting", "Łączenie..."},
            {"status_connected", "Połączony"},
            {"status_auth_failed", "Błąd autoryzacji – sprawdź token"},
            {"status_reconnecting", "Ponowne łączenie..."},
            {"status_error", "Błąd"},
            {"status_unknown", "Nieznany"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Zysk"},
            {"profit_per_hour", "Zysk/Godzina"},
            {"tp_sell", "Sprzedaż TP"},
            {"tp_instant", "Szybka Sprzedaż TP"},
            {"total_items", "Suma Przedmiotów"},
            {"session", "Sesja"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "API GW2"},
            {"session_time_label", "Czas Sesji"},
            {"reset_button", "Resetuj"},
            {"reset_tooltip", "Zresetuj wszystkie liczniki farmingu (reset ręczny)"},

            // Tabs
            {"tab_summary", "Przegląd"},
            {"tab_items", "Przedmioty"},
            {"tab_currencies", "Waluty"},
            {"tab_profit", "Zysk"},
            {"tab_favorites", "Ulubione"},
            {"tab_ignored", "Ignorowane"},
            {"tab_filter", "Filtr"},
            {"tab_custom_profit", "Zysk Niestandardowy"},
            {"tab_debug", "Debugowanie"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF nie podłączony"},
            {"warning_drf_not_connected_desc", "Ten plugin wymaga DRF do transmisji danych."},
            {"warning_drf_install", "Zainstaluj DRF przez Nexus Addon Manager lub https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ Nieprawidłowy token DRF"},
            {"warning_drf_token_invalid_desc", "Proszę sprawdź swój token DRF w ustawieniach."},
            {"warning_gw2_api_key_not_set", "⚠️ Klucz API GW2 nie ustawiony"},
            {"warning_gw2_api_key_not_set_desc", "Proszę ustaw swój klucz API GW2 w ustawieniach dla szczegółów przedmiotów."},
            {"overview", "Przegląd"},
            {"overview_tooltip", "Przegląd aktualnej sesji farmingu"},
            {"total_profit", "Całkowity Zysk"},
            {"total_profit_tooltip", "Całkowity zysk niestandardowy ze wszystkich przedmiotów"},
            {"total_items_count", "Suma Przedmiotów"},
            {"total_items_tooltip", "Całkowita liczba unikalnych przedmiotów śledzonych"},
            {"total_currencies", "Suma Walut"},
            {"total_currencies_tooltip", "Całkowita liczba unikalnych walut śledzonych"},
            {"profit_per_hour_label", "Zysk Na Godzinę"},
            {"profit_per_hour_tooltip", "Zysk na godzinę na podstawie czasu trwania sesji"},
            {"session_duration", "Czas Trwania Sesji"},
            {"session_duration_tooltip", "Czas trwania aktualnej sesji farmingu"},
            {"top_items_profit", "Top Przedmioty (Zysk)"},
            {"top_items_profit_tooltip", "Top 5 przedmiotów według wartości zysku"},
            {"loading", "Ładowanie..."},
            {"coin", "Moneta"},
            {"top_items_count", "Top Przedmioty (Ilość)"},
            {"top_items_count_tooltip", "Top 5 przedmiotów według ilości"},
            {"top_currencies", "Top Waluty"},
            {"top_currencies_tooltip", "Top 5 walut według ilości"},
            {"quick_statistics", "Szybkie Statystyki"},
            {"quick_statistics_tooltip", "Przegląd statystyk farmingu"},
            {"average_item_value", "Średnia Wartość Przedmiotu"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Suma Unikalnych Przedmiotów"},
            {"warning_no_data", "⚠️ Brak załadowanych danych"},
            {"warning_no_data_desc", "Oczekiwanie na dane DRF..."},
            {"export", "Eksportuj"},
            {"export_tooltip", "Eksportuj dane farmingu do pliku"},
            {"export_json", "Eksportuj jako JSON"},
            {"export_csv", "Eksportuj jako CSV"},

            // Items Tab
            {"search_hint", "Szukaj przedmiotów..."},
            {"clear", "Wyczyść"},
            {"sort_count_high", "Sortuj: |Ilość| wysoka"},
            {"sort_count_low", "Sortuj: |Ilość| niska"},
            {"sort_id_up", "Sortuj: ID Przedmiotu wysokie"},
            {"sort_id_down", "Sortuj: ID Przedmiotu niskie"},
            {"sort_name_az", "Sortuj: Nazwa A–Z"},
            {"sort_tooltip", "Sortuj przedmioty według ilości, ID lub nazwy"},
            {"rarity_all", "Rzadkość: wszystkie"},
            {"rarity_basic", "Rzadkość: Podstawowa+"},
            {"rarity_fine", "Rzadkość: Fine+"},
            {"rarity_masterwork", "Rzadkość: Mistrzowska+"},
            {"rarity_rare", "Rzadkość: Rzadka+"},
            {"rarity_exotic", "Rzadkość: Egzotyczna+"},
            {"rarity_ascended", "Rzadkość: Wzniesiona+"},
            {"rarity_legendary", "Rzadkość: Tylko Legendarna"},
            {"rarity_tooltip", "Filtruj przedmioty według minimalnej rzadkości"},
            {"rarity", "Rzadkość"},
            {"type", "Typ"},
            {"vendor_value", "Wartość U Sprzedawcy"},
            {"tp_buy_net", "Zakup TP (Netto)"},
            {"account_bound", "Przypisany do konta"},
            {"yes", "Tak"},
            {"no", "Nie"},
            {"nosell", "Nie do sprzedania"},
            {"favorite", "Ulubiony"},
            {"ignore", "Ignoruj"},

            // Currencies Tab
            {"search_currencies_hint", "Szukaj walut..."},
            {"api_id", "ID API"},
            {"currency_name", "Nazwa Waluty"},
            {"count", "Ilość"},

            // Profit Tab
            {"profits", "Zyski"},
            {"profits_tooltip", "Całkowite zyski z farmingu"},
            {"approx_profits", "Przybliżone Zyski"},
            {"approx_gold_per_hour", "Przybliżone Złoto Na Godzinę"},
            {"trading_profits", "Zyski Handlowe"},
            {"trading_profits_tooltip", "Zyski z Giełdy Handlowej"},
            {"approx_trading_profits_listings", "Przybliżone Zyski Handlowe (Listy)"},
            {"approx_trading_profits_instant", "Przybliżone Zyski Handlowe (Szybka Sprzedaż)"},
            {"trading_details", "Szczegóły Handlu (Koszt Alternatywny)"},
            {"trading_details_tooltip", "Koszt alternatywny używania przedmiotów zamiast sprzedawania"},
            {"lost_profit_vs_tp_sell", "Utracony Zysk (vs Sprzedaż TP)"},
            {"lost_profit_per_hour_vs_tp_sell", "Utracony Zysk Na Godzinę (vs Sprzedaż TP)"},
            {"session_duration_label", "Czas trwania sesji"},
            {"session_duration_tooltip", "Czas trwania aktualnej sesji farmingu"},

            // Filter Tab
            {"sell_method_filters", "Filtry Metody Sprzedaży"},
            {"sellable_to_vendor", "Do sprzedania u sprzedawcy"},
            {"sellable_to_vendor_tooltip", "Pokaż przedmioty do sprzedania u sprzedawcy"},
            {"sellable_on_tp", "Do sprzedania na TP"},
            {"sellable_on_tp_tooltip", "Pokaż przedmioty do sprzedania na Giełdzie Handlowej"},
            {"has_custom_profit", "Ma zysk niestandardowy"},
            {"has_custom_profit_tooltip", "Pokaż przedmioty z wartościami zysku niestandardowego"},
            {"api_knowledge_filters", "Filtry Wiedzy API"},
            {"known_by_api", "Znane przez API"},
            {"known_by_api_tooltip", "Pokaż przedmioty znane przez API GW2"},
            {"unknown_by_api", "Nieznane przez API"},
            {"unknown_by_api_tooltip", "Pokaż przedmioty nieznane przez API GW2"},
            {"item_type_filters", "Filtry Typu Przedmiotu"},
            {"type_armor", "Zbroja"},
            {"type_armor_tooltip", "Pokaż przedmioty zbroi"},
            {"type_weapon", "Broń"},
            {"type_weapon_tooltip", "Pokaż przedmioty broni"},
            {"type_trinket", "Ozdoba"},
            {"type_trinket_tooltip", "Pokaż przedmioty ozdób"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Pokaż przedmioty gizmo"},
            {"type_crafting_material", "Materiał Krawiecki"},
            {"type_crafting_material_tooltip", "Pokaż materiały krawieckie"},
            {"type_consumable", "Przedmiot zużywalny"},
            {"type_consumable_tooltip", "Pokaż przedmioty zużywalne"},
            {"type_gathering_tool", "Narzędzie Zbierania"},
            {"type_gathering_tool_tooltip", "Pokaż narzędzia zbierania"},
            {"type_bag", "Torba"},
            {"type_bag_tooltip", "Pokaż torby"},
            {"type_container", "Kontener"},
            {"type_container_tooltip", "Pokaż kontenery"},
            {"type_mini_pet", "Mini Zwierzątko"},
            {"type_mini_pet_tooltip", "Pokaż mini zwierzątka"},
            {"currency_filters_label", "Filtry Walut"},
            {"currency_main", "Główne Waluty"},
            {"currency_fractal", "Waluty Fraktalne/Rajd/Loch"},
            {"currency_wvw_pvp", "Waluty WvW/PvP"},
            {"currency_map", "Waluty Specyficzne dla Mapy"},
            {"filter_karma", "Karma"},
            {"currency_karma_tooltip", "Pokaż walutę Karma"},
            {"currency_laurel", "Wawrzyn"},
            {"currency_laurel_tooltip", "Pokaż walutę Wawrzyn"},
            {"currency_gem", "Klejnot"},
            {"currency_gem_tooltip", "Pokaż walutę Klejnot"},
            {"currency_fractal_relic", "Relikt Fraktalny"},
            {"currency_fractal_relic_tooltip", "Pokaż walutę Relikt Fraktalny"},
            {"currency_badge_of_honor", "Odznaka Honoru"},
            {"currency_badge_of_honor_tooltip", "Pokaż walutę Odznaka Honoru"},
            {"currency_guild_commendation", "Rekomendacja Gildii"},
            {"currency_guild_commendation_tooltip", "Pokaż walutę Rekomendacja Gildii"},
            {"currency_transmutation_charge", "Ładunek Transmutacji"},
            {"currency_transmutation_charge_tooltip", "Pokaż walutę Ładunek Transmutacji"},
            {"currency_spirit_shards", "Odłamki Ducha"},
            {"currency_spirit_shards_tooltip", "Pokaż walutę Odłamki Ducha"},
            {"currency_unbound_magic", "Niewiązana Magia"},
            {"currency_unbound_magic_tooltip", "Pokaż walutę Niewiązana Magia"},
            {"currency_volatile_magic", "Lotna Magia"},
            {"currency_volatile_magic_tooltip", "Pokaż walutę Lotna Magia"},
            {"currency_airship_parts", "Części Sterowca"},
            {"currency_airship_parts_tooltip", "Pokaż walutę Części Sterowca"},
            {"currency_geode", "Geoda"},
            {"currency_geode_tooltip", "Pokaż walutę Geoda"},
            {"currency_ley_line_crystals", "Kryształy Linii Ley"},
            {"currency_ley_line_crystals_tooltip", "Pokaż walutę Kryształy Linii Ley"},
            {"currency_trade_contracts", "Kontrakty Handlowe"},
            {"currency_trade_contracts_tooltip", "Pokaż walutę Kontrakty Handlowe"},
            {"currency_elegy_mosaic", "Mozaika Elegii"},
            {"currency_elegy_mosaic_tooltip", "Pokaż walutę Mozaika Elegii"},
            {"currency_uncommon_coins", "Niezwykłe Monety"},
            {"currency_uncommon_coins_tooltip", "Pokaż walutę Niezwykłe Monety"},
            {"currency_astral_acclaim", "Astralny Aplauz"},
            {"currency_astral_acclaim_tooltip", "Pokaż walutę Astralny Aplauz"},
            {"currency_pristine_fractal_relics", "Nienaruszone Relikty Fraktalne"},
            {"currency_pristine_fractal_relics_tooltip", "Pokaż walutę Nienaruszone Relikty Fraktalne"},
            {"currency_unstable_fractal_essence", "Niestabilna Esencja Fraktalna"},
            {"currency_unstable_fractal_essence_tooltip", "Pokaż walutę Niestabilna Esencja Fraktalna"},
            {"currency_magnetite_shards", "Odłamki Magnetytu"},
            {"currency_magnetite_shards_tooltip", "Pokaż walutę Odłamki Magnetytu"},
            {"currency_gaeting_crystals", "Kryształy Gaeting"},
            {"currency_gaeting_crystals_tooltip", "Pokaż walutę Kryształy Gaeting"},
            {"currency_prophet_shards", "Odłamki Proroka"},
            {"currency_prophet_shards_tooltip", "Pokaż walutę Odłamki Proroka"},
            {"currency_green_prophet_shards", "Zielone Odłamki Proroka"},
            {"currency_green_prophet_shards_tooltip", "Pokaż walutę Zielone Odłamki Proroka"},
            {"currency_wvw_skirmish_tickets", "Bilety Skirmish WvW"},
            {"currency_wvw_skirmish_tickets_tooltip", "Pokaż walutę Bilety Skirmish WvW"},
            {"currency_proofs_of_heroics", "Dowody Heroizmu"},
            {"currency_proofs_of_heroics_tooltip", "Pokaż walutę Dowody Heroizmu"},
            {"currency_pvp_league_tickets", "Bilety Ligi PvP"},
            {"currency_pvp_league_tickets_tooltip", "Pokaż walutę Bilety Ligi PvP"},
            {"currency_ascended_shards_of_glory", "Wzniesione Odłamki Chwały"},
            {"currency_ascended_shards_of_glory_tooltip", "Pokaż walutę Wzniesione Odłamki Chwały"},
            {"currency_research_notes", "Notatki Badawcze"},
            {"currency_research_notes_tooltip", "Pokaż walutę Notatki Badawcze"},
            {"currency_tyrian_defense_seal", "Pieczęć Obrony Tyrijskiej"},
            {"currency_tyrian_defense_seal_tooltip", "Pokaż walutę Pieczęć Obrony Tyrijskiej"},
            {"currency_testimony_of_desert_heroics", "Świadectwo Heroizmu Pustyni"},
            {"currency_testimony_of_desert_heroics_tooltip", "Pokaż walutę Świadectwo Heroizmu Pustyni"},
            {"currency_testimony_of_jade_heroics", "Świadectwo Heroizmu Jade"},
            {"currency_testimony_of_jade_heroics_tooltip", "Pokaż walutę Świadectwo Heroizmu Jade"},
            {"currency_testimony_of_castoran_heroics", "Świadectwo Heroizmu Castoran"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Pokaż walutę Świadectwo Heroizmu Castoran"},
            {"currency_legendary_insight", "Legendarna Wiedza"},
            {"currency_legendary_insight_tooltip", "Pokaż walutę Legendarna Wiedza"},
            {"currency_tales_of_dungeon_delving", "Opowieści o Eksploracji Lochów"},
            {"currency_tales_of_dungeon_delving_tooltip", "Pokaż walutę Opowieści o Eksploracji Lochów"},
            {"currency_imperial_favor", "Łaska Imperialna"},
            {"currency_imperial_favor_tooltip", "Pokaż walutę Łaska Imperialna"},
            {"currency_canach_coins", "Monety Canach"},
            {"currency_canach_coins_tooltip", "Pokaż walutę Monety Canach"},
            {"currency_ancient_coin", "Starożytna Moneta"},
            {"currency_ancient_coin_tooltip", "Pokaż walutę Starożytna Moneta"},
            {"currency_unusual_coin", "Niezwykła Moneta"},
            {"currency_unusual_coin_tooltip", "Pokaż walutę Niezwykła Moneta"},
            {"currency_jade_sliver", "Odłamek Jadeitu"},
            {"currency_jade_sliver_tooltip", "Pokaż walutę Odłamek Jadeitu"},
            {"currency_static_charge", "Ładunek Statyczny"},
            {"currency_static_charge_tooltip", "Pokaż walutę Ładunek Statyczny"},
            {"currency_pinch_of_stardust", "Szczypta Pyłu Gwiezdnego"},
            {"currency_pinch_of_stardust_tooltip", "Pokaż walutę Szczypta Pyłu Gwiezdnego"},
            {"currency_calcified_gasp", "Skamieniały Westchnienie"},
            {"currency_calcified_gasp_tooltip", "Pokaż walutę Skamieniały Westchnienie"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Pokaż walutę Ursus Oblige"},
            {"currency_gaeting_crystal_janthir", "Kryształ Gaeting (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Pokaż walutę Kryształ Gaeting (Janthir)"},
            {"currency_antiquated_ducat", "Prastary Dukat"},
            {"currency_antiquated_ducat_tooltip", "Pokaż walutę Prastary Dukat"},
            {"currency_aether_rich_sap", "Sok Bogaty w Eter"},
            {"currency_aether_rich_sap_tooltip", "Pokaż walutę Sok Bogaty w Eter"},

            // Additional Filters
            {"additional_filters", "Dodatkowe Filtry"},
            {"account_bound", "Przypisany do konta"},
            {"account_bound_tooltip", "Pokaż przedmioty przypisane do konta"},
            {"not_account_bound", "Nieprzypisany do konta"},
            {"not_account_bound_tooltip", "Pokaż przedmioty nieprzypisane do konta"},
            {"nosell_items", "Nie do sprzedania"},
            {"nosell_items_tooltip", "Pokaż przedmioty nie do sprzedania"},
            {"not_nosell", "Do sprzedania"},
            {"not_nosell_tooltip", "Pokaż przedmioty do sprzedania"},
            {"favorite_items", "Ulubiony"},
            {"favorite_items_tooltip", "Pokaż ulubione przedmioty"},
            {"not_favorite", "Nieulubiony"},
            {"not_favorite_tooltip", "Pokaż nieulubione przedmioty"},
            {"ignored_items", "Ignorowane"},
            {"ignored_items_tooltip", "Pokaż ignorowane przedmioty"},
            {"not_ignored", "Nieignorowane"},
            {"not_ignored_tooltip", "Pokaż nieignorowane przedmioty"},

            // Range Filters
            {"range_filters", "Filtry Zakresu"},
            {"show_range_filters", "Pokaż Filtry Zakresu"},
            {"filter_min_price", "Filtr Min Cena"},
            {"filter_max_price", "Filtr Max Cena"},
            {"filter_min_quantity", "Filtr Min Ilość"},
            {"filter_max_quantity", "Filtr Max Ilość"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Okno"},
            {"show_profit", "Pokaż Zysk"},
            {"show_profit_tooltip", "Wyświetl całkowity zysk w mini oknie"},
            {"show_profit_per_hour", "Pokaż Zysk/Godzina"},
            {"show_profit_per_hour_tooltip", "Wyświetl zysk na godzinę w mini oknie"},
            {"show_tp_sell", "Pokaż Sprzedaż TP (Listy)"},
            {"show_tp_sell_tooltip", "Wyświetl zysk sprzedaży TP (listy) w mini oknie"},
            {"show_tp_instant", "Pokaż Szybką Sprzedaż TP"},
            {"show_tp_instant_tooltip", "Wyświetl zysk szybkiej sprzedaży TP w mini oknie"},
            {"show_total_items", "Pokaż Sumę Przedmiotów"},
            {"show_total_items_tooltip", "Wyświetl całkowitą liczbę przedmiotów w mini oknie"},
            {"show_session_duration", "Pokaż Czas Trwania Sesji"},
            {"show_session_duration_tooltip", "Wyświetl czas trwania sesji w mini oknie"},
            {"window_click_through", "Klikanie przez okno"},
            {"window_click_through_tooltip", "Pozwala klikać przez mini okno do gry"},

            // Main Window Settings
            {"main_window", "Okno Główne"},
            {"click_through", "Klikanie przez"},
            {"click_through_tooltip", "Pozwala klikać przez okno główne do gry"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Zaawansowane Ustawienia UI"},
            {"no_advanced_ui_settings", "(Brak dostępnych zaawansowanych ustawień UI)"},

            // Display Settings
            {"display_settings", "Ustawienia Wyświetlania"},
            {"show_item_icons", "Pokaż Ikony Przedmiotów"},
            {"show_item_icons_tooltip", "Wyświetl ikony przedmiotów na liście"},
            {"show_rarity_border", "Pokaż Obramowanie Rzadkości"},
            {"show_rarity_border_tooltip", "Wyświetl kolorowe obramowanie na podstawie rzadkości przedmiotu"},
            {"enable_grid_view", "Włącz Widok Siatki"},
            {"enable_grid_view_tooltip", "Wyświetl przedmioty w układzie siatki zamiast listy"},
            {"grid_icon_size", "Rozmiar Ikony Siatki"},
            {"grid_icon_size_tooltip", "Rozmiar ikon w widoku siatki"},

            // Count Display Settings
            {"count_display_settings", "Ustawienia Wyświetlania Ilości"},
            {"count_text_color", "Kolor Tekstu Ilości"},
            {"count_text_color_tooltip", "Kolor tekstu ilości"},
            {"count_background_color", "Kolor Tła Ilości"},
            {"count_background_color_tooltip", "Kolor tła ilości"},
            {"count_font_size", "Rozmiar Czcionki Ilości"},
            {"count_font_size_tooltip", "Rozmiar czcionki ilości"},
            {"count_horizontal_alignment", "Wyrównanie Poziome Ilości"},
            {"count_horizontal_alignment_tooltip", "Wyrównanie poziome tekstu ilości"},

            // Gradient Background Settings
            {"gradient_background_settings", "Ustawienia Tła Gradientowego"},
            {"enable_gradient_backgrounds", "Włącz Tła Gradientowe"},
            {"enable_gradient_backgrounds_tooltip", "Włącz tło gradientowe dla okien"},
            {"gradient_top_color", "Górny Kolor Gradientu"},
            {"gradient_top_color_tooltip", "Górny kolor tła gradientowego"},
            {"gradient_bottom_color", "Dolny Kolor Gradientu"},
            {"gradient_bottom_color_tooltip", "Dolny kolor tła gradientowego"},

            // Custom Profit System
            {"custom_profit_system", "System Zysku Niestandardowego"},
            {"enable_custom_profit", "Włącz Zysk Niestandardowy"},
            {"enable_custom_profit_tooltip", "Włącz wartości zysku niestandardowego dla przedmiotów"},

            // Search
            {"search_settings", "Wyszukiwanie"},
            {"enable_search", "Włącz Wyszukiwanie"},
            {"enable_search_tooltip", "Włącz funkcję wyszukiwania"},

            // Ignored Items
            {"ignored_items_settings", "Ignorowane Przedmioty"},
            {"enable_ignored_items", "Włącz Ignorowane Przedmioty"},
            {"enable_ignored_items_tooltip", "Włącz funkcję ignorowanych przedmiotów"},

            // Auto Reset
            {"auto_reset_settings", "Auto Reset"},
            {"enable_auto_reset", "Włącz Auto Reset"},
            {"enable_auto_reset_tooltip", "Automatycznie resetuj sesję farmingu po określonym czasie"},
            {"auto_reset_duration", "Czas Auto Resetu (minuty)"},
            {"auto_reset_duration_tooltip", "Czas w minutach przed auto resetem"},

            // DRF Settings
            {"drf_settings", "Ustawienia DRF"},
            {"drf_token", "Token DRF"},
            {"drf_token_tooltip", "Twój token autoryzacji DRF"},
            {"edit_token", "Edytuj Token"},
            {"save_token", "Zapisz Token"},

            // GW2 API Settings
            {"gw2_api_settings", "Ustawienia API GW2"},
            {"gw2_api_key", "Klucz API GW2"},
            {"gw2_api_key_tooltip", "Twój klucz API GW2 dla szczegółów przedmiotów"},
            {"edit_key", "Edytuj Klucz"},
            {"save_key", "Zapisz Klucz"},

            // Language Settings
            {"language_settings", "Język"},
            {"language_tooltip", "Wybierz język interfejsu"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "Brak skonfigurowanych kont"},
            {"no_profiles_created", "Jeszcze nie utworzono profili"},
            {"count_label", "Ilość:"},
            {"profit_label", "Zysk:"},
            {"no_profit", "Brak zysku"},
            {"vendor_value_label", "Wartość U Sprzedawcy:"},
            {"tp_sell_gross_label", "Sprzedaż TP (Brutto):"},
            {"tp_sell_net_label", "Sprzedaż TP (Netto):"},
            {"tp_buy_gross_label", "Zakup TP (Brutto):"},
            {"tp_buy_net_label", "Zakup TP (Netto):"},
            {"ignored_items_label", "Ignorowane Przedmioty:"},
            {"ignored_currencies_label", "Ignorowane Waluty:"},
            {"total_items_label", "Suma Przedmiotów:"},
            {"total_currencies_label", "Suma Walut:"},
            {"total_profit_label", "Całkowity Zysk:"},
            {"tp_sell_profit_label", "Zysk Sprzedaży TP:"},
            {"vendor_profit_label", "Zysk Sprzedaży U Sprzedawcy:"},
            {"profit_per_hour_label", "Zysk Na Godzinę:"},
            {"opportunity_cost_profit_label", "Zysk Kosztu Alternatywnego:"},
            {"opportunity_cost_profit_per_hour_label", "Zysk Kosztu Alternatywnego/Godzina:"},
            {"custom_profit_feature_placeholder", "Funkcja zaimplementowana - UI nastąpi"},
            {"custom_profit_items_header", "Przedmioty z Niestandardowym Zyskiem"},
            {"custom_profit_currencies_header", "Waluty z Niestandardowym Zyskiem"},
            {"add_custom_profit_item", "Dodaj Niestandardowy Zysk dla Przedmiotu"},
            {"add_custom_profit_currency", "Dodaj Niestandardowy Zysk dla Waluty"},
            {"custom_profit_set_profit", "Ustaw Zysk"},
            {"custom_profit_remove", "Usuń"},
            {"custom_profit_value", "Wartość Zysku (Miedź)"},
            {"custom_profit_set_tooltip", "Ustaw niestandardową wartość zysku dla tego przedmiotu"},
            {"custom_profit_remove_tooltip", "Usuń niestandardową wartość zysku dla tego przedmiotu"},
            {"no_custom_profit_items", "(Brak przedmiotów z niestandardowym zyskiem)"},
            {"no_custom_profit_currencies", "(Brak walut z niestandardowym zyskiem)"},
            {"clear_all_custom_profits", "Wyczyść wszystkie niestandardowe zyski"},
            {"clear_all_custom_profits_tooltip", "Wyczyść wszystkie wartości niestandardowego zysku"},
            {"tabs_settings", "Inne Zakładki"},
            {"tabs_description", "Pokaż lub ukryj inne zakładki"},
            {"enable_ignored_tab", "Włącz zakładkę Ignorowane"},
            {"enable_ignored_tab_tooltip", "Pokaż zakładkę Ignorowane w widoku głównym"},
            {"custom_profit_settings", "Niestandardowy Zysk"},
            {"overview_label", "Przegląd:"},
            {"total_profit_label_simple", "Całkowity Zysk"},
            {"total_items_label_simple", "Suma Przedmiotów"},
            {"total_currencies_label_simple", "Suma Walut"},
            {"profit_per_hour_label_simple", "Zysk Na Godzinę"},
            {"session_duration_label_simple", "Czas Trwania Sesji"},
            {"export_label", "Eksportuj:"},
            {"quick_actions", "Szybkie Akcje:"},
            {"reset_confirm", "Czy na pewno chcesz zresetować wszystkie ustawienia do domyślnych?"},
            {"reset_warning", "Ta akcja nie może być cofnięta."},
            {"export_settings", "Eksportuj Ustawienia do Pliku:"},
            {"import_settings", "Importuj Ustawienia z Pliku:"},
            {"edit_account", "Edytuj Konto: %s"},
            {"account_name", "Nazwa Konta:"},
            {"drf_token_label", "Token DRF:"},
            {"gw2_api_key_label", "Klucz API GW2:"},
            {"reload_config", "Przeładuj Konfigurację:"},
            {"auto_reset_label", "Auto Reset:"},
            {"next_reset_utc", "Następny zaplanowany reset (UTC): %s"},
            {"favorites_ui", "UI Ulubionych:"},
            {"favorites_colors", "Kolory Ulubionych:"},
            {"visual_enhancements", "Ulepszenia Wizualne:"},
            {"mini_window_widget", "Mini Okno (Widget Overlay):"},
            {"main_window_label", "Okno Główne:"},
            {"profiles_description", "Profile pozwalają zapisywać różne konfiguracje i szybko przełączać się między nimi."},
            {"create_new_profile", "Utwórz Nowy Profil:"},
            {"current_profile", "Aktualny Profil: %s"},
            {"auto_backup", "Automatycznie twórz kopię zapasową ustawień przed dużymi zmianami"},
            {"notifications", "Skonfiguruj powiadomienia w grze dla ważnych wydarzeń"},
            {"profit_goal", "Cel Zysku:"},
            {"reset_warning_label", "Ostrzeżenie Resetu:"},
            {"session_complete", "Sesja Zakończona:"},
            {"manage_ignored_items", "Zarządzaj ignorowanymi przedmiotami"},
            {"manage_ignored_currencies", "Zarządzaj ignorowanymi walutami"},
            {"rarity_label", "Rzadkość: %s"},
            {"type_label", "Typ: %d"},
            {"account_bound_label", "Przypisany do konta: %s"},
            {"nosell_label", "Nie do sprzedania: %s"},
            {"sell_method_filters_label", "Filtry Metody Sprzedaży:"},
            {"api_knowledge_filters_label", "Filtry Wiedzy API:"},
            {"additional_filters_label", "Dodatkowe Filtry:"},
            {"item_type_filters_label", "Filtry Typu Przedmiotu:"},
            {"currency_filters_label", "Filtry Walut:"},
            {"price_range", "Zakres Ceny (Miedź):"},
            {"quantity_range", "Zakres Ilości:"},
            {"debug_info", "Informacje Debugowania"},
            {"drf_status", "Status DRF: %s"},
            {"drf_reconnect_count", "Licznik Ponownych Połączeń DRF: %d"},
            {"gw2_api_status", "Status API GW2: %s"},
            {"gw2_api_reconnect_count", "Licznik Ponownych Połączeń API GW2: %d"},
            {"session_duration_debug", "Czas Trwania Sesji: %s"},
            {"gw2_memory", "Pamięć Procesu GW2: %zu MB"},
            {"gw2_api_request_count", "Licznik Żądań API GW2: %d"},
            {"ignored_items_count", "Ignorowane Przedmioty: %d"},
            {"ignored_currencies_count", "Ignorowane Waluty: %d"},
            {"drf_logs", "Logi DRF:"},
            {"last_100_entries", "(Ostatnie 100 wpisów)"},
            {"gw2_api_logs", "Logi API GW2:"},
            {"item_currency_details", "Szczegóły Przedmiotu/Waluty (Pierwsze 5):"},
            {"item_label", "Przedmiot %d: %s (Ilość: "},
            {"loaded_label", ", Załadowano: %s)"},
            {"currency_label", "Waluta %d: %s (Ilość: "},
            {"custom_profit_items", "Przedmioty Zysku Niestandardowego (Pierwsze 5):"},
            {"custom_profit_item", "Przedmiot %d: %s (Zysk Niestandardowy: "},
            {"no_custom_profit_items", "(Brak przedmiotów zysku niestandardowego)"},
            {"ignored_items_debug", "Ignorowane Przedmioty (Pierwsze 5):"},
            {"yes_label", "Tak"},
            {"no_label", "Nie"},
            {"profits_label", "Zyski:"},
            {"profits_tooltip", "Całkowity zysk z farmingu"},
            {"approx_profits_label", "Przybliżony Zysk:"},
            {"approx_profits_tooltip", "Całkowity zysk z wartości zysku niestandardowego"},
            {"approx_gold_per_hour_label", "Przybliżone Złoto Na Godzinę:"},
            {"approx_gold_per_hour_tooltip", "Zysk na godzinę oparty na czasie trwania sesji"},
            {"trading_profits_label", "Zyski z Handlu:"},
            {"trading_profits_tooltip", "Zyski ze sprzedaży przedmiotów na Trading Post"},
            {"approx_trading_profits_listings_label", "Przybliżone Zyski z Handlu (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Całkowity zysk jeśli sprzedane via TP listings"},
            {"approx_trading_profits_instant_label", "Przybliżone Zyski z Handlu (Sprzedaż Natychmiastowa):"},
            {"approx_trading_profits_instant_tooltip", "Całkowity zysk jeśli sprzedane via TP buy orders natychmiastowe"},
            {"trading_details_label", "Szczegóły Handlu (Koszt Alternatywny):"},
            {"trading_details_tooltip", "Utracony zysk przez niesprzedanie via TP listings"},
            {"lost_profit_vs_tp_sell_label", "Utracony Zysk (vs Sprzedaż TP):"},
            {"lost_profit_vs_tp_sell_tooltip", "Złoto = utracony zysk, Czerwony = zysk zyskany vs sprzedaż TP"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Utracony Zysk Na Godzinę (vs Sprzedaż TP):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Koszt alternatywny na godzinę"},
            {"session_duration_debug_label", "Czas trwania sesji: %s"},
            {"session_duration_debug_tooltip", "Aktualny czas trwania sesji farmingu"},
            {"tab_items", "Przedmioty"},
            {"manage_ignored_items", "Zarządzaj ignorowanymi przedmiotami"},
            {"clear_all_ignored_items", "Wyczyść wszystkie ignorowane przedmioty"},
            {"unignore_item", "Przestań ignorować przedmiot"},
            {"tab_currencies", "Waluty"},
            {"manage_ignored_currencies", "Zarządzaj ignorowanymi walutami"},
            {"clear_all_ignored_currencies", "Wyczyść wszystkie ignorowane waluty"},
            {"unignore_currency", "Przestań ignorować walutę"},
            {"sell_method_filters_label", "Filtry Metody Sprzedaży:"},
            {"api_knowledge_filters_label", "Filtry Wiedzy API:"},
            {"additional_filters_label", "Dodatkowe Filtry:"},
            {"item_type_filters_label", "Filtry Typu Przedmiotu:"},
            {"currency_filters_label", "Filtry Walut:"},
            {"price_range", "Zakres Ceny (Miedź):"},
            {"quantity_range", "Zakres Ilości:"},
            {"debug_information", "Informacje Debugowania"},
            {"drf_status_label", "Status DRF: %s"},
            {"drf_status_tooltip", "Aktualny status połączenia DRF"},
            {"drf_reconnect_count_label", "Licznik Reconnect DRF: %d"},
            {"drf_reconnect_count_tooltip", "Liczba prób reconnect DRF"},
            {"gw2_api_status_label", "Status API GW2: %s"},
            {"gw2_api_status_tooltip", "Aktualny status połączenia API GW2"},
            {"gw2_api_reconnect_count_label", "Licznik Reconnect API GW2: %d"},
            {"gw2_api_reconnect_count_tooltip", "Liczba prób reconnect API GW2"},
            {"session_duration_debug", "Czas Trwania Sesji: %s"},
            {"session_duration_debug_tooltip", "Aktualny czas trwania sesji farmingu"},
            {"gw2_process_memory_label", "Pamięć Procesu GW2: %zu MB"},
            {"gw2_process_memory_tooltip", "Aktualne użycie pamięci procesu GW2"},
            {"gw2_api_request_count_label", "Licznik Żądań API GW2: %d"},
            {"gw2_api_request_count_tooltip", "Całkowita liczba żądań API GW2"},
            {"ignored_items_debug_label", "Ignorowane Przedmioty: %d"},
            {"ignored_items_debug_tooltip", "Liczba ignorowanych przedmiotów"},
            {"ignored_currencies_debug_label", "Ignorowane Waluty: %d"},
            {"ignored_currencies_debug_tooltip", "Liczba ignorowanych walut"},
            {"drf_logs_label", "Logi DRF:"},
            {"clear_drf_logs", "Wyczyść Logi DRF"},
            {"clear_drf_logs_tooltip", "Wyczyść wszystkie wpisy logów DRF"},
            {"last_100_entries", "(Ostatnie 100 wpisów)"},
            {"gw2_api_logs_label", "Logi API GW2:"},
            {"clear_gw2_logs", "Wyczyść Logi GW2"},
            {"clear_gw2_logs_tooltip", "Wyczyść wszystkie wpisy logów API GW2"},
            {"settings_label", "Ustawienia:"},
            {"api_key_label", "Klucz API: %s"},
            {"api_key_tooltip", "Status klucza API GW2"},
            {"not_set", "Nie ustawiony"},
            {"set", "Ustawiony"},
            {"drf_token_label", "Token DRF: %s"},
            {"drf_token_tooltip", "Status tokenu DRF"},
            {"toggle_hotkey_label", "Klawisz Przełączania: %s"},
            {"toggle_hotkey_tooltip", "Klawisz przełączania okna głównego"},
            {"auto_reset_mode_label", "Tryb Auto-Reset: %d"},
            {"auto_reset_mode_tooltip", "Aktualny tryb automatycznego resetu"},
            {"next_reset_label", "Następny Reset: %s"},
            {"next_reset_tooltip", "Czas następnego planowanego resetu (UTC)"},
            {"fake_drf_server_label", "Fałszywy Serwer DRF:"},
            {"use_fake_drf_server", "Użyj fałszywego serwera DRF"},
            {"use_fake_drf_server_tooltip", "Tylko do celów testowych"},
            {"reset_all_data", "Zresetuj Wszystkie Dane"},
            {"reset_all_data_tooltip", "Zresetuj wszystkie dane farmingu"},
            {"coin", "Moneta"},
            {"rarity_label", "Rzadkość: %s"},
            {"type_label", "Typ: %d"},
            {"account_bound_label", "Przypisane do Konta: %s"},
            {"nosell_label", "NoSell: %s"},
            {"item_id_label", "ID Przedmiotu: %d"},
            {"currency_id_label", "ID Waluty: %d"},
            {"rarity_tooltip", "Filtruj przedmioty według minimalnej rzadkości"},
            {"yes_label", "Tak"},
            {"no_label", "Nie"},
            {"sort_price_down", "Sortuj: Cena przedmiotu malejąco"},
            {"sort_price_up", "Sortuj: Cena przedmiotu rosnąco"},
            {"sort_count_high", "Sortuj: |Licznik| wysoki"},
            {"sort_count_low", "Sortuj: |Licznik| niski"},
            {"sort_name_az", "Sortuj: Nazwa A–Z"},
            {"sort_tooltip", "Sortuj przedmioty według licznika, ID lub nazwy"},
            {"rarity_all", "Rzadkość: wszystkie"},
            {"rarity_basic", "Rzadkość: Podstawowe+"},
            {"rarity_fine", "Rzadkość: Dobre+"},
            {"rarity_masterwork", "Rzadkość: Mistrzowskie+"},
            {"rarity_rare", "Rzadkość: Rzadkie+"},
            {"rarity_exotic", "Rzadkość: Egzotyczne+"},
            {"rarity_ascended", "Rzadkość: Wzniesione+"},
            {"rarity_legendary", "Rzadkość: Tylko legendarny"},
            {"rarity_tooltip", "Filtruj przedmioty według minimalnej rzadkości"},
            {"search_items_hint", "Szukaj przedmiotów..."},
            {"column_icon", "Ikona"},
            {"column_name", "Nazwa"},
            {"column_count", "Licznik"},
            {"column_profit", "Zysk"},
            {"column_favorite", "Ulubione"},
            {"column_ignore", "Ignoruj"},
            {"toggle_favorite", "Przełącz ulubione"},
            {"toggle_ignore", "Przełącz ignoruj"},
            {"vendor_value_format", "Wartość sprzedawcy: %s"},
            {"tp_sell_gross_format", "Sprzedaż TP (Brutto): %s"},
            {"tp_sell_net_format", "Sprzedaż TP (Netto): %s"},
            {"tp_buy_gross_format", "Zakup TP (Brutto): %s"},
            {"tp_buy_net_format", "Zakup TP (Netto): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Ustawienia Ulubionych"},
            {"favorites_first", "Ulubione najpierw"},
            {"favorites_first_tooltip", "Pokazuje ulubione jako pierwsze na listach przedmiotów/walut"},
            {"enable_favorite_text_color", "Włącz kolor tekstu ulubionych"},
            {"enable_favorite_text_color_tooltip", "Wyróżnia ulubione przedmioty/waluty niestandardowym kolorem tekstu"},
            {"text_color", "Kolor Tekstu"},
            {"enable_favorite_row_color", "Włącz kolor wiersza ulubionych"},
            {"enable_favorite_row_color_tooltip", "Wyróżnia ulubione przedmioty/waluty niestandardowym kolorem tła wiersza"},
            {"row_color", "Kolor Wiersza"},
            
            // Filter - Additional
            {"filter_favorite", "Ulubione"},
            {"filter_favorite_tooltip", "Pokaż ulubione przedmioty (poza zakładką Ulubione)"},
            {"filter_not_favorite", "Nieulubione"},
            {"filter_not_favorite_tooltip", "Pokaż nieulubione przedmioty"},
            {"filter_research_notes", "Notatki Badawcze"},
            {"filter_research_notes_tooltip", "Pokaż walutę notatki badawcze"},
            {"range_filters", "Filtry Zakresu"},
            {"range_filters_tooltip", "Pokaż filtry zakresu ceny i ilości"},
            {"filter_min_price_tooltip", "Filtr minimalnej ceny (0 = wyłączony)"},
            {"filter_max_price_tooltip", "Filtr maksymalnej ceny (0 = wyłączony)"},
            {"filter_min_quantity_tooltip", "Filtr minimalnej ilości (0 = wyłączony)"},
            {"filter_max_quantity_tooltip", "Filtr maksymalnej ilości (0 = wyłączony)"},
            {"filter_min_price", "Cena Min"},
            {"filter_max_price", "Cena Max"},
            {"filter_min_quantity", "Min Ilość"},
            {"filter_max_quantity", "Max Ilość"},
            {"gold", "Złoto"},
            {"silver", "Srebro"},
            {"copper", "Miedź"},
            
            // Summary Tab - Table Columns
            {"column_label", "Etykieta"},
            {"column_value", "Wartość"},
            {"column_item", "Przedmiot"},
            {"column_count", "Ilość"},
            {"column_currency", "Waluta"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Przedmioty według zysku"},
            {"top_items_count_header", "Top Przedmioty (Ilość)"},
            {"top_currencies_count_header", "Top Waluty (Ilość)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 przedmiotów według wartości zysku"},
            {"top_items_count_tooltip", "Top 10 przedmiotów według ilości"},
            {"top_currencies_count_tooltip", "Top 10 walut według ilości"},
            
            // Settings Tab - General
            {"show_main_window", "Pokaż główne okno"},
            {"reset_all", "Resetuj wszystko"},
            {"reset_all_tooltip", "Zresetuj wszystkie ustawienia do wartości domyślnych"},
            {"export", "Eksportuj"},
            {"export_tooltip", "Eksportuj ustawienia do pliku JSON"},
            {"import", "Importuj"},
            {"import_tooltip", "Importuj ustawienia z pliku JSON"},
            {"save", "Zapisz"},
            {"save_tooltip", "Zapisz bieżące ustawienia"},
            {"general_settings", "Ustawienia ogólne"},
            {"account_management", "Zarządzanie kontami"},
            {"add_account", "+ Dodaj konto"},
            {"remove_account", "- Usuń konto"},
            {"save_account", "Zapisz konto"},
            {"reload_drf_token", "Przeładuj token DRF"},
            {"reload_gw2_api_key", "Przeładuj klucz API GW2"},
            {"reset_settings", "Auto Reset"},
            {"visual_settings", "Ustawienia wizualne"},
            {"gradient_backgrounds", "Tła gradientowe"},
            {"gradient_backgrounds_tooltip", "Włącza płynne tła gradientowe dla nowoczesnego wyglądu"},
            {"top_gradient_color", "Górny kolor gradientu"},
            {"top_gradient_color_tooltip", "Górny kolor gradientu"},
            {"bottom_gradient_color", "Dolny kolor gradientu"},
            {"bottom_gradient_color_tooltip", "Dolny kolor gradientu"},
            {"show_item_icons", "Pokaż ikony przedmiotów (render GW2)"},
            {"show_item_icons_tooltip", "Ładuje ikony z render.guildwars2.com przez Nexus."},
            {"icon_size", "Rozmiar ikony"},
            {"icon_size_tooltip", "Rozmiar ikon przedmiotów w pikselach (16-96)"},
            {"show_rarity_borders", "Pokaż obramowania rzadkości"},
            {"show_rarity_borders_tooltip", "Pokazuje kolorowe obramowania wokół ikon na podstawie rzadkości"},
            {"rarity_border_thickness", "Grubość obramowania rzadkości"},
            {"rarity_border_thickness_tooltip", "Dostosuj grubość obramowań rzadkości (1.0 - 10.0)"},
            {"enable_grid_view_items", "Włącz widok siatki (Przedmioty)"},
            {"enable_grid_view_items_tooltip", "Przełącz między widokiem listy a siatki na karcie Przedmioty"},
            {"grid_icon_size_items", "Rozmiar ikony siatki (Przedmioty)"},
            {"grid_icon_size_items_tooltip", "Rozmiar ikon w widoku siatki dla Przedmiotów (16-128)"},
            {"enable_grid_view_currencies", "Włącz widok siatki (Waluty)"},
            {"enable_grid_view_currencies_tooltip", "Przełącz między widokiem listy a siatki na karcie Waluty"},
            {"grid_icon_size_currencies", "Rozmiar ikony siatki (Waluty)"},
            {"grid_icon_size_currencies_tooltip", "Rozmiar ikon w widoku siatki dla Walut (16-128)"},
            {"show_mini_window", "Pokaż mini okno"},
            {"show_mini_window_tooltip", "Pokazuje mały widget nakładki z kluczowymi statystykami"},
            {"mini_window_show_profit", "Pokaż zysk"},
            {"mini_window_show_profit_tooltip", "Pokaż całkowity zysk w mini oknie"},
            {"mini_window_show_profit_per_hour", "Pokaż zysk/godz"},
            {"mini_window_show_profit_per_hour_tooltip", "Pokaż zysk na godzinę w mini oknie"},
            {"mini_window_show_tp_sell", "Pokaż sprzedaż TP (Listy)"},
            {"mini_window_show_tp_sell_tooltip", "Pokaż zysk sprzedaży TP (listy) w mini oknie"},
            {"mini_window_show_tp_instant", "Pokaż natychmiastową sprzedaż TP"},
            {"mini_window_show_tp_instant_tooltip", "Pokaż zysk natychmiastowej sprzedaży TP w mini oknie"},
            {"mini_window_show_total_items", "Pokaż całkowitą liczbę przedmiotów"},
            {"mini_window_show_total_items_tooltip", "Pokaż całkowitą liczbę przedmiotów w mini oknie"},
            {"mini_window_show_session_duration", "Pokaż czas trwania sesji"},
            {"mini_window_show_session_duration_tooltip", "Pokaż czas trwania sesji w mini oknie"},
            {"mini_window_click_through", "Okno klikalne"},
            {"mini_window_click_through_tooltip", "Pozwala klikać przez mini okno do gry"},
            {"main_window_click_through", "Klikalne"},
            {"main_window_click_through_tooltip", "Pozwala klikać przez główne okno do gry"},
            {"settings_profiles", "Profile ustawień"},
            {"select_profile", "Wybierz profil, aby zastosować jego ustawienia"},
            {"create_new_profile", "Utwórz nowy profil"},
            {"create_new_profile_tooltip", "Utwórz nowy profil z bieżącymi ustawieniami"},
            {"create", "Utwórz"},
            {"update_profile", "Zaktualizuj profil"},
            {"update_profile_tooltip", "Zaktualizuj bieżący profil z bieżącymi ustawieniami"},
            {"delete_profile", "Usuń profil"},
            {"delete_profile_tooltip", "Usuń bieżący profil"},
            {"automatic_backups", "Automatyczne kopie zapasowe"},
            {"enable_automatic_backups", "Włącz automatyczne kopie zapasowe"},
            {"enable_automatic_backups_tooltip", "Automatycznie twórz kopie zapasowe przed zmianami"},
            {"backup_frequency", "Częstotliwość kopii zapasowych"},
            {"backup_frequency_tooltip", "Jak często tworzyć automatyczne kopie zapasowe"},
            {"max_backups", "Maksymalne kopie zapasowe"},
            {"max_backups_tooltip", "Maksymalna liczba kopii zapasowych do zachowania (1-20)"},
            {"notification_settings", "Ustawienia powiadomień"},
            {"enable_notifications", "Włącz powiadomienia"},
            {"enable_notifications_tooltip", "Włącz powiadomienia w grze"},
            {"notify_profit_goal", "Powiadom po osiągnięciu celu zysku"},
            {"notify_profit_goal_tooltip", "Powiadom, gdy osiągniesz cel zysku"},
            {"profit_goal_gold", "Cel zysku (Złoto)"},
            {"profit_goal_gold_tooltip", "Cel zysku w monetach złota (1-1000)"},
            {"notify_reset_warning", "Powiadom przed resetem"},
            {"notify_reset_warning_tooltip", "Powiadom przed automatycznym resetem"},
            {"reset_warning_minutes", "Ostrzeżenie resetu (Minuty)"},
            {"reset_warning_minutes_tooltip", "Minuty przed resetem, aby pokazać ostrzeżenie (1-60)"},
            {"notify_session_complete", "Powiadom po czasie trwania sesji"},
            {"notify_session_complete_tooltip", "Powiadom po farmieniu przez określony czas"},
            {"session_complete_hours", "Sesja zakończona (Godziny)"},
            {"session_complete_hours_tooltip", "Godziny farmienia przed powiadomieniem (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Sprzedawalny u handlarza"},
            {"filter_sellable_to_vendor_tooltip", "Pokaż przedmioty sprzedawalne u handlarza"},
            {"filter_sellable_on_tp", "Sprzedawalny na TP"},
            {"filter_sellable_on_tp_tooltip", "Pokaż przedmioty sprzedawalne na Giełdzie Handlowej"},
            {"filter_custom_profit", "Niestandardowy zysk"},
            {"filter_custom_profit_tooltip", "Pokaż przedmioty z niestandardowym zyskiem"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Znany przez API"},
            {"filter_known_by_api_tooltip", "Pokaż przedmioty znane przez API GW2"},
            {"filter_unknown_by_api", "Nieznany przez API"},
            {"filter_unknown_by_api_tooltip", "Pokaż przedmioty nieznane przez API GW2"},
            
            // Filter - Additional
            {"show_ignored_items", "Pokaż ignorowane przedmioty"},
            {"show_ignored_items_tooltip", "Pokaż ignorowane przedmioty/waluty w zakładkach Przedmioty i Waluty (wyłącz, aby ukryć). Różnica od filtra 'Ignorowane': Ten filtr steruje wyświetlaniem w zakładkach Przedmioty/Waluty, filtr 'Ignorowane' steruje wyświetlaniem w zakładce Filtr."},
            
            // Filter - Item Types
            {"filter_type_armor", "Zbroja"},
            {"filter_type_armor_tooltip", "Pokaż przedmioty zbroi"},
            {"filter_type_backpack", "Plecak"},
            {"filter_type_backpack_tooltip", "Pokaż przedmioty plecaka"},
            {"filter_type_bag", "Torba"},
            {"filter_type_bag_tooltip", "Pokaż torby"},
            {"filter_type_container", "Kontener"},
            {"filter_type_container_tooltip", "Pokaż kontenery"},
            {"filter_type_consumable", "Przedmiot zużywalny"},
            {"filter_type_consumable_tooltip", "Pokaż przedmioty zużywalne"},
            {"filter_type_crafting_material", "Materiał rzemieślniczy"},
            {"filter_type_crafting_material_tooltip", "Pokaż materiały rzemieślnicze"},
            {"filter_type_gathering_tool", "Narzędzie zbierania"},
            {"filter_type_gathering_tool_tooltip", "Pokaż narzędzia zbierania"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Pokaż przedmioty gizmo"},
            {"filter_type_gizmo_container", "Kontener Gizmo"},
            {"filter_type_gizmo_container_tooltip", "Pokaż przedmioty kontener gizmo"},
            {"filter_type_mini_pet", "Mini Zwierzątko"},
            {"filter_type_mini_pet_tooltip", "Pokaż mini zwierzątka"},
            {"filter_type_tool", "Narzędzie"},
            {"filter_type_tool_tooltip", "Pokaż przedmioty narzędzia"},
            {"filter_type_trinket", "Ozdoba"},
            {"filter_type_trinket_tooltip", "Pokaż przedmioty ozdób"},
            {"filter_type_trophy", "Trofeum"},
            {"filter_type_trophy_tooltip", "Pokaż przedmioty trofeów"},
            {"filter_type_unlock", "Odblokowanie"},
            {"filter_type_unlock_tooltip", "Pokaż przedmioty odblokowania"},
            {"filter_type_upgrade_component", "Komponent ulepszenia"},
            {"filter_type_upgrade_component_tooltip", "Pokaż komponenty ulepszenia"},
            {"filter_type_weapon", "Broń"},
            {"filter_type_weapon_tooltip", "Pokaż przedmioty broni"},
            
            // Filter - Currencies
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Pokaż walutę Karma"},
            {"filter_laurel", "Wawrzyn"},
            {"filter_laurel_tooltip", "Pokaż walutę Wawrzyn"},
            {"filter_gem", "Klejnot"},
            {"filter_gem_tooltip", "Pokaż walutę Klejnot"},
            {"filter_fractal_relic", "Relikt fraktalny"},
            {"filter_fractal_relic_tooltip", "Pokaż walutę Relikt fraktalny"},
            {"filter_badge_of_honor", "Odznaka honoru"},
            {"filter_badge_of_honor_tooltip", "Pokaż walutę Odznaka honoru"},
            {"filter_guild_commendation", "Rekomendacja gildii"},
            {"filter_guild_commendation_tooltip", "Pokaż walutę Rekomendacja gildii"},
            {"filter_transmutation_charge", "Ładunek transmutacji"},
            {"filter_transmutation_charge_tooltip", "Pokaż walutę Ładunek transmutacji"},
            {"filter_spirit_shards", "Odłamki ducha"},
            {"filter_spirit_shards_tooltip", "Pokaż walutę Odłamki ducha"},
            {"filter_unbound_magic", "Niewiązana magia"},
            {"filter_unbound_magic_tooltip", "Pokaż walutę Niewiązana magia"},
            {"filter_volatile_magic", "Lotna magia"},
            {"filter_volatile_magic_tooltip", "Pokaż walutę Lotna magia"},
            {"filter_airship_parts", "Części sterowca"},
            {"filter_airship_parts_tooltip", "Pokaż walutę Części sterowca"},
            {"filter_geode", "Geoda"},
            {"filter_geode_tooltip", "Pokaż walutę Geoda"},
            {"filter_ley_line_crystals", "Kryształy linii ley"},
            {"filter_ley_line_crystals_tooltip", "Pokaż walutę Kryształy linii ley"},
            {"filter_trade_contracts", "Kontrakty handlowe"},
            {"filter_trade_contracts_tooltip", "Pokaż walutę Kontrakty handlowe"},
            {"filter_elegy_mosaic", "Mozaika elegii"},
            {"filter_elegy_mosaic_tooltip", "Pokaż walutę Mozaika elegii"},
            {"filter_uncommon_coins", "Niezwykłe monety"},
            {"filter_uncommon_coins_tooltip", "Pokaż walutę Niezwykłe monety"},
            {"filter_astral_acclaim", "Astralny aplauz"},
            {"filter_astral_acclaim_tooltip", "Pokaż walutę Astralny aplauz"},
            
            // Debug Tab
            {"total_tracked_items", "Całkowita liczba śledzonych przedmiotów"},
            {"total_tracked_items_tooltip", "Całkowita liczba śledzonych przedmiotów"},
            {"total_tracked_currencies", "Całkowita liczba śledzonych walut"},
            {"total_tracked_currencies_tooltip", "Całkowita liczba śledzonych walut"},
            {"total_custom_profit", "Całkowity niestandardowy zysk"},
            {"total_custom_profit_tooltip", "Całkowity niestandardowy zysk"},
            {"total_tp_sell_profit", "Całkowity zysk sprzedaży TP"},
            {"total_tp_sell_profit_tooltip", "Całkowity zysk sprzedaży TP"},
            {"total_vendor_sell_profit", "Całkowity zysk sprzedaży handlarza"},
            {"total_vendor_sell_profit_tooltip", "Całkowity zysk sprzedaży handlarza"},
            {"profit_per_hour_calculation", "Obliczanie zysku na godzinę"},
            {"profit_per_hour_calculation_tooltip", "Obliczanie zysku na godzinę"},
            {"opportunity_cost_vs_tp_sell", "Koszt alternatywny vs sprzedaż TP"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Koszt alternatywny vs sprzedaż TP"},
            {"opportunity_cost_per_hour", "Koszt alternatywny na godzinę"},
            {"opportunity_cost_per_hour_tooltip", "Koszt alternatywny na godzinę"},
            {"first_5_tracked_items", "Pierwsze 5 śledzonych przedmiotów i walut ze szczegółami"},
            {"first_5_tracked_items_tooltip", "Pierwsze 5 śledzonych przedmiotów i walut ze szczegółami"},
            {"first_5_custom_profit", "Pierwsze 5 przedmiotów z niestandardowym zyskiem"},
            {"first_5_custom_profit_tooltip", "Pierwsze 5 przedmiotów z niestandardowym zyskiem"},
            {"first_5_ignored_items", "Pierwsze 5 ignorowanych przedmiotów"},
            {"first_5_ignored_items_tooltip", "Pierwsze 5 ignorowanych przedmiotów"},
            
            // Debug Settings
            {"debug_settings", "Ustawienia Debugowania"},
            {"enable_debug_tab", "Włącz zakładkę debugowania"},
            {"enable_debug_tab_tooltip", "Pokazuje zakładkę debugowania z dodatkowymi informacjami"},
            
            // Currencies Tab
            {"gold_format", "Złoto: %lld"},
            {"count_format", "Ilość: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Przełącz ulubione"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Przełącz ignoruj"},
            
            // Additional Filters
            {"filter_account_bound", "Wiązane z kontem"},
            {"filter_account_bound_tooltip", "Pokaż przedmioty związane z kontem"},
            {"filter_not_account_bound", "Niewiązane z kontem"},
            {"filter_not_account_bound_tooltip", "Pokaż przedmioty niezwiązane z kontem"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "Pokaż przedmioty NoSell"},
            {"filter_not_nosell", "Nie NoSell"},
            {"filter_not_nosell_tooltip", "Pokaż przedmioty sprzedawalne"},
            {"filter_ignored", "Ignorowane"},
            {"filter_ignored_tooltip", "Pokaż ignorowane przedmioty"},
            {"filter_not_ignored", "Nie Ignorowane"},
            {"filter_not_ignored_tooltip", "Pokaż nieignorowane przedmioty"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Nienaruszone relikty fraktalne"},
            {"filter_pristine_fractal_relics_tooltip", "Pokaż walutę Nienaruszone relikty fraktalne"},
            {"filter_unstable_fractal_essence", "Niestabilna esencja fraktalna"},
            {"filter_unstable_fractal_essence_tooltip", "Pokaż walutę Niestabilna esencja fraktalna"},
            {"filter_magnetite_shards", "Odłamki magnetytu"},
            {"filter_magnetite_shards_tooltip", "Pokaż walutę Odłamki magnetytu"},
            {"filter_gaeting_crystals", "Kryształy Gaeting"},
            {"filter_gaeting_crystals_tooltip", "Pokaż walutę Kryształy Gaeting"},
            {"filter_prophet_shards", "Odłamki proroka"},
            {"filter_prophet_shards_tooltip", "Pokaż walutę Odłamki proroka"},
            {"filter_green_prophet_shards", "Zielone odłamki proroka"},
            {"filter_green_prophet_shards_tooltip", "Pokaż walutę Zielone odłamki proroka"},
            {"filter_wvw_skirmish_tickets", "Bilety potyczek WvW"},
            {"filter_wvw_skirmish_tickets_tooltip", "Pokaż walutę Bilety potyczek WvW"},
            {"filter_proofs_of_heroics", "Dowody heroizmu"},
            {"filter_proofs_of_heroics_tooltip", "Pokaż walutę Dowody heroizmu"},
            {"filter_pvp_league_tickets", "Bilety ligi PvP"},
            {"filter_pvp_league_tickets_tooltip", "Pokaż walutę Bilety ligi PvP"},
            {"filter_ascended_shards_of_glory", "Wznoszące odłamki chwały"},
            {"filter_ascended_shards_of_glory_tooltip", "Pokaż walutę Wznoszące odłamki chwały"},
            {"filter_tyrian_defense_seal", "Pieczęć obrony tyriańskiej"},
            {"filter_tyrian_defense_seal_tooltip", "Pokaż walutę Pieczęć obrony tyriańskiej"},
            {"filter_testimony_of_desert_heroics", "Świadectwo heroizmu pustynnego"},
            {"filter_testimony_of_desert_heroics_tooltip", "Pokaż walutę Świadectwo heroizmu pustynnego"},
            {"filter_testimony_of_jade_heroics", "Świadectwo heroizmu jadeitowego"},
            {"filter_testimony_of_jade_heroics_tooltip", "Pokaż walutę Świadectwo heroizmu jadeitowego"},
            {"filter_testimony_of_castoran_heroics", "Świadectwo heroizmu kastorańskiego"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Pokaż walutę Świadectwo heroizmu kastorańskiego"},
            {"filter_legendary_insight", "Legendarna wnikliwość"},
            {"filter_legendary_insight_tooltip", "Pokaż walutę Legendarna wnikliwość"},
            {"filter_tales_of_dungeon_delving", "Opowieści o eksploracji lochów"},
            {"filter_tales_of_dungeon_delving_tooltip", "Pokaż walutę Opowieści o eksploracji lochów"},
            {"filter_imperial_favor", "Łaska imperialna"},
            {"filter_imperial_favor_tooltip", "Pokaż walutę Łaska imperialna"},
            {"filter_canach_coins", "Monety Canach"},
            {"filter_canach_coins_tooltip", "Pokaż walutę Monety Canach"},
            {"filter_ancient_coin", "Starożytna moneta"},
            {"filter_ancient_coin_tooltip", "Pokaż walutę Starożytna moneta"},
            {"filter_unusual_coin", "Niezwykła moneta"},
            {"filter_unusual_coin_tooltip", "Pokaż walutę Niezwykła moneta"},
            {"filter_jade_sliver", "Odłamek jadeitu"},
            {"filter_jade_sliver_tooltip", "Pokaż walutę Odłamek jadeitu"},
            {"filter_static_charge", "Ładunek statyczny"},
            {"filter_static_charge_tooltip", "Pokaż walutę Ładunek statyczny"},
            {"filter_pinch_of_stardust", "Szczypta pyłu gwiazdowego"},
            {"filter_pinch_of_stardust_tooltip", "Pokaż walutę Szczypta pyłu gwiazdowego"},
            {"filter_calcified_gasp", "Skamieniały oddech"},
            {"filter_calcified_gasp_tooltip", "Pokaż walutę Skamieniały oddech"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Pokaż walutę Ursus Oblige"},
            {"filter_gaeting_crystal_janthir", "Kryształ Gaeting (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Pokaż walutę Kryształ Gaeting (Janthir)"},
            {"filter_antiquated_ducat", "Zastarzały dukat"},
            {"filter_antiquated_ducat_tooltip", "Pokaż walutę Zastarzały dukat"},
            {"filter_aether_rich_sap", "Sok bogaty w eter"},
            {"filter_aether_rich_sap_tooltip", "Pokaż walutę Sok bogaty w eter"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Zresetuj wszystko"},
            {"reset_all_tooltip", "Zresetuj wszystkie ustawienia do wartości domyślnych"},
            {"reset_confirm", "Czy na pewno chcesz zresetować wszystkie ustawienia?"},
            {"reset_warning", "Tej akcji nie można cofnąć."},
            {"yes_reset", "Tak, zresetuj"},
            {"cancel", "Anuluj"},
            {"export", "Eksportuj"},
            {"export_tooltip", "Eksportuj ustawienia do pliku JSON"},
            {"export_settings", "Eksportuj ustawienia"},
            {"import", "Importuj"},
            {"import_settings", "Importuj ustawienia"},
            {"save", "Zapisz"},
            {"save_tooltip", "Zapisz bieżące ustawienia"},
            
            // Settings Tab - General
            {"general_settings", "Ustawienia ogólne"},
            {"account_management", "Zarządzanie kontami"},
            {"account_prefix", "Konto"},
            {"remove_account", "- Usuń konto"},
            {"save_account", "Zapisz konto"},
            {"reconnect_drf_token", "Ponownie połącz z DRF z bieżącym tokenem"},
            {"reload_gw2_api_key_tooltip", "Przeładuj klucz API GW2 do pobierania danych przedmiotów"},
            {"reset_settings", "Zresetuj ustawienia"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Nigdy (tylko ręczne resetowanie)"},
            {"auto_reset_on_load", "Przy ładowaniu dodatku"},
            {"auto_reset_daily", "Codzienne resetowanie (00:00 UTC)"},
            {"auto_reset_weekly", "Tygodniowo (Pon 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Tygodniowo NA WvW (Sob 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Tygodniowo EU WvW (Pią 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Tygodniowo bonus mapy (Czw 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minuty po ostatnim rozładowaniu"},
            {"auto_reset_custom_days", "Niestandardowe (dni)"},
            {"auto_reset_tooltip", "Kiedy automatycznie resetować liczniki farmienia"},
            {"minutes_after_unload_tooltip", "Minuty po rozładowaniu dodatku przed automatycznym resetem"},
            {"reset_interval_days", "Interwał resetowania (dni)"},
            {"reset_interval_days_tooltip", "Niestandardowy interwał resetowania w dniach (1-30 dni)"},
            
            // Visual Settings
            {"top_gradient_color", "Góra"},
            {"top_gradient_color_tooltip", "Górny kolor gradientu"},
            {"bottom_gradient_color", "Dół"},
            {"bottom_gradient_color_tooltip", "Dolny kolor gradientu"},
            {"icon_size", "Rozmiar ikony"},
            {"icon_size_tooltip", "Rozmiar ikon przedmiotów w pikselach (16-96)"},
            {"border_size", "Rozmiar obramowania"},
            {"border_size_tooltip", "Dostosuj grubość obramowań rzadkości (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Przełącz między widokiem listy a siatki na karcie Przedmioty"},
            {"grid_icon_size_items", "Rozmiar ikony siatki (Przedmioty)"},
            {"grid_icon_size_items_tooltip", "Rozmiar ikon w widoku siatki dla Przedmiotów (16-128)"},
            {"grid_icon_size_currencies", "Rozmiar ikony siatki (Waluty)"},
            {"grid_icon_size_currencies_tooltip", "Rozmiar ikon w widoku siatki dla Walut (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Pokaż mini okno"},
            {"show_mini_window_tooltip", "Pokazuje mały widget nakładki z kluczowymi statystykami"},
            {"mini_window_show_profit", "Pokaż zysk"},
            {"mini_window_show_profit_tooltip", "Pokaż całkowity zysk w mini oknie"},
            {"mini_window_show_profit_per_hour", "Pokaż zysk/godz"},
            {"mini_window_show_profit_per_hour_tooltip", "Pokaż zysk na godzinę w mini oknie"},
            {"mini_window_show_tp_sell", "Pokaż sprzedaż TP (Listy)"},
            {"mini_window_show_tp_sell_tooltip", "Pokaż zysk sprzedaży TP (listy) w mini oknie"},
            {"mini_window_show_tp_instant", "Pokaż natychmiastową sprzedaż TP"},
            {"mini_window_show_tp_instant_tooltip", "Pokaż zysk natychmiastowej sprzedaży TP w mini oknie"},
            {"mini_window_show_total_items", "Pokaż łączną liczbę przedmiotów"},
            {"mini_window_show_total_items_tooltip", "Pokaż łączną liczbę przedmiotów w mini oknie"},
            {"mini_window_show_session_duration", "Pokaż czas trwania sesji"},
            {"mini_window_show_session_duration_tooltip", "Pokaż czas trwania sesji w mini oknie"},
            {"mini_window_click_through", "Okno klikalne"},
            {"mini_window_click_through_tooltip", "Pozwala klikać przez mini okno do gry"},
            
            // Main Window
            {"main_window_label", "Okno główne"},
            {"main_window_click_through", "Klikalne"},
            {"main_window_click_through_tooltip", "Pozwala klikać przez okno główne do gry"},
            
            // Settings Profiles
            {"settings_profiles", "Profile ustawień"},
            {"default_no_profile", "Domyślne (Brak profilu)"},
            {"select_profile_tooltip", "Wybierz profil, aby zastosować jego ustawienia"},
            {"create", "Utwórz"},
            {"create_tooltip", "Utwórz nowy profil z bieżącymi ustawieniami"},
            {"update_profile", "Zaktualizuj profil"},
            {"update_profile_tooltip", "Zaktualizuj bieżący profil z bieżącymi ustawieniami"},
            {"delete_profile", "Usuń profil"},
            {"delete_profile_tooltip", "Usuń bieżący profil"},
            
            // Automatic Backups
            {"automatic_backups", "Automatyczne kopie zapasowe"},
            {"enable_automatic_backups", "Włącz automatyczne kopie zapasowe"},
            {"enable_automatic_backups_tooltip", "Automatycznie twórz kopie zapasowe przed zmianami"},
            {"backup_frequency", "Częstotliwość kopii zapasowych"},
            {"backup_frequency_tooltip", "Jak często tworzyć automatyczne kopie zapasowe"},
            {"backup_manual_only", "Tylko ręcznie"},
            {"backup_daily", "Codziennie"},
            {"backup_weekly", "Tygodniowo"},
            {"max_backup_count", "Maks. liczba kopii"},
            {"max_backup_count_tooltip", "Maksymalna liczba kopii zapasowych do zachowania (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Ustawienia powiadomień"},
            {"enable_notifications", "Włącz powiadomienia"},
            {"enable_notifications_tooltip", "Włącz powiadomienia w grze"},
            {"profit_goal", "Cel zysku"},
            {"notify_profit_goal", "Powiadom po osiągnięciu celu zysku"},
            {"notify_profit_goal_tooltip", "Powiadom, gdy osiągniesz cel zysku"},
            {"profit_goal_gold", "Cel zysku (złoto)"},
            {"profit_goal_gold_tooltip", "Cel zysku w monetach złota (1-1000)"},
            {"reset_warning_label", "Ostrzeżenie resetowania"},
            {"notify_reset_warning", "Powiadom przed resetem"},
            {"notify_reset_warning_tooltip", "Powiadom przed automatycznym resetem"},
            {"warning_minutes", "Minuty ostrzeżenia"},
            {"warning_minutes_tooltip", "Minuty przed resetem, aby pokazać ostrzeżenie (1-60)"},
            {"session_complete", "Sesja zakończona"},
            {"notify_session_complete", "Powiadom po czasie trwania sesji"},
            {"notify_session_complete_tooltip", "Powiadom po farmieniu przez określony czas"},
            {"session_hours", "Godziny sesji"},
            {"session_hours_tooltip", "Godziny farmienia przed powiadomieniem (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Szukaj walut..."},
            {"clear_search", "Wyczyść"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Szukaj ulubionych przedmiotów..."},
            {"search_favorite_currencies_hint", "Szukaj ulubionych walut..."},
            {"clear_search_favorites", "Wyczyść"},
        };
        return translations;
    }
}
