// ---------------------------------------------------------------------------
// localization_it.cpp – Italian translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetItalianTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Disconnesso"},
            {"status_connecting", "Connessione..."},
            {"status_connected", "Connesso"},
            {"status_auth_failed", "Autenticazione fallita – verifica il token"},
            {"status_reconnecting", "Riconnessione..."},
            {"status_error", "Errore"},
            {"status_unknown", "Sconosciuto"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Profitto"},
            {"profit_per_hour", "Profitto/Ora"},
            {"tp_sell", "Vendita TP"},
            {"tp_instant", "Vendita Istantanea TP"},
            {"total_items", "Totale Oggetti"},
            {"session", "Sessione"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "API GW2"},
            {"session_time_label", "Tempo Sessione"},
            {"reset_button", "Resetta"},
            {"reset_tooltip", "Resetta tutti i contatori di farming (reset manuale)"},

            // Tabs
            {"tab_summary", "Panoramica"},
            {"tab_items", "Oggetti"},
            {"tab_currencies", "Valute"},
            {"tab_profit", "Profitto"},
            {"tab_favorites", "Preferiti"},
            {"tab_ignored", "Ignorati"},
            {"tab_filter", "Filtro"},
            {"tab_custom_profit", "Profitto Personalizzato"},
            {"tab_debug", "Debug"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF non connesso"},
            {"warning_drf_not_connected_desc", "Questo plugin richiede DRF per la trasmissione dati."},
            {"warning_drf_install", "Installa DRF tramite Nexus Addon Manager o https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ Token DRF non valido"},
            {"warning_drf_token_invalid_desc", "Per favore verifica il tuo Token DRF nelle Impostazioni."},
            {"warning_gw2_api_key_not_set", "⚠️ Chiave API GW2 non impostata"},
            {"warning_gw2_api_key_not_set_desc", "Per favore imposta la tua Chiave API GW2 nelle Impostazioni per i dettagli degli oggetti."},
            {"overview", "Panoramica"},
            {"overview_tooltip", "Panoramica della sessione di farming attuale"},
            {"total_profit", "Profitto Totale"},
            {"total_profit_tooltip", "Profitto personalizzato totale da tutti gli oggetti"},
            {"total_items_count", "Totale Oggetti"},
            {"total_items_tooltip", "Numero totale di oggetti unici tracciati"},
            {"total_currencies", "Totale Valute"},
            {"total_currencies_tooltip", "Numero totale di valute uniche tracciate"},
            {"profit_per_hour_label", "Profitto Per Ora"},
            {"profit_per_hour_tooltip", "Profitto per ora basato sulla durata della sessione"},
            {"session_duration", "Durata Sessione"},
            {"session_duration_tooltip", "Durata della sessione di farming attuale"},
            {"top_items_profit", "Top Oggetti (Profitto)"},
            {"top_items_profit_tooltip", "Top 5 oggetti per valore di profitto"},
            {"loading", "Caricamento..."},
            {"coin", "Moneta"},
            {"top_items_count", "Top Oggetti (Quantità)"},
            {"top_items_count_tooltip", "Top 5 oggetti per quantità"},
            {"top_currencies", "Top Valute"},
            {"top_currencies_tooltip", "Top 5 valute per quantità"},
            {"quick_statistics", "Statistiche Rapide"},
            {"quick_statistics_tooltip", "Panoramica delle statistiche di farming"},
            {"average_item_value", "Valore Medio Oggetto"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Totale Oggetti Unici"},
            {"warning_no_data", "⚠️ Nessun dato caricato"},
            {"warning_no_data_desc", "In attesa dei dati DRF..."},
            {"export", "Esporta"},
            {"export_tooltip", "Esporta i dati di farming in un file"},
            {"export_json", "Esporta come JSON"},
            {"export_csv", "Esporta come CSV"},

            // Items Tab
            {"search_hint", "Cerca oggetti..."},
            {"clear", "Cancella"},
            {"sort_count_high", "Ordina: |Qta| alto"},
            {"sort_count_low", "Ordina: |Qta| basso"},
            {"sort_id_up", "Ordina: ID Oggetto alto"},
            {"sort_id_down", "Ordina: ID Oggetto basso"},
            {"sort_name_az", "Ordina: Nome A–Z"},
            {"sort_tooltip", "Ordina oggetti per quantità, ID o nome"},
            {"rarity_all", "Rarità: tutte"},
            {"rarity_basic", "Rarità: Base+"},
            {"rarity_fine", "Rarità: Fine+"},
            {"rarity_masterwork", "Rarità: Maestro+"},
            {"rarity_rare", "Rarità: Raro+"},
            {"rarity_exotic", "Rarità: Esotico+"},
            {"rarity_ascended", "Rarità: Ascensione+"},
            {"rarity_legendary", "Rarità: Solo Leggendario"},
            {"rarity_tooltip", "Filtra oggetti per rarità minima"},
            {"rarity", "Rarità"},
            {"type", "Tipo"},
            {"vendor_value", "Valore Mercante"},
            {"tp_buy_net", "Acquisto TP (Netto)"},
            {"account_bound", "Legato all'Account"},
            {"yes", "Sì"},
            {"no", "No"},
            {"nosell", "Non vendibile"},
            {"favorite", "Preferito"},
            {"ignore", "Ignora"},

            // Currencies Tab
            {"search_currencies_hint", "Cerca valute..."},
            {"api_id", "ID API"},
            {"currency_name", "Nome Valuta"},
            {"count", "Quantità"},

            // Profit Tab
            {"profits", "Profitti"},
            {"profits_tooltip", "Profitti totali dal farming"},
            {"approx_profits", "Profitti Appross."},
            {"approx_gold_per_hour", "Oro Appross. Per Ora"},
            {"trading_profits", "Profitti di Scambio"},
            {"trading_profits_tooltip", "Profitti dal Posto di Scambio"},
            {"approx_trading_profits_listings", "Profitti di Scambio Appross. (Liste)"},
            {"approx_trading_profits_instant", "Profitti di Scambio Appross. (Vendita Istantanea)"},
            {"trading_details", "Dettagli di Scambio (Costo Opportunità)"},
            {"trading_details_tooltip", "Costo opportunità di usare gli oggetti invece di venderli"},
            {"lost_profit_vs_tp_sell", "Profitto Perso (vs Vendita TP)"},
            {"lost_profit_per_hour_vs_tp_sell", "Profitto Perso Per Ora (vs Vendita TP)"},
            {"session_duration_label", "Durata sessione"},
            {"session_duration_tooltip", "Durata della sessione di farming attuale"},

            // Filter Tab
            {"sell_method_filters", "Filtri Metodo Vendita"},
            {"sellable_to_vendor", "Vendibile al mercante"},
            {"sellable_to_vendor_tooltip", "Mostra oggetti vendibili al mercante"},
            {"sellable_on_tp", "Vendibile su TP"},
            {"sellable_on_tp_tooltip", "Mostra oggetti vendibili sul Posto di Scambio"},
            {"has_custom_profit", "Ha profitto personalizzato"},
            {"has_custom_profit_tooltip", "Mostra oggetti con valori di profitto personalizzati"},
            {"api_knowledge_filters", "Filtri Conoscenza API"},
            {"known_by_api", "Conosciuto da API"},
            {"known_by_api_tooltip", "Mostra oggetti conosciuti dall'API GW2"},
            {"unknown_by_api", "Sconosciuto da API"},
            {"unknown_by_api_tooltip", "Mostra oggetti non conosciuti dall'API GW2"},
            {"item_type_filters", "Filtri Tipo Oggetto"},
            {"type_armor", "Armatura"},
            {"type_armor_tooltip", "Mostra oggetti armatura"},
            {"type_weapon", "Arma"},
            {"type_weapon_tooltip", "Mostra oggetti arma"},
            {"type_trinket", "Monile"},
            {"type_trinket_tooltip", "Mostra oggetti monile"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Mostra oggetti gizmo"},
            {"type_crafting_material", "Materiale di Creazione"},
            {"type_crafting_material_tooltip", "Mostra materiali di creazione"},
            {"type_consumable", "Consumabile"},
            {"type_consumable_tooltip", "Mostra consumabili"},
            {"type_gathering_tool", "Strumento di Raccolta"},
            {"type_gathering_tool_tooltip", "Mostra strumenti di raccolta"},
            {"type_bag", "Borsa"},
            {"type_bag_tooltip", "Mostra borse"},
            {"type_container", "Contenitore"},
            {"type_container_tooltip", "Mostra contenitori"},
            {"type_mini_pet", "Mini Animale Domestico"},
            {"type_mini_pet_tooltip", "Mostra mini animali domestici"},
            {"currency_filters", "Filtri Valute"},
            {"currency_karma", "Karma"},
            {"currency_karma_tooltip", "Mostra valuta Karma"},
            {"currency_laurel", "Alloro"},
            {"currency_laurel_tooltip", "Mostra valuta Alloro"},
            {"currency_gem", "Gemma"},
            {"currency_gem_tooltip", "Mostra valuta Gemma"},
            {"currency_fractal_relic", "Reliquia Frattale"},
            {"currency_fractal_relic_tooltip", "Mostra valuta Reliquia Frattale"},
            {"currency_badge_of_honor", "Distintivo d'Onore"},
            {"currency_badge_of_honor_tooltip", "Mostra valuta Distintivo d'Onore"},
            {"currency_guild_commendation", "Encomio Gilda"},
            {"currency_guild_commendation_tooltip", "Mostra valuta Encomio Gilda"},
            {"currency_transmutation_charge", "Carica di Trasmutazione"},
            {"currency_transmutation_charge_tooltip", "Mostra valuta Carica di Trasmutazione"},
            {"currency_spirit_shards", "Frammenti di Spirito"},
            {"currency_spirit_shards_tooltip", "Mostra valuta Frammenti di Spirito"},
            {"currency_unbound_magic", "Magia Non Vincolata"},
            {"currency_unbound_magic_tooltip", "Mostra valuta Magia Non Vincolata"},
            {"currency_volatile_magic", "Magia Volatile"},
            {"currency_volatile_magic_tooltip", "Mostra valuta Magia Volatile"},
            {"currency_airship_parts", "Parti di Dirigibile"},
            {"currency_airship_parts_tooltip", "Mostra valuta Parti di Dirigibile"},
            {"currency_geode", "Geode"},
            {"currency_geode_tooltip", "Mostra valuta Geode"},
            {"currency_ley_line_crystals", "Cristalli Linea Ley"},
            {"currency_ley_line_crystals_tooltip", "Mostra valuta Cristalli Linea Ley"},
            {"currency_trade_contracts", "Contratti Commerciali"},
            {"currency_trade_contracts_tooltip", "Mostra valuta Contratti Commerciali"},
            {"currency_elegy_mosaic", "Mosaico Elegia"},
            {"currency_elegy_mosaic_tooltip", "Mostra valuta Mosaico Elegia"},
            {"currency_uncommon_coins", "Monete Non Comuni"},
            {"currency_uncommon_coins_tooltip", "Mostra valuta Monete Non Comuni"},
            {"currency_astral_acclaim", "Acclamazione Astrale"},
            {"currency_astral_acclaim_tooltip", "Mostra valuta Acclamazione Astrale"},
            {"currency_pristine_fractal_relics", "Reliquie Frattali Pristine"},
            {"currency_pristine_fractal_relics_tooltip", "Mostra valuta Reliquie Frattali Pristine"},
            {"currency_unstable_fractal_essence", "Essenza Frattale Instabile"},
            {"currency_unstable_fractal_essence_tooltip", "Mostra valuta Essenza Frattale Instabile"},
            {"currency_magnetite_shards", "Frammenti di Magnetite"},
            {"currency_magnetite_shards_tooltip", "Mostra valuta Frammenti di Magnetite"},
            {"currency_gaeting_crystals", "Cristalli Gaeting"},
            {"currency_gaeting_crystals_tooltip", "Mostra valuta Cristalli Gaeting"},
            {"currency_prophet_shards", "Frammenti di Profeta"},
            {"currency_prophet_shards_tooltip", "Mostra valuta Frammenti di Profeta"},
            {"currency_green_prophet_shards", "Frammenti di Profeta Verdi"},
            {"currency_green_prophet_shards_tooltip", "Mostra valuta Frammenti di Profeta Verdi"},
            {"currency_wvw_skirmish_tickets", "Biglietti Skirmish WvW"},
            {"currency_wvw_skirmish_tickets_tooltip", "Mostra valuta Biglietti Skirmish WvW"},
            {"currency_proofs_of_heroics", "Prove di Eroismo"},
            {"currency_proofs_of_heroics_tooltip", "Mostra valuta Prove di Eroismo"},
            {"currency_pvp_league_tickets", "Biglietti Lega PvP"},
            {"currency_pvp_league_tickets_tooltip", "Mostra valuta Biglietti Lega PvP"},
            {"currency_ascended_shards_of_glory", "Frammenti di Gloria Ascensione"},
            {"currency_ascended_shards_of_glory_tooltip", "Mostra valuta Frammenti di Gloria Ascensione"},
            {"currency_research_notes", "Note di Ricerca"},
            {"currency_research_notes_tooltip", "Mostra valuta Note di Ricerca"},
            {"currency_tyrian_defense_seal", "Sigillo Difesa Tirenio"},
            {"currency_tyrian_defense_seal_tooltip", "Mostra valuta Sigillo Difesa Tirenio"},
            {"currency_testimony_of_desert_heroics", "Testimonianza Eroismo del Deserto"},
            {"currency_testimony_of_desert_heroics_tooltip", "Mostra valuta Testimonianza Eroismo del Deserto"},
            {"currency_testimony_of_jade_heroics", "Testimonianza Eroismo di Giada"},
            {"currency_testimony_of_jade_heroics_tooltip", "Mostra valuta Testimonianza Eroismo di Giada"},
            {"currency_testimony_of_castoran_heroics", "Testimonianza Eroismo Castorano"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Mostra valuta Testimonianza Eroismo Castorano"},
            {"currency_legendary_insight", "Intuizione Leggendaria"},
            {"currency_legendary_insight_tooltip", "Mostra valuta Intuizione Leggendaria"},
            {"currency_tales_of_dungeon_delving", "Racconti di Esplorazione Dungeon"},
            {"currency_tales_of_dungeon_delving_tooltip", "Mostra valuta Racconti di Esplorazione Dungeon"},
            {"currency_imperial_favor", "Favore Imperiale"},
            {"currency_imperial_favor_tooltip", "Mostra valuta Favore Imperiale"},
            {"currency_canach_coins", "Monete Canach"},
            {"currency_canach_coins_tooltip", "Mostra valuta Monete Canach"},
            {"currency_ancient_coin", "Moneta Antica"},
            {"currency_ancient_coin_tooltip", "Mostra valuta Moneta Antica"},
            {"currency_unusual_coin", "Moneta Insolita"},
            {"currency_unusual_coin_tooltip", "Mostra valuta Moneta Insolita"},
            {"currency_jade_sliver", "Scheggia di Giada"},
            {"currency_jade_sliver_tooltip", "Mostra valuta Scheggia di Giada"},
            {"currency_static_charge", "Carica Statica"},
            {"currency_static_charge_tooltip", "Mostra valuta Carica Statica"},
            {"currency_pinch_of_stardust", "Pizzico di Polvere Stellare"},
            {"currency_pinch_of_stardust_tooltip", "Mostra valuta Pizzico di Polvere Stellare"},
            {"currency_calcified_gasp", "Respiro Calcificato"},
            {"currency_calcified_gasp_tooltip", "Mostra valuta Respiro Calcificato"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Mostra valuta Ursus Oblige"},
            {"currency_gaeting_crystal_janthir", "Cristallo Gaeting (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Mostra valuta Cristallo Gaeting (Janthir)"},
            {"currency_antiquated_ducat", "Ducato Antico"},
            {"currency_antiquated_ducat_tooltip", "Mostra valuta Ducato Antico"},
            {"currency_aether_rich_sap", "Linfa Ricca di Etere"},
            {"currency_aether_rich_sap_tooltip", "Mostra valuta Linfa Ricca di Etere"},

            // Additional Filters
            {"additional_filters", "Filtri Aggiuntivi"},
            {"account_bound", "Legato all'Account"},
            {"account_bound_tooltip", "Mostra oggetti legati all'account"},
            {"not_account_bound", "Non Legato all'Account"},
            {"not_account_bound_tooltip", "Mostra oggetti non legati all'account"},
            {"nosell_items", "Non vendibile"},
            {"nosell_items_tooltip", "Mostra oggetti non vendibili"},
            {"not_nosell", "Vendibile"},
            {"not_nosell_tooltip", "Mostra oggetti vendibili"},
            {"favorite_items", "Preferito"},
            {"favorite_items_tooltip", "Mostra oggetti preferiti"},
            {"not_favorite", "Non Preferito"},
            {"not_favorite_tooltip", "Mostra oggetti non preferiti"},
            {"ignored_items", "Ignorato"},
            {"ignored_items_tooltip", "Mostra oggetti ignorati"},
            {"not_ignored", "Non Ignorato"},
            {"not_ignored_tooltip", "Mostra oggetti non ignorati"},

            // Range Filters
            {"range_filters", "Filtri Intervallo"},
            {"show_range_filters", "Mostra Filtri Intervallo"},
            {"filter_min_price", "Filtro Prezzo Min"},
            {"filter_max_price", "Filtro Prezzo Max"},
            {"filter_min_quantity", "Filtro Quantità Min"},
            {"filter_max_quantity", "Filtro Quantità Max"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Finestra"},
            {"show_profit", "Mostra Profitto"},
            {"show_profit_tooltip", "Mostra profitto totale nella mini finestra"},
            {"show_profit_per_hour", "Mostra Profitto/Ora"},
            {"show_profit_per_hour_tooltip", "Mostra profitto per ora nella mini finestra"},
            {"show_tp_sell", "Mostra Vendita TP (Liste)"},
            {"show_tp_sell_tooltip", "Mostra profitto vendita TP (liste) nella mini finestra"},
            {"show_tp_instant", "Mostra Vendita Istantanea TP"},
            {"show_tp_instant_tooltip", "Mostra profitto vendita istantanea TP nella mini finestra"},
            {"show_total_items", "Mostra Totale Oggetti"},
            {"show_total_items_tooltip", "Mostra quantità totale oggetti nella mini finestra"},
            {"show_session_duration", "Mostra Durata Sessione"},
            {"show_session_duration_tooltip", "Mostra durata sessione nella mini finestra"},
            {"window_click_through", "Clic attraverso finestra"},
            {"window_click_through_tooltip", "Permette di cliccare attraverso la mini finestra verso il gioco"},

            // Main Window Settings
            {"main_window", "Finestra Principale"},
            {"click_through", "Clic attraverso"},
            {"click_through_tooltip", "Permette di cliccare attraverso la finestra principale verso il gioco"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Impostazioni UI Avanzate"},
            {"no_advanced_ui_settings", "(Nessuna impostazione UI avanzata disponibile)"},

            // Display Settings
            {"display_settings", "Impostazioni Visualizzazione"},
            {"show_item_icons", "Mostra Icone Oggetti"},
            {"show_item_icons_tooltip", "Mostra icone oggetti nella lista"},
            {"show_rarity_border", "Mostra Bordo Rarità"},
            {"show_rarity_border_tooltip", "Mostra bordo colorato basato sulla rarità dell'oggetto"},
            {"enable_grid_view", "Attiva Vista Griglia"},
            {"enable_grid_view_tooltip", "Mostra oggetti in layout griglia invece di lista"},
            {"grid_icon_size", "Dimensione Icona Griglia"},
            {"grid_icon_size_tooltip", "Dimensione delle icone in vista griglia"},

            // Count Display Settings
            {"count_display_settings", "Impostazioni Visualizzazione Quantità"},
            {"count_text_color", "Colore Testo Quantità"},
            {"count_text_color_tooltip", "Colore del testo quantità"},
            {"count_background_color", "Colore Sfondo Quantità"},
            {"count_background_color_tooltip", "Colore dello sfondo quantità"},
            {"count_font_size", "Dimensione Font Quantità"},
            {"count_font_size_tooltip", "Dimensione del font quantità"},
            {"count_horizontal_alignment", "Allineamento Orizzontale Quantità"},
            {"count_horizontal_alignment_tooltip", "Allineamento orizzontale del testo quantità"},

            // Gradient Background Settings
            {"gradient_background_settings", "Impostazioni Sfondo Gradiente"},
            {"enable_gradient_backgrounds", "Attiva Sfondi Gradiente"},
            {"enable_gradient_backgrounds_tooltip", "Attiva sfondo gradiente per le finestre"},
            {"gradient_top_color", "Colore Superiore Gradiente"},
            {"gradient_top_color_tooltip", "Colore superiore dello sfondo gradiente"},
            {"gradient_bottom_color", "Colore Inferiore Gradiente"},
            {"gradient_bottom_color_tooltip", "Colore inferiore dello sfondo gradiente"},

            // Custom Profit System
            {"custom_profit_system", "Sistema Profitto Personalizzato"},
            {"enable_custom_profit", "Attiva Profitto Personalizzato"},
            {"enable_custom_profit_tooltip", "Attiva valori di profitto personalizzati per gli oggetti"},

            // Search
            {"search_settings", "Ricerca"},
            {"enable_search", "Attiva Ricerca"},
            {"enable_search_tooltip", "Attiva funzionalità di ricerca"},

            // Ignored Items
            {"ignored_items_settings", "Oggetti Ignorati"},
            {"enable_ignored_items", "Attiva Oggetti Ignorati"},
            {"enable_ignored_items_tooltip", "Attiva funzionalità oggetti ignorati"},

            // Auto Reset
            {"auto_reset_settings", "Auto Reset"},
            {"enable_auto_reset", "Attiva Auto Reset"},
            {"enable_auto_reset_tooltip", "Resetta automaticamente la sessione di farming dopo una durata"},
            {"auto_reset_duration", "Durata Auto Reset (minuti)"},
            {"auto_reset_duration_tooltip", "Durata in minuti prima dell'auto reset"},

            // DRF Settings
            {"drf_settings", "Impostazioni DRF"},
            {"drf_token", "Token DRF"},
            {"drf_token_tooltip", "Il tuo token di autenticazione DRF"},
            {"edit_token", "Modifica Token"},
            {"save_token", "Salva Token"},

            // GW2 API Settings
            {"gw2_api_settings", "Impostazioni API GW2"},
            {"gw2_api_key", "Chiave API GW2"},
            {"gw2_api_key_tooltip", "La tua chiave API GW2 per i dettagli degli oggetti"},
            {"edit_key", "Modifica Chiave"},
            {"save_key", "Salva Chiave"},

            // Language Settings
            {"language_settings", "Lingua"},
            {"language_tooltip", "Seleziona lingua interfaccia"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "Nessun account configurato"},
            {"no_profiles_created", "Nessun profilo creato ancora"},
            {"count_label", "Quantità:"},
            {"profit_label", "Profitto:"},
            {"no_profit", "Nessun profitto"},
            {"vendor_value_label", "Valore Mercante:"},
            {"tp_sell_gross_label", "Vendita TP (Lordo):"},
            {"tp_sell_net_label", "Vendita TP (Netto):"},
            {"tp_buy_gross_label", "Acquisto TP (Lordo):"},
            {"tp_buy_net_label", "Acquisto TP (Netto):"},
            {"ignored_items_label", "Oggetti Ignorati:"},
            {"ignored_currencies_label", "Valute Ignorate:"},
            {"total_items_label", "Totale Oggetti:"},
            {"total_currencies_label", "Totale Valute:"},
            {"total_profit_label", "Profitto Totale:"},
            {"tp_sell_profit_label", "Profitto Vendita TP:"},
            {"vendor_profit_label", "Profitto Vendita Mercante:"},
            {"profit_per_hour_label", "Profitto Per Ora:"},
            {"opportunity_cost_profit_label", "Profitto Costo Opportunità:"},
            {"opportunity_cost_profit_per_hour_label", "Profitto Costo Opportunità/Ora:"},
            {"custom_profit_feature_placeholder", "Funzionalità implementata - UI da aggiungere"},
            {"overview_label", "Panoramica:"},
            {"total_profit_label_simple", "Profitto Totale"},
            {"total_items_label_simple", "Totale Oggetti"},
            {"total_currencies_label_simple", "Totale Valute"},
            {"profit_per_hour_label_simple", "Profitto Per Ora"},
            {"session_duration_label_simple", "Durata Sessione"},
            {"export_label", "Esporta:"},
            {"quick_actions", "Azioni Rapide:"},
            {"reset_confirm", "Sei sicuro di voler ripristinare tutte le impostazioni ai valori predefiniti?"},
            {"reset_warning", "Questa azione non può essere annullata."},
            {"export_settings", "Esporta Impostazioni su File:"},
            {"import_settings", "Importa Impostazioni da File:"},
            {"edit_account", "Modifica Account: %s"},
            {"account_name", "Nome Account:"},
            {"drf_token_label", "Token DRF:"},
            {"gw2_api_key_label", "Chiave API GW2:"},
            {"reload_config", "Ricarica Configurazione:"},
            {"auto_reset_label", "Auto Reset:"},
            {"next_reset_utc", "Prossimo reset programmato (UTC): %s"},
            {"favorites_ui", "UI Preferiti:"},
            {"favorites_colors", "Colori Preferiti:"},
            {"visual_enhancements", "Miglioramenti Visivi:"},
            {"mini_window_widget", "Mini Finestra (Widget Overlay):"},
            {"main_window_label", "Finestra Principale:"},
            {"profiles_description", "I profili consentono di salvare diverse configurazioni e passare rapidamente da una all'altra."},
            {"create_new_profile", "Crea Nuovo Profilo:"},
            {"current_profile", "Profilo Attuale: %s"},
            {"auto_backup", "Esegui automaticamente il backup delle impostazioni prima di modifiche importanti"},
            {"notifications", "Configura notifiche in-game per eventi importanti"},
            {"profit_goal", "Obiettivo Profitto:"},
            {"reset_warning_label", "Avviso Reset:"},
            {"session_complete", "Sessione Completata:"},
            {"manage_ignored_items", "Gestisci oggetti ignorati"},
            {"manage_ignored_currencies", "Gestisci valute ignorate"},
            {"rarity_label", "Rarità: %s"},
            {"type_label", "Tipo: %d"},
            {"account_bound_label", "Legato all'Account: %s"},
            {"nosell_label", "Non vendibile: %s"},
            {"sell_method_filters_label", "Filtri Metodo Vendita:"},
            {"api_knowledge_filters_label", "Filtri Conoscenza API:"},
            {"additional_filters_label", "Filtri Aggiuntivi:"},
            {"item_type_filters_label", "Filtri Tipo Oggetto:"},
            {"currency_filters_label", "Filtri Valute:"},
            {"price_range", "Intervallo Prezzo (Rame):"},
            {"quantity_range", "Intervallo Quantità:"},
            {"debug_info", "Informazioni Debug"},
            {"drf_status", "Stato DRF: %s"},
            {"drf_reconnect_count", "Conteggio Riconnessioni DRF: %d"},
            {"gw2_api_status", "Stato API GW2: %s"},
            {"gw2_api_reconnect_count", "Conteggio Riconnessioni API GW2: %d"},
            {"session_duration_debug", "Durata Sessione: %s"},
            {"gw2_memory", "Memoria Processo GW2: %zu MB"},
            {"gw2_api_request_count", "Conteggio Richieste API GW2: %d"},
            {"ignored_items_count", "Oggetti Ignorati: %d"},
            {"ignored_currencies_count", "Valute Ignorate: %d"},
            {"drf_logs", "Log DRF:"},
            {"last_100_entries", "(Ultimi 100 record)"},
            {"gw2_api_logs", "Log API GW2:"},
            {"item_currency_details", "Dettagli Oggetto/Valuta (Primi 5):"},
            {"item_label", "Oggetto %d: %s (Quantità: "},
            {"loaded_label", ", Caricato: %s)"},
            {"currency_label", "Valuta %d: %s (Quantità: "},
            {"custom_profit_items", "Oggetti Profitto Personalizzato (Primi 5):"},
            {"custom_profit_item", "Oggetto %d: %s (Profitto Personalizzato: "},
            {"no_custom_profit_items", "(Nessun oggetto profitto personalizzato)"},
            {"ignored_items_debug", "Oggetti Ignorati (Primi 5):"},
            {"yes_label", "Sì"},
            {"no_label", "No"},
            {"profits_label", "Profitti:"},
            {"profits_tooltip", "Profitti totali del farming"},
            {"approx_profits_label", "Profitti Approssimativi:"},
            {"approx_profits_tooltip", "Profitto totale dai valori di profitto personalizzato"},
            {"approx_gold_per_hour_label", "Oro Per Ora Approssimativo:"},
            {"approx_gold_per_hour_tooltip", "Profitto per ora basato sulla durata della sessione"},
            {"trading_profits_label", "Profitti di Trading:"},
            {"trading_profits_tooltip", "Profitti dalla vendita di oggetti sul Trading Post"},
            {"approx_trading_profits_listings_label", "Profitti di Trading Approssimativi (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Profitto totale se venduto via TP listings"},
            {"approx_trading_profits_instant_label", "Profitti di Trading Approssimativi (Vendita Istantanea):"},
            {"approx_trading_profits_instant_tooltip", "Profitto totale se venduto via TP buy orders istantanei"},
            {"trading_details_label", "Dettagli di Trading (Costo Opportunità):"},
            {"trading_details_tooltip", "Profitto perso non vendendo via TP listings"},
            {"lost_profit_vs_tp_sell_label", "Profitto Perso (vs Vendita TP):"},
            {"lost_profit_vs_tp_sell_tooltip", "Oro = profitto perso, Rosso = profitto guadagnato vs vendita TP"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Profitto Perso Per Ora (vs Vendita TP):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Costo opportunità per ora"},
            {"session_duration_debug_label", "Durata sessione: %s"},
            {"session_duration_debug_tooltip", "Durata sessione farming attuale"},
            {"tab_items", "Oggetti"},
            {"manage_ignored_items", "Gestisci oggetti ignorati"},
            {"clear_all_ignored_items", "Cancella tutti gli oggetti ignorati"},
            {"unignore_item", "Smetti di ignorare oggetto"},
            {"tab_currencies", "Valute"},
            {"manage_ignored_currencies", "Gestisci valute ignorate"},
            {"clear_all_ignored_currencies", "Cancella tutte le valute ignorate"},
            {"unignore_currency", "Smetti di ignorare valuta"},
            {"sell_method_filters_label", "Filtri Metodo Vendita:"},
            {"api_knowledge_filters_label", "Filtri Conoscenza API:"},
            {"additional_filters_label", "Filtri Aggiuntivi:"},
            {"item_type_filters_label", "Filtri Tipo Oggetto:"},
            {"currency_filters_label", "Filtri Valute:"},
            {"price_range", "Intervallo Prezzo (Rame):"},
            {"quantity_range", "Intervallo Quantità:"},
            {"debug_information", "Informazioni di Debug"},
            {"drf_status_label", "Stato DRF: %s"},
            {"drf_status_tooltip", "Stato connessione DRF attuale"},
            {"drf_reconnect_count_label", "Conteggio Reconnect DRF: %d"},
            {"drf_reconnect_count_tooltip", "Numero di tentativi di reconnect DRF"},
            {"gw2_api_status_label", "Stato API GW2: %s"},
            {"gw2_api_status_tooltip", "Stato connessione API GW2 attuale"},
            {"gw2_api_reconnect_count_label", "Conteggio Reconnect API GW2: %d"},
            {"gw2_api_reconnect_count_tooltip", "Numero di tentativi di reconnect API GW2"},
            {"session_duration_debug", "Durata Sessione: %s"},
            {"session_duration_debug_tooltip", "Durata sessione farming attuale"},
            {"gw2_process_memory_label", "Memoria Processo GW2: %zu MB"},
            {"gw2_process_memory_tooltip", "Utilizzo memoria processo GW2 attuale"},
            {"gw2_api_request_count_label", "Conteggio Richieste API GW2: %d"},
            {"gw2_api_request_count_tooltip", "Numero totale di richieste API GW2 effettuate"},
            {"ignored_items_debug_label", "Oggetti Ignorati: %d"},
            {"ignored_items_debug_tooltip", "Numero di oggetti ignorati"},
            {"ignored_currencies_debug_label", "Valute Ignorate: %d"},
            {"ignored_currencies_debug_tooltip", "Numero di valute ignorate"},
            {"drf_logs_label", "Log DRF:"},
            {"clear_drf_logs", "Cancella Log DRF"},
            {"clear_drf_logs_tooltip", "Cancella tutte le voci di log DRF"},
            {"last_100_entries", "(Ultimi 100 voci)"},
            {"gw2_api_logs_label", "Log API GW2:"},
            {"clear_gw2_logs", "Cancella Log GW2"},
            {"clear_gw2_logs_tooltip", "Cancella tutte le voci di log API GW2"},
            {"settings_label", "Impostazioni:"},
            {"api_key_label", "Chiave API: %s"},
            {"api_key_tooltip", "Stato chiave API GW2"},
            {"not_set", "Non impostata"},
            {"set", "Impostata"},
            {"drf_token_label", "Token DRF: %s"},
            {"drf_token_tooltip", "Stato token DRF"},
            {"toggle_hotkey_label", "Tasto Toggle: %s"},
            {"toggle_hotkey_tooltip", "Tasto di alternanza finestra principale"},
            {"auto_reset_mode_label", "Modalità Auto-Reset: %d"},
            {"auto_reset_mode_tooltip", "Modalità di reset automatico attuale"},
            {"next_reset_label", "Prossimo Reset: %s"},
            {"next_reset_tooltip", "Ora del prossimo reset pianificato (UTC)"},
            {"fake_drf_server_label", "Server DRF Falso:"},
            {"use_fake_drf_server", "Usa server DRF falso"},
            {"use_fake_drf_server_tooltip", "Solo per scopi di test"},
            {"reset_all_data", "Resetta Tutti i Dati"},
            {"reset_all_data_tooltip", "Resetta tutti i dati di farming"},
            {"coin", "Moneta"},
            {"rarity_label", "Rarità: %s"},
            {"type_label", "Tipo: %d"},
            {"account_bound_label", "Vincolato all'account: %s"},
            {"nosell_label", "Non vendibile: %s"},
            {"yes_label", "Sì"},
            {"no_label", "No"},
            {"sort_price_down", "Ordina: Prezzo oggetto decrescente"},
            {"sort_price_up", "Ordina: Prezzo oggetto crescente"},
            {"sort_count_high", "Ordina: |Conteggio| alto"},
            {"sort_count_low", "Ordina: |Conteggio| basso"},
            {"sort_name_az", "Ordina: Nome A–Z"},
            {"sort_tooltip", "Ordina oggetti per conteggio, ID o nome"},
            {"rarity_all", "Rarità: tutti"},
            {"rarity_basic", "Rarità: Base+"},
            {"rarity_fine", "Rarità: Fine+"},
            {"rarity_masterwork", "Rarità: Maestro+"},
            {"rarity_rare", "Rarità: Raro+"},
            {"rarity_exotic", "Rarità: Esotico+"},
            {"rarity_ascended", "Rarità: Asceso+"},
            {"rarity_legendary", "Rarità: Solo leggendario"},
            {"rarity_tooltip", "Filtra oggetti per rarità minima"},
            {"search_items_hint", "Cerca oggetti..."},
            {"column_icon", "Icona"},
            {"column_name", "Nome"},
            {"column_count", "Conteggio"},
            {"column_profit", "Profitto"},
            {"column_favorite", "Preferito"},
            {"column_ignore", "Ignora"},
            {"toggle_favorite", "Attiva/Disattiva preferito"},
            {"toggle_ignore", "Attiva/Disattiva ignora"},
            {"vendor_value_format", "Valore venditore: %s"},
            {"tp_sell_gross_format", "Vendita TP (Lordo): %s"},
            {"tp_sell_net_format", "Vendita TP (Netto): %s"},
            {"tp_buy_gross_format", "Acquisto TP (Lordo): %s"},
            {"tp_buy_net_format", "Acquisto TP (Netto): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Impostazioni Preferiti"},
            {"favorites_first", "Preferiti prima"},
            {"favorites_first_tooltip", "Mostra preferiti prima nelle liste oggetti/valute"},
            {"enable_favorite_text_color", "Abilita colore testo preferiti"},
            {"enable_favorite_text_color_tooltip", "Evidenzia oggetti/valute preferiti con colore testo personalizzato"},
            {"text_color", "Colore Testo"},
            {"enable_favorite_row_color", "Abilita colore riga preferiti"},
            {"enable_favorite_row_color_tooltip", "Evidenzia oggetti/valute preferiti con colore sfondo riga personalizzato"},
            {"row_color", "Colore Riga"},
            
            // Filter - Additional
            {"filter_favorite", "Preferito"},
            {"filter_favorite_tooltip", "Mostra oggetti preferiti"},
            {"filter_not_favorite", "Non Preferito"},
            {"filter_not_favorite_tooltip", "Mostra oggetti non preferiti"},
            {"filter_research_notes", "Note di Ricerca"},
            {"filter_research_notes_tooltip", "Mostra valuta note di ricerca"},
            {"range_filters", "Filtri Intervallo"},
            {"range_filters_tooltip", "Mostra filtri intervallo prezzo e quantità"},
            {"filter_min_price_tooltip", "Filtro prezzo minimo (0 = disabilitato)"},
            {"filter_max_price_tooltip", "Filtro prezzo massimo (0 = disabilitato)"},
            {"filter_min_quantity_tooltip", "Filtro quantità minima (0 = disabilitato)"},
            {"filter_max_quantity_tooltip", "Filtro quantità massima (0 = disabilitato)"},
            {"filter_min_price", "Prezzo Min"},
            {"filter_max_price", "Prezzo Max"},
            {"filter_min_quantity", "Quantità Min"},
            {"filter_max_quantity", "Quantità Max"},
            
            // Summary Tab - Table Columns
            {"column_label", "Etichetta"},
            {"column_value", "Valore"},
            {"column_item", "Oggetto"},
            {"column_count", "Quantità"},
            {"column_currency", "Valuta"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Oggetti per Profitto"},
            {"top_items_count_header", "Top Oggetti (Quantità)"},
            {"top_currencies_count_header", "Top Valute (Quantità)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 oggetti per valore di profitto"},
            {"top_items_count_tooltip", "Top 10 oggetti per quantità"},
            {"top_currencies_count_tooltip", "Top 10 valute per quantità"},
            
            // Settings Tab - General
            {"show_main_window", "Mostra finestra principale"},
            {"reset_all", "Resetta tutto"},
            {"reset_all_tooltip", "Resetta tutte le impostazioni ai valori predefiniti"},
            {"export", "Esporta"},
            {"export_tooltip", "Esporta le impostazioni in un file JSON"},
            {"import", "Importa"},
            {"import_tooltip", "Importa le impostazioni da un file JSON"},
            {"save", "Salva"},
            {"save_tooltip", "Salva le impostazioni correnti"},
            {"general_settings", "Impostazioni generali"},
            {"account_management", "Gestione account"},
            {"add_account", "+ Aggiungi account"},
            {"remove_account", "- Rimuovi account"},
            {"save_account", "Salva account"},
            {"reload_drf_token", "Ricarica token DRF"},
            {"reload_gw2_api_key", "Ricarica chiave API GW2"},
            {"reset_settings", "Auto Reset"},
            {"visual_settings", "Impostazioni visive"},
            {"gradient_backgrounds", "Sfondi sfumati"},
            {"gradient_backgrounds_tooltip", "Abilita sfondi sfumati per un aspetto più moderno"},
            {"top_gradient_color", "Colore sfumata superiore"},
            {"top_gradient_color_tooltip", "Colore sfumata superiore"},
            {"bottom_gradient_color", "Colore sfumata inferiore"},
            {"bottom_gradient_color_tooltip", "Colore sfumata inferiore"},
            {"show_item_icons", "Mostra icone oggetti (render GW2)"},
            {"show_item_icons_tooltip", "Carica le icone da render.guildwars2.com tramite Nexus."},
            {"icon_size", "Dimensione icona"},
            {"icon_size_tooltip", "Dimensione delle icone degli oggetti in pixel (16-96)"},
            {"show_rarity_borders", "Mostra bordi rarità"},
            {"show_rarity_borders_tooltip", "Mostra bordi colorati attorno alle icone basati sulla rarità"},
            {"rarity_border_thickness", "Spessore bordo rarità"},
            {"rarity_border_thickness_tooltip", "Regola lo spessore dei bordi di rarità (1.0 - 10.0)"},
            {"enable_grid_view_items", "Abilita vista griglia (Oggetti)"},
            {"enable_grid_view_items_tooltip", "Alterna tra vista elenco e griglia nella scheda Oggetti"},
            {"grid_icon_size_items", "Dimensione icona griglia (Oggetti)"},
            {"grid_icon_size_items_tooltip", "Dimensione delle icone in vista griglia per Oggetti (16-128)"},
            {"enable_grid_view_currencies", "Abilita vista griglia (Valute)"},
            {"enable_grid_view_currencies_tooltip", "Alterna tra vista elenco e griglia nella scheda Valute"},
            {"grid_icon_size_currencies", "Dimensione icona griglia (Valute)"},
            {"grid_icon_size_currencies_tooltip", "Dimensione delle icone in vista griglia per Valute (16-128)"},
            {"show_mini_window", "Mostra mini finestra"},
            {"show_mini_window_tooltip", "Mostra un piccolo widget di sovrapposizione con statistiche chiave"},
            {"mini_window_show_profit", "Mostra profitto"},
            {"mini_window_show_profit_tooltip", "Mostra il profitto totale nella mini finestra"},
            {"mini_window_show_profit_per_hour", "Mostra profitto/ora"},
            {"mini_window_show_profit_per_hour_tooltip", "Mostra il profitto per ora nella mini finestra"},
            {"mini_window_show_tp_sell", "Mostra vendita TP (Liste)"},
            {"mini_window_show_tp_sell_tooltip", "Mostra il profitto di vendita TP (liste) nella mini finestra"},
            {"mini_window_show_tp_instant", "Mostra vendita istantanea TP"},
            {"mini_window_show_tp_instant_tooltip", "Mostra il profitto di vendita istantanea TP nella mini finestra"},
            {"mini_window_show_total_items", "Mostra totale oggetti"},
            {"mini_window_show_total_items_tooltip", "Mostra il numero totale di oggetti nella mini finestra"},
            {"mini_window_show_session_duration", "Mostra durata sessione"},
            {"mini_window_show_session_duration_tooltip", "Mostra la durata della sessione nella mini finestra"},
            {"mini_window_click_through", "Finestra cliccabile"},
            {"mini_window_click_through_tooltip", "Permette di cliccare attraverso la mini finestra verso il gioco"},
            {"main_window_click_through", "Cliccabile"},
            {"main_window_click_through_tooltip", "Permette di cliccare attraverso la finestra principale verso il gioco"},
            {"settings_profiles", "Profili impostazioni"},
            {"select_profile", "Seleziona un profilo per applicare le sue impostazioni"},
            {"create_new_profile", "Crea nuovo profilo"},
            {"create_new_profile_tooltip", "Crea un nuovo profilo con le impostazioni correnti"},
            {"create", "Crea"},
            {"update_profile", "Aggiorna profilo"},
            {"update_profile_tooltip", "Aggiorna il profilo corrente con le impostazioni correnti"},
            {"delete_profile", "Elimina profilo"},
            {"delete_profile_tooltip", "Elimina il profilo corrente"},
            {"automatic_backups", "Backup automatici"},
            {"enable_automatic_backups", "Abilita backup automatici"},
            {"enable_automatic_backups_tooltip", "Crea automaticamente backup prima delle modifiche"},
            {"backup_frequency", "Frequenza backup"},
            {"backup_frequency_tooltip", "Con quale frequenza creare backup automatici"},
            {"max_backups", "Backup massimi"},
            {"max_backups_tooltip", "Numero massimo di backup da mantenere (1-20)"},
            {"notification_settings", "Impostazioni notifiche"},
            {"enable_notifications", "Abilita notifiche"},
            {"enable_notifications_tooltip", "Abilita notifiche in gioco"},
            {"notify_profit_goal", "Notifica quando raggiunto obiettivo profitto"},
            {"notify_profit_goal_tooltip", "Notifica quando raggiungi il tuo obiettivo di profitto"},
            {"profit_goal_gold", "Obiettivo profitto (Oro)"},
            {"profit_goal_gold_tooltip", "Obiettivo di profitto in monete d'oro (1-1000)"},
            {"notify_reset_warning", "Notifica prima del reset"},
            {"notify_reset_warning_tooltip", "Notifica prima che si verifichi un reset automatico"},
            {"reset_warning_minutes", "Avviso reset (Minuti)"},
            {"reset_warning_minutes_tooltip", "Minuti prima del reset per mostrare l'avviso (1-60)"},
            {"notify_session_complete", "Notifica dopo durata sessione"},
            {"notify_session_complete_tooltip", "Notifica dopo aver farmato per una certa durata"},
            {"session_complete_hours", "Sessione completata (Ore)"},
            {"session_complete_hours_tooltip", "Ore di farm prima della notifica (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Vendibile al mercante"},
            {"filter_sellable_to_vendor_tooltip", "Mostra oggetti vendibili al mercante"},
            {"filter_sellable_on_tp", "Vendibile su TP"},
            {"filter_sellable_on_tp_tooltip", "Mostra oggetti vendibili sul Trading Post"},
            {"filter_custom_profit", "Profitto personalizzato"},
            {"filter_custom_profit_tooltip", "Mostra oggetti con profitto personalizzato"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Conosciuto da API"},
            {"filter_known_by_api_tooltip", "Mostra oggetti conosciuti dall'API GW2"},
            {"filter_unknown_by_api", "Sconosciuto da API"},
            {"filter_unknown_by_api_tooltip", "Mostra oggetti sconosciuti dall'API GW2"},
            
            // Filter - Additional
            {"show_ignored_items", "Mostra oggetti ignorati"},
            {"show_ignored_items_tooltip", "Mostra oggetti/valute ignorati nelle schede Oggetti e Valute (deseleziona per nascondere)"},
            
            // Filter - Item Types
            {"filter_type_armor", "Armatura"},
            {"filter_type_armor_tooltip", "Mostra oggetti armatura"},
            {"filter_type_weapon", "Arma"},
            {"filter_type_weapon_tooltip", "Mostra oggetti arma"},
            {"filter_type_trinket", "Monile"},
            {"filter_type_trinket_tooltip", "Mostra oggetti monile"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Mostra oggetti gizmo"},
            {"filter_type_crafting_material", "Materiale crafting"},
            {"filter_type_crafting_material_tooltip", "Mostra materiali crafting"},
            {"filter_type_consumable", "Consumabile"},
            {"filter_type_consumable_tooltip", "Mostra consumabili"},
            {"filter_type_gathering_tool", "Strumento raccolta"},
            {"filter_type_gathering_tool_tooltip", "Mostra strumenti di raccolta"},
            {"filter_type_bag", "Borsa"},
            {"filter_type_bag_tooltip", "Mostra borse"},
            {"filter_type_container", "Contenitore"},
            {"filter_type_container_tooltip", "Mostra contenitori"},
            {"filter_type_mini_pet", "Mini animale"},
            {"filter_type_mini_pet_tooltip", "Mostra mini animali"},
            
            // Filter - Currencies
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Mostra valuta Karma"},
            {"filter_laurel", "Alloro"},
            {"filter_laurel_tooltip", "Mostra valuta Alloro"},
            {"filter_gem", "Gemma"},
            {"filter_gem_tooltip", "Mostra valuta Gemma"},
            {"filter_fractal_relic", "Reliquia frattale"},
            {"filter_fractal_relic_tooltip", "Mostra valuta Reliquia frattale"},
            {"filter_badge_of_honor", "Distintivo d'onore"},
            {"filter_badge_of_honor_tooltip", "Mostra valuta Distintivo d'onore"},
            {"filter_guild_commendation", "Lode gilda"},
            {"filter_guild_commendation_tooltip", "Mostra valuta Lode gilda"},
            {"filter_transmutation_charge", "Carica trasmutazione"},
            {"filter_transmutation_charge_tooltip", "Mostra valuta Carica trasmutazione"},
            {"filter_spirit_shards", "Frammenti spirito"},
            {"filter_spirit_shards_tooltip", "Mostra valuta Frammenti spirito"},
            {"filter_unbound_magic", "Magia non vincolata"},
            {"filter_unbound_magic_tooltip", "Mostra valuta Magia non vincolata"},
            {"filter_volatile_magic", "Magia volatile"},
            {"filter_volatile_magic_tooltip", "Mostra valuta Magia volatile"},
            {"filter_airship_parts", "Parti aeronave"},
            {"filter_airship_parts_tooltip", "Mostra valuta Parti aeronave"},
            {"filter_geode", "Geode"},
            {"filter_geode_tooltip", "Mostra valuta Geode"},
            {"filter_ley_line_crystals", "Cristalli linee telluriche"},
            {"filter_ley_line_crystals_tooltip", "Mostra valuta Cristalli linee telluriche"},
            {"filter_trade_contracts", "Contratti commerciali"},
            {"filter_trade_contracts_tooltip", "Mostra valuta Contratti commerciali"},
            {"filter_elegy_mosaic", "Mosaico elegia"},
            {"filter_elegy_mosaic_tooltip", "Mostra valuta Mosaico elegia"},
            {"filter_uncommon_coins", "Monete non comuni"},
            {"filter_uncommon_coins_tooltip", "Mostra valuta Monete non comuni"},
            {"filter_astral_acclaim", "Acclamazione astrale"},
            {"filter_astral_acclaim_tooltip", "Mostra valuta Acclamazione astrale"},
            
            // Debug Tab
            {"total_tracked_items", "Numero totale di oggetti tracciati"},
            {"total_tracked_items_tooltip", "Numero totale di oggetti tracciati"},
            {"total_tracked_currencies", "Numero totale di valute tracciate"},
            {"total_tracked_currencies_tooltip", "Numero totale di valute tracciate"},
            {"total_custom_profit", "Profitto personalizzato totale"},
            {"total_custom_profit_tooltip", "Profitto personalizzato totale"},
            {"total_tp_sell_profit", "Profitto vendita TP totale"},
            {"total_tp_sell_profit_tooltip", "Profitto vendita TP totale"},
            {"total_vendor_sell_profit", "Profitto vendita mercante totale"},
            {"total_vendor_sell_profit_tooltip", "Profitto vendita mercante totale"},
            {"profit_per_hour_calculation", "Calcolo profitto per ora"},
            {"profit_per_hour_calculation_tooltip", "Calcolo profitto per ora"},
            {"opportunity_cost_vs_tp_sell", "Costo opportunità vs vendita TP"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Costo opportunità vs vendita TP"},
            {"opportunity_cost_per_hour", "Costo opportunità per ora"},
            {"opportunity_cost_per_hour_tooltip", "Costo opportunità per ora"},
            {"first_5_tracked_items", "Primi 5 oggetti e valute tracciati con dettagli"},
            {"first_5_tracked_items_tooltip", "Primi 5 oggetti e valute tracciati con dettagli"},
            {"first_5_custom_profit", "Primi 5 oggetti con profitto personalizzato"},
            {"first_5_custom_profit_tooltip", "Primi 5 oggetti con profitto personalizzato"},
            {"first_5_ignored_items", "Primi 5 oggetti ignorati"},
            {"first_5_ignored_items_tooltip", "Primi 5 oggetti ignorati"},
            
            // Debug Settings
            {"debug_settings", "Impostazioni di Debug"},
            {"enable_debug_tab", "Attiva Scheda di Debug"},
            {"enable_debug_tab_tooltip", "Mostra la scheda di debug con informazioni aggiuntive"},
            
            // Currencies Tab
            {"gold_format", "Oro: %lld"},
            {"count_format", "Quantità: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Attiva preferito"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Attiva ignora"},
            
            // Additional Filters
            {"filter_account_bound", "Vincolato all'account"},
            {"filter_account_bound_tooltip", "Mostra oggetti vincolati all'account"},
            {"filter_not_account_bound", "Non vincolato all'account"},
            {"filter_not_account_bound_tooltip", "Mostra oggetti non vincolati all'account"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "Mostra oggetti NoSell"},
            {"filter_not_nosell", "Non NoSell"},
            {"filter_not_nosell_tooltip", "Mostra oggetti vendibili"},
            {"filter_ignored", "Ignorato"},
            {"filter_ignored_tooltip", "Mostra oggetti ignorati"},
            {"filter_not_ignored", "Non Ignorato"},
            {"filter_not_ignored_tooltip", "Mostra oggetti non ignorati"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Reliquie frattali immacolate"},
            {"filter_pristine_fractal_relics_tooltip", "Mostra valuta Reliquie frattali immacolate"},
            {"filter_unstable_fractal_essence", "Essenza frattale instabile"},
            {"filter_unstable_fractal_essence_tooltip", "Mostra valuta Essenza frattale instabile"},
            {"filter_magnetite_shards", "Frammenti di magnetite"},
            {"filter_magnetite_shards_tooltip", "Mostra valuta Frammenti di magnetite"},
            {"filter_gaeting_crystals", "Cristalli Gaeting"},
            {"filter_gaeting_crystals_tooltip", "Mostra valuta Cristalli Gaeting"},
            {"filter_prophet_shards", "Frammenti di profeta"},
            {"filter_prophet_shards_tooltip", "Mostra valuta Frammenti di profeta"},
            {"filter_green_prophet_shards", "Frammenti di profeta verdi"},
            {"filter_green_prophet_shards_tooltip", "Mostra valuta Frammenti di profeta verdi"},
            {"filter_wvw_skirmish_tickets", "Biglietti schermaglia WvW"},
            {"filter_wvw_skirmish_tickets_tooltip", "Mostra valuta Biglietti schermaglia WvW"},
            {"filter_proofs_of_heroics", "Prove di eroismo"},
            {"filter_proofs_of_heroics_tooltip", "Mostra valuta Prove di eroismo"},
            {"filter_pvp_league_tickets", "Biglietti lega PvP"},
            {"filter_pvp_league_tickets_tooltip", "Mostra valuta Biglietti lega PvP"},
            {"filter_ascended_shards_of_glory", "Frammenti di gloria ascendenti"},
            {"filter_ascended_shards_of_glory_tooltip", "Mostra valuta Frammenti di gloria ascendenti"},
            {"filter_tyrian_defense_seal", "Sigillo di difesa tiriano"},
            {"filter_tyrian_defense_seal_tooltip", "Mostra valuta Sigillo di difesa tiriano"},
            {"filter_testimony_of_desert_heroics", "Testimonianza di eroismo del deserto"},
            {"filter_testimony_of_desert_heroics_tooltip", "Mostra valuta Testimonianza di eroismo del deserto"},
            {"filter_testimony_of_jade_heroics", "Testimonianza di eroismo di giada"},
            {"filter_testimony_of_jade_heroics_tooltip", "Mostra valuta Testimonianza di eroismo di giada"},
            {"filter_testimony_of_castoran_heroics", "Testimonianza di eroismo castorano"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Mostra valuta Testimonianza di eroismo castorano"},
            {"filter_legendary_insight", "Intuizione leggendaria"},
            {"filter_legendary_insight_tooltip", "Mostra valuta Intuizione leggendaria"},
            {"filter_tales_of_dungeon_delving", "Racconti di esplorazione dungeon"},
            {"filter_tales_of_dungeon_delving_tooltip", "Mostra valuta Racconti di esplorazione dungeon"},
            {"filter_imperial_favor", "Favorito imperiale"},
            {"filter_imperial_favor_tooltip", "Mostra valuta Favorito imperiale"},
            {"filter_canach_coins", "Monete Canach"},
            {"filter_canach_coins_tooltip", "Mostra valuta Monete Canach"},
            {"filter_ancient_coin", "Moneta antica"},
            {"filter_ancient_coin_tooltip", "Mostra valuta Moneta antica"},
            {"filter_unusual_coin", "Moneta insolita"},
            {"filter_unusual_coin_tooltip", "Mostra valuta Moneta insolita"},
            {"filter_jade_sliver", "Frammento di giada"},
            {"filter_jade_sliver_tooltip", "Mostra valuta Frammento di giada"},
            {"filter_static_charge", "Carica statica"},
            {"filter_static_charge_tooltip", "Mostra valuta Carica statica"},
            {"filter_pinch_of_stardust", "Pizzico di polvere stellare"},
            {"filter_pinch_of_stardust_tooltip", "Mostra valuta Pizzico di polvere stellare"},
            {"filter_calcified_gasp", "Respiro calcificato"},
            {"filter_calcified_gasp_tooltip", "Mostra valuta Respiro calcificato"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Mostra valuta Ursus Oblige"},
            {"filter_gaeting_crystal_janthir", "Cristallo Gaeting (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Mostra valuta Cristallo Gaeting (Janthir)"},
            {"filter_antiquated_ducat", "Ducato antiquato"},
            {"filter_antiquated_ducat_tooltip", "Mostra valuta Ducato antiquato"},
            {"filter_aether_rich_sap", "Linfa ricca di etere"},
            {"filter_aether_rich_sap_tooltip", "Mostra valuta Linfa ricca di etere"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Reimposta tutto"},
            {"reset_all_tooltip", "Reimposta tutte le impostazioni ai valori predefiniti"},
            {"reset_confirm", "Sei sicuro di voler reimpostare tutte le impostazioni?"},
            {"reset_warning", "Questa azione non può essere annullata."},
            {"yes_reset", "Sì, reimposta"},
            {"cancel", "Annulla"},
            {"export", "Esporta"},
            {"export_tooltip", "Esporta le impostazioni in un file JSON"},
            {"export_settings", "Esporta impostazioni"},
            {"import", "Importa"},
            {"import_settings", "Importa impostazioni"},
            {"save", "Salva"},
            {"save_tooltip", "Salva le impostazioni correnti"},
            
            // Settings Tab - General
            {"general_settings", "Impostazioni generali"},
            {"account_management", "Gestione account"},
            {"account_prefix", "Account"},
            {"remove_account", "- Rimuovi account"},
            {"save_account", "Salva account"},
            {"reconnect_drf_token", "Riconnetti a DRF con il token corrente"},
            {"reload_gw2_api_key_tooltip", "Ricarica la chiave API GW2 per il recupero dei dati degli oggetti"},
            {"reset_settings", "Reimposta impostazioni"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Mai (solo reimpostazione manuale)"},
            {"auto_reset_on_load", "Al caricamento dell'addon"},
            {"auto_reset_daily", "Reimpostazione giornaliera (00:00 UTC)"},
            {"auto_reset_weekly", "Settimanale (Lun 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Settimanale NA WvW (Sab 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Settimanale EU WvW (Ven 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Settimanale bonus mappa (Gio 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minuti dopo l'ultimo scaricamento"},
            {"auto_reset_custom_days", "Personalizzato (giorni)"},
            {"auto_reset_tooltip", "Quando reimpostare automaticamente i contatori di farming"},
            {"minutes_after_unload_tooltip", "Minuti dopo lo scaricamento dell'addon prima della reimpostazione automatica"},
            {"reset_interval_days", "Intervallo di reimpostazione (giorni)"},
            {"reset_interval_days_tooltip", "Intervallo di reimpostazione personalizzato in giorni (1-30 giorni)"},
            
            // Visual Settings
            {"top_gradient_color", "Superiore"},
            {"top_gradient_color_tooltip", "Colore sfumatura superiore"},
            {"bottom_gradient_color", "Inferiore"},
            {"bottom_gradient_color_tooltip", "Colore sfumatura inferiore"},
            {"icon_size", "Dimensione icona"},
            {"icon_size_tooltip", "Dimensione delle icone degli oggetti in pixel (16-96)"},
            {"border_size", "Dimensione bordo"},
            {"border_size_tooltip", "Regola lo spessore dei bordi di rarità (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Alterna tra vista elenco e griglia nella scheda Oggetti"},
            {"grid_icon_size_items", "Dimensione icona griglia (Oggetti)"},
            {"grid_icon_size_items_tooltip", "Dimensione delle icone nella vista griglia per Oggetti (16-128)"},
            {"grid_icon_size_currencies", "Dimensione icona griglia (Valute)"},
            {"grid_icon_size_currencies_tooltip", "Dimensione delle icone nella vista griglia per Valute (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Mostra mini finestra"},
            {"show_mini_window_tooltip", "Mostra un piccolo widget di sovrapposizione con statistiche chiave"},
            {"mini_window_show_profit", "Mostra profitto"},
            {"mini_window_show_profit_tooltip", "Mostra il profitto totale nella mini finestra"},
            {"mini_window_show_profit_per_hour", "Mostra profitto/ora"},
            {"mini_window_show_profit_per_hour_tooltip", "Mostra il profitto per ora nella mini finestra"},
            {"mini_window_show_tp_sell", "Mostra vendita TP (Elenchi)"},
            {"mini_window_show_tp_sell_tooltip", "Mostra il profitto di vendita TP (elenchi) nella mini finestra"},
            {"mini_window_show_tp_instant", "Mostra vendita istantanea TP"},
            {"mini_window_show_tp_instant_tooltip", "Mostra il profitto di vendita istantanea TP nella mini finestra"},
            {"mini_window_show_total_items", "Mostra totale oggetti"},
            {"mini_window_show_total_items_tooltip", "Mostra il numero totale di oggetti nella mini finestra"},
            {"mini_window_show_session_duration", "Mostra durata sessione"},
            {"mini_window_show_session_duration_tooltip", "Mostra la durata della sessione nella mini finestra"},
            {"mini_window_click_through", "Finestra cliccabile"},
            {"mini_window_click_through_tooltip", "Permette di cliccare attraverso la mini finestra al gioco"},
            
            // Main Window
            {"main_window_label", "Finestra principale"},
            {"main_window_click_through", "Cliccabile"},
            {"main_window_click_through_tooltip", "Permette di cliccare attraverso la finestra principale al gioco"},
            
            // Settings Profiles
            {"settings_profiles", "Profili impostazioni"},
            {"default_no_profile", "Predefinito (Nessun profilo)"},
            {"select_profile_tooltip", "Seleziona un profilo per applicare le sue impostazioni"},
            {"create", "Crea"},
            {"create_tooltip", "Crea un nuovo profilo con le impostazioni correnti"},
            {"update_profile", "Aggiorna profilo"},
            {"update_profile_tooltip", "Aggiorna il profilo corrente con le impostazioni correnti"},
            {"delete_profile", "Elimina profilo"},
            {"delete_profile_tooltip", "Elimina il profilo corrente"},
            
            // Automatic Backups
            {"automatic_backups", "Backup automatici"},
            {"enable_automatic_backups", "Abilita backup automatici"},
            {"enable_automatic_backups_tooltip", "Crea automaticamente backup prima delle modifiche"},
            {"backup_frequency", "Frequenza backup"},
            {"backup_frequency_tooltip", "Con quale frequenza creare backup automatici"},
            {"backup_manual_only", "Solo manuale"},
            {"backup_daily", "Giornaliero"},
            {"backup_weekly", "Settimanale"},
            {"max_backup_count", "Max numero backup"},
            {"max_backup_count_tooltip", "Numero massimo di backup da mantenere (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Impostazioni notifiche"},
            {"enable_notifications", "Abilita notifiche"},
            {"enable_notifications_tooltip", "Abilita notifiche in-game"},
            {"profit_goal", "Obiettivo profitto"},
            {"notify_profit_goal", "Notifica quando raggiunto l'obiettivo di profitto"},
            {"notify_profit_goal_tooltip", "Notifica quando raggiungi il tuo obiettivo di profitto"},
            {"profit_goal_gold", "Obiettivo profitto (oro)"},
            {"profit_goal_gold_tooltip", "Obiettivo di profitto in monete d'oro (1-1000)"},
            {"reset_warning_label", "Avviso reimpostazione"},
            {"notify_reset_warning", "Notifica prima della reimpostazione"},
            {"notify_reset_warning_tooltip", "Notifica prima che avvenga la reimpostazione automatica"},
            {"warning_minutes", "Minuti avviso"},
            {"warning_minutes_tooltip", "Minuti prima della reimpostazione per mostrare l'avviso (1-60)"},
            {"session_complete", "Sessione completata"},
            {"notify_session_complete", "Notifica dopo durata sessione"},
            {"notify_session_complete_tooltip", "Notifica dopo aver fatto farming per una certa durata"},
            {"session_hours", "Ore sessione"},
            {"session_hours_tooltip", "Ore di farming prima della notifica (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Cercare valute..."},
            {"clear_search", "Cancella"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Cerca oggetti preferiti..."},
            {"search_favorite_currencies_hint", "Cerca valute preferite..."},
            {"clear_search_favorites", "Cancella"},
        };
        return translations;
    }
}
