// ---------------------------------------------------------------------------
// localization_cs.cpp – Czech translations for Farming Tracker
// ---------------------------------------------------------------------------

#include "localization.h"
#include <unordered_map>

namespace Localization
{
    const std::unordered_map<std::string, const char*> GetCzechTranslations()
    {
        static const std::unordered_map<std::string, const char*> translations = {
            // Status texts
            {"status_disconnected", "Odpojeno"},
            {"status_connecting", "Připojuji..."},
            {"status_connected", "Připojeno"},
            {"status_auth_failed", "Selhání autentizace – zkontrolujte token"},
            {"status_reconnecting", "Znovu připojuji..."},
            {"status_error", "Chyba"},
            {"status_unknown", "Neznámé"},

            // Mini Window
            {"mini_window_title", "Farming Tracker Mini"},
            {"profit", "Zisk"},
            {"profit_per_hour", "Zisk/Hodina"},
            {"tp_sell", "TP Prodej"},
            {"tp_instant", "TP Okamžitý Prodej"},
            {"total_items", "Celkem Položek"},
            {"session", "Relace"},

            // Main Window
            {"main_window_title", "Farming Tracker"},
            {"drf_label", "DRF"},
            {"gw2_api_label", "GW2 API"},
            {"session_time_label", "Čas Relace"},
            {"reset_button", "Resetovat"},
            {"reset_tooltip", "Resetovat všechny počítadla farmingu (manuální reset)"},

            // Tabs
            {"tab_summary", "Přehled"},
            {"tab_items", "Položky"},
            {"tab_currencies", "Měny"},
            {"tab_profit", "Zisk"},
            {"tab_favorites", "Oblíbené"},
            {"tab_ignored", "Ignorované"},
            {"tab_filter", "Filtr"},
            {"tab_custom_profit", "Vlastní Zisk"},
            {"tab_debug", "Ladění"},

            // Summary Tab
            {"warning_drf_not_connected", "⚠️ DRF nepřipojeno"},
            {"warning_drf_not_connected_desc", "Tento plugin vyžaduje DRF pro přenos dat."},
            {"warning_drf_install", "Nainstalujte DRF přes Nexus Addon Manager nebo https://drf.rs/"},
            {"warning_drf_token_invalid", "⚠️ Neplatný DRF Token"},
            {"warning_drf_token_invalid_desc", "Prosím zkontrolujte svůj DRF Token v nastavení."},
            {"warning_gw2_api_key_not_set", "⚠️ GW2 API klíč nenastaven"},
            {"warning_gw2_api_key_not_set_desc", "Prosím nastavte svůj GW2 API klíč v nastavení pro detaily položek."},
            {"overview", "Přehled"},
            {"overview_tooltip", "Přehled aktuální relace farmingu"},
            {"total_profit", "Celkový Zisk"},
            {"total_profit_tooltip", "Celkový vlastní zisk ze všech položek"},
            {"total_items_count", "Celkem Položek"},
            {"total_items_tooltip", "Celkový počet unikátních položek sledovaných"},
            {"total_currencies", "Celkem Měn"},
            {"total_currencies_tooltip", "Celkový počet unikátních měn sledovaných"},
            {"profit_per_hour_label", "Zisk Za Hodinu"},
            {"profit_per_hour_tooltip", "Zisk za hodinu založený na délce relace"},
            {"session_duration", "Délka Relace"},
            {"session_duration_tooltip", "Délka aktuální relace farmingu"},
            {"top_items_profit", "Top Položky (Zisk)"},
            {"top_items_profit_tooltip", "Top 5 položek podle hodnoty zisku"},
            {"loading", "Načítám..."},
            {"coin", "Mince"},
            {"top_items_count", "Top Položky (Počet)"},
            {"top_items_count_tooltip", "Top 5 položek podle počtu"},
            {"top_currencies", "Top Měny"},
            {"top_currencies_tooltip", "Top 5 měn podle počtu"},
            {"quick_statistics", "Rychlé Statistiky"},
            {"quick_statistics_tooltip", "Přehled statistik farmingu"},
            {"average_item_value", "Průměrná Hodnota Položky"},
            {"average_item_value_na", "N/A"},
            {"total_unique_items", "Celkem Unikátních Položek"},
            {"warning_no_data", "⚠️ Žádná data načtena"},
            {"warning_no_data_desc", "Čekám na data DRF..."},
            {"export", "Exportovat"},
            {"export_tooltip", "Exportovat data farmingu do souboru"},
            {"export_json", "Exportovat jako JSON"},
            {"export_csv", "Exportovat jako CSV"},

            // Items Tab
            {"search_hint", "Hledat položky..."},
            {"clear", "Vymazat"},
            {"sort_count_high", "Řazení: |Počet| vysoký"},
            {"sort_count_low", "Řazení: |Počet| nízký"},
            {"sort_id_up", "Řazení: ID Položky vysoké"},
            {"sort_id_down", "Řazení: ID Položky nízké"},
            {"sort_name_az", "Řazení: Název A–Z"},
            {"sort_tooltip", "Seřadit položky podle počtu, ID nebo názvu"},
            {"rarity_all", "Vzácnost: všechny"},
            {"rarity_basic", "Vzácnost: Základní+"},
            {"rarity_fine", "Vzácnost: Jemný+"},
            {"rarity_masterwork", "Vzácnost: Mistrovský+"},
            {"rarity_rare", "Vzácnost: Vzácný+"},
            {"rarity_exotic", "Vzácnost: Exotický+"},
            {"rarity_ascended", "Vzácnost: Vzestupný+"},
            {"rarity_legendary", "Vzácnost: Pouze Legendární"},
            {"rarity_tooltip", "Filtrovat položky podle minimální vzácnosti"},
            {"rarity", "Vzácnost"},
            {"type", "Typ"},
            {"vendor_value", "Hodnota Prodejce"},
            {"tp_buy_net", "TP Nákup (Čistý)"},
            {"account_bound", "Vázáno k účtu"},
            {"yes", "Ano"},
            {"no", "Ne"},
            {"nosell", "Neprodejné"},
            {"favorite", "Oblíbené"},
            {"ignore", "Ignorovat"},

            // Currencies Tab
            {"search_currencies_hint", "Hledat měny..."},
            {"api_id", "API ID"},
            {"currency_name", "Název Měny"},
            {"count", "Počet"},

            // Profit Tab
            {"profits", "Zisky"},
            {"profits_tooltip", "Celkové zisky z farmingu"},
            {"approx_profits", "Přibližné Zisky"},
            {"approx_gold_per_hour", "Přibližně Zlata Za Hodinu"},
            {"trading_profits", "Obchodní Zisky"},
            {"trading_profits_tooltip", "Zisky z Obchodního Místa"},
            {"approx_trading_profits_listings", "Přibližné Obchodní Zisky (Nabídky)"},
            {"approx_trading_profits_instant", "Přibližné Obchodní Zisky (Okamžitý Prodej)"},
            {"trading_details", "Detaily Obchodu (Příležitostní Náklady)"},
            {"trading_details_tooltip", "Příležitostní náklady na používání položek místo prodeje"},
            {"lost_profit_vs_tp_sell", "Ztracený Zisk (vs TP Prodej)"},
            {"lost_profit_per_hour_vs_tp_sell", "Ztracený Zisk Za Hodinu (vs TP Prodej)"},
            {"session_duration_label", "Délka relace"},
            {"session_duration_tooltip", "Délka aktuální relace farmingu"},

            // Filter Tab
            {"sell_method_filters", "Filtry Metody Prodeje"},
            {"sellable_to_vendor", "Prodejné prodejci"},
            {"sellable_to_vendor_tooltip", "Zobrazit položky prodejné prodejci"},
            {"sellable_on_tp", "Prodejné na TP"},
            {"sellable_on_tp_tooltip", "Zobrazit položky prodejné na Obchodním Místě"},
            {"has_custom_profit", "Má vlastní zisk"},
            {"has_custom_profit_tooltip", "Zobrazit položky s hodnotami vlastního zisku"},
            {"api_knowledge_filters", "Filtry Znalosti API"},
            {"known_by_api", "Známé API"},
            {"known_by_api_tooltip", "Zobrazit položky známé GW2 API"},
            {"unknown_by_api", "Neznámé API"},
            {"unknown_by_api_tooltip", "Zobrazit položky neznámé GW2 API"},
            {"item_type_filters", "Filtry Typu Položky"},
            {"type_armor", "Zbroj"},
            {"type_armor_tooltip", "Zobrazit položky zbroje"},
            {"type_weapon", "Zbraň"},
            {"type_weapon_tooltip", "Zobrazit položky zbraní"},
            {"type_trinket", "Šperk"},
            {"type_trinket_tooltip", "Zobrazit položky šperků"},
            {"type_gizmo", "Gizmo"},
            {"type_gizmo_tooltip", "Zobrazit položky gizmo"},
            {"type_crafting_material", "Výrobní Materiál"},
            {"type_crafting_material_tooltip", "Zobrazit výrobní materiály"},
            {"type_consumable", "Spotřební Zboží"},
            {"type_consumable_tooltip", "Zobrazit spotřební zboží"},
            {"type_gathering_tool", "Nástroj pro Sběr"},
            {"type_gathering_tool_tooltip", "Zobrazit nástroje pro sběr"},
            {"type_bag", "Batoh"},
            {"type_bag_tooltip", "Zobrazit batohy"},
            {"type_container", "Kontejner"},
            {"type_container_tooltip", "Zobrazit kontejnery"},
            {"type_mini_pet", "Mini Mazlíček"},
            {"type_mini_pet_tooltip", "Zobrazit mini mazlíčky"},
            {"currency_filters", "Filtry Měn"},
            {"currency_karma", "Karma"},
            {"currency_karma_tooltip", "Zobrazit měnu Karma"},
            {"currency_laurel", "Vavřín"},
            {"currency_laurel_tooltip", "Zobrazit měnu Vavřín"},
            {"currency_gem", "Drahokam"},
            {"currency_gem_tooltip", "Zobrazit měnu Drahokam"},
            {"currency_fractal_relic", "Fraktální Relikvie"},
            {"currency_fractal_relic_tooltip", "Zobrazit měnu Fraktální Relikvie"},
            {"currency_badge_of_honor", "Odznak Cti"},
            {"currency_badge_of_honor_tooltip", "Zobrazit měnu Odznak Cti"},
            {"currency_guild_commendation", "Cenění Guildy"},
            {"currency_guild_commendation_tooltip", "Zobrazit měnu Cenění Guildy"},
            {"currency_transmutation_charge", "Náboj Transmutace"},
            {"currency_transmutation_charge_tooltip", "Zobrazit měnu Náboj Transmutace"},
            {"currency_spirit_shards", "Střepy Ducha"},
            {"currency_spirit_shards_tooltip", "Zobrazit měnu Střepy Ducha"},
            {"currency_unbound_magic", "Nevázaná Magie"},
            {"currency_unbound_magic_tooltip", "Zobrazit měnu Nevázaná Magie"},
            {"currency_volatile_magic", "Volatile Magie"},
            {"currency_volatile_magic_tooltip", "Zobrazit měnu Volatile Magie"},
            {"currency_airship_parts", "Díly Vzducholodi"},
            {"currency_airship_parts_tooltip", "Zobrazit měnu Díly Vzducholodi"},
            {"currency_geode", "Geoda"},
            {"currency_geode_tooltip", "Zobrazit měnu Geoda"},
            {"currency_ley_line_crystals", "Krystaly Ley Line"},
            {"currency_ley_line_crystals_tooltip", "Zobrazit měnu Krystaly Ley Line"},
            {"currency_trade_contracts", "Obchodní Smlouvy"},
            {"currency_trade_contracts_tooltip", "Zobrazit měnu Obchodní Smlouvy"},
            {"currency_elegy_mosaic", "Elegie Mozaika"},
            {"currency_elegy_mosaic_tooltip", "Zobrazit měnu Elegie Mozaika"},
            {"currency_uncommon_coins", "Vzácné Mince"},
            {"currency_uncommon_coins_tooltip", "Zobrazit měnu Vzácné Mince"},
            {"currency_astral_acclaim", "Astrální Ováce"},
            {"currency_astral_acclaim_tooltip", "Zobrazit měnu Astrální Ováce"},
            {"currency_pristine_fractal_relics", "Čisté Fraktální Relikvie"},
            {"currency_pristine_fractal_relics_tooltip", "Zobrazit měnu Čisté Fraktální Relikvie"},
            {"currency_unstable_fractal_essence", "Nestabilní Fraktální Esence"},
            {"currency_unstable_fractal_essence_tooltip", "Zobrazit měnu Nestabilní Fraktální Esence"},
            {"currency_magnetite_shards", "Střepy Magnetitu"},
            {"currency_magnetite_shards_tooltip", "Zobrazit měnu Střepy Magnetitu"},
            {"currency_gaeting_crystals", "Krystaly Gaeting"},
            {"currency_gaeting_crystals_tooltip", "Zobrazit měnu Krystaly Gaeting"},
            {"currency_prophet_shards", "Střepy Proroka"},
            {"currency_prophet_shards_tooltip", "Zobrazit měnu Střepy Proroka"},
            {"currency_green_prophet_shards", "Zelené Střepy Proroka"},
            {"currency_green_prophet_shards_tooltip", "Zobrazit měnu Zelené Střepy Proroka"},
            {"currency_wvw_skirmish_tickets", "Lístky WvW Skirmish"},
            {"currency_wvw_skirmish_tickets_tooltip", "Zobrazit měnu Lístky WvW Skirmish"},
            {"currency_proofs_of_heroics", "Důkazy Hrdinství"},
            {"currency_proofs_of_heroics_tooltip", "Zobrazit měnu Důkazy Hrdinství"},
            {"currency_pvp_league_tickets", "Lístky PvP Ligy"},
            {"currency_pvp_league_tickets_tooltip", "Zobrazit měnu Lístky PvP Ligy"},
            {"currency_ascended_shards_of_glory", "Vzestupné Střepy Slávy"},
            {"currency_ascended_shards_of_glory_tooltip", "Zobrazit měnu Vzestupné Střepy Slávy"},
            {"currency_research_notes", "Výzkumné Poznámky"},
            {"currency_research_notes_tooltip", "Zobrazit měnu Výzkumné Poznámky"},
            {"currency_tyrian_defense_seal", "Pečeť Tyrijské Obrany"},
            {"currency_tyrian_defense_seal_tooltip", "Zobrazit měnu Pečeť Tyrijské Obrany"},
            {"currency_testimony_of_desert_heroics", "Svědectví Pouštního Hrdinství"},
            {"currency_testimony_of_desert_heroics_tooltip", "Zobrazit měnu Svědectví Pouštního Hrdinství"},
            {"currency_testimony_of_jade_heroics", "Svědectví Jade Hrdinství"},
            {"currency_testimony_of_jade_heroics_tooltip", "Zobrazit měnu Svědectví Jade Hrdinství"},
            {"currency_testimony_of_castoran_heroics", "Svědectví Castoran Hrdinství"},
            {"currency_testimony_of_castoran_heroics_tooltip", "Zobrazit měnu Svědectví Castoran Hrdinství"},
            {"currency_legendary_insight", "Legendární Vhled"},
            {"currency_legendary_insight_tooltip", "Zobrazit měnu Legendární Vhled"},
            {"currency_tales_of_dungeon_delving", "Příběhy Dungeon Prozkoumávání"},
            {"currency_tales_of_dungeon_delving_tooltip", "Zobrazit měnu Příběhy Dungeon Prozkoumávání"},
            {"currency_imperial_favor", "Císařská Přízeň"},
            {"currency_imperial_favor_tooltip", "Zobrazit měnu Císařská Přízeň"},
            {"currency_canach_coins", "Canach Mince"},
            {"currency_canach_coins_tooltip", "Zobrazit měnu Canach Mince"},
            {"currency_ancient_coin", "Starověká Mince"},
            {"currency_ancient_coin_tooltip", "Zobrazit měnu Starověká Mince"},
            {"currency_unusual_coin", "Neobvyklá Mince"},
            {"currency_unusual_coin_tooltip", "Zobrazit měnu Neobvyklá Mince"},
            {"currency_jade_sliver", "Jade Střep"},
            {"currency_jade_sliver_tooltip", "Zobrazit měnu Jade Střep"},
            {"currency_static_charge", "Statický Náboj"},
            {"currency_static_charge_tooltip", "Zobrazit měnu Statický Náboj"},
            {"currency_pinch_of_stardust", "Špetka Hvězdného Prachu"},
            {"currency_pinch_of_stardust_tooltip", "Zobrazit měnu Špetka Hvězdného Prachu"},
            {"currency_calcified_gasp", "Kalcifikované Nadechnutí"},
            {"currency_calcified_gasp_tooltip", "Zobrazit měnu Kalcifikované Nadechnutí"},
            {"currency_ursus_oblige", "Ursus Oblige"},
            {"currency_ursus_oblige_tooltip", "Zobrazit měnu Ursus Oblige"},
            {"currency_gaeting_crystal_janthir", "Krystal Gaeting (Janthir)"},
            {"currency_gaeting_crystal_janthir_tooltip", "Zobrazit měnu Krystal Gaeting (Janthir)"},
            {"currency_antiquated_ducat", "Antický Dukát"},
            {"currency_antiquated_ducat_tooltip", "Zobrazit měnu Antický Dukát"},
            {"currency_aether_rich_sap", "Éter Bohatá Šťáva"},
            {"currency_aether_rich_sap_tooltip", "Zobrazit měnu Éter Bohatá Šťáva"},

            // Additional Filters
            {"additional_filters", "Další Filtry"},
            {"account_bound", "Vázáno k účtu"},
            {"account_bound_tooltip", "Zobrazit položky vázané k účtu"},
            {"not_account_bound", "Nevázáno k účtu"},
            {"not_account_bound_tooltip", "Zobrazit položky nevázané k účtu"},
            {"nosell_items", "Neprodejné"},
            {"nosell_items_tooltip", "Zobrazit neprodejné položky"},
            {"not_nosell", "Prodejné"},
            {"not_nosell_tooltip", "Zobrazit prodejné položky"},
            {"favorite_items", "Oblíbené"},
            {"favorite_items_tooltip", "Zobrazit oblíbené položky"},
            {"not_favorite", "Neoblíbené"},
            {"not_favorite_tooltip", "Zobrazit neoblíbené položky"},
            {"ignored_items", "Ignorované"},
            {"ignored_items_tooltip", "Zobrazit ignorované položky"},
            {"not_ignored", "Neignorované"},
            {"not_ignored_tooltip", "Zobrazit neignorované položky"},

            // Range Filters
            {"range_filters", "Filtry Rozsahu"},
            {"show_range_filters", "Zobrazit Filtry Rozsahu"},
            {"filter_min_price", "Filtr Minimální Cena"},
            {"filter_max_price", "Filtr Maximální Cena"},
            {"filter_min_quantity", "Filtr Minimální Množství"},
            {"filter_max_quantity", "Filtr Maximální Množství"},

            // Mini Window Settings
            {"mini_window_settings", "Mini Okno"},
            {"show_profit", "Zobrazit Zisk"},
            {"show_profit_tooltip", "Zobrazit celkový zisk v mini okně"},
            {"show_profit_per_hour", "Zobrazit Zisk/Hodina"},
            {"show_profit_per_hour_tooltip", "Zobrazit zisk za hodinu v mini okně"},
            {"show_tp_sell", "Zobrazit TP Prodej (Nabídky)"},
            {"show_tp_sell_tooltip", "Zobrazit zisk TP prodeje (nabídky) v mini okně"},
            {"show_tp_instant", "Zobrazit TP Okamžitý Prodej"},
            {"show_tp_instant_tooltip", "Zobrazit zisk TP okamžitého prodeje v mini okně"},
            {"show_total_items", "Zobrazit Celkem Položek"},
            {"show_total_items_tooltip", "Zobrazit celkový počet položek v mini okně"},
            {"show_session_duration", "Zobrazit Délku Relace"},
            {"show_session_duration_tooltip", "Zobrazit délku relace v mini okně"},
            {"window_click_through", "Proklikávání Okna"},
            {"window_click_through_tooltip", "Umožňuje proklikávání přes mini okno do hry"},

            // Main Window Settings
            {"main_window", "Hlavní Okno"},
            {"click_through", "Proklikávání"},
            {"click_through_tooltip", "Umožňuje proklikávání přes hlavní okno do hry"},

            // Advanced UI Settings
            {"advanced_ui_settings", "Pokročilá Nastavení UI"},
            {"no_advanced_ui_settings", "(Žádná pokročilá nastavení UI k dispozici)"},

            // Display Settings
            {"display_settings", "Nastavení Zobrazení"},
            {"show_item_icons", "Zobrazit Ikony Položek"},
            {"show_item_icons_tooltip", "Zobrazit ikony položek v seznamu"},
            {"show_rarity_border", "Zobrazit Okraj Vzácnosti"},
            {"show_rarity_border_tooltip", "Zobrazit barevný okraj založený na vzácnosti položky"},
            {"enable_grid_view", "Povolit Mřížkové Zobrazení"},
            {"enable_grid_view_tooltip", "Zobrazit položky v mřížkovém rozložení místo seznamu"},
            {"grid_icon_size", "Velikost Ikony Mřížky"},
            {"grid_icon_size_tooltip", "Velikost ikon v mřížkovém zobrazení"},

            // Count Display Settings
            {"count_display_settings", "Nastavení Zobrazení Počtu"},
            {"count_text_color", "Barva Textu Počtu"},
            {"count_text_color_tooltip", "Barva textu počtu"},
            {"count_background_color", "Barva Pozadí Počtu"},
            {"count_background_color_tooltip", "Barva pozadí počtu"},
            {"count_font_size", "Velikost Písma Počtu"},
            {"count_font_size_tooltip", "Velikost písma počtu"},
            {"count_horizontal_alignment", "Horizontální Zarovnání Počtu"},
            {"count_horizontal_alignment_tooltip", "Horizontální zarovnání textu počtu"},

            // Gradient Background Settings
            {"gradient_background_settings", "Nastavení Přechodového Pozadí"},
            {"enable_gradient_backgrounds", "Povolit Přechodová Pozadí"},
            {"enable_gradient_backgrounds_tooltip", "Povolit přechodové pozadí pro okna"},
            {"gradient_top_color", "Horní Barva Přechodu"},
            {"gradient_top_color_tooltip", "Horní barva přechodového pozadí"},
            {"gradient_bottom_color", "Dolní Barva Přechodu"},
            {"gradient_bottom_color_tooltip", "Dolní barva přechodového pozadí"},

            // Custom Profit System
            {"custom_profit_system", "Systém Vlastního Zisku"},
            {"enable_custom_profit", "Povolit Vlastní Zisk"},
            {"enable_custom_profit_tooltip", "Povolit hodnoty vlastního zisku pro položky"},

            // Search
            {"search_settings", "Hledání"},
            {"enable_search", "Povolit Hledání"},
            {"enable_search_tooltip", "Povolit funkci hledání"},

            // Ignored Items
            {"ignored_items_settings", "Ignorované Položky"},
            {"enable_ignored_items", "Povolit Ignorované Položky"},
            {"enable_ignored_items_tooltip", "Povolit funkci ignorovaných položek"},

            // Auto Reset
            {"auto_reset_settings", "Auto Reset"},
            {"enable_auto_reset", "Povolit Auto Reset"},
            {"enable_auto_reset_tooltip", "Automaticky resetovat relaci farmingu po určité době"},
            {"auto_reset_duration", "Doba Auto Resetu (minuty)"},
            {"auto_reset_duration_tooltip", "Doba v minutách před auto resetem"},

            // DRF Settings
            {"drf_settings", "Nastavení DRF"},
            {"drf_token", "DRF Token"},
            {"drf_token_tooltip", "Váš autentizační token DRF"},
            {"edit_token", "Upravit Token"},
            {"save_token", "Uložit Token"},

            // GW2 API Settings
            {"gw2_api_settings", "Nastavení GW2 API"},
            {"gw2_api_key", "GW2 API Klíč"},
            {"gw2_api_key_tooltip", "Váš GW2 API klíč pro detaily položek"},
            {"edit_key", "Upravit Klíč"},
            {"save_key", "Uložit Klíč"},

            // Language Settings
            {"language_settings", "Jazyk"},
            {"language_tooltip", "Vybrat jazyk rozhraní"},
            {"language_english", "English"},
            {"language_german", "Deutsch"},
            {"language_french", "Français"},
            {"language_spanish", "Español"},
            {"language_chinese", "Chinese"},
            {"language_czech", "Čeština"},
            {"language_italian", "Italiano"},
            {"language_polish", "Polski"},
            {"language_portuguese", "Português"},
            {"language_russian", "Русский"},

            // Additional hardcoded strings found in UI
            {"farming_tracker_title", "Farming Tracker"},
            {"no_accounts_configured", "Žádné účty konfigurovány"},
            {"no_profiles_created", "Zatím nevytvořeny žádné profily"},
            {"count_label", "Počet:"},
            {"profit_label", "Zisk:"},
            {"no_profit", "Žádný zisk"},
            {"vendor_value_label", "Hodnota Prodejce:"},
            {"tp_sell_gross_label", "TP Prodej (Hrubý):"},
            {"tp_sell_net_label", "TP Prodej (Čistý):"},
            {"tp_buy_gross_label", "TP Nákup (Hrubý):"},
            {"tp_buy_net_label", "TP Nákup (Čistý):"},
            {"ignored_items_label", "Ignorované Položky:"},
            {"ignored_currencies_label", "Ignorované Měny:"},
            {"total_items_label", "Celkem Položek:"},
            {"total_currencies_label", "Celkem Měn:"},
            {"total_profit_label", "Celkový Zisk:"},
            {"tp_sell_profit_label", "TP Prodej Zisk:"},
            {"vendor_profit_label", "Prodejce Prodej Zisk:"},
            {"profit_per_hour_label", "Zisk Za Hodinu:"},
            {"opportunity_cost_profit_label", "Zisk Nákladů Příležitosti:"},
            {"opportunity_cost_profit_per_hour_label", "Zisk Nákladů Příležitosti/Hodina:"},
            {"custom_profit_feature_placeholder", "Funkce implementována - UI k přidání"},
            {"overview_label", "Přehled:"},
            {"total_profit_label_simple", "Celkový Zisk"},
            {"total_items_label_simple", "Celkem Položek"},
            {"total_currencies_label_simple", "Celkem Měn"},
            {"profit_per_hour_label_simple", "Zisk Za Hodinu"},
            {"session_duration_label_simple", "Délka Relace"},
            {"export_label", "Export:"},
            {"quick_actions", "Rychlé Akce:"},
            {"reset_confirm", "Jste si jisti, že chcete resetovat všechna nastavení na výchozí hodnoty?"},
            {"reset_warning", "Tato akce nemůže být vrácena zpět."},
            {"export_settings", "Exportovat Nastavení do Souboru:"},
            {"import_settings", "Importovat Nastavení ze Souboru:"},
            {"edit_account", "Upravit Účet: %s"},
            {"account_name", "Název Účtu:"},
            {"drf_token_label", "Token DRF:"},
            {"gw2_api_key_label", "Klíč API GW2:"},
            {"reload_config", "Znovu Načíst Konfiguraci:"},
            {"auto_reset_label", "Auto Reset:"},
            {"next_reset_utc", "Další naplánovaný reset (UTC): %s"},
            {"favorites_ui", "UI Oblíbených:"},
            {"favorites_colors", "Barvy Oblíbených:"},
            {"visual_enhancements", "Vizuální Vylepšení:"},
            {"mini_window_widget", "Mini Okno (Overlay Widget):"},
            {"main_window_label", "Hlavní Okno:"},
            {"profiles_description", "Profily umožňují ukládat různé konfigurace a rychle mezi nimi přepínat."},
            {"create_new_profile", "Vytvořit Nový Profil:"},
            {"current_profile", "Aktuální Profil: %s"},
            {"auto_backup", "Automaticky zálohovat nastavení před velkými změnami"},
            {"notifications", "Konfigurovat notifikace ve hře pro důležité události"},
            {"profit_goal", "Cíl Zisku:"},
            {"reset_warning_label", "Varování Resetu:"},
            {"session_complete", "Relace Dokončena:"},
            {"manage_ignored_items", "Spravovat ignorované položky"},
            {"manage_ignored_currencies", "Spravovat ignorované měny"},
            {"rarity_label", "Rarita: %s"},
            {"type_label", "Typ: %d"},
            {"account_bound_label", "Vázáno k účtu: %s"},
            {"nosell_label", "Neprodejné: %s"},
            {"sell_method_filters_label", "Filtry Metody Prodeje:"},
            {"api_knowledge_filters_label", "Filtry Znalostí API:"},
            {"additional_filters_label", "Další Filtry:"},
            {"item_type_filters_label", "Filtry Typu Položky:"},
            {"currency_filters_label", "Filtry Měn:"},
            {"price_range", "Rozsah Ceny (Měď):"},
            {"quantity_range", "Rozsah Množství:"},
            {"debug_info", "Ladící Informace"},
            {"drf_status", "Stav DRF: %s"},
            {"drf_reconnect_count", "Počet Reconnect DRF: %d"},
            {"gw2_api_status", "Stav API GW2: %s"},
            {"gw2_api_reconnect_count", "Počet Reconnect API GW2: %d"},
            {"session_duration_debug", "Délka Relace: %s"},
            {"gw2_memory", "Paměť Procesu GW2: %zu MB"},
            {"gw2_api_request_count", "Počet Požadavků API GW2: %d"},
            {"ignored_items_count", "Ignorované Položky: %d"},
            {"ignored_currencies_count", "Ignorované Měny: %d"},
            {"drf_logs", "Logy DRF:"},
            {"last_100_entries", "(Posledních 100 záznamů)"},
            {"gw2_api_logs", "Logy API GW2:"},
            {"item_currency_details", "Detaily Položky/Měny (Prvních 5):"},
            {"item_label", "Položka %d: %s (Počet: "},
            {"loaded_label", ", Načteno: %s)"},
            {"currency_label", "Měna %d: %s (Počet: "},
            {"custom_profit_items", "Položky Vlastního Zisku (Prvních 5):"},
            {"custom_profit_item", "Položka %d: %s (Vlastní Zisk: "},
            {"no_custom_profit_items", "(Žádné položky vlastního zisku)"},
            {"ignored_items_debug", "Ignorované Položky (Prvních 5):"},
            {"yes_label", "Ano"},
            {"no_label", "Ne"},
            {"profits_label", "Zisky:"},
            {"profits_tooltip", "Celkový zisk z farmingu"},
            {"approx_profits_label", "Přibližný Zisk:"},
            {"approx_profits_tooltip", "Celkový zisk z hodnot vlastního zisku"},
            {"approx_gold_per_hour_label", "Přibližné Zlato Za Hodinu:"},
            {"approx_gold_per_hour_tooltip", "Zisk za hodinu založen na délce relace"},
            {"trading_profits_label", "Zisky z Obchodování:"},
            {"trading_profits_tooltip", "Zisky z prodeje položek na Trading Post"},
            {"approx_trading_profits_listings_label", "Přibližné Zisky z Obchodování (Listings):"},
            {"approx_trading_profits_listings_tooltip", "Celkový zisk při prodeji přes TP listings"},
            {"approx_trading_profits_instant_label", "Přibližné Zisky z Obchodování (Okamžitý Prodej):"},
            {"approx_trading_profits_instant_tooltip", "Celkový zisk při prodeji přes TP okamžité nákupní objednávky"},
            {"trading_details_label", "Detaily Obchodování (Náklady Příležitosti):"},
            {"trading_details_tooltip", "Ztracený zisk neprodejem přes TP listings"},
            {"lost_profit_vs_tp_sell_label", "Ztracený Zisk (vs Prodej TP):"},
            {"lost_profit_vs_tp_sell_tooltip", "Zlato = ztracený zisk, Červená = získaný zisk vs prodej TP"},
            {"lost_profit_per_hour_vs_tp_sell_label", "Ztracený Zisk Za Hodinu (vs Prodej TP):"},
            {"lost_profit_per_hour_vs_tp_sell_tooltip", "Náklady příležitosti za hodinu"},
            {"session_duration_debug_label", "Délka relace: %s"},
            {"session_duration_debug_tooltip", "Aktuální délka relace farmingu"},
            {"tab_items", "Položky"},
            {"manage_ignored_items", "Spravovat ignorované položky"},
            {"clear_all_ignored_items", "Vymazat všechny ignorované položky"},
            {"unignore_item", "Přestat ignorovat položku"},
            {"tab_currencies", "Měny"},
            {"manage_ignored_currencies", "Spravovat ignorované měny"},
            {"clear_all_ignored_currencies", "Vymazat všechny ignorované měny"},
            {"unignore_currency", "Přestat ignorovat měnu"},
            {"sell_method_filters_label", "Filtry Metody Prodeje:"},
            {"api_knowledge_filters_label", "Filtry Znalostí API:"},
            {"additional_filters_label", "Další Filtry:"},
            {"item_type_filters_label", "Filtry Typu Položky:"},
            {"currency_filters_label", "Filtry Měn:"},
            {"price_range", "Rozsah Ceny (Měď):"},
            {"quantity_range", "Rozsah Množství:"},
            {"debug_information", "Ladící Informace"},
            {"drf_status_label", "Stav DRF: %s"},
            {"drf_status_tooltip", "Aktuální stav připojení DRF"},
            {"drf_reconnect_count_label", "Počet Reconnect DRF: %d"},
            {"drf_reconnect_count_tooltip", "Počet pokusů o reconnect DRF"},
            {"gw2_api_status_label", "Stav API GW2: %s"},
            {"gw2_api_status_tooltip", "Aktuální stav připojení API GW2"},
            {"gw2_api_reconnect_count_label", "Počet Reconnect API GW2: %d"},
            {"gw2_api_reconnect_count_tooltip", "Počet pokusů o reconnect API GW2"},
            {"session_duration_debug", "Délka Relace: %s"},
            {"session_duration_debug_tooltip", "Aktuální délka relace farmingu"},
            {"gw2_process_memory_label", "Paměť Procesu GW2: %zu MB"},
            {"gw2_process_memory_tooltip", "Aktuální využití paměti procesu GW2"},
            {"gw2_api_request_count_label", "Počet Požadavků API GW2: %d"},
            {"gw2_api_request_count_tooltip", "Celkový počet požadavků API GW2"},
            {"ignored_items_debug_label", "Ignorované Položky: %d"},
            {"ignored_items_debug_tooltip", "Počet ignorovaných položek"},
            {"ignored_currencies_debug_label", "Ignorované Měny: %d"},
            {"ignored_currencies_debug_tooltip", "Počet ignorovaných měn"},
            {"drf_logs_label", "Logy DRF:"},
            {"clear_drf_logs", "Vymazat Logy DRF"},
            {"clear_drf_logs_tooltip", "Vymazat všechny záznamy logů DRF"},
            {"last_100_entries", "(Posledních 100 záznamů)"},
            {"gw2_api_logs_label", "Logy API GW2:"},
            {"clear_gw2_logs", "Vymazat Logy GW2"},
            {"clear_gw2_logs_tooltip", "Vymazat všechny záznamy logů API GW2"},
            {"settings_label", "Nastavení:"},
            {"api_key_label", "API Klíč: %s"},
            {"api_key_tooltip", "Stav klíče API GW2"},
            {"not_set", "Nenastaveno"},
            {"set", "Nastaveno"},
            {"drf_token_label", "Token DRF: %s"},
            {"drf_token_tooltip", "Stav tokenu DRF"},
            {"toggle_hotkey_label", "Klávesa Přepnutí: %s"},
            {"toggle_hotkey_tooltip", "Klávesa přepnutí hlavního okna"},
            {"auto_reset_mode_label", "Režim Auto-Reset: %d"},
            {"auto_reset_mode_tooltip", "Aktuální režim automatického resetu"},
            {"next_reset_label", "Další Reset: %s"},
            {"next_reset_tooltip", "Čas dalšího plánovaného resetu (UTC)"},
            {"fake_drf_server_label", "Falešný Server DRF:"},
            {"use_fake_drf_server", "Použít falešný server DRF"},
            {"use_fake_drf_server_tooltip", "Pouze pro testovací účely"},
            {"reset_all_data", "Resetovat Všechna Data"},
            {"reset_all_data_tooltip", "Resetovat všechna data farmingu"},
            {"coin", "Mince"},
            {"rarity_label", "Vzácnost: %s"},
            {"type_label", "Typ: %d"},
            {"account_bound_label", "Vázáno na účet: %s"},
            {"nosell_label", "Neprodejné: %s"},
            {"yes_label", "Ano"},
            {"no_label", "Ne"},
            {"sort_price_down", "Řadit: Cena položky sestupně"},
            {"sort_price_up", "Řadit: Cena položky vzestupně"},
            {"sort_count_high", "Řadit: |Počet| vysoký"},
            {"sort_count_low", "Řadit: |Počet| nízký"},
            {"sort_name_az", "Řadit: Název A–Z"},
            {"sort_tooltip", "Řadit položky podle počtu, ID nebo názvu"},
            {"rarity_all", "Vzácnost: všechny"},
            {"rarity_basic", "Vzácnost: Základní+"},
            {"rarity_fine", "Vzácnost: Jemné+"},
            {"rarity_masterwork", "Vzácnost: Mistrovské+"},
            {"rarity_rare", "Vzácnost: Vzácné+"},
            {"rarity_exotic", "Vzácnost: Exotické+"},
            {"rarity_ascended", "Vzácnost: Vzestupné+"},
            {"rarity_legendary", "Vzácnost: Pouze legendární"},
            {"rarity_tooltip", "Filtrovat položky podle minimální vzácnosti"},
            {"search_items_hint", "Hledat položky..."},
            {"column_icon", "Ikona"},
            {"column_name", "Název"},
            {"column_count", "Počet"},
            {"column_profit", "Zisk"},
            {"column_favorite", "Oblíbené"},
            {"column_ignore", "Ignorovat"},
            {"toggle_favorite", "Přepnout oblíbené"},
            {"toggle_ignore", "Přepnout ignorovat"},
            {"vendor_value_format", "Hodnota prodejce: %s"},
            {"tp_sell_gross_format", "TP Prodej (Hrubý): %s"},
            {"tp_sell_net_format", "TP Prodej (Čistý): %s"},
            {"tp_buy_gross_format", "TP Nákup (Hrubý): %s"},
            {"tp_buy_net_format", "TP Nákup (Čistý): %s"},
            
            // Favorites Settings
            {"favorites_settings", "Nastavení Oblíbených"},
            {"favorites_first", "Oblíbené první"},
            {"favorites_first_tooltip", "Zobrazí oblíbené jako první v seznamech položek/měn"},
            {"enable_favorite_text_color", "Povolit barvu textu oblíbených"},
            {"enable_favorite_text_color_tooltip", "Zvýrazní oblíbené položky/měny vlastní barvou textu"},
            {"text_color", "Barva Textu"},
            {"enable_favorite_row_color", "Povolit barvu řádku oblíbených"},
            {"enable_favorite_row_color_tooltip", "Zvýrazní oblíbené položky/měny vlastní barvou pozadí řádku"},
            {"row_color", "Barva Řádku"},
            
            // Filter - Additional
            {"filter_favorite", "Oblíbené"},
            {"filter_favorite_tooltip", "Zobrazit oblíbené položky"},
            {"filter_not_favorite", "Neoblíbené"},
            {"filter_not_favorite_tooltip", "Zobrazit neoblíbené položky"},
            {"filter_research_notes", "Poznámky k Výzkumu"},
            {"filter_research_notes_tooltip", "Zobrazit měnu poznámky k výzkumu"},
            {"range_filters", "Filtry Rozsahu"},
            {"range_filters_tooltip", "Zobrazit filtry rozsahu ceny a množství"},
            {"filter_min_price_tooltip", "Filtr minimální ceny (0 = vypnuto)"},
            {"filter_max_price_tooltip", "Filtr maximální ceny (0 = vypnuto)"},
            {"filter_min_quantity_tooltip", "Filtr minimálního množství (0 = vypnuto)"},
            {"filter_max_quantity_tooltip", "Filtr maximálního množství (0 = vypnuto)"},
            {"filter_min_price", "Min Cena"},
            {"filter_max_price", "Max Cena"},
            {"filter_min_quantity", "Min Množství"},
            {"filter_max_quantity", "Max Množství"},
            
            // Summary Tab - Table Columns
            {"column_label", "Štítek"},
            {"column_value", "Hodnota"},
            {"column_item", "Položka"},
            {"column_count", "Počet"},
            {"column_currency", "Měna"},
            
            // Summary Tab - Headers
            {"top_items_profit_header", "Top Položky podle zisku"},
            {"top_items_count_header", "Top Položky (Počet)"},
            {"top_currencies_count_header", "Top Měny (Počet)"},
            
            // Summary Tab - Tooltips
            {"top_items_profit_tooltip", "Top 10 položek podle hodnoty zisku"},
            {"top_items_count_tooltip", "Top 10 položek podle počtu"},
            {"top_currencies_count_tooltip", "Top 10 měn podle počtu"},
            
            // Settings Tab - General
            {"show_main_window", "Zobrazit hlavní okno"},
            {"reset_all", "Resetovat vše"},
            {"reset_all_tooltip", "Resetovat všechna nastavení na výchozí hodnoty"},
            {"export", "Exportovat"},
            {"export_tooltip", "Exportovat nastavení do souboru JSON"},
            {"import", "Importovat"},
            {"import_tooltip", "Importovat nastavení ze souboru JSON"},
            {"save", "Uložit"},
            {"save_tooltip", "Uložit aktuální nastavení"},
            {"general_settings", "Obecná nastavení"},
            {"account_management", "Správa účtů"},
            {"add_account", "+ Přidat účet"},
            {"remove_account", "- Odebrat účet"},
            {"save_account", "Uložit účet"},
            {"reload_drf_token", "Znovu načíst token DRF"},
            {"reload_gw2_api_key", "Znovu načíst klíč API GW2"},
            {"reset_settings", "Auto Reset"},
            {"visual_settings", "Vizuální nastavení"},
            {"gradient_backgrounds", "Přechodová pozadí"},
            {"gradient_backgrounds_tooltip", "Povolí hladká přechodová pozadí pro modernější vzhled"},
            {"top_gradient_color", "Horní barva přechodu"},
            {"top_gradient_color_tooltip", "Horní barva přechodu"},
            {"bottom_gradient_color", "Dolní barva přechodu"},
            {"bottom_gradient_color_tooltip", "Dolní barva přechodu"},
            {"show_item_icons", "Zobrazit ikony položek (GW2 render)"},
            {"show_item_icons_tooltip", "Načítá ikony z render.guildwars2.com přes Nexus."},
            {"icon_size", "Velikost ikony"},
            {"icon_size_tooltip", "Velikost ikon položek v pixelech (16-96)"},
            {"show_rarity_borders", "Zobrazit okraje vzácnosti"},
            {"show_rarity_borders_tooltip", "Zobrazí barevné okraje kolem ikon na základě vzácnosti"},
            {"rarity_border_thickness", "Tloušťka okraje vzácnosti"},
            {"rarity_border_thickness_tooltip", "Upravit tloušťku okrajů vzácnosti (1.0 - 10.0)"},
            {"enable_grid_view_items", "Povolit zobrazení mřížky (Položky)"},
            {"enable_grid_view_items_tooltip", "Přepínat mezi zobrazením seznamu a mřížky na kartě Položky"},
            {"grid_icon_size_items", "Velikost ikony mřížky (Položky)"},
            {"grid_icon_size_items_tooltip", "Velikost ikon v zobrazení mřížky pro Položky (16-128)"},
            {"enable_grid_view_currencies", "Povolit zobrazení mřížky (Měny)"},
            {"enable_grid_view_currencies_tooltip", "Přepínat mezi zobrazením seznamu a mřížky na kartě Měny"},
            {"grid_icon_size_currencies", "Velikost ikony mřížky (Měny)"},
            {"grid_icon_size_currencies_tooltip", "Velikost ikon v zobrazení mřížky pro Měny (16-128)"},
            {"show_mini_window", "Zobrazit mini okno"},
            {"show_mini_window_tooltip", "Zobrazí malý widget překryvu s klíčovými statistikami"},
            {"mini_window_show_profit", "Zobrazit zisk"},
            {"mini_window_show_profit_tooltip", "Zobrazit celkový zisk v mini okně"},
            {"mini_window_show_profit_per_hour", "Zobrazit zisk/hod"},
            {"mini_window_show_profit_per_hour_tooltip", "Zobrazit zisk za hodinu v mini okně"},
            {"mini_window_show_tp_sell", "Zobrazit prodej TP (Seznamy)"},
            {"mini_window_show_tp_sell_tooltip", "Zobrazit zisk prodeje TP (seznamy) v mini okně"},
            {"mini_window_show_tp_instant", "Zobrazit okamžitý prodej TP"},
            {"mini_window_show_tp_instant_tooltip", "Zobrazit zisk okamžitého prodeje TP v mini okně"},
            {"mini_window_show_total_items", "Zobrazit celkový počet položek"},
            {"mini_window_show_total_items_tooltip", "Zobrazit celkový počet položek v mini okně"},
            {"mini_window_show_session_duration", "Zobrazit trvání relace"},
            {"mini_window_show_session_duration_tooltip", "Zobrazit trvání relace v mini okně"},
            {"mini_window_click_through", "Okno proklikávací"},
            {"mini_window_click_through_tooltip", "Umožňuje proklikávání přes mini okno do hry"},
            {"main_window_click_through", "Proklikávací"},
            {"main_window_click_through_tooltip", "Umožňuje proklikávání přes hlavní okno do hry"},
            {"settings_profiles", "Profily nastavení"},
            {"select_profile", "Vyberte profil pro použití jeho nastavení"},
            {"create_new_profile", "Vytvořit nový profil"},
            {"create_new_profile_tooltip", "Vytvořit nový profil s aktuálním nastavením"},
            {"create", "Vytvořit"},
            {"update_profile", "Aktualizovat profil"},
            {"update_profile_tooltip", "Aktualizovat aktuální profil s aktuálním nastavením"},
            {"delete_profile", "Smazat profil"},
            {"delete_profile_tooltip", "Smazat aktuální profil"},
            {"automatic_backups", "Automatické zálohy"},
            {"enable_automatic_backups", "Povolit automatické zálohy"},
            {"enable_automatic_backups_tooltip", "Automaticky vytvářet zálohy před změnami"},
            {"backup_frequency", "Frekvence zálohování"},
            {"backup_frequency_tooltip", "Jak často vytvářet automatické zálohy"},
            {"max_backups", "Maximální zálohy"},
            {"max_backups_tooltip", "Maximální počet záloh k uchování (1-20)"},
            {"notification_settings", "Nastavení oznámení"},
            {"enable_notifications", "Povolit oznámení"},
            {"enable_notifications_tooltip", "Povolit oznámení ve hře"},
            {"notify_profit_goal", "Oznámit při dosažení cíle zisku"},
            {"notify_profit_goal_tooltip", "Oznámit, když dosáhnete cíle zisku"},
            {"profit_goal_gold", "Cíl zisku (Zlato)"},
            {"profit_goal_gold_tooltip", "Cíl zisku ve zlatých mincích (1-1000)"},
            {"notify_reset_warning", "Oznámit před resetem"},
            {"notify_reset_warning_tooltip", "Oznámit před automatickým resetem"},
            {"reset_warning_minutes", "Varování resetu (Minuty)"},
            {"reset_warning_minutes_tooltip", "Minuty před resetem pro zobrazení varování (1-60)"},
            {"notify_session_complete", "Oznámit po trvání relace"},
            {"notify_session_complete_tooltip", "Oznámit po farmování po určitou dobu"},
            {"session_complete_hours", "Relace dokončena (Hodiny)"},
            {"session_complete_hours_tooltip", "Hodiny farmování před oznámením (1-24)"},
            
            // Filter - Sell Method
            {"filter_sellable_to_vendor", "Prodejné obchodníkovi"},
            {"filter_sellable_to_vendor_tooltip", "Zobrazit položky prodejné obchodníkovi"},
            {"filter_sellable_on_tp", "Prodejné na TP"},
            {"filter_sellable_on_tp_tooltip", "Zobrazit položky prodejné na obchodním místě"},
            {"filter_custom_profit", "Vlastní zisk"},
            {"filter_custom_profit_tooltip", "Zobrazit položky s vlastním ziskem"},
            
            // Filter - API Knowledge
            {"filter_known_by_api", "Známé API"},
            {"filter_known_by_api_tooltip", "Zobrazit položky známé API GW2"},
            {"filter_unknown_by_api", "Neznámé API"},
            {"filter_unknown_by_api_tooltip", "Zobrazit položky neznámé API GW2"},
            
            // Filter - Additional
            {"show_ignored_items", "Zobrazit ignorované položky"},
            {"show_ignored_items_tooltip", "Zobrazit ignorované položky/měny na kartách Položky a Měny (zrušit zaškrtnutí pro skrytí)"},
            
            // Filter - Item Types
            {"filter_type_armor", "Zbroj"},
            {"filter_type_armor_tooltip", "Zobrazit položky zbroje"},
            {"filter_type_weapon", "Zbraň"},
            {"filter_type_weapon_tooltip", "Zobrazit položky zbraní"},
            {"filter_type_trinket", "Šperk"},
            {"filter_type_trinket_tooltip", "Zobrazit položky šperků"},
            {"filter_type_gizmo", "Gizmo"},
            {"filter_type_gizmo_tooltip", "Zobrazit položky gizmo"},
            {"filter_type_crafting_material", "Výrobní materiál"},
            {"filter_type_crafting_material_tooltip", "Zobrazit výrobní materiály"},
            {"filter_type_consumable", "Spotřební materiál"},
            {"filter_type_consumable_tooltip", "Zobrazit spotřební materiály"},
            {"filter_type_gathering_tool", "Sběratelský nástroj"},
            {"filter_type_gathering_tool_tooltip", "Zobrazit sběratelské nástroje"},
            {"filter_type_bag", "Batoh"},
            {"filter_type_bag_tooltip", "Zobrazit batohy"},
            {"filter_type_container", "Kontejner"},
            {"filter_type_container_tooltip", "Zobrazit kontejnery"},
            {"filter_type_mini_pet", "Mini mazlíček"},
            {"filter_type_mini_pet_tooltip", "Zobrazit mini mazlíčky"},
            
            // Filter - Currencies
            {"filter_karma", "Karma"},
            {"filter_karma_tooltip", "Zobrazit měnu Karma"},
            {"filter_laurel", "Vavřín"},
            {"filter_laurel_tooltip", "Zobrazit měnu Vavřín"},
            {"filter_gem", "Drahokam"},
            {"filter_gem_tooltip", "Zobrazit měnu Drahokam"},
            {"filter_fractal_relic", "Fraktální relikvie"},
            {"filter_fractal_relic_tooltip", "Zobrazit měnu Fraktální relikvie"},
            {"filter_badge_of_honor", "Znak cti"},
            {"filter_badge_of_honor_tooltip", "Zobrazit měnu Znak cti"},
            {"filter_guild_commendation", "Cená guildy"},
            {"filter_guild_commendation_tooltip", "Zobrazit měnu Cená guildy"},
            {"filter_transmutation_charge", "Transmutační náboj"},
            {"filter_transmutation_charge_tooltip", "Zobrazit měnu Transmutační náboj"},
            {"filter_spirit_shards", "Střepy ducha"},
            {"filter_spirit_shards_tooltip", "Zobrazit měnu Střepy ducha"},
            {"filter_unbound_magic", "Nevázaná magie"},
            {"filter_unbound_magic_tooltip", "Zobrazit měnu Nevázaná magie"},
            {"filter_volatile_magic", "Volatile magie"},
            {"filter_volatile_magic_tooltip", "Zobrazit měnu Volatile magie"},
            {"filter_airship_parts", "Díly vzducholodi"},
            {"filter_airship_parts_tooltip", "Zobrazit měnu Díly vzducholodi"},
            {"filter_geode", "Geoda"},
            {"filter_geode_tooltip", "Zobrazit měnu Geoda"},
            {"filter_ley_line_crystals", "Krystaly leňových linek"},
            {"filter_ley_line_crystals_tooltip", "Zobrazit měnu Krystaly leňových linek"},
            {"filter_trade_contracts", "Obchodní smlouvy"},
            {"filter_trade_contracts_tooltip", "Zobrazit měnu Obchodní smlouvy"},
            {"filter_elegy_mosaic", "Elegická mozaika"},
            {"filter_elegy_mosaic_tooltip", "Zobrazit měnu Elegická mozaika"},
            {"filter_uncommon_coins", "Vzácné mince"},
            {"filter_uncommon_coins_tooltip", "Zobrazit měnu Vzácné mince"},
            {"filter_astral_acclaim", "Astrální potlesk"},
            {"filter_astral_acclaim_tooltip", "Zobrazit měnu Astrální potlesk"},
            
            // Debug Tab
            {"total_tracked_items", "Celkový počet sledovaných položek"},
            {"total_tracked_items_tooltip", "Celkový počet sledovaných položek"},
            {"total_tracked_currencies", "Celkový počet sledovaných měn"},
            {"total_tracked_currencies_tooltip", "Celkový počet sledovaných měn"},
            {"total_custom_profit", "Celkový vlastní zisk"},
            {"total_custom_profit_tooltip", "Celkový vlastní zisk"},
            {"total_tp_sell_profit", "Celkový zisk prodeje TP"},
            {"total_tp_sell_profit_tooltip", "Celkový zisk prodeje TP"},
            {"total_vendor_sell_profit", "Celkový zisk prodeje obchodníka"},
            {"total_vendor_sell_profit_tooltip", "Celkový zisk prodeje obchodníka"},
            {"profit_per_hour_calculation", "Výpočet zisku za hodinu"},
            {"profit_per_hour_calculation_tooltip", "Výpočet zisku za hodinu"},
            {"opportunity_cost_vs_tp_sell", "Příležitostní náklady vs prodej TP"},
            {"opportunity_cost_vs_tp_sell_tooltip", "Příležitostní náklady vs prodej TP"},
            {"opportunity_cost_per_hour", "Příležitostní náklady za hodinu"},
            {"opportunity_cost_per_hour_tooltip", "Příležitostní náklady za hodinu"},
            {"first_5_tracked_items", "Prvních 5 sledovaných položek a měn s detaily"},
            {"first_5_tracked_items_tooltip", "Prvních 5 sledovaných položek a měn s detaily"},
            {"first_5_custom_profit", "Prvních 5 položek s vlastním ziskem"},
            {"first_5_custom_profit_tooltip", "Prvních 5 položek s vlastním ziskem"},
            {"first_5_ignored_items", "Prvních 5 ignorovaných položek"},
            {"first_5_ignored_items_tooltip", "Prvních 5 ignorovaných položek"},
            
            // Debug Settings
            {"debug_settings", "Ladící Nastavení"},
            {"enable_debug_tab", "Povolit Ladící Záložku"},
            {"enable_debug_tab_tooltip", "Zobrazí ladící záložku s dalšími informacemi"},
            
            // Currencies Tab
            {"gold_format", "Zlato: %lld"},
            {"count_format", "Počet: %lld"},
            
            // Favorites Tab
            {"toggle_favorite_tooltip", "Přepnout oblíbené"},
            
            // Currencies Tab
            {"toggle_ignore_tooltip", "Přepnout ignorovat"},
            
            // Additional Filters
            {"filter_account_bound", "Vázáno na účet"},
            {"filter_account_bound_tooltip", "Zobrazit položky vázané na účet"},
            {"filter_not_account_bound", "Nevázáno na účet"},
            {"filter_not_account_bound_tooltip", "Zobrazit položky nevázané na účet"},
            {"filter_nosell", "NoSell"},
            {"filter_nosell_tooltip", "Zobrazit NoSell položky"},
            {"filter_not_nosell", "Ne NoSell"},
            {"filter_not_nosell_tooltip", "Zobrazit prodejné položky"},
            {"filter_ignored", "Ignorováno"},
            {"filter_ignored_tooltip", "Zobrazit ignorované položky"},
            {"filter_not_ignored", "Ne Ignorováno"},
            {"filter_not_ignored_tooltip", "Zobrazit neignorované položky"},
            
            // Additional Currencies
            {"filter_pristine_fractal_relics", "Čisté fraktální relikvie"},
            {"filter_pristine_fractal_relics_tooltip", "Zobrazit měnu Čisté fraktální relikvie"},
            {"filter_unstable_fractal_essence", "Nestabilní fraktální esence"},
            {"filter_unstable_fractal_essence_tooltip", "Zobrazit měnu Nestabilní fraktální esence"},
            {"filter_magnetite_shards", "Magnetitové střepy"},
            {"filter_magnetite_shards_tooltip", "Zobrazit měnu Magnetitové střepy"},
            {"filter_gaeting_crystals", "Gaeting krystaly"},
            {"filter_gaeting_crystals_tooltip", "Zobrazit měnu Gaeting krystaly"},
            {"filter_prophet_shards", "Prorocké střepy"},
            {"filter_prophet_shards_tooltip", "Zobrazit měnu Prorocké střepy"},
            {"filter_green_prophet_shards", "Zelené prorocké střepy"},
            {"filter_green_prophet_shards_tooltip", "Zobrazit měnu Zelené prorocké střepy"},
            {"filter_wvw_skirmish_tickets", "WvW šarvátkové lístky"},
            {"filter_wvw_skirmish_tickets_tooltip", "Zobrazit měnu WvW šarvátkové lístky"},
            {"filter_proofs_of_heroics", "Důkazy o hrdinství"},
            {"filter_proofs_of_heroics_tooltip", "Zobrazit měnu Důkazy o hrdinství"},
            {"filter_pvp_league_tickets", "PvP ligové lístky"},
            {"filter_pvp_league_tickets_tooltip", "Zobrazit měnu PvP ligové lístky"},
            {"filter_ascended_shards_of_glory", "Vzestupné střepy slávy"},
            {"filter_ascended_shards_of_glory_tooltip", "Zobrazit měnu Vzestupné střepy slávy"},
            {"filter_tyrian_defense_seal", "Tyrijský obranný pečeť"},
            {"filter_tyrian_defense_seal_tooltip", "Zobrazit měnu Tyrijský obranný pečeť"},
            {"filter_testimony_of_desert_heroics", "Svědectví o pouštním hrdinství"},
            {"filter_testimony_of_desert_heroics_tooltip", "Zobrazit měnu Svědectví o pouštním hrdinství"},
            {"filter_testimony_of_jade_heroics", "Svědectví o jadeitovém hrdinství"},
            {"filter_testimony_of_jade_heroics_tooltip", "Zobrazit měnu Svědectví o jadeitovém hrdinství"},
            {"filter_testimony_of_castoran_heroics", "Svědectví o castoranském hrdinství"},
            {"filter_testimony_of_castoran_heroics_tooltip", "Zobrazit měnu Svědectví o castoranském hrdinství"},
            {"filter_legendary_insight", "Legendární vhled"},
            {"filter_legendary_insight_tooltip", "Zobrazit měnu Legendární vhled"},
            {"filter_tales_of_dungeon_delving", "Příběhy průzkumu dungeonů"},
            {"filter_tales_of_dungeon_delving_tooltip", "Zobrazit měnu Příběhy průzkumu dungeonů"},
            {"filter_imperial_favor", "Císařská přízeň"},
            {"filter_imperial_favor_tooltip", "Zobrazit měnu Císařská přízeň"},
            {"filter_canach_coins", "Canach mince"},
            {"filter_canach_coins_tooltip", "Zobrazit měnu Canach mince"},
            {"filter_ancient_coin", "Starověká mince"},
            {"filter_ancient_coin_tooltip", "Zobrazit měnu Starověká mince"},
            {"filter_unusual_coin", "Neobvyklá mince"},
            {"filter_unusual_coin_tooltip", "Zobrazit měnu Neobvyklá mince"},
            {"filter_jade_sliver", "Jadeitový střep"},
            {"filter_jade_sliver_tooltip", "Zobrazit měnu Jadeitový střep"},
            {"filter_static_charge", "Statický náboj"},
            {"filter_static_charge_tooltip", "Zobrazit měnu Statický náboj"},
            {"filter_pinch_of_stardust", "Špetka hvězdného prachu"},
            {"filter_pinch_of_stardust_tooltip", "Zobrazit měnu Špetka hvězdného prachu"},
            {"filter_calcified_gasp", "Kalcifikované vydechnutí"},
            {"filter_calcified_gasp_tooltip", "Zobrazit měnu Kalcifikované vydechnutí"},
            {"filter_ursus_oblige", "Ursus Oblige"},
            {"filter_ursus_oblige_tooltip", "Zobrazit měnu Ursus Oblige"},
            {"filter_gaeting_crystal_janthir", "Gaeting krystal (Janthir)"},
            {"filter_gaeting_crystal_janthir_tooltip", "Zobrazit měnu Gaeting krystal (Janthir)"},
            {"filter_antiquated_ducat", "Zastaralý dukát"},
            {"filter_antiquated_ducat_tooltip", "Zobrazit měnu Zastaralý dukát"},
            {"filter_aether_rich_sap", "Éter bohatá míza"},
            {"filter_aether_rich_sap_tooltip", "Zobrazit měnu Éter bohatá míza"},
            
            // Settings Tab - Quick Actions
            {"reset_all", "Resetovat vše"},
            {"reset_all_tooltip", "Resetovat všechna nastavení na výchozí hodnoty"},
            {"reset_confirm", "Opravdu chcete resetovat všechna nastavení?"},
            {"reset_warning", "Tato akce nemůže být vrácena zpět."},
            {"yes_reset", "Ano, resetovat"},
            {"cancel", "Zrušit"},
            {"export", "Export"},
            {"export_tooltip", "Exportovat nastavení do souboru JSON"},
            {"export_settings", "Exportovat nastavení"},
            {"import", "Import"},
            {"import_settings", "Importovat nastavení"},
            {"save", "Uložit"},
            {"save_tooltip", "Uložit aktuální nastavení"},
            
            // Settings Tab - General
            {"general_settings", "Obecná nastavení"},
            {"account_management", "Správa účtů"},
            {"account_prefix", "Účet"},
            {"remove_account", "- Odebrat účet"},
            {"save_account", "Uložit účet"},
            {"reconnect_drf_token", "Znovu připojit k DRF s aktuálním tokenem"},
            {"reload_gw2_api_key_tooltip", "Znovu načíst klíč GW2 API pro získání dat položek"},
            {"reset_settings", "Auto Reset"},
            
            // Auto Reset Modes
            {"auto_reset_never", "Nikdy (pouze manuální reset)"},
            {"auto_reset_on_load", "Při načtení addonu"},
            {"auto_reset_daily", "Denní reset (00:00 UTC)"},
            {"auto_reset_weekly", "Týdně (Po 07:30 UTC)"},
            {"auto_reset_weekly_na_wvw", "Týdně NA WvW (So 02:00 UTC)"},
            {"auto_reset_weekly_eu_wvw", "Týdně EU WvW (Pá 18:00 UTC)"},
            {"auto_reset_weekly_map_bonus", "Týdně bonus mapy (Čt 20:00 UTC)"},
            {"auto_reset_minutes_unload", "Minuty po posledním uvolnění"},
            {"auto_reset_custom_days", "Vlastní (dny)"},
            {"auto_reset_tooltip", "Kdy automaticky resetovat počítadla farmingu"},
            {"minutes_after_unload_tooltip", "Minuty po uvolnění addonu před automatickým resetem"},
            {"reset_interval_days", "Interval resetu (dny)"},
            {"reset_interval_days_tooltip", "Vlastní interval resetu v dnech (1-30 dní)"},
            
            // Visual Settings
            {"top_gradient_color", "Horní"},
            {"top_gradient_color_tooltip", "Horní barva přechodu"},
            {"bottom_gradient_color", "Dolní"},
            {"bottom_gradient_color_tooltip", "Dolní barva přechodu"},
            {"icon_size", "Velikost ikony"},
            {"icon_size_tooltip", "Velikost ikon položek v pixelech (16-96)"},
            {"border_size", "Velikost ohraničení"},
            {"border_size_tooltip", "Upravit tloušťku ohraničení vzácnosti (1.0 - 10.0)"},
            {"enable_grid_view_items_tooltip", "Přepínat mezi zobrazením seznamu a mřížky na kartě Položky"},
            {"grid_icon_size_items", "Velikost ikony mřížky (Položky)"},
            {"grid_icon_size_items_tooltip", "Velikost ikon v zobrazení mřížky pro Položky (16-128)"},
            {"grid_icon_size_currencies", "Velikost ikony mřížky (Měny)"},
            {"grid_icon_size_currencies_tooltip", "Velikost ikon v zobrazení mřížky pro Měny (16-128)"},
            
            // Mini Window
            {"show_mini_window", "Zobrazit mini okno"},
            {"show_mini_window_tooltip", "Zobrazí malý widget překryvu s klíčovými statistikami"},
            {"mini_window_show_profit", "Zobrazit zisk"},
            {"mini_window_show_profit_tooltip", "Zobrazit celkový zisk v mini okně"},
            {"mini_window_show_profit_per_hour", "Zobrazit zisk/hod"},
            {"mini_window_show_profit_per_hour_tooltip", "Zobrazit zisk za hodinu v mini okně"},
            {"mini_window_show_tp_sell", "Zobrazit prodej TP (Seznamy)"},
            {"mini_window_show_tp_sell_tooltip", "Zobrazit zisk prodeje TP (seznamy) v mini okně"},
            {"mini_window_show_tp_instant", "Zobrazit okamžitý prodej TP"},
            {"mini_window_show_tp_instant_tooltip", "Zobrazit zisk okamžitého prodeje TP v mini okně"},
            {"mini_window_show_total_items", "Zobrazit celkový počet položek"},
            {"mini_window_show_total_items_tooltip", "Zobrazit celkový počet položek v mini okně"},
            {"mini_window_show_session_duration", "Zobrazit trvání relace"},
            {"mini_window_show_session_duration_tooltip", "Zobrazit trvání relace v mini okně"},
            {"mini_window_click_through", "Okno klikatelné"},
            {"mini_window_click_through_tooltip", "Umožňuje klikání přes mini okno do hry"},
            
            // Main Window
            {"main_window_label", "Hlavní okno"},
            {"main_window_click_through", "Klikatelné"},
            {"main_window_click_through_tooltip", "Umožňuje klikání přes hlavní okno do hry"},
            
            // Settings Profiles
            {"settings_profiles", "Profily nastavení"},
            {"default_no_profile", "Výchozí (Žádný profil)"},
            {"select_profile_tooltip", "Vybrat profil pro použití jeho nastavení"},
            {"create", "Vytvořit"},
            {"create_tooltip", "Vytvořit nový profil s aktuálním nastavením"},
            {"update_profile", "Aktualizovat profil"},
            {"update_profile_tooltip", "Aktualizovat aktuální profil s aktuálním nastavením"},
            {"delete_profile", "Smazat profil"},
            {"delete_profile_tooltip", "Smazat aktuální profil"},
            
            // Automatic Backups
            {"automatic_backups", "Automatické zálohy"},
            {"enable_automatic_backups", "Povolit automatické zálohy"},
            {"enable_automatic_backups_tooltip", "Automaticky vytvářet zálohy před změnami"},
            {"backup_frequency", "Frekvence zálohování"},
            {"backup_frequency_tooltip", "Jak často vytvářet automatické zálohy"},
            {"backup_manual_only", "Pouze manuálně"},
            {"backup_daily", "Denně"},
            {"backup_weekly", "Týdně"},
            {"max_backup_count", "Max počet záloh"},
            {"max_backup_count_tooltip", "Maximální počet záloh k uložení (1-20)"},
            
            // Notification Settings
            {"notification_settings", "Nastavení oznámení"},
            {"enable_notifications", "Povolit oznámení"},
            {"enable_notifications_tooltip", "Povolit oznámení ve hře"},
            {"profit_goal", "Cíl zisku"},
            {"notify_profit_goal", "Oznámit při dosažení cíle zisku"},
            {"notify_profit_goal_tooltip", "Oznámit, když dosáhnete cíle zisku"},
            {"profit_goal_gold", "Cíl zisku (zlato)"},
            {"profit_goal_gold_tooltip", "Cíl zisku v zlatých mincích (1-1000)"},
            {"reset_warning_label", "Varování resetu"},
            {"notify_reset_warning", "Oznámit před resetem"},
            {"notify_reset_warning_tooltip", "Oznámit před automatickým resetem"},
            {"warning_minutes", "Minuty varování"},
            {"warning_minutes_tooltip", "Minuty před resetem pro zobrazení varování (1-60)"},
            {"session_complete", "Relace dokončena"},
            {"notify_session_complete", "Oznámit po trvání relace"},
            {"notify_session_complete_tooltip", "Oznámit po farmingu po určitou dobu"},
            {"session_hours", "Hodiny relace"},
            {"session_hours_tooltip", "Hodiny farmingu před oznámením (1-24)"},
            
            // Currencies Tab
            {"search_currencies_hint", "Hledat měny..."},
            {"clear_search", "Vymazat"},
            
            // Favorites Tab
            {"search_favorite_items_hint", "Hledat oblíbené položky..."},
            {"search_favorite_currencies_hint", "Hledat oblíbené měny..."},
            {"clear_search_favorites", "Vymazat"},
        };
        return translations;
    }
}
